### DISCUSSION TITLE
Using Airbyte on Google Compute Engine with configuration in Google Cloud SQL

### DISCUSSION THREAD

**Discussion by joseph-maddox** [airbytehq/airbyte#29379] [Show and tell]
Documenting this here in case it helps future-me or someone else in the community. (Also, a shout-out to the engineers on Airbyte office-hours who gave me some helpful pointers and ideas. 👏)

If you want to run Airbyte on a GCE VM with its configs in an external Cloud SQL Postgres instance, you'll need to add a Google Cloud SQL Proxy container to the docker-compose environment to make your config database accessible to Airbyte. Running the proxy on the host doesn't appear to be enough (probably due to some esoterica of Docker networking).

**Replace the `db` service in `docker-compose.yaml` with the following:**
```
  cloudsql:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.6.0
    container_name: airbyte-cloudsql-proxy
    # replace your-gcp-project:us-central1:airbyte, below with the ID of your Cloud SQL instance
    command: --address 0.0.0.0 --credentials-file /secrets/airbyte-sa.json your-gcp-project:us-central1:airbyte?port=5432
    volumes:
      - ./airbyte-sa.json:/secrets/airbyte-sa.json
    networks:
      - airbyte_internal
    ports:
      - 5432:5432
    restart: always
```

**Update the `.env` to reflect the following:**
```
DATABASE_USER=airbyte
DATABASE_PASSWORD=your-password-here
DATABASE_HOST=cloudsql
DATABASE_PORT=5432
DATABASE_DB=airbyte
DATABASE_URL=jdbc:postgresql://cloudsql:5432/airbyte
```

This setup assumes that a service account JSON key (for a service account with the `cloudsql.client` role) is stored in a file named `airbyte-sa.json` in the root Airbyte folder (with `docker-compose.yaml`, `run-ab-platform.sh`, etc.)
