### DISCUSSION TITLE
How to set custom schema in database connection for external database?

### DISCUSSION THREAD

**Discussion by winston0410** [airbytehq/airbyte#30451] [Connector Questions]
I am reading the configuration of the helm chart for airbytes. I want to connect airbyte to an external database to a specific schema. This is helm chart's configuration default value:

```yaml
externalDatabase:
  host: localhost
  user: airbyte
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: ""
  database: db-airbyte
  port: 5432
  jdbcUrl: ""
```

There seems to be no related option for setting schema, is there any other place I can set the target schema?

[a comment by an automated account is not shown]
