### DISCUSSION TITLE
Multiple connections for same source with different tenants

### DISCUSSION THREAD

**Discussion by vishaldesai28** [airbytehq/airbyte#31805] [General]
I built connector for API but want to use that source for multiple connections and each connection has different api. How can I create different connections and give each one unique name?

**Comment by marcosmarxm** [comment]
You can maybe inject a field based on a specification parameter.
Let's say you have your spec:
```yaml
spec:
  connection_unique_name:
    type: string
    examples: ["conn_1", "conn_2"]
```

and in your connector
```yaml
stream:
  <...>
  transformations:
      - type: AddFields
        fields:
          - path: [ "connection_name" ]
            value: { { config.get("connection_unique_name") } }
```

[a comment by an automated account is not shown]
