### DISCUSSION TITLE
How to specify the Airbyte Version in the Helm Chart?

### DISCUSSION THREAD

**Discussion by lukaszsurfer** [airbytehq/airbyte#32349] [Connector Questions] [answered]
Hi!

How can I set explicitly the App Version while using helm charts for installing airbyte?

I use Kustomize and set `version: 0.48.10` in helm chart manifest. It has been installed on two separate K8s clusters at different time, and on one cluster the Airbyte version is `0.50.29`, while using the same code on the other day in other cluster, the Airbyte version that is installed is: `0.50.11`

**Comment by lukaszsurfer** [comment]
Setting up `version` parameter in helm `values.yaml` does not work.

**Comment by marcosmarxm** [comment]
You need to override the `env_vars`  and specify the version you want to use.
There is the option to change the [global](https://github.com/airbytehq/airbyte-platform/blob/9ffa4e9f44f06e65fe3b138204367d5da8c98f2c/charts/airbyte/values.yaml#L5-L13) setting and impact all services or send the `env_vars` to a single service.
```yaml
env_vars:
   AIRBYTE_VERSION: 0.50.11
```

**Comment by lukaszsurfer** [comment]
Well it looks like setting this env var does not work. Tried both setting via `global` \ `env_vars` or directly for particular microservice, like here:
```yaml
webapp:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 250m
  env_vars:
    AIRBYTE_VERSION: "0.50.11"
```
results with:
```
one or more objects failed to apply, reason: Deployment.apps "airbyte-webapp" is invalid: spec.template.spec.containers[0].env[4].valueFrom: Invalid value: "": may not be specified when `value` is not empty.
```
In general setting env vars injection does work, like setting `FOO: BAR` is accepted and variable is visible within the container.

**Comment by lukaszsurfer** [comment, marked as answer]
Well, it looks like the working solution for this case is setting version in values in following manner:
```yaml
version: "0.50.11"
global:
  image:
    tag: "0.50.11"
```
