### DISCUSSION TITLE
[cdk] Support for Content-Type: `multipart/form-data`

### DISCUSSION THREAD

**Discussion by glevineLeap** [airbytehq/airbyte#33160] [Connector Ideas and Features]
I'm trying to write an integration using the Low-Code CDK for an API that accepts multipart/form-data. I can't get a working integration using the Connector Builder, but I can successfully call the API using Postman or the following Python snippet:
```python
r = requests.post('https://www.elitecxsolutions.net/api/v2/execute', files={"post": (None, '{"action": "exec", "dataset": {"datasetname": "/Apps/SM/APIv2/Query/ClientAnalytics/Clients"}}')})
```
I've attempted to hack multipart/form-data functionality using the YAML but it's not working for me either presumably due to a yaml parsing issue. Here's my attempt:
```yaml
spec:
  type: Spec
  documentation_url: https://example.org
  connection_specification:
    type: object
    $schema: http://json-schema.org/draft-07/schema#
    required:
      - client_id
      - client_secret
    properties:
      client_id:
        type: string
        order: 0
        title: Client ID
        airbyte_secret: true
      client_secret:
        type: string
        order: 1
        title: Client secret
        airbyte_secret: true
    additionalProperties: true
type: DeclarativeSource
check:
  type: CheckStream
  stream_names:
    - clients
streams:
  - name: clients
    type: DeclarativeStream
    retriever:
      type: SimpleRetriever
      paginator:
        type: NoPagination
      requester:
        path: /api/v2/execute
        type: HttpRequester
        url_base: https://www.elitecxsolutions.net
        http_method: POST
        authenticator:
          type: OAuthAuthenticator
          client_id: '{{ config[''client_id''] }}'
          grant_type: client_credentials
          client_secret: '{{ config[''client_secret''] }}'
          refresh_request_body: {}
          token_refresh_endpoint: https://www.elitecxsolutions.net/oauth/connect/token
        request_headers:
          Content-Type: multipart/form-data; boundary=400fb894cb72b274c6d27973d8f73d53
        request_body_data: |
          --400fb894cb72b274c6d27973d8f73d53\r\nContent-Disposition: form-data;
          name="post"\r\n\r\n{"action": "exec", "dataset": {"datasetname":
          "/Apps/SM/APIv2/Query/ClientAnalytics/Clients"}}\r\n--400fb894cb72b274c6d27973d8f73d53--\r\n
        request_parameters: {}
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_path:
            - dataset
            - data
    primary_key: []
    schema_loader:
      type: InlineSchemaLoader
      schema:
        type: object
        $schema: http://json-schema.org/draft-07/schema#
        properties: {}
        additionalProperties: true
version: 0.51.16
metadata:
  autoImportSchema:
    clients: true
```
