### DISCUSSION TITLE
Custom Labels to the dynamically created sync and normalization pods

### DISCUSSION THREAD

**Discussion by sookeke** [airbytehq/airbyte#33888] [Connector Questions]
I am looking for a way to inject custom labels the dynamically created **sync** pods during sync process(orchestrator, destination write, source read, normalization etc). I have tried using the below but couldn't get it to work. I am currently currently deploying Aribyte 0.50.38 on Kubernetes using the Helm Chart with Chart version 0.50.17
```
  jobs:

    .....

    kube:
      ## JOB_KUBE_ANNOTATIONS
      ## pod annotations of the sync job and the default pod annotations fallback for others jobs
      ##  jobs.kube.annotations [object] key/value annotations applied to kube jobs
      annotations: {}

      ## JOB_KUBE_LABELS
      ## pod labels of the sync job and the default pod labels fallback for others jobs
      ##  jobs.kube.labels [object] key/value labels applied to kube jobs
      labels:
         label1: test
         label2: airbyte-worker-pods
```

[a comment by an automated account is not shown]
