### DISCUSSION TITLE
storageClassName configurable in volumeClaimTemplates

### DISCUSSION THREAD

**Discussion by thenu97** [airbytehq/airbyte#37377] [Connector Ideas and Features]
We deployed airbyte during helm in kube with minio as our storage.

For PersistentVolumeClaim, we'd like StorageClass to be configurable as we do not use the default one in kube

something like below:
```
  volumeClaimTemplates:
      - metadata:
          name: airbyte-minio-pv-claim
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: {{ .Values.minio.storage.storageClassName}}
          resources:
            requests:
              storage: {{ .Values.minio.storage.volumeClaimValue}}
```

Please update the helm chart template

[a comment by an automated account is not shown]
