### DISCUSSION TITLE
What Postgres permissions does Airbyte need for external Postgres as metadata store?

### DISCUSSION THREAD

**Discussion by hongbo-miao** [airbytehq/airbyte#39519] [Connector Questions] [answered]
Based on https://github.com/airbytehq/airbyte-platform/blob/6b1b9661b878fd7d8398fbbef84f5f83caef90e8/charts/airbyte/values.yaml#L1397-L1398

It mentions "non-root username"

```yaml
externalDatabase:
  # -- Database host
  host: ""
  # -- non-root Username for Airbyte Database
  user: ""
```

What Postgres permissions does Airbyte need for external Postgres as metadata store?

Thanks!

**Comment by hongbo-miao** [comment, marked as answer]
Okay, here is my final psql script, basically I granted all privileges

```
create user airbyte_user with encrypted password 'xxx';

create database airbyte_db;
create database temporal_db;
create database temporal_visibility_db;

grant all privileges on database airbyte_db to airbyte_user;
grant all privileges on database temporal_db to airbyte_user;
grant all privileges on database temporal_visibility_db to airbyte_user;

\connect airbyte_db
grant all privileges on schema public to airbyte_user;

\connect temporal_db
grant all privileges on schema public to airbyte_user;

\connect temporal_visibility_db
grant all privileges on schema public to airbyte_user;
```

Note in my case, my Helm chart custom values have which is why you saw I created those Temporal databases in advance:

```yaml
temporal:
  extraEnv:
    # https://github.com/temporalio/docker-builds/blob/main/docker/auto-setup.sh
    # Ensure that the boolean values below are in string format
    - name: SKIP_DB_CREATE
      value: "true"
    - name: DBNAME
      value: temporal_db
    - name: VISIBILITY_DBNAME
      value: temporal_visibility_db
```

I published all my setup code at https://github.com/hongbo-miao/hongbomiao.com/issues/17463#issuecomment-2180242019 Hope it saves some time for folks who come here in future ☺️
