### DISCUSSION TITLE
Request to upload in ECR and use in EKS clsuter

### DISCUSSION THREAD

**Discussion by mrdevops12** [airbytehq/airbyte#42399] [General]
Hi Team, 
wget https://raw.githubusercontent.com/airbytehq/airbyte/master/run-ab-platform.sh
chmod +x run-ab-platform.sh
I am able to install Airbyte  in AWS EC2 instance or any Host machine using above method. I have 2 queries .
1. Query:
        In this approach image will automatically download from docker hub and install required dependences.
        My requirement is to upload in AWS ECR repo and try to run these. May I know how can we use this .
2 Query:
     May I know how can run this script in EKS kind of environment?.

**Comment by szemek** [comment]
If you want to have Docker images for Airbyte components / connectors stored on ECR, I recommend checking ECR pull through cache https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html

For EKS, use Helm charts https://docs.airbyte.com/deploying-airbyte/on-kubernetes-via-helm

**Reply by mrdevops12** [reply]
Thank you Szemek for your reply. EKS I will try using helm charts. My question is here to push aitbyate images to AWS ECR . If I run alone these images , envireonmnt will not up and running I think it has to go through via wget https://raw.githubusercontent.com/airbytehq/airbyte/master/run-ab-platform.sh
chmod +x run-ab-platform.sh like when We did using this script automatically it will fetch the desire images and configuration even .env file also has to create , even If I push images to ECR , How can we utilize these images to in this script

**Reply by szemek** [reply]
In `docker-compose.yaml` you need to update all the places

```yaml
    image: alpine/socat
    # ...
    image: airbyte/init:${VERSION}
    # ...
    image: airbyte/bootloader:${VERSION}
    # ...
    image: airbyte/db:${VERSION}
    # ...
    image: airbyte/worker:${VERSION}
    # ...
    image: airbyte/server:${VERSION}
    # ...
    image: airbyte/webapp:${VERSION}
    # ...
    image: airbyte/temporal:${VERSION}
    # ...
    image: airbyte/cron:${VERSION}
    # ...
    image: airbyte/airbyte-api-server:${VERSION}
    # ...
    image: airbyte/connector-builder-server:${VERSION}
    # ...
    image: airbyte/proxy:${VERSION}
    # ...
```
with ECR URIs
