### DISCUSSION TITLE
[helm/load balancer] Auth issue

### DISCUSSION THREAD

**Discussion by muhammadhrazzaq** [airbytehq/airbyte#44586] [Deployment]
Hello everyone,

I hope this message finds you well.

I am currently working on deploying Airbyte on Azure Kubernetes Service (AKS). I have successfully deployed Airbyte, and I can access it using port forwarding. However, I am facing an issue with authentication when accessing Airbyte through the LoadBalancer. Specifically, while the credentials configured in my values.yaml file work fine with port forwarding, they do not work when using the LoadBalancer.

I would greatly appreciate any assistance or insights you can provide to help resolve this issue. If there are specific configurations or steps that I might have overlooked, or if there are best practices for ensuring that credentials work properly with a LoadBalancer, your guidance would be invaluable.

Thank you very much for your support!

Best regards,

**Comment by marcosmarxm** [comment]
Can you provide more information about how are you configuring the load balancer and installing abctl? Thanks.

**Reply by muhammadhrazzaq** [reply]
I am using helm and 
this is my **nginx-configmap**

```
`apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: airbyte
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        upstream airbyte {
            server airbyte-airbyte-webapp-svc.airbyte.svc.cluster.local:80;
        }
        server {
            listen 80;

            location / {
                proxy_pass http://airbyte;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            # Error handling
            error_page 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
        }
    }`
```

This is my **nginx-deployment.yaml**

```
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
  namespace: airbyte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config`
```
          
This is mine **nginx-service.yaml**
```
`apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: airbyte
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer`
```

**Reply by muhammadhrazzaq** [reply]
> Can you provide more information about how are you configuring the load balancer and installing abctl? Thanks.

**I am using a reverse proxy in front of Airbyte**

**Reply by muhammadhrazzaq** [reply]
https://github.com/airbytehq/airbyte/discussions/44586?sort=new#discussioncomment-10430598

**Comment by muhammadhrazzaq** [comment]
This is my helm values.yaml file

```
global:
  edition: "community"
  airbyteUrl: "ip of lb"
  auth:
    enabled: true
    
  instanceAdmin:
      # -- Secret name where the instanceAdmin configuration is stored
      secretName: "airbyte-auth-secrets" 
      # -- The first name of the initial user
      firstName: ""
      # -- The last name of the initial user
      lastName:  ""
      emailSecretKey: "instance-admin-email"
      passwordSecretKey: "instance-admin-password"
  ingress:
    # -- Set to true to enable ingress record generation
    enabled: True
    # -- Specifies ingressClassName for clusters >= 1.18+
    className: "airbyte-ingress"
    # -- Ingress annotations done as key:value pairs
    annotations: 
      - kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # -- The list of hostnames to be covered with this ingress record.
    hosts: 
      - host: "ip of lb"
        http:
          paths:
            - backend:
                service:
                  # format is ${RELEASE_NAME}-airbyte-webapp-svc
                  name: airbyte-airbyte-webapp-svc
                  port:
                    number: 80 # service port, example: 8080
              path: /
              pathType: Prefix

```

[a comment by an automated account is not shown]
