### DISCUSSION TITLE
Airbyte & Snowflake connector

### DISCUSSION THREAD

**Discussion by l-taranenko** [airbytehq/airbyte#45946] [Connector Builder]
We have an issue connecting Airbyte which is hosted in GCP in Kubernetes and Snowflake trial account in GCP as well
We did all the steps provided in the airbyte guide https://docs.airbyte.com/integrations/destinations/snowflake
However, once we try the connection we have 502 error, which shown after the timeout

For example connection between airbyte and other SaaS tool (Chargebee) to pull the data from Chargebee works as expected

And we were able to connect Snowflake and Looker

Does anyone have ideas what can be wrong?

**Comment by szemek** [comment]
Have you tried to increase timeouts with values.yaml

```yaml
global:
  env_vars:
    HTTP_IDLE_TIMEOUT: 1800s

webapp:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: internal
      nginx.ingress.kubernetes.io/proxy-body-size: 16m
      nginx.ingress.kubernetes.io/proxy-send-timeout: 1800
      nginx.ingress.kubernetes.io/proxy-read-timeout: 1800
```
and increase timeouts for load balancers?

[a comment by an automated account is not shown]
