### DISCUSSION TITLE
Configure TEMPORAL_HISTORY_RETENTION_IN_DAYS in abctl deployment

### DISCUSSION THREAD

**Discussion by cernadasjuan** [airbytehq/airbyte#46355] [Deployment] [answered]
Hi, I migrated from a docker deployment to abctl, and I don't know how to configure the env variable `TEMPORAL_HISTORY_RETENTION_IN_DAYS`. This is very important for me to save disk space.

Thanks a lot!

**Comment by lideke** [comment]
Hi @marcosmarxm, 
Any idea ?

**Comment by cernadasjuan** [comment, marked as answer]
Solved: add this to the `values.yaml` file

```yaml
global:
  env_vars:
    TEMPORAL_HISTORY_RETENTION_IN_DAYS: 7
```
