### DISCUSSION TITLE
Changing to private images

### DISCUSSION THREAD

**Discussion by meneizs** [airbytehq/airbyte#46913] [Platform General Questions]
I'm deploying Airbyte on Kubernetes, version 0.64.1, and we've been facing issues with Docker Hub image pull limits. As a workaround, we started duplicating the images to a private repository. However, when I change the orchestrator container image in the YAML file, the change is not applied to the jobs, and Airbyte's default image is still used. Below is the section where I defined the image (I've placed it in two spots based on the YAML examples I found):

```
worker:
   containerOrchestrator:
   # -- Orchestrator image
   image: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/container-orchestrator
   tag: 0.64.1

workload-launcher:
   containerOrchestrator:
   # -- Orchestrator image
   image: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/container-orchestrator
   tag: 0.64.1
```

I also need to change the image for the Socat and connector sidecar. 
For these i've tried to change de extraEnv in yaml too, but doesn't worked.. 

```
worker:
  extraEnv:
    - name: CONNECTOR_SIDECAR_IMAGE
      value: #########################/connector-sidecar:0.64.1
    - name: CONTAINER_ORCHESTRATOR_IMAGE
      value: #########################/container-orchestrator:0.64.1
    - name: JOB_KUBE_SOCAT_IMAGE
      value: #########################/socat:1.7.3.4-r0
    - name: JOB_KUBE_BUSYBOX_IMAGE
      value: #########################/busybox:1.28
    - name: JOB_KUBE_CURL_IMAGE
      value: #########################/curl:7.83.1
```

Can anyone help me with this?
