### DISCUSSION TITLE
temporal pod not finding an expected key on deployment with external database

### DISCUSSION THREAD

**Discussion by bstamas42** [airbytehq/airbyte#51054] [Deployment]
Hi, I am really struggling with configuring an external database on GCP for Airbyte. 

I've read the documentation here: https://docs.airbyte.com/operator-guides/configuring-airbyte-db
and have tried a bunch of different ways to configure my values.yaml file, but I'm not getting anywhere. 

The temporal pod is having difficulty finding a key for the database ending the logs with this message when it boots up: 
Unable to load configuration: config file corrupted: yaml: line 11: did not find expected key.

- I can connect to the external database from the cluster.
- I've deleted everything in the database between deployments just to make sure there's nothing there to trip the installation up.
- I'm installing with helm using a values.yaml file.
- I've added a secret that has mounted successfully prior with the DATABASE_USER/DATABASE_PASSWORD variables in it.
- This deployment process worked with the internal database.  

Below are the parts of the values file I think are applicable to this question - am I missing something? Please, any help would be greatly appreciated.

```
# Helm Values.yaml for Airbyte
apiVersion: v1
global:
  airbyteUrl: <url>
  database:
    type: external
    userSecretKey: DATABASE_USER
    secretName: airbyte-config-secrets
    host: <ip-address>
    5432
    database: airbyte
    passwordSecretKey: DATABASE_PASSWORD
  storage:
    type: "GCS"
    storageSecretName: airbyte-config-secrets
    bucket:
      log: airbyte-persistent-storage
      state: airbyte-persistent-storage
      workloadOutput: airbyte-persistent-storage
    gcs:
      projectId: <project-id>
      credentialsPath: <path>

airbyteBootloader:
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: 1
  nodeSelector:
    dedicated: airbyte
  tolerations:
    - key: "key"
      operator: "Equal"
      value: "airbyte"
      effect: "NoSchedule"

postgresql:
  enabled: false

externalDatabase:
  secretName: airbyte-config-secrets
  host: <ip>
  port: 5432
  database: airbyte
  userSecretKey: DATABASE_USER
  passwordSecretKey: DATABASE_PASSWORD

temporal:
  nodeSelector:
    dedicated: airbyte
  tolerations:
    - key: "key"
      operator: "Equal"
      value: "airbyte"
      effect: "NoSchedule"
```
