### DISCUSSION TITLE
Helm chart doesn't use auth secretName value

### DISCUSSION THREAD

**Discussion by akondaurov** [airbytehq/airbyte#52720] [Deployment]
I have a helm chart with values:
```
 auth:
      # -- Secret name where the instanceAdmin configuration is stored
      secretName: "airbyte-secrets"
      # -- The first name of the initial user
      firstName: ""
      # -- The last name of the initial user
      lastName:  ""
      # -- The key within `emailSecretName` where the initial user's email is stored
      emailSecretKey: "AIRBYTE_USER_NAME"
      # -- The key within `passwordSecretName` where the initial user's password is stored
      passwordSecretKey: "AIRBYTE_USER_PASS"
```

but, during deployment I have the error:

`Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.20.0.1:443/api/v1/namespaces/airbyte/secrets/airbyte-auth-secrets. Message: secrets "airbyte-auth-secrets" is forbidden: User "system:serviceaccount:airbyte:airbyte-sa" cannot get resource "secrets" in API group "" in the namespace "airbyte". Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=secrets, name=airbyte-auth-secrets, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=secrets "airbyte-auth-secrets" is forbidden: User "system:serviceaccount:airbyte:airbyte-sa" cannot get resource "secrets" in API group "" in the namespace "airbyte", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).`

Chart should use **airbyte-secrets**  secretName instead of **airbyte-auth-secrets**.
