### DISCUSSION TITLE
Deploying Airbyte on VM through abctl with self-signed TLS Certificate

### DISCUSSION THREAD

**Discussion by baronvonbeck** [airbytehq/airbyte#53157] [Deployment]
Attempting to install a self-signed TLS certificate on a VM-hosted installation of Airbyte, as I'd prefer not to use the --insecure-cookies option. No issues running abctl, configuring basic auth, pointing to an external Postgres database, getting in and building connectors with that option enabled, etc. But trying to get a self-signed cert installed has been just about impossible. I've searched and made various attempts at combinations of the below settings for several hours:
- Creating TLS secrets via:
    -  A yaml file with base64 key/cert pasted in, and using the `--secret tls_secret.yaml` parameter during abctl local install
    - Directly via kubectl, referencing key/cert files stored locally on the VM
- Referencing both of those secrets through values.yaml webapp.ingress (see below)
- Running `abctl local install` and without host parameter in the install command, i.e. `abctl local install --host "myairbyte.local"`
- Various things within the values.yaml before running `abctl local install --values values.yaml` (see below) 
- Editing nginx ingress in place directly with kubectl after Airbyte is up and running

Example section in values.yaml:
```
webapp:
  ingress:
    enabled: true  # Have tried with this true and false; false doesn't generate anything, true generates the ingress.
    className: nginx  # Have left this commented and uncommented; commenting out results in an entirely separate ingress object named "airbyte-abctl-webapp" getting made, leaving it in either creates it as part of the standard nginx ingress or throws a conflict error depending on if I specified --host when running abctl local install.
    hosts:
      - host: myairbyte.local
        paths:
          - path: /
          pathType: ImplementationSpecific
    tls:
      - secretName: airbyte-tls-secrets
         hosts:
         - myairbyte.local
```

The farthest I get is that I see a 308 permanent redirect to the custom host when curling it with http on port 8000, but if I go to it with https on either 443 or 8000 I get connection refused. Not doing anything custom with ports otherwise, and I opened up NSGs on the VM to allow everything inbound on 443 and 8000 to rule anything out. 

Haven't been able to find any documentation or examples of getting a cert installed - the end of Airbyte's youtube video https://www.youtube.com/watch?v=1yBBkzJizKk hinted that they were going to release another video showing how, but I don't see it on their channel. Not able to find anything on Google that's worked either, with abctl specifically or with kubectl + nginx in general. If anyone has an example of a working configuration, or something else to try, I'd be extremely grateful.

[a comment by an automated account is not shown]
