### DISCUSSION TITLE
Password prompting not working

### DISCUSSION THREAD

**Discussion by reikmich** [airbytehq/airbyte#55824] [Deployment]
Hello, I'm quite new to deploying stuff with helm charts so sorry for maybe a quite obvious question. 

So I'm trying to deploy airbyte in my kubernetes cluster and have the following values.yaml:

```yaml
global:
  edition: "community"
  airbyteUrl: https://airbyte.myCompany.com
  auth:
    enabled: true
    instanceAdmin:
      secretName: "airbyte-config-secrets"
      firstName: "XXX"
      lastName: "XXX"
      emailSecretKey: "instance-admin-email"
      passwordSecretKey: "instance-admin-password"

airbyte:
  webapp:
    enabled: true
  worker:
    enabled: true
  db:
    host: airbyte-db.airbyte.svc.cluster.local
    port: 5432
    database: airbyte
    username: airbyte
    password: 'XXX'
```

and it doesn't matter if I put the auth inside the airbyte block

```yaml
global:
  edition: "community"
  airbyteUrl: https://airbyte.myCompany.com

airbyte:
  webapp:
    enabled: true
  worker:
    enabled: true
  db:
    host: airbyte-db.airbyte.svc.cluster.local
    port: 5432
    database: airbyte
    username: airbyte
    password: 'XXX'
  auth:
    enabled: true
    instanceAdmin:
      secretName: "airbyte-config-secrets"
      firstName: "XXX"
      lastName: "XXX"
      emailSecretKey: "instance-admin-email"
      passwordSecretKey: "instance-admin-password"
```

    
  I have also applied the airbyte-config-secrets.yaml file accordingly.
  
  However it's not working  that I'm getting a username password prompt if I'm accessing the page it's directly and public available.

[a comment by an automated account is not shown]
