### DISCUSSION TITLE
path_in_oauth_response without effect

### DISCUSSION THREAD

**Discussion by wuwenrufeng** [airbytehq/airbyte#58589] [Connector Builder]
OAuth Flow returns the nested access_token only, under the data property
```yaml
oauth_config_specification:
      oauth_connector_input_specification:
        consent_url: >-
          https://open.oceanengine.com/audit/oauth.html?app_id={{client_id_value}}&state={{state}}&material_auth=1&rid=ndung0tt71
        access_token_url: https://ad.oceanengine.com/open_api/oauth2/access_token/
        extract_output:
          - access_token
          - refresh_token
        access_token_headers:
          Content-Type: "application/json"
        access_token_params:
          grant_type: "auth_code"
          app_id: "{{client_id_value}}"
          secret: "{{client_secret_value}}"
          auth_code: "{{auth_code_value}}"
      complete_oauth_output_specification:
        required:
          - access_token
          - refresh_token
          - token_expiry_date
        properties:
          access_token:
            type: string
            path_in_connector_config:
              - client_access_token
            path_in_oauth_response:
              - data
              - access_token
          refresh_token:
            type: string
            path_in_connector_config:
              - client_refresh_token
            path_in_oauth_response:
              - data
              - refresh_token
          token_expiry_date:
            type: string
            path_in_connector_config:
              - token_expiry_date
            path_in_oauth_response:
              - data
              - expires_in
```
when Authenticate your oceanengine account get error return:
Internal Server Error: java.io.IOException: Missing 'access_token' field in the `OAuth Output`. Expected fields: [access_token, refresh_token]. Response data: {"code":0,"message":"OK","request_id":"20250422155842CC6E962055","data":{"access_token":"d80a378a2bc88074123","advertiser_ids":[1823828494349465],"expires_in":86400,"refresh_token":"92d4305eeaa56b8e0ed881","refresh_token_expires_in":2592000}}

[a comment by an automated account is not shown]
