### ISSUE TITLE
Helm Chart: missing hooks deletion policy

### ISSUE THREAD

**Issue by EinavDanielDX** [airbytehq/airbyte#11150]
## Environment
- **Airbyte chart version**: 0.3.0

## Current Behavior
When deploying Airbyte from helm chart, if  'airbyte-bootloader' pre upgrade hook is already exist - the upgrade will fail with this this error:

> Error: UPGRADE FAILED: pre-upgrade hooks failed: warning: Hook pre-upgrade datricks/charts/airbyte/templates/bootloader/pod.yaml failed: object is being deleted: pods "airbyte-bootloader" already exists

## Expected Behavior
Kubernetes objects created by hooks should have (some) deletion policy so it would be refreshable

## Suggestion:
add `deletePolicy: before-hook-creation` annotation where hook annotations takes place, such as
```
annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    deletePolicy: before-hook-creation
```

that includes the following files:
- env-configmap.yaml
- external-db.yaml
- serviceaccount.yaml
- pod.yaml
