### ISSUE TITLE
Make Connector docs CHANGELOG into a machine readable file to support auto generation and appending to docs files

### ISSUE THREAD

**Issue by noahkawasaki-airbyte** [airbytehq/airbyte#12031]
## Tell us about the problem you're trying to solve
In order to support a fully automated Connector version bumping pipeline, the changelog needs to be reliably automatically managed because it contains a row for each version bump. Currently you need to manually change a version in the Dockefile, and the CHANGELOG of a markdown file with this. Its two places containing the same info and can be annoying, another annoying thing is that there is a Date column which can change everyday the PR does not merge.

Changelogs contain the following:
- Version
- Date
- Pull Request
- Subject

Each of those things could be totally generated into a row for a markdown table if the changelogs were managed in a machine readable format.

## Describe the solution you’d like

1) in each source/destination dir, create something like CHANGELOG.yaml that might look like:

```yaml
CHANGELOG:
  - version: 0.4.11
     date: 2022-04-13
     pull_request: 11954
     subject: PR title
  - version: 0.4.10
     date: 2022-04-10
     pull_request: 11950
     subject: PR title
```

2. Create a script that can read this file, generate a new row at the top with the current PRs bumped version, the date this is happening (also helps devs not have to keep updating the date if the PR takes longer than anticipated), the PR number/URL, and the PR title
3. Take this YAML file and convert it into a Markdown table with something like [this](https://stackoverflow.com/questions/33181846/programmatically-convert-pandas-dataframe-to-markdown-table)
4. Delete current changelog table in the docs markdown page and replace

## Describe the alternative you’ve considered or used
Manually updating version and rows

## Are you willing to submit a PR?
Yes
