### ISSUE TITLE
[EPIC] All CDK Connectors emit `AirbyteTraceMessage` when something goes wrong

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#12322]
Using `AirbyteTraceMessage` will set `failure_reason` metadata automagically.  This replaces the current failure behavior of logging and throwing when something goes wrong.  This story is to update the CDK as naively as possible such that any crash produces a log message in the right format before existing.  e.g. this would be wrapping the calls to `read()` and `write()` in a try/catch.

Relevant Spec: https://docs.google.com/document/d/1ctrj3Yh_GjtQ93aND-WH3ocqGxsmxyC3jfiarrF6NY0/edit#

```ts
Class AirbyteLoggedException () {
  constructor(e:Error, display_message:string, failureType=ENUM<failure_types>=”system_error”) {
    log(new AirbyteLogMessage(e, level)) ;   
    log(new AirbyteTraceMessage(type=”error”, display_message, internalMessage=e, stack_trace=e.stack, failureType)) ;
    process.exit(1)
  }
}

// usage

try {
  await read(config, configured_catalog);
} catch (error) {
  throw AirbyteLoggedException(error, ‘could not connect to API, check your password’, “user_error”);
}
```

Which produces:

```yml
 AirbyteTraceMessage:
    type: error_status
    emitted_at: 123456
    error_status: 
        message: Cannot connect to postgres.  Check your credentials
        internal_message: JDBC Error - ssl cert invalid
        stack_trace: JDBC Error - ssl cert invalid (line 101)\nfrom connect() on line 101\nfrom read() on line 202
        failure_type: config_error
```

**CDKs**
- [x] #12471
- [x] #12472
- [ ] https://github.com/airbytehq/airbyte/issues/11322
- [x] #12473

---

SAT Ideas:
* All connectors have an invalid config file - so, if you run a sync with the invalid config file, an AirbyteTraceMessage should be emitted
