### ISSUE TITLE
Low-code connectors: Support configurable checkpoint interval

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#12976]
## What
The CDK provides a mechanism to checkpoint the state. Currently, streams can leverage this feature by overriding the `state_checkpoint_interval` function to return an int representing the interval (int terms of records) at which we should checkpoint.

We should make this feature an option in low-code cdk.

## How
Simple retriever can override `state_checkpoint_interval` and have an additional field defining the interval, and defaulting to None.

Sample config:
```
retriever:
  class_name: "airbyte_cdk.sources.declarative.retrievers.simple_retriever.SimpleRetriever"
  name: "{{ options['name'] }}"
  state: <...>
  stream_slicer: <...>
  paginator: <...>
  primary_key: "{{ options['primary_key'] }}"
  state_checkpoint_interval: 1000
```
