### ISSUE TITLE
Low-code connectors: Support removing fields from records

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#12988]
## What
The freshsales and twilio connectors remove fields from the records before emitting them. This should be an option in low-code cdk

## How
```
extractor:
  class_name: airbyte_cdk.sources.declarative.extractors.jq.JqFetcher
    decoder: "*ref(decoder)"
    transformer:
      class_name: airbyte_cdk.sources.declarative.extractors.FieldTranformer
        transform:
          remove_fields:
           - field
```

removing the fields can then be done by iterating over the records and over the fields to remove
```
for record in records:
  for field in self._fields_to_remove:
    record.pop(field, None)
yield from records
```

## Alternative
The simplest, but not so low-code way to do this is with jello with a non-trivial transform
`"[{k:v for k,v in d.items() if k != 'value_to_remove'} for d in _.data]"`
