### ISSUE TITLE
Low-code connectors: Support min and max start/end dates

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#12990]
## What
Many sources will throw error if we requests data for a future date.
The harvest source will throw an error if we request data with a start_date more recent than 1 year ago.
It should be possible to configure a min and a max date and let the connector adjust the requested date

## How
this can be done in the `DatetimeStreamSlicer`, which already takes in a start_time and an end_time.
We'll want to update these parameters with a `Date` object
```
MinMaxDate: 
  date: InterpolatedString
  min: Optiona[InterpolatedString]
  max: Optiona[InterpolatedString]
```
the datetime stream slicer can then ensures the date passed in from the config is valid.

To support min/max dates that are relative to now, we can add a `daydelta` function to the jinja template which will produce a timedelta
example: `"{{today_utc() + daydelta(1)}}"`

### start date cannot be earlier than 1 year prior to the end date
```
stream_slicer:
  class_name: DatetimeStreamSlicer
  start_date:
     class_name: MinMaxDate
     date: "{{ config['start_date'] }}
     min: "{{ end_date + daydelta(-365) }}"
  end_date: "{{ today_utc() }}"

```
