### ISSUE TITLE
Low-code connectors: support adding fields to records before emitting them

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#12998]
## How
Similar to https://github.com/airbytehq/airbyte/issues/12988

Add a transformer property to the extractor object. Then add the fields that are in the fields_to_add map

```
record_selector: extractor: 
  class_name: airbyte_cdk.sources.declarative.extractors.jq.JqFetcher
    decoder: "*ref(decoder)"
    transformer:
      class_name: airbyte_cdk.sources.declarative.extractors.FieldTranformer
        transform:
          add_fields:
           field: "{{ }}"
```

## Examples
Add a field from a subobject in the record (pivotal-tracker)
```
transformer:
    class_name: airbyte_cdk.sources.declarative.extractors.FieldTranformer
    transform:
    add_fields:
      project_id: "{{ record.project.id }}"
```

Add a field coming from the config (woocommerce)
```
transformer:
  class_name: airbyte_cdk.sources.declarative.extractors.FieldTranformer
   transform:
   add_fields:
      shop: "{{ config.shop }}"
```

Add a field coming from the state (zendesk-sunshine)
```
transformer:
  class_name: airbyte_cdk.sources.declarative.extractors.FieldTranformer
   transform:
   add_fields:
    object_type: "{{ stream_state.type }}"
```
## Alternative
The smallest lift for this feature would be to use Jello with a non-trivial transform
`"[{**{k:v for k,v in d.items()}, **{'project_id': d['project']['id']}} for d in _.data]"`
