### ISSUE TITLE
Low-code connectors: Support configurable OAuth payload and refresh authenticator

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#12995]
## What
The authenticator for the Outreach and tplcentral connectors requires a custom payload

## How
* The payload in `get_refresh_request_body` should be configurable
* ~It should be possible to configure an authenticator to use when refreshing the request token~  done as part of https://github.com/airbytehq/airbyte/pull/13733

Sample config:
```
authenticator:
  class: Oauth2Authenticator
  token_refresh_endpoint: ""https://api.outreach.io/oauth/token""
  client_id: "{{ config['client_id'] }}"
  client_secret: "{{ config['client_secret'] }}"
  scopes:
    - "scope1"
    - "scope2"
  token_expiry_date: ""
  access_token_name: ""
  expires_in_name: ""
  refresh_request_body:
    grant_type: "refresh_token"
    client_secret: "{{ config['client_secret'] }}"
    redirect_uri: "{{ config['redirect_uri'] }}
  refresh_authenticator: "*ref(refresh_authenticator)"
```
