### ISSUE TITLE
Low-code connectors: Support configurable lookback window

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#12997]
Connectors needing a lookback window:
* facebook marketing
* orb
* paystack
* slack
* stripe

In all cases, the lookback window is used to substract days from the stream_state when setting a start time in the request parameters

**Comment by brianjlai** [comment]
notes from grooming:
- in the future add examples of what the config would look like
- General consensus is it can be included as a part of the DatetimeStreamSlicer as a field

Potential Config Options:
DatetimeStreamSlicer
```
stream_slicer:
  type: "DatetimeStreamSlicer"
  start_time: "2017-01-01"
  end_time: "2022-01-01"
  step: "10d"
  lookback: "2d"
  cursor_field: "created"
  datetime_format: "%Y-%m-%d"
  request_parameters:
    start_time_param_name: "start_time"
    end_time_param_name: "end_time"
```

-- or --

MinMaxDatetime:
```
MinMaxDatetime:
  datetime: "{{ timestamp() }}"
  min_datetime: "{{ stream_state['cursor'] }}"
  lookback: "1d"
```
