### ISSUE TITLE
Low-code connectors: Support custom stream slices

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#13002]
## What
The Metafields stream of the recharge connector reads records with hardcoded stream slices

```
    def read_records(self, stream_slice: Optional[Mapping[str, Any]] = None, **kwargs) -> Iterable[Mapping[str, Any]]:
        owner_resources = ["customer", "store", "subscription"]
        for owner in owner_resources:
            yield from super().read_records(stream_slice={"owner_resource": owner}, **kwargs)
```

The streams for google-search-console also read records from a list of configurated values
```
    def stream_slices(
        self, sync_mode: SyncMode, cursor_field: List[str] = None, stream_state: Mapping[str, Any] = None
    ) -> Iterable[Optional[Mapping[str, Any]]]:
        for site_url in self._site_urls:
            yield {"site_url": site_url}
```

It should be possible to configure this list through the declarative DSL

## Connectors
- recharge
```
slicer:
  class_name: "airbyte_cdk.sources.declarative.stream_slicers.substream_slicer.ListIteratorSlicer"
  slice_values:
    - customer
    - store
    - subscription
  slice_definition:
    owner_resource: "{{ slice_value }}"
  state: "*ref(state)"
```
- github
refer to an array in the config
```
slicer:
  class_name: "airbyte_cdk.sources.declarative.stream_slicers.substream_slicer.ListIteratorSlicer"
  slice_values: "*ref(config['repositories'])
  slice_definition:
    repository: "{{ slice_value }}"
  state: "*ref(state)"
```
- google-search-console
Just like github. Worth pointing out this will also require exposing a method to sanitize the urls
```
slicer:
  class_name: "airbyte_cdk.sources.declarative.stream_slicers.substream_slicer.ListIteratorSlicer"
  slice_values: "*ref(config['site_url'])
  slice_definition:
    repository: "{{ slice_value }}"
  state: "*ref(state)"
```
