### ISSUE TITLE
[Low-code connectors] Support stream slicing on multiple dimensions

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#13434]
google-search-console's stream slicing is a 3-way zip of 
1. site_url: user can pass many site_url, and we want to process all of them
2. search_type: can be one or many of `['web', 'news ','image', 'video']`
3. time window: given a time period, yield start_date and end_dates.

This feature can be built on top of the [list based stream slicer ](https://github.com/airbytehq/airbyte/issues/13002) and the [datetime stream slicer](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/stream_slicers/datetime_stream_slicer.py#L15)

The resulting slicer would look like
```
site_url_slicer:
  class_name: "airbyte_cdk.sources.declarative.stream_slicers.substream_slicer.ListIteratorSlicer"
  slice_values:
    - https://airbyte.io
    - https://google.com
  slice_definition:
    site_url: "{{ slice_value }}"
  state: "*ref(state)"

search_type_slicer:
  class_name: "airbyte_cdk.sources.declarative.stream_slicers.substream_slicer.ListIteratorSlicer"
  valid_slice_values:
    - web
    - news
    - image
    - video
  slice_values:
    - web
  slice_definition:
    owner_resource: "{{ slice_value }}"
  state: "*ref(state)"

datetime_stream_slicer:
  class_name: "airbyte_cdk.sources.declarative.stream_slicers.datetime_stream_slicer.DatetimeStreamSlicer"
  start_time:
    class_name: "airbyte_cdk.sources.declarative.interpolation.interpolated_string.InterpolatedString"
    string: "{{ stream_state['created'] }}"
    default: "{{ config['start_time'] }}"
  end_time: "{{ today_utc() }}"
  step: "1000d"
  cursor_value: "{{ stream_state['created'] }}"
  datetime_format: "%Y-%m-%d"

stream_slicer:
  class_name: "airbyte_cdk.sources.declarative.stream_slicers.zip_stream_slicer.ZipStreamSlicer"
  slicers:
    - "ref(site_url_slicer)"
    - "ref(search_type_slicer)"
    - "ref(datetime_stream_slicer)"
```

mixpanel has a very similar stream slicing algorithm for the funnel stream, but depends on a parent stream:
```
substream_slicer:
  class_name: "airbyte_cdk.sources.declarative.stream_slicers.substream_slicer.SubstreamSlicer"
  parent_stream: "*ref(applications_stream)"
  slice_definition:
    parent_id: "{{ parent_record['id'] }}"
    parent_name: "{{ parent_record['name'] }}"
  state: "*ref(state)"

datetime_stream_slicer:
  class_name: "airbyte_cdk.sources.declarative.stream_slicers.datetime_stream_slicer.DatetimeStreamSlicer"
  start_time:
    class_name: "airbyte_cdk.sources.declarative.interpolation.interpolated_string.InterpolatedString"
    string: "{{ stream_state['created'] }}"
    default: "{{ config['start_time'] }}"
  end_time: "{{ today_utc() }}"
  step: "1000d"
  cursor_value: "{{ stream_state['created'] }}"
  datetime_format: "%Y-%m-%d"

stream_slicer:
  class_name: "airbyte_cdk.sources.declarative.stream_slicers.zip_stream_slicer.ZipStreamSlicer"
  slicers:
    - "ref(substream_slicer)"
    - "ref(datetime_stream_slicer)"
```

the zenloop connector follows a similar pattern:
* loop over `parent_record["public_hash_id"]`
* loop over dates to process
```
