### ISSUE TITLE
Regression: Helm install failing with YAML parse error

### ISSUE THREAD

**Issue by erikcw** [airbytehq/airbyte#13898]
I'm attempting to upgrade to the latest airbyte version with the helm chart for my K8s cluster on EKS.  I had successfully installed airbyte a few weeks ago with these same settings.

```
helm install airbyte ./charts/airbyte -f values.yaml --namespace airbyte
Error: INSTALLATION FAILED: YAML parse error on airbyte/templates/worker/deployment.yaml: error converting YAML to JSON: yaml: line 213: did not find expected key
```

values.yaml
```
postgresql:
  enabled: false
externalDatabase:
  host: "*************************"
  existingSecret: "airbyte-extra-secrets"
  existingSecretPasswordKey: "POSTGRES_PASSWORD"
logs:
  minio:
    enabled: false
  s3:
    enabled: true
    bucket: ************
    bucketRegion: us-east-1
  accessKey:
    existingSecret: "airbyte-extra-secrets"
    existingSecretKey: "LOGS_S3_AWS_ACCESS_KEY_ID"
  secretKey:
    existingSecret: "airbyte-extra-secrets"
    existingSecretKey: "LOGS_S3_AWS_SECRET_ACCESS_KEY"
podSweeper:
  nodeSelector:
    kubernetes.io/arch: amd64
  extraEnv:
    - name: JOB_KUBE_SOCAT_IMAGE
      value: "alpine/socat:1.7.4.3-r0"
    - name: JOB_KUBE_NODE_SELECTORS
      value: "kubernetes.io/arch=amd64"
temporal:
  nodeSelector:
    kubernetes.io/arch: amd64
minio:
  persistence:
    enabled: false
  nodeSelector:
    kubernetes.io/arch: amd64

```
