### ISSUE TITLE
Refactor low-code paginator and stream slicer to increase cohesion

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#14305]
## Tell us about the problem you're trying to solve
Implementing pagination requires the developer to define a paginator, and update the request parameters or headers. We can streamline this process by keeping the semantics together and letting the paginator update the request parameters or headers as needed.

The same is true to support incremental syncs. This subset stream definition shows that incremental supports requires 3 related, but disjoint fields:
```python
bounces_stream:
  options:
    cursor_field: ["created"]
    retriever:
      requester:
        request_options_provider:
          request_parameters:
            start_time: "{{ max(stream_state['created'], timestamp(stream_slice['start_date'])) }}"
            end_time: "{{ timestamp(stream_slice['end_date']) }}"
      state:
        initial_mapping:
          created: "{{ last_record.created }}"
      stream_slicer:
        type: "DatetimeStreamSlicer"
        start_time: "2017-01-01"
        end_time: "2022-01-01"
        step: "10d"
        cursor_value: "{{ stream_state['created'] }}"
        datetime_format: "%Y-%m-%d"
```
* state object with a `created` field pointing to the created value of the last record read
* `start_time` request parameters pointing to the `created` field of the state object
* stream slicer's date range

## Describe the solution you’d like
We can add more context to the stream_slicer and pagination object so they're responsible for everything related to state and pagination respectively.

The update stream definition would look like
```python
bounces_stream:
  options:
    retriever:
      stream_slicer:
        type: "DatetimeStreamSlicer"
        start_time: "2017-01-01"
        end_time: "2022-01-01"
        step: "10d"
        cursor_field: "created"
        datetime_format: "%Y-%m-%d"
        request_options_provider:
          request_parameters:
            start_time: "{{ timestamp(cursor) }}"
            end_time: "{{ timestamp(end_time) }}"
```

the same pattern can be applied on the paginator:
```
  paginator:
    type: "NextPageUrlPaginator"
      path: "{{ decoded_response._metadata.next}}"
```
or
```
  paginator:
    type: "OffsetPaginator"
        request_options_provider:
          request_parameters:
            offset: "{{ decoded_response.offset}}"
```

**Comment by girarda** [comment]
grooming notes:
* need to make sure we have an easy way to assess the params set on a request 

* we can make this more declarative:
```
bounces_stream:
  options:
    retriever:
      stream_slicer:
        type: "DatetimeStreamSlicer"
        start_time: "2017-01-01"
        end_time: "2022-01-01"
        step: "10d"
        cursor_field: "created"
        datetime_format: "%Y-%m-%d" # this is how we'll parse the cursor field and how we'll format the request param values
        request_parameters:
            start_time_param_name: "start_time"
            end_time_param_name: "end_time"
```
