### ISSUE TITLE
Upgrading Airbyte - Helm chart has `version: placeholder` in some dependencies

### ISSUE THREAD

**Issue by jan-benisek** [airbytehq/airbyte#15656]
## Environment
- **Airbyte version**:  example is 0.39.35-alpha
- **OS Version / Instance**:  -
- **Deployment**: k8s with Helm chart
- **Source Connector and version**: NA
- **Destination Connector and version**:  NA
- **Step where error happened**: Upgrade Airbyte

## Current Behavior
- when I am trying to update Airbyte, I am getting an error
```
dependency build error: failed to add remote dependency 'temporal': improper constraint: placeholder
```
- when looking at [Chart.yaml](https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/Chart.yaml) I see `placeholder` where should be a version in the dependencies:

```yaml
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - condition: postgresql.enabled
    name: postgresql
    version: 10.x.x
    repository: https://charts.bitnami.com/bitnami
  - condition: logs.minio.enabled
    name: minio
    version: 11.x.x
    repository: https://charts.bitnami.com/bitnami
  - condition: airbyte-bootloader.enabled
    name: airbyte-bootloader
    repository: "https://airbytehq.github.io/helm-charts/"
    version: placeholder # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - condition: temporal.enabled
    name: temporal
    repository: "https://airbytehq.github.io/helm-charts/"
    version: placeholder # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - condition: webapp.enabled
    name: webapp
    repository: "https://airbytehq.github.io/helm-charts/"
    version: placeholder # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - condition: server.enabled
    name: server
    repository: "https://airbytehq.github.io/helm-charts/"
    version: placeholder # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - condition: worker.enabled
    name: worker
    repository: "https://airbytehq.github.io/helm-charts/"
    version: placeholder # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - condition: pod-sweeper.enabled
    name: pod-sweeper
    repository: "https://airbytehq.github.io/helm-charts/"
    version: placeholder # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```
- Looks like this happened in this PR: https://github.com/airbytehq/airbyte/pull/14794

## Expected Behavior
- upgrade should work

## Logs
- NA

## Steps to Reproduce
1. deploy k8s using flux
2.
3.

## Are you willing to submit a PR?
- no

**Comment by jan-benisek** [comment]
Update - I think we can resolve this by pointing to the Helm repository, instead of pulling chart from this repo.
Is there an official guide? It is a little bit confusing, thanks 🙏

**Comment by xpuska513** [comment]
https://docs.airbyte.com/deploying-airbyte/on-kubernetes-via-helm

**Comment by xpuska513** [comment]
Hi @jan-benisek , so in short explaination you need to grab latest version of the chart here: https://artifacthub.io/packages/helm/airbyte/airbyte
And replace the placeholder value with the version itself.
I did that in order to simplify the CI workflow I developed, but looks like I added more confusion with that step.
I'll do a PR that will mitigate this confusion, but while I do that I'll do a fast doc update.

Sorry for inconvenience. If you'll have more questions, don't hesitate to ask them here.

**Comment by xpuska513** [comment]
EDIT: Sorry for another confusion @jan-benisek , you don't need to replase everything while deploying from the helm repo, just add it as described in docs and it'll work.

**Comment by xpuska513** [comment]
The CI workflows replaces the `placeholder` value in the `Chart.yaml` file with the new release version.

**Comment by jan-benisek** [comment]
@xpuska513 thanks a lot for your time and help, I appreciate it. We tried to pull from help repo and it worked (that part).
We struggled a bit with external database (we use RDS and we were getting "wrong secret") and eventually this worked:
```yaml
database:
        secretName: foo
        secretValue: BAR
```

But then we got another error with Minio. Despite the fact that we are not using it, it was complaining that secrets were missing. Looks like it is enabled even if we explicitly disable it like so:
```yaml
logs:
        minio:
          enabled: false
        externalMinio:
          enabled: false
```
I thought you might want to know. I will probably create another issue if I have time. But in the meantime, we can close this one. Again, thanks a lot!
