### ISSUE TITLE
Helm Chart: improve airbyte-metrics support

### ISSUE THREAD

**Issue by milesarmstrong** [airbytehq/airbyte#16129]
## Tell us about the problem you're trying to solve
We are deploying airbyte using the [Helm chart](https://github.com/airbytehq/airbyte/tree/master/charts/airbyte).

We'd like to enable metrics collection via Open Telemetry. The Helm chart doesn't currently support the required `airbyte-metrics` deployment. Nor does it support setting `METRIC_CLIENT` or `OTEL_COLLECTOR_ENDPOINT` via the values file, they are hardcoded in the [airbyte-env ConfigMap](https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/env-configmap.yaml#L56-L57).

## Describe the solution you’d like
1. An additional (optionally enabled) Helm chart as a dependency of the main airbyte Helm chart, that handles a Deployment of `airbyte-metrics`.
2. The ability to set values for `METRIC_CLIENT` and `OTEL_COLLECTOR_ENDPOINT` in the [airbyte-env Configmap](https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/env-configmap.yaml#L56-L57) from the values file.

## Describe the alternative you’ve considered or used
We currently have an internal 'wrapper' chart which deploys:
- The airbyte Chart
- The open-telemetry-collector Chart
- A Deployment of `airbyte-metrics`

We've attempted to use `worker.extraEnv` in the values file to set `METRIC_CLIENT` and `OTEL_COLLECTOR_ENDPOINT` on the airbyte-worker deployment, however we get the following result (which is invalid):

```yaml
- name: METRIC_CLIENT
  value: otel
  valueFrom:
    configMapKeyRef:
      name: airbyte-airbyte-env
- name: OTEL_COLLECTOR_ENDPOINT
  value: 'http://airbyte-opentelemetry-collector:4317'
  valueFrom:
    configMapKeyRef:
      name: airbyte-airbyte-env
```

## Additional context
N/A

## Are you willing to submit a PR?
Yes 😄
