### ISSUE TITLE
Helm chart incorrectly renders extraContainers

### ISSUE THREAD

**Issue by bdashrad** [airbytehq/airbyte#16470]
## Environment
- **Airbyte version**:  0.40.3
- **Chart Version**: 0.45.1
- **OS Version / Instance**: helm 3.9.4, macOS 12.3.1
- **Deployment**: kubernetes/helm
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy 

## Current Behavior
```
Error: YAML parse error on airbyte/charts/worker/templates/deployment.yaml: error converting YAML to JSON: yaml: line 300: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 300: mapping values are not allowed in this context
YAML parse error on airbyte/charts/worker/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:259
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:264
main.newTemplateCmd.func2
	helm.sh/helm/v3/cmd/helm/template.go:82
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.4.0/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_arm64.s:1133
```

### incorrectly rendered yaml
```yaml
        resources:
          limits: {}
          requests: {}
        volumeMounts:
        - name: gcs-log-creds-volume
          mountPath: /secrets/gcs-log-creds
          readOnly: true
              - args:
          - -ip_address_types=PRIVATE
          - -instances=random-id-123456:us-east1:airbyte=tcp:5432
          - -log_debug_stdout=true
          - -structured_logs
          command:
          - /cloud_sql_proxy
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/key.json
          image: gcr.io/cloudsql-docker/gce-proxy:1.26.0
          name: cloud-sql-proxy
          securityContext:
            runAsNonRoot: true
          volumeMounts:
          - mountPath: /secrets/
            name: service-account
```

## Expected Behavior
`extraContainers` in values are properly rendered.

### sample correctly rendered yaml
```yaml
        resources:
          limits: {}
          requests: {}
        volumeMounts:
        - name: gcs-log-creds-volume
          mountPath: /secrets/gcs-log-creds
          readOnly: true

      - args:
        - -ip_address_types=PRIVATE
        - -instances=random-id-123456:us-east1:airbyte=tcp:5432
        - -log_debug_stdout=true
        - -structured_logs
        command:
        - /cloud_sql_proxy
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/key.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.26.0
        name: cloud-sql-proxy
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /secrets/
          name: service-account
```

## Steps to Reproduce
1. Add additional containers in `worker.extraContainers`, `global.extraContainers`, `metrics.extraContainers`, `server.extraContainers`, `temporal.extraContainers`, or `webapp.extraContainers`
2. Attempt to install or upgrade the helm chart

## Are you willing to submit a PR?
yes
