### ISSUE TITLE
Provide visual indication whether a stream is a table or a view

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#16623]

**Comment by grishick** [comment]
@salima-airbyte @evantahler this seems like a candidate for a small protocol change.

@timroes if/when this feature is prioritized it will likely have a UI part

**Comment by evantahler** [comment]
This might be related to https://github.com/airbytehq/airbyte/pull/16487 (cc @sherifnada and @pedroslopez).  

Maybe rather than having an `available_for_syncing` and  `unavailability_reason` on a stream, we have a `type (string)`, `type_reason (string)`, and `available (boolean)`

```yaml
streams:
  - users
    type: table
    available: true
    type_reason: null
  - users-view
    type: view
    available: true
    type_reason: null  
  - credit-cards
    type: table
    available: false
    type_reason: permission denied  
```
