### ISSUE TITLE
[Epic] Decouple Normalization from platform version

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#16671]
Rather than hard-code the normalization version in the platform, the version of normalization that each destination wants to use should be stored as metadata in within `destination_definititions.yaml`.   This information would then propagate into 2 new columns on the `actor_definitions` table, `normalization_repository` and `normalization_docker_tag`.  

[Tech Spec](https://docs.google.com/document/d/18g3RrOOoMqlXHlgvSJazeq_X-vJ_vlnx7ky0dV-c9r4/edit#)

- [x] 1. #18230
- [x] 2. #18232
     - [x] 2.1. #18235
- [ ] 3. #18238
- [ ] 4. #18239
- [ ] 5. #18240

This is the code to replace with new information in `destination_definititions.yaml` and the database:

https://github.com/airbytehq/airbyte/blob/39b816eb024e4583770672810f3078acb2318b73/airbyte-workers/src/main/java/io/airbyte/workers/normalization/NormalizationRunnerFactory.java#L16-L38

With something like 

```yaml
- name: BigQuery
  destinationDefinitionId: 22f6c74f-5699-40ff-833c-4a879ea40133
  dockerRepository: airbyte/destination-bigquery
  dockerImageTag: 1.2.0
  normalizationRepository: airbyte/normalization-bigquery   # NEW!
  normalizationTag: 0.2.21                                  # NEW!
  documentationUrl: https://docs.airbyte.io/integrations/destinations/bigquery
  icon: bigquery.svg
```

The hard-coding of normalization into the platform causes the following problems:
* Connectors cannot change their normalization version without updating the platform (strong coupling) that removes the ability to rollback or change incrementally
* All connectors share the same version of normalization, meaning a hotfix cannot be released for one destination at a time. 
* Connector metadata is obscured by the platfrom
