### ISSUE TITLE
Low-code connectors: Can't interpolate strings from the DpathExtractor

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#17107]
Sample config:

```
  selector:
    type: RecordSelector
    extractor:
      type: DpathExtractor
      field_pointer:
        - payments
#        - "{{ options['name'] }}"
```
