### ISSUE TITLE
Proposal: enhance API sources by adding API category/usecase metadata

### ISSUE THREAD

**Issue by sw-yx** [airbytehq/airbyte#17893]
## Tell us about the problem you're trying to solve

in https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/source_definitions.yaml , we only indicate APIs vs Databases. However, we're at a scale where this is starting to be less informative and doesn't map to specific usecases that our users have. 

We have a manually maintained, nonauthoritative categorization here: https://airbyte.com/connectors
which is pretty useful, but not tied in to our code as source of truth

this info should be driving both our UX and analytics

was discussing with @ChristopheDuong

## Describe the solution you’d like

- consensus/agreement that we should do this
- doing this
- implementing as a multiple tags system rather than shoehorning each connector into a single category because its likely that some connectors will fit multiple usecases

sample

```yml

- name: AWS CloudTrail
  sourceDefinitionId: 6ff047c0-f5d5-4ce5-8c81-204a830fa7e1
  dockerRepository: airbyte/source-aws-cloudtrail
  dockerImageTag: 0.1.4
  documentationUrl: https://docs.airbyte.com/integrations/sources/aws-cloudtrail
  icon: awscloudtrail.svg
  sourceType: api
  releaseStage: alpha
  usecaseTags:
		- event streaming
		- observability
- name: Amazon Ads
  sourceDefinitionId: c6b0a29e-1da9-4512-9002-7bfd0cba2246
  dockerRepository: airbyte/source-amazon-ads
  dockerImageTag: 0.1.22
  documentationUrl: https://docs.airbyte.com/integrations/sources/amazon-ads
  icon: amazonads.svg
  sourceType: api
  releaseStage: generally_available
  usecaseTags:
		- marketing
- name: Amazon Seller Partner
  sourceDefinitionId: e55879a8-0ef8-4557-abcf-ab34c53ec460
  dockerRepository: airbyte/source-amazon-seller-partner
  dockerImageTag: 0.2.27
  sourceType: api
  documentationUrl: https://docs.airbyte.com/integrations/sources/amazon-seller-partner
  icon: amazonsellerpartner.svg
  releaseStage: alpha
  usecaseTags:
		- ecommerce
```

## Describe the alternative you’ve considered or used

maintaining an external google sheet that does this job

## Are you willing to submit a PR?

 yea
