### ISSUE TITLE
Helm Chart: enable explicit Postgres DATABASE_URL value (e.g. to enable SSL options)

### ISSUE THREAD

**Issue by jtv8** [airbytehq/airbyte#17995]
## Tell us about the problem you're trying to solve
When deploying Airbyte via Helm, it is currently impossible to provide extra arguments to the JDBC driver (e.g. to enable SSL options) - see [Connecting to an External Postgres database](https://docs.airbyte.com/operator-guides/configuring-airbyte-db/#connecting-to-an-external-postgres-database) in the docs.

> Additionally, you must redefine the JDBC URL constructed in the environment variable DATABASE_URL to include the correct host, port, and database. If you need to provide extra arguments to the JDBC driver (for example, to handle SSL) you should add it here as well:
>
> `DATABASE_URL=jdbc:postgresql://host.docker.internal:3000/postgres?ssl=true&sslmode=require`

Currently this environment variable is constructed in `/charts/airbyte/templates/_helpers.tpl` and cannot be overridden:

```
{{/*
Add environment variables to configure database values
*/}}
{{- define "airbyte.database.url" -}}
{{- $host := (include "airbyte.database.host" .) -}}
{{- $dbName := (include "airbyte.database.name" .) -}}
{{- $port := (include "airbyte.database.port" . ) -}}
{{- printf "jdbc:postgresql://%s:%s/%s" $host $port $dbName -}}
{{- end -}}
```

## Describe the solution you’d like

Either of the following solutions would be acceptable as a valid `externalDatabase` configuration in the `values.yaml`:

```
externalDatabase:
  host: localhost
  user: airbyte
  password: foo
  # existingSecret: ""
  # existingSecretPasswordKey: ""
  database: db-airbyte
  port: 5432
  connectionParameters:
    ssl: "true"
    sslmode: "require"
```

Or:

```
externalDatabase:
  # host: localhost
  user: airbyte
  password: foo
  # existingSecret: ""
  # existingSecretPasswordKey: ""
  # database: db-airbyte
  # port: 5432
  url: jdbc:postgresql://localhost:5432/db-airbyte?ssl=true&sslmode=require
```

## Describe the alternative you’ve considered or used
Currently the only workarounds I can think of are:

1.  to patch the ConfigMap generated by `/charts/airbyte/templates/env-configmap.yaml` after deployment (which is messy) or
2.  to disable SSL on the external database (which is unacceptable in most production environments).

## Additional context
n/a

## Are you willing to submit a PR?

Yes, if you provide some feedback on which solution you prefer!
