### ISSUE TITLE
Creation of a Jinja filter that allows hashing of sensitive data before arriving at a destination.

### ISSUE THREAD

**Issue by alexander-marquardt** [airbytehq/airbyte#17993]
## Tell us about the problem you're trying to solve
For GDPR compliance, it may be necessary to obfuscate personally identifiable information. With the jinja2 template support in the low code connectors, this is relatively straightforward to implement. 

I've written a protype running locally running in a virtual environment:

file:  `interpolation/filters.py`:
```
import hashlib

def hash(value, hash_type="md5", salt=None):
    """
    Example filter providing custom Jinja2 filter - hash

    Hash type defaults to 'sha1' if one is not specified

    :param value: value to be hashed
    :param hash_type: valid hash type
    :return: computed hash as a hexadecimal string
    """
    hash_obj = getattr(hashlib, hash_type, None)()
    hash_obj.update(str(value).encode("utf-8"))
    hash_obj.update(str(salt).encode("utf-8"))


    if hash_obj:
        computed_hash = hash_obj.hexdigest()
    else:
        raise AttributeError(
            "No hashing function named {hname}".format(hname=hash_type)
        )

    return computed_hash


_filters_list = [hash]
filters = {f.__name__: f for f in _filters_list}

```

And it requires the following addition to `interpolation/jinja.py`:
```
from airbyte_cdk.sources.declarative.interpolation.filters import filters
```

And
```
    def __init__(self):
        self._environment = Environment()
        self._environment.filters.update(**filters)
        self._environment.globals.update(**macros)

```
The lowcode yaml can then make use of the above as follows:

```
  rates_stream:
    $ref: "*ref(definitions.base_stream)"
    $options:
      name: "rates"
      primary_key: "date"
      path: "/exchangerates_data/latest"
    transformations:
      - type: AddFields
        fields:
          - path: ["some_new_path"]
            value: "{{ record['rates']['CAD'] | hash('md5', 'mysalt')  }}"


``` 

## Describe the alternative you’ve considered or used
Overwriting the field with a static value could be done, but in my experience this is less desirable than a consistent (salted) hash.

## Additional context
Once the error mentioned in https://github.com/airbytehq/airbyte/issues/17957, I expect that this code should apply a hash to a field as expected. Currently, te hash is applied the an incorrect field, but the calculation of the hash appears to work correctly. 

      "exchangerates_data": {
        "latest": "5c0fb4a0564c87d0093eaae56db0b4a1769c7258"
      }

## Are you willing to submit a PR?
Yes - I plan on converting the code above into a proper PR that follows proper standards.
