### ISSUE TITLE
E(t)LT -- Connector support for jinja transformations, not only custom lowcode connector definitions

### ISSUE THREAD

**Issue by alexander-marquardt** [airbytehq/airbyte#18064]
## Tell us about the problem you're trying to solve
For GDPR compliance, it may be necessary for clients to do small "t" tranformations on their data to obfuscate personally identifiable information so that it is never sent to a destination. Examples would be a social security number or an email address. 

I have added support to do this in Jinja templates that are accessed within the lowcode connector, via a jinja filter that calculates a hash of a value + salt as discussed in https://github.com/airbytehq/airbyte/issues/17993 

It would be nice to expose this in a more generic way so that it could be used more generally in standard connectors for users that require such functionality.

## Describe the solution you’d like
A more generic implementation that allows implementation of hashing after extraction, and before loading.  Perhaps it could be defined in the catalog or json schema, or a new "tranformations.json" file ...  or somewhere else as part of the specification that is created or modified by a user. 

## Describe the alternative you’ve considered or used
This is achievable in the lowcode connector definition -- the problem is that it cannot easily be applied to existing connectors, which could make it difficult for users to remain GDPR compliant. 

Eg. 

```
  rates_stream:
    $ref: "*ref(definitions.base_stream)"
    $options:
      name: "rates"
      primary_key: "date"
      path: "/exchangerates_data/latest"
    transformations:
      - type: AddFields
        fields:
          - path: ["some_new_path"]
            value: "{{ record['rates']['CAD'] | hash('md5', 'mysalt')  }}"
```

## Are you willing to submit a PR?
No - this is likely a non-trivial engineering project
