### ISSUE TITLE
Connectors with Single Use Refresh tokens (`single-connection`) cannot be used in more than one connection

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#18083]
```yaml
- name: Jira
  sourceDefinitionId: 68e63de2-bb83-4c7e-93fa-a8a9051e3993
  dockerRepository: airbyte/source-jira
  dockerImageTag: 0.2.21
  documentationUrl: https://docs.airbyte.com/integrations/sources/jira
  icon: jira.svg
  sourceType: api
  releaseStage: alpha
  connectorRestrictions: [ single-connection ] # ← new! 
```

Connectors with `connectorRestrictions.includes('single-connection')` cannot be added to more than one connection.
Existing connectors that should not be in more than one connection that are already can stay as-is.  

This validation should be done every time a connector's config is updated as well, to inform users that they should remove this connector from multiple connections.
