### ISSUE TITLE
Schedule Sync Job pods on Dedicated Node

### ISSUE THREAD

**Issue by TalhaNaeem101** [airbytehq/airbyte#18104]
Hi, I have applied node affinity and taints & tolerations on the core components of airbyte (scheduler, worker, server, and all) And these pods are being scheduled correctly on the dedicated Node. But the pods of sync jobs are being scheduled dynamically, which depicts node affinity and taints%tolerations are not being applied on the sync job pods. **I want my sync job pods to be scheduled on the dedicated Node.**
 I have airbyte 0.35.31 deployed on my EKS cluster. Here is the .env file:
```
AIRBYTE_VERSION=0.35.31-alpha

DATABASE_HOST=<>
DATABASE_PORT=5432
DATABASE_DB=airbyte
DATABASE_URL=<>
JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=0.29.15.001
CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=0.35.15.001
CONFIG_DATABASE_URL=<>

CONFIG_ROOT=/configs
DATA_DOCKER_MOUNT=airbyte_data
DB_DOCKER_MOUNT=airbyte_db

RUN_DATABASE_MIGRATION_ON_STARTUP=true


TEMPORAL_HOST=airbyte-temporal-svc:7233
TEMPORAL_WORKER_PORTS=9001,9002,9003,9004,9005,9006,9007,9008,9009,9010,9011,9012,9013,9014,9015,9016,9017,9018,9019,9020,9021,9022,9023,9024,9025,9026,9027,9028,9029,9030,9031,9032,9033,9034,9035,9036,9037,9038,9039,9040


WORKSPACE_ROOT=/workspace
WORKSPACE_DOCKER_MOUNT=airbyte_workspace

LOCAL_ROOT=/tmp/airbyte_local

# Maximum total simultaneous jobs across all worker nodes
SUBMITTER_NUM_THREADS=10

# Miscellaneous
TRACKING_STRATEGY=segment
WEBAPP_URL=airbyte-webapp-svc:80
API_URL=/api/v1/
INTERNAL_API_HOST=airbyte-server-svc:8001

WORKER_ENVIRONMENT=kubernetes
FULLSTORY=enabled
IS_DEMO=false
LOG_LEVEL=INFO

# S3/Minio Log Configuration
S3_LOG_BUCKET=airbyte-dev-logs
S3_LOG_BUCKET_REGION=us-east-2
S3_MINIO_ENDPOINT=
S3_PATH_STYLE_ACCESS=
AWS_ACCESS_KEY_ID=<>
AWS_SECRET_ACCESS_KEY=<>

# GCS Log Configuration
GCS_LOG_BUCKET=

# State Storage Configuration
STATE_STORAGE_MINIO_BUCKET_NAME=airbyte-dev-logs
STATE_STORAGE_MINIO_ENDPOINT=http://airbyte-minio-svc:9000/

# Docker Resource Limits
JOB_MAIN_CONTAINER_CPU_REQUEST=
JOB_MAIN_CONTAINER_CPU_LIMIT=
JOB_MAIN_CONTAINER_MEMORY_REQUEST=
JOB_MAIN_CONTAINER_MEMORY_LIMIT=

# Worker pod tolerations and node selectors
JOB_KUBE_TOLERATIONS=
JOB_KUBE_NODE_SELECTORS=

# Job image pull policyplishi
JOB_KUBE_MAIN_CONTAINER_IMAGE_PULL_POLICY=

# Launch a separate pod to orchestrate sync steps
CONTAINER_ORCHESTRATOR_ENABLED=false
```
I have used its kustomize for deployment and updated the manifests of its core components in airbyte/resources directly, as shown below:
```
.
.
 spec:
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "airbyte"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: dedicated
                  operator:  In
                  values:
                    - airbyte
.
.
.
```

My Question: **Is there any way to schedule the sync jobs pods on the dedicated node, if yes what's that?** 

PS: I have done preliminary R&D on this issue, and also read airbyte's documentation, but haven't found any way to achieve this. So please help me out in accomplishing this. That would be great. Thanks

---

**Comment by sh4sh** [comment]
Hey @TalhaNaeem101 thanks for providing your configs. These envs should allow you to specify tolerations and node affinity selectors, can you let me know if they help?
```
# Worker pod tolerations and node selectors
JOB_KUBE_TOLERATIONS=
JOB_KUBE_NODE_SELECTORS=
```

**Comment by TalhaNaeem101** [comment]
@sh4sh Can you please help me further like what to provide in these variables? and how will it apply the effect on the sync job pods? I would highly appreciate it. Thanks

**Comment by sh4sh** [comment]
For sure @TalhaNaeem101 , I've found an example of the format here in our discussion forum: https://discuss.airbyte.io/t/deploy-kubernetes-job-kube-tolerations-with-no-effect/2153

It should look something like this:
```
JOB_KUBE_TOLERATIONS=key=dedicated,operator=Equal,effect=NoSchedule,value= airbyte
JOB_KUBE_NODE_SELECTORS=dedicated=airbyte
```

I'm not 100% on this but I think it is just the `nodeSelector` field rather than node affinity proper. If you would prefer to use `nodeSelectorTerms`, you can add it with kustomize to `airbyte-scheduler`: https://github.com/airbytehq/airbyte/issues/6086#issuecomment-920241356

There's a little bit more on jobs config here: https://docs.airbyte.com/operator-guides/configuring-airbyte#jobs-1

**Comment by TalhaNaeem101** [comment]
@sh4sh Thank you so much for your kindness. It worked. I appreciate that you contributed in achieving my goal:)
 
**Closing this ticket with this summary. (might be helpful for someone)**

- Use these parameters in .env file while deploying airbyte:

```
# Worker pod tolerations and node selectors
JOB_KUBE_TOLERATIONS=key=dedicated,operator=Equal,effect=NoSchedule,value=airbyte
JOB_KUBE_NODE_SELECTORS=dedicated=airbyte
```
- For node affinity, you need to include this in definitions of airbyte server, worker, scheduler, and other components within the resources directory in my case ( as I was using Kustomize). 
```
 spec:
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "airbyte"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: dedicated
                  operator:  In
                  values:
                    - airbyte

```

- Also make sure you have applied taints on the node with key-value=dedicated=airbyte

- **Result achieved:**

> By this, all the sync pods and pods of the airbyte's core components will be scheduled and run on a dedicated node in your cluster. 


Regards
