### ISSUE TITLE
Low-code SDK: PageIncrement strategy never stops with custom field_pointer

### ISSUE THREAD

**Issue by delenamalan** [airbytehq/airbyte#18135]
## Environment
- **Airbyte version**:  0.1.102
- **OS Version / Instance**: macOS Monterey
- **Deployment**: Docker
- **Source Connector and version**: N/A
- **Destination Connector and version**: N/A
- **Step where error happened**: Sync job

## Current Behavior

I'm working on adding support for [Lokalise](https://developers.lokalise.com/reference/list-all-keys) with the low-code SDK.

I'm using the `PageIncrement` pagination strategy because pagination mechanism receives a `page` and `limit` query parameter. I'm also using a custom `field_pointer` in my stream's configuration because their response looks like this:

```
{
    "project_id": "<my_project_id>",
    "keys": []
}
```

However, the `PageIncrement` pagination strategy never detects that `keys` is empty because it isn't aware of the `field_pointer`.

I've added a `print` statement to `airbyte-integrations/connectors/source-lokalise/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/paginators/strategies/page_increment.py::PageIncrement::next_page_token` to see what `last_records` looks like and it prints out the following:

```
[{'project_id': '<my_project_id>', 'keys': []}]
```

## Expected Behavior

I would expect the `PageIncrement` pagination strategy to use the `field_pointer` to check that the `keys` value is empty.

## Logs

Logs show Airbyte trying to fetch an increasing number of pages even though `keys` is an empty dict:

```
{"type": "DEBUG", "message": "Making outbound API request", "data": {"url": "https://api.lokalise.com/api2/projects/<my_project_id>/keys?page=8&limit=1", "request_body": "None", "headers": "{'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Api-Token': '****'}"}}
{"type": "DEBUG", "message": "Making outbound API request", "data": {"url": "https://api.lokalise.com/api2/projects/<my_project_id>/keys?page=9&limit=1", "request_body": "None", "headers": "{'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Api-Token': '****'}"}}
```

## Steps to Reproduce

Use the `PageIncrement` strategy on an API that also uses a custom `field_pointer` per stream.

Example:

```
  retriever:
    record_selector:
      $ref: "*ref(definitions.selector)"
    paginator:
      type: DefaultPaginator
      url_base: "*ref(definitions.requester.url_base)"
      pagination_strategy:
        type: PageIncrement
        page_size: "*ref(definitions.page_size)"
      page_size_option:
        inject_into: "request_parameter"
        field_name: "limit"
      page_token_option:
        inject_into: "request_parameter"
        field_name: "page"
```

You can try the full connector by pulling [ this commit](https://github.com/delenamalan/airbyte/commit/98509cb53a63053f2ea733ccd89ba9287ee80a71).

Full YAML example:

```
version: "0.1.0"

definitions:
  page_size: 1
  schema_loader:
    type: JsonSchema
    file_path: "./source_sentry/schemas/{{ options.name }}.json"
  selector:
    extractor:
      field_pointer: [ ]
  requester:
    url_base: "https://api.lokalise.com"
    http_method: "GET"
    authenticator:
      type: ApiKeyAuthenticator
      header: "X-Api-Token"
      api_token: "{{ config['api_key'] }}"
  retriever:
    record_selector:
      $ref: "*ref(definitions.selector)"
    paginator:
      type: DefaultPaginator
      url_base: "*ref(definitions.requester.url_base)"
      pagination_strategy:
        type: PageIncrement
        page_size: "*ref(definitions.page_size)"
      page_size_option:
        inject_into: "request_parameter"
        field_name: "limit"
      page_token_option:
        inject_into: "request_parameter"
        field_name: "page"
    requester:
      $ref: "*ref(definitions.requester)"
  base_stream:
    retriever:
      $ref: "*ref(definitions.retriever)"

  keys_stream:
    $ref: "*ref(definitions.base_stream)"
    $options:
      name: "keys"
      primary_key: "key_id"
      path: "/api2/projects/{{ config['project_id'] }}/keys"
      field_pointer: ["keys"]
  languages_stream:
    $ref: "*ref(definitions.base_stream)"
    $options:
      name: "languages"
      primary_key: "lang_id"
      path: "/api2/projects/{{ config['project_id'] }}/languages"
      field_pointer: ["languages"]


streams:
  - "*ref(definitions.keys_stream)"
  - "*ref(definitions.languages_stream)"

check:
  stream_names:
    - "keys"
    - "languages"
```

**Comment by delenamalan** [comment]
Interestingly, when I set the default selector's `field_pointer` to `keys`, then the pagination for the keys stream is successful. However, no records are returned for the languages stream. Am I perhaps setting the custom `field_pointer` value per stream incorrectly?

This is how my updated YAML file looks:

```
version: "0.1.0"

definitions:
  page_size: 1
  schema_loader:
    type: JsonSchema
    file_path: "./source_sentry/schemas/{{ options.name }}.json"
  selector:
    extractor:
      field_pointer: ["keys"]
  requester:
    url_base: "https://api.lokalise.com"
    http_method: "GET"
    authenticator:
      type: ApiKeyAuthenticator
      header: "X-Api-Token"
      api_token: "{{ config['api_key'] }}"
  retriever:
    record_selector:
      $ref: "*ref(definitions.selector)"
    paginator:
      type: DefaultPaginator
      url_base: "*ref(definitions.requester.url_base)"
      pagination_strategy:
        type: PageIncrement
        page_size: "*ref(definitions.page_size)"
      page_size_option:
        inject_into: "request_parameter"
        field_name: "limit"
      page_token_option:
        inject_into: "request_parameter"
        field_name: "page"
    requester:
      $ref: "*ref(definitions.requester)"
  base_stream:
    retriever:
      $ref: "*ref(definitions.retriever)"

  keys_stream:
    $ref: "*ref(definitions.base_stream)"
    $options:
      name: "keys"
      primary_key: "key_id"
      path: "/api2/projects/{{ config['project_id'] }}/keys"
      field_pointer: ["keys"]
  languages_stream:
    $ref: "*ref(definitions.base_stream)"
    $options:
      name: "languages"
      primary_key: "lang_id"
      path: "/api2/projects/{{ config['project_id'] }}/languages"
      field_pointer: ["languages"]


streams:
  - "*ref(definitions.keys_stream)"
  - "*ref(definitions.languages_stream)"

check:
  stream_names:
    - "keys"
    - "languages"
```

**Comment by delenamalan** [comment]
What solves the issue for me is if I instead specify the stream's retriever explicitly like this:

```
  keys_stream:
    $ref: "*ref(definitions.base_stream)"
    retriever:
      $ref: "*ref(definitions.retriever)"
      record_selector:
        extractor:
          field_pointer: ["keys"]
    $options:
      name: "keys"
      primary_key: "key_id"
      path: "/api2/projects/{{ config['project_id'] }}/keys"
```
