### ISSUE TITLE
SAT[strict_mode]: validate that all `tests` are enabled 

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#18219]
## Tell us about the problem you're trying to solve
All the tests declared in `acceptance-test-config.yml`, under the `tests` field are optional:
```python
class TestConfig(BaseConfig):
    spec: Optional[List[SpecTestConfig]] = Field(description="TODO")
    connection: Optional[List[ConnectionTestConfig]] = Field(description="TODO")
    discovery: Optional[List[DiscoveryTestConfig]] = Field(description="TODO")
    basic_read: Optional[List[BasicReadTestConfig]] = Field(description="TODO")
    full_refresh: Optional[List[FullRefreshConfig]] = Field(description="TODO")
    incremental: Optional[List[IncrementalConfig]] = Field(description="TODO")
``` 

**I want all these tests not to be optional when `strict_mode = strict`.**

## Describe the solution you’d like
When `strict_mode = strict` I want all the test configuration to be declared, a pydantic.ValidationError should be raised otherwise. If a specific test can be configured on the connector it can be bypassed by declaring a `bypass_reason`.
 
```yaml 
connector_image: airbyte/source-pokeapi:dev
strict_mode: strict
tests:
  spec:
    bypass_reason: "Explain the reason why spec tests are disabled"
  connection:
    - config_path: "integration_tests/config.json"
      status: "succeed"
  discovery:
    - config_path: "integration_tests/config.json"
  basic_read:
    - config_path: "integration_tests/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
  full_refresh:
    - config_path: "integration_tests/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
  incremental:
    bypass_reason: "Explain the reason why spec tests are disabled"
```

**If a `bypass_reason` is filled SAT should log a warning.**
