### ISSUE TITLE
SAT: declare a global `strict_mode` in `acceptance-test-config.yml`

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#18215]
## Tell us about the problem you're trying to solve
I'd like to make the SAT suite behave according to a `strict_mode` level.
This will be useful to enforce stricter testing on GA connectors.

## Describe the solution you’d like
Add a `strict_mode` string field at the top level of the `acceptance-test-config.yml` file.
Make this field optional, default to null, and values should be an enum of : `[None, "strict"]` to start.

```yaml
connector_image: airbyte/source-ga-connector:dev
strict_mode: "strict"
tests:
   # all test config below
```

## Acceptance criteria
Tests can access a `strict_mode`  fixture parsed from the test configuration.

## Additional context
[Tech spec](https://docs.google.com/document/d/19hnZslQUbvxuHeFQd9hbzVQmuK4INzDcwiXEA7FwA4U/edit#)
