### ISSUE TITLE
SAT [strict_mode]: `basic_read.expect_records` must be set

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#18222]
## Tell us about the problem you're trying to solve
`basic_read.expect_record` is currently optionally used to declare a file with a list of records expected to receive on a `read` command. Making it mandatory for GA connectors is required to validate record schema and limit regression on `read`.

## Describe the solution you’d like
SAT must enforce the presence of the `expect_record` field in the `basic_read` test section for GA connectors.
I'd like these expect_records to be split by stream for maximum control and granularity in a future coverage computation.

**If a bypass_reason is filled SAT should log a warning.**

Example for a partially seeded sandbox account:
```yaml
strict_mode: strict
tests:
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      expect_records:
        streams:
           - stream_name: stream_a
             expected_records_path: "integration_tests/a_expected_records.txt"
             extra_fields: no
             exact_order: yes
             extra_records: no
           - stream_name: stream_b
             bypass_reason: "We cannot seed stream b"
```

Example for a not seeded sandbox account:

```yaml
strict_mode: strict
tests:
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      expect_records:
        bypass_reason: "No stream can be seeded on our sandbox account"
```

**If a bypass_reason is filled SAT should log a warning.**

This will require changing the configuration structure of `expect_records` which is not currently stream-specific:
```yaml
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      expect_records:
        path: "integration_tests/expected_records.txt"
        extra_fields: no
        exact_order: yes
        extra_records: no
```
