### ISSUE TITLE
SAT[strict_mode]: `basic_read` should use the discovered catalog at least once

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#18306]
## Tell us about the problem you're trying to solve
User defined catalog can be used on the `basic_read` test.
Some streams can be omitted from these custom catalog, leading to partial coverage of `basic_read`.
I would like to ensure `basic_read` test is run at least once with the discovered

Current behavior:
In `acceptance-test-catalog.yml` when `configured_catalog_path` is not set under `basic_read`, `basic_read` will use the discovered catalog: 
```yaml
tests:
  basic_read:
    - config_path: "integration_tests/config.json"
```
But users can defined a custom configured catalog that  can omit some streams
```yaml
tests:
  basic_read:
    - config_path: "integration_tests/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
```

## Suggested solution

**Solution A**:  <-- Preference 
1. When `test_mode == strict` run all basic_read test twice: once with the if the custom `configured_catalog` and once with the discovered_catalog. Modification to `configured_catalog` or `discovered_catalog` fixtures could help achieve this.

**Solution B:**
1. Expose a new fixture that parses all the basic_read test configurations and checks if `configured_catalog_path is None` for one of these tests.
3. `test_read`uses this fixture, if we are in strict mode and the fixture returns `false` the test fails with the reason "Strict mode: test_read should run at least once the discovered catalog"
