### ISSUE TITLE
source-xkcd: `spec` outputs an invalid json schema.

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#18352]
The new xkcd source  https://github.com/airbytehq/airbyte/pull/18049 declares a `connectionSpecification` field as on object, but  `properties` field is missing: invalid json schema.

 
```
documentationUrl: https://docs.airbyte.io/integrations/sources/xkcd
connectionSpecification:
  $schema: http://json-schema.org/draft-07/schema#
  title: Xkcd Spec
  type: object
```

It broke connector base build so I disabled this connector in https://github.com/airbytehq/airbyte/pull/18351
