### ISSUE TITLE
airbyte-metrics helm chart DATABASE_PASSWORD inconsistent

### ISSUE THREAD

**Issue by hpias** [airbytehq/airbyte#18539]
The airbyte-metrics deployment.yaml has what seems to be incorrect expressions for env variable DATABASE_PASSWORD.
It will only work properly if airbyte helm chart values file has the following global values set:
```yaml
global:


  ##  ...
  ##  database [object] -- Object used to overrite database configuration(to use external DB)
  ##  database.secretName -- secret name where DB creds are stored
  ##  database.secretValue -- secret value for database password
  ##  database.host -- Database host override
  ##  database.port -- Database port override
  database:
    secretName: "airbyte-airbyte-secrets"
    secretValue: "DATABASE_PASSWORD"
    host: "example.com"
    port: "5432"
```
airbyte-metrics incorrect DATABASE_PASSWORD expressions:
https://github.com/airbytehq/airbyte/blob/4117f9d7a4258a767dbbff053349d2528ab26836/charts/airbyte-metrics/templates/deployment.yaml#L56-L60

The correct expression that properly sets the secret name and key (airbyte-airbyte-secrets, DATABASE_PASSWORD) can be seen in airbyte-server and airbyte-worker deployment.yaml files:
https://github.com/airbytehq/airbyte/blob/4117f9d7a4258a767dbbff053349d2528ab26836/charts/airbyte-server/templates/deployment.yaml#L60-L64              

https://github.com/airbytehq/airbyte/blob/4117f9d7a4258a767dbbff053349d2528ab26836/charts/airbyte-worker/templates/deployment.yaml#L69-L73

The workaround for the airbyte-metrics has been given at the beginning but it seems like a simple fix.
