### ISSUE TITLE
Airbyte Helm Chart throws "secret "metrics-0.40.33" not found" error due to referencing invalid secret when metrics is enabled

### ISSUE THREAD

**Issue by geoffreytran** [airbytehq/airbyte#18637]
When enabling the metrics reporter within the main Airbyte Helm Chart, the airbyte-metrics sub-chart causes k8s to throw an invalid secret error.

```
Error: secret "metrics-0.40.33" not found
```

This error occurs because the database password environment config is referencing an invalid property. Suggest referencing ` {{ .Release.Name }}-airbyte-secrets` to match the DATABASE_USER config below.

https://github.com/airbytehq/airbyte/blob/63c024bd3df70112f5532635b8302eca9ad1c01b/charts/airbyte-metrics/templates/deployment.yaml#L56

Workaround is defining the secret name in the values.yaml for deployment:

```
global:
  database:
    # Must be specified due to big in the airbyte-metrics chart looking at an invalid secret
    secretName: airbyte-airbyte-secrets
    secretValue: DATABASE_PASSWORD
```
