### ISSUE TITLE
Low-code CDK: Tutorial Bug

### ISSUE THREAD

**Issue by scottleechua** [airbytehq/airbyte#18663]
## Environment
- **Airbyte version**:  0.40.17
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Step where error happened**: [Tutorial Step 5: Incremental Reads](https://docs.airbyte.com/connector-development/config-based/tutorial/incremental-reads)

## Current Behavior
I copy the full `spec.yaml` and `exchange_rate_tutorial,.yaml` from tutorial step 5 (reproduced fully in Appendix below).

Then I run
```
python main.py read --config secrets/config.json --catalog integration_tests/configured_catalog.json
```
and obtain the errors attached under "Logs".

## Expected Behavior
No error.

## Logs

[log.txt](https://github.com/airbytehq/airbyte/files/9895960/log.txt)

## Steps to Reproduce
Follow the tutorial steps 1 through 5. (Steps 1 to 4 work exactly as intended.)

## Are you willing to submit a PR?
Yes, with guidance!

## Appendix
The full `spec.yaml`:
```
documentationUrl: https://docs.airbyte.io/integrations/sources/exchangeratesapi
connectionSpecification:
  $schema: http://json-schema.org/draft-07/schema#
  title: exchangeratesapi.io Source Spec
  type: object
  required:
    - start_date
    - access_key
    - base
  additionalProperties: true
  properties:
    start_date:
      type: string
      description: Start getting data from that date.
      pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}$
      examples:
        - YYYY-MM-DD
    access_key:
      type: string
      description: >-
        Your API Access Key. See <a
        href="https://exchangeratesapi.io/documentation/">here</a>. The key is
        case sensitive.
      airbyte_secret: true
    base:
      type: string
      description: >-
        ISO reference currency. See <a
        href="https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html">here</a>.
      examples:
        - EUR
        - USD
```

and the full `exchange_rate_tutorial.yaml`:
```
version: "0.1.0"

definitions:
  selector:
    extractor:
      field_pointer: [ ]
  requester:
    url_base: "https://api.apilayer.com"
    http_method: "GET"
    authenticator:
      type: ApiKeyAuthenticator
      header: "apikey"
      api_token: "{{ config['access_key'] }}"
    request_options_provider:
      request_parameters:
        base: "{{ config['base'] }}"
  stream_slicer:
    type: "DatetimeStreamSlicer"
    start_datetime:
      datetime: "{{ config['start_date'] }}"
      datetime_format: "%Y-%m-%d"
    end_datetime:
      datetime: "{{ now_utc() }}"
      datetime_format: "%Y-%m-%d %H:%M:%S.%f"
    step: "1d"
    datetime_format: "%Y-%m-%d"
    cursor_field: "{{ options['stream_cursor_field'] }}"
  retriever:
    record_selector:
      $ref: "*ref(definitions.selector)"
    paginator:
      type: NoPagination
    requester:
      $ref: "*ref(definitions.requester)"
    stream_slicer:
      $ref: "*ref(definitions.stream_slicer)"
  base_stream:
    retriever:
      $ref: "*ref(definitions.retriever)"
  rates_stream:
    $ref: "*ref(definitions.base_stream)"
    $options:
      name: "rates"
      primary_key: "date"
      path: "/exchangerates_data/{{stream_slice['start_time'] or 'latest'}}"
      stream_cursor_field: "date"
streams:
  - "*ref(definitions.rates_stream)"
check:
  stream_names:
    - "rates"
```

**Comment by juweins** [comment]
Hey All! I just stumbled across this Issue while looking for my next task here. By validating Issue #20047 I opened a similar issue 
 #20071 because I was unable to follow the tutorial. Turns out, that both keywords in the tutorial are invalid:

```yaml
spec: 
  documentationUrl: https://docs.airbyte.io/integrations/sources/exchangeratesapi
  connectionSpecification:
```

I opened a pull request a few minutes ago, which therefore also resolves this one!
