### ISSUE TITLE
lowcode: request_body_json should accept any valid json object or array

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#18784]
## Tell us about the problem you're trying to solve
The requester's request_body_json only accepts json key-value pairs, but some APIs require nested fields or an array

### json array
request_body_json should also accept arrays:
Given the following expected body:
```
[{
  "clause": {
    "type": "timestamp",
    "operator": 4,
    "parameters": [{
        "value": <cursor-value>
      }
    ]
  },
  "columnName": "Timestamp"
}]
```

The request_options_provider should be defined as 
```
request_options_provider:
  request_body_json: 
    - clause:
        type: timestamp
        operator: 4
        parameters:
          - value: <some-value>
        columnName: Timestamp
```

### nested fields
Given the following expected body:
```
{
"request":{
  "auth": "token",
  "limitMessages": "1000"
  }
}
```

The request_options_provider should be defined as 
```
request_options_provider:
  request_body_json: 
    request:
      auth: token
      limitMessages: "1000"
```

## Acceptance Criteria
- [ ] accept JSON arrays
- [ ] accept JSON objects with nested values
- [ ] support interpolation of variables at any depth

## Additional context
Example use case for array https://airbytehq-team.slack.com/archives/C03UEMGGEGZ/p1667289768822399
Example use case for nested fields https://airbytehq-team.slack.com/archives/C03UEMGGEGZ/p1668770340946759
