### ISSUE TITLE
Lowcode CDK: endpoint path interpolated incorrectly

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19365]
## Current Behavior
My manifest defines only one stream, whose URL path is `/bill`: 

```yaml

version: "0.1.0"
definitions:
  page_size: 1
  selector:
    type: RecordSelector
    extractor:
      type: DpathExtractor
      field_pointer: ["{{ options['data_pointer']}}"]
  requester:
    type: HttpRequester
    http_method: "GET"
    request_options_provider:
      request_parameters:
        api_key: "{{ config['api_key'] }}"
    path: "{{ options.path }}"
  retriever:
    type: SimpleRetriever
    $options:
      url_base: https://api.congress.gov/v3/
    name: "{{ options['name'] }}"
    primary_key: "{{ options['primary_key'] }}"
    record_selector:
      $ref: "*ref(definitions.selector)"
    requester:
      $ref: "*ref(definitions.requester)"
    # slicer:
    #   $ref: "*ref(definitions.slicer)"
streams:
  - type: DeclarativeStream
    retriever: 
      $ref: "*ref(definitions.retriever)"
    $options:
      name: "bills"
      data_pointer: "bills"
      path: "/bill"

check:
  type: CheckStream
  stream_names: ["bills"]
```

When I run `read`, I get the following error (prettified): 

```
{
  "type": "DEBUG",
  "message": "Making outbound API request",
  "data": {
    "request_body": "None",
    "headers": "{'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Cookie': '__cf_bm=8wEbxvXS_lAdtG_4seRzq3mzAX2EefFuFKoNgNoSsYc-1668298457-0-AXOpEqVOfFreWZEA3PtFQiKGwhCO1ByT6513DmYTPGN8d95KfIAOMY0tpvsCqxCRBz+p7dzmn3zW320Sn2zK3cQ='}",
    "url": "https://api.congress.gov/v3/InterpolatedString(string='/bill',%20default='/bill')?api_key=****&limit=1"
  }
}
{
  "type": "DEBUG",
  "message": "Receiving response",
  "data": {
    "status": "404",
    "headers": "{'Date': 'Sun, 13 Nov 2022 00:14:17 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Age': '0', 'Cf-Cache-Status': 'DYNAMIC', 'Cf-Ray': '76934e705b55c6fd-SEA', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; preload', 'Vary': 'Accept-Encoding', 'Via': 'http/1.1 api-umbrella (ApacheTrafficServer [cMsSf ])', 'X-Cache': 'MISS', 'X-Ratelimit-Limit': '1000', 'X-Ratelimit-Remaining': '986', 'X-Vcap-Request-Id': 'f9ce2b54-f215-4ed1-7d66-e2c59c0d46c8', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block'}",
    "body": "{\n    \"error\": \"Unknown resource: InterpolatedString(string='/bill', default='/bill')\"\n}"
  }
}
```

Notice that the URL that the CDK attempted to hit was `https://api.congress.gov/v3/InterpolatedString(string='/bill',%20default='/bill')?api_key=****&limit=1` whereas it should be `https://api.congress.gov/v3/bill?api_key=****&limit=1` i.e: the interpolation isn't happening correctly

## Expected Behavior
Interpolation should happen correctly, the URL should be `https://api.congress.gov/v3/InterpolatedString(string='/bill',%20default='/bill')?api_key=****&limit=1`
