### ISSUE TITLE
[Low-Code CDK] Rename $options keyword to $parameter in the connector manifest

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#19408]
## Tell us about the problem you're trying to solve
**BREAKING CHANGE**

The keyword `$options` is a very vague and overloaded term that doesn't do a good job of conveying its purpose.
This field keyword is used to propagate values accessible at runtime for string interpolation and to be assigned to component fields. We should replace this with the `$parameters` keyword which is a more accurate term

## Describe the solution you would like
As explained above, all usages of `$options` should be replaced with `$parameters`. An example of what the new manifest should look like:
```
sample_stream:
  type: DeclarativeStream
  $parameters:
    name: sample
  primary_key: id
  schema_loader:
    $ref: "*ref(definitions.schema_loader)"
  retriever:
    $ref: "*ref(definitions.retriever)"
    record_selector:
      $ref: "*ref(definitions.results_selector)"
    requester:
      $ref: "*ref(definitions.requester)"
      path: "/messages/{{ stream_slice.id }}/history"
```

The low-code documentation should also be reflected to use the new `$parameter` keyword.

The sample manifest file `{{snakeCase name}}.yaml.hbs` in the low-code generator should also have `$options` switched to `$parameters`.

A well tested script to replace all instances of `$options` with `$parameters` should be written and ready for use when we make the major version bump. The script should also check for any usage of options within interpolation blocks such as `{{ options['name'] }}` and replace it as `{{ parameters['name'] }}`

## Acceptance Criteria

- [ ] The parser should now interpret $parameters instead of $options keyword
- [ ] The declarative component dataclasses should be renamed from options to parameters and they should be passed to interpolated classes as parameters
- [ ] A migration should transform all usage of the $options keyword to $parameters
- [ ] A migration should transform all existing interpolation templates that use options to use parameters
- [ ] Documentation should be updated to reflect the change

## Implementation Approach
The basic flow for how a low code connector transforms a YAML spec into a declarative source that can handle connector operations is made up of two steps:

1. Parse the source's manifest YAML file into a mapping of component definition mappings.
2. Depending on the operation (spec, check, read), we use the `DeclarativeComponentFactory` to construct the relevant declarative components. It is during this create component step that we read apply `$options` at the current level and pass it down to child components. 

In `factory.py` and `create_partial.py` anywhere we use the keyword `$options` should be replaced with `$parameters`.

For consistency, we should also rename the `options` parameter on all declarative components to `parameters`.
