### ISSUE TITLE
[Low-Code CDK] Remove request_options_provider from the manifest language

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#19410]
## Tell us about the problem you're trying to solve
**BREAKING CHANGE**

The `request_options_provider` component was originally implemented to organize all relevant request parameter fields under a common component during sync processing. However, from the perspective of a developer writing a manifest, this just feels like an arbitrary component that doesn't provide much value. 

We should promote the following fields from the `request_options_provider` component to the parent `http_requester` component and remove `request_options_provider` from the language:

- request_parameters
- request_headers
- request_body_data
- request_body_json

## Describe the solution you would like

A sample of the manifest for the `http_request` component is as follows:
```
requester:
  url_base: "https://sample-state.com"
  http_method: "GET"
  authenticator:
    type: BearerAuthenticator
    api_token: "{{ config['api_key'] }}"
  request_parameters:
    created_after: "{{ config['start_date'] }}"
  request_headers:
    company_id: "{{ config['company_id'] }}"
  request_body_json:
    body_key: "body_val"
  request_body_data:
    body_data: "body_str_val"
```

Any documentation related to the request_options_provider should be removed and any code examples should be modified to reflect the various request options being defined the requester itself.

Given that very few connectors actually use `request_options_provider`, it might be simpler to just un-indent the various fields and remove the `request_options_provider` field.

The low-code generator templates don't have `request_options_provider` defined so they should not need to be modified.

## Acceptance Criteria

- [ ] request_parameters, request_headers, request_body_json, and request_body_data should be fields of the requester and not be nested underneath a request_options_provider
- [ ] Existing low-code connector manifests should reflect the new changes (either via migration or handwritten)
- [ ] documentation and code samples should be updated accordingly
- [ ] Update connector builder

## Implementation Approach
Under the hood, we should retain the `InterpolatedRequestOptionsProvider` class because it still useful for consolidate request input evaluation under a common object for organization purposes. However, we can avoid forcing developers to specify it in the language by changing the `HttpRequester` dataclass. We can replace the `request_options_provider` field with fields for `request_parameters`, `request_headers`, `request_body_data`, and `request_body_json`. And `__post_init__()` we can use the inputs to instantiate an `InterpolatedRequestOptionsProvider`. That allows us to still use the structure behind the scenes but not expose it to developers.
