### ISSUE TITLE
[connector builder]: Support declaring & exporting stream schemas in the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19499]
## Tell us about the problem you're trying to solve
a user of the connector builder UI needs the ability to specify stream schemas in the UI such that when they click "export connector" the schemas they specified in the UI are the same ones that actually run in the connector itself outside of the connector builder. 

## Implementation options

**Bundle into manifest**
The most obvious way to achieve this is to bundle schema definitions into the manifest itself. This way the user maintains only one file they download from the UI, which they copy-paste into their connector directory to build the connector. 

The pro of this approach is that it is the most portable/lightweight
The con is that it makes the YAML file very large/maybe unreadable

Implementation steps:
1. Create `StaticSchemaLoader` class which takes a schema mapping object as parameter
2. Add `StaticSchemaLoader` to the class type registry
3. Update one of the connectors to use the new schema definition:
```
  applications_stream:
    $ref: "*ref(definitions.base_incremental_stream)"
    $options:
      name: "applications"
      path: "applications"
    stream_cursor_field: "applied_at"
    schema_loader:
      type: "StaticSchema"
      schema:
        status:
          type: string
        source:
          type: object
          properties:
            public_name:
              type: string
            id:
              type: integer
    <...>
    retriever:
      $ref: "*ref(definitions.retriever)"
      requester: "*ref(definitions.requester)"
      stream_slicer:
        request_cursor_field: "created_after"
        cursor_field: "applied_at"
        class_name: source_greenhouse.components.GreenHouseSlicer
```

**Continue using `schemas/` folders pattern**
Instead of bundling, we could also change the behavior of the "export YAML" button to download instead a zip folder which contains the YAML manifest in addition to a `schemas/` folder, containing one `.json` schema file per stream. This would mirror exactly the way we typically specify schemas today. 

The pro of this approach is that it keeps the YAML file clean
The con of this approach is that it complicates how a user consumes a downloaded connector

### Acceptance Criteria
- [x] Follow implementation steps for "bundle" option 1 above
- [x] At least 1 existing connector defines its stream schemas inline
- [x] The output of the discover method must be unchanged for connectors we migrated

Out of scope:
- Schema auto-detection 

### Open questions
- do we want to rename `SchemaLoader` to `Schema` since we're not always loading it from a file?
