### ISSUE TITLE
add endpoint to connector builder to validate and dereference the components of a connector manifest

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#19761]
## Tell us about the problem you're trying to solve
The FE will have to transform a yaml file into the form. The yaml representation of the manifest can contain references to other components which the FE does not know how to resolve.

Example:
```
  schema_loader:
    type: JsonFileSchemaLoader
    file_path: "./source_greenhouse/schemas/{{ options['name'] }}.json"

  base_stream:
    $options:
      name: "applications"
    primary_key: "id"
    schema_loader:
      $ref: "*ref(definitions.schema_loader)"
   <maybe more refs...>

  close_reasons_stream:
    $options:
      name: "close_reasons"
      path: "close_reasons"
    primary_key: "id
    schema_loader:
      type: JsonFileSchemaLoader
      file_path: "./source_greenhouse/schemas/{{ options['name'] }}.json"
    <...>
```

## Describe the solution you’d like
Add an endpoint on the connector builder server that accepts a manifest and
1. validates the schema of the manifest
2. dereferences the references (using a [ManifestReferenceResolver](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/parsers/manifest_reference_resolver.py#L11))

The FE will then be able to transform the content of the yaml file into the form

## Implementation details
1. Add an endpoint to the openapi spec. Its input and output must be of type ConnectorManifest (or `type: object`)
2. ManifestReferenceResolver().preprocess_manifest(input_manifest, {}, "")
  * The function signature can be changed such that the 2nd and 3rd parameters are default values
3. Return the output of (2)

## Acceptance criteria
- A user can call `/resolve_manifest` with a manifest containing references, and obtain a manifest whose references are resolved
