### ISSUE TITLE
low-code: Customize auth header when using OAuth

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#19827]
## Tell us about the problem you're trying to solve
When using OAuth 2.0, the auth header is hardcoded to `{"Authorization": f"Bearer {self.get_access_token()}"}`
It should be possible to customize it for APIs that do not use Bearer authentication

## Describe the solution you’d like
```
authenticator:
  type:  OAuthAuthenticator
  token_refresh_endpoint: <...>
  client_id: "{{config['client_id'] }}"
  client_secret: "{{ config['client_secret'] }}
  auth_header:
    Authorization: "Bearer {{ access_token }}"
```

Note that this uses a new keyword "access_token" which is scoped to the authenticator and returns the access token (using `get_access_token`)
