### ISSUE TITLE
[Low-Code CDK] Separate date time iteration from stream slice iteration within the SimpleRetriever component

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#19961]
## Tell us about the problem you're trying to solve
**BREAKING CHANGE**

Stream slicers are a difficult concept to reason about for new connector developers to grasp because they cover two related but different concepts: incremental syncs, and partitioning the records. For the `SimpleRetriever` component, the `stream_slicer` field allows for various types of slicers the most common of which include the DatetimeStreamSlicer and the SubstreamSlicer.

## Tell us the solution you would like

In order to clearly delineate components that are used to implement incremental syncs, the `SimpleRetriever` should have a new field called `datetime_range` which accepts a DatetimeStreamSlicer component which will continue to function as it currently does.

In order to clearly delineate components that perform partitioning and iteration based on a heuristic, we will rename the existing `stream_slicer` on the `SimpleRetriever` component to `iterator`. This field will accept `CartesianProductStreamSlicer`, `SingleSlice`, `Substreamslicer`, and `CustomStreamSlicer`.

New Manifest:
```
retriever:
    type: SimpleRetriever
    name: "{{ options['name'] }}"
    primary_key: "{{ options['primary_key'] }}"
    datetime_range:
      type: DatetimeStreamSlicer
      cursor_field: updated_at
      start_datetime: 12-12-2022
      end_datetime: 01-13-2022
      ...
      step: 1D
    iterator:
      type: SubstreamSlicer
      parent_stream_configs
        - stream: "#/definitions/messages_stream"
           parent_key: id
           stream_slice_field: id
```

## Open Questions

- Should we rename DatetimeStreamSlicer to DatetimeRangePartition?
- Do we foresee a need to allow multiple DatetimeStreamSlicers per requester? (We don't currently have connectors that need the cartesian product of multiple stream slicers)

## Acceptance Criteria

- [ ] The declarative_component_schema.yaml should be updated with the decouples `iterator` and `datetime_range`
- [ ] Models have been regenerated
- [ ] Retrievers that have both `iterator` and `datetime_range` defined use the cartesian product of both slicers
- [ ] Existing connectors are migrated so that datetime slicers are under the `datetime_range` field and other slicers are `iterator`. Stream slicer is a frequently used field, so a migration script to rename is likely needed.
- [ ] Documentation is updated to reflect the changes.

## Implementation Approach

A few points of interest during implementation.

- We have a component called CartesianProductStreamSlicer. This is used in a couple different connectors to combine substream and DatetimeStreamSlicer behavior that loops over both partitions. In order to replicate this behavior, when iterating over slices, we should continue to loop over both the `datetime_range` and the `stream_slicer` under the hood thus resulting in the same cartesian product.
- We will likely need to define a new custom type `CustomDatetimeRange` because we have some CustomStreamSlicers that are meant to be custom implementations of the now `DatetimeStreamSlicer`
