### ISSUE TITLE
Low Code Connector tutorial example invalid yaml config

### ISSUE THREAD

**Issue by juweins** [airbytehq/airbyte#20071]
### Tell us about the documentation you'd like us to add or update.
During reproduction of Issue [Issue #20047](https://github.com/airbytehq/airbyte/issues/20047#issue-1474466553) I found inconsistencies in the tutorials yaml file. By following the tutorial and the provided code snippets I came across the following problems in `source_exchange_rates_tutorial/exchange_rates_tutorial.yaml`:

```yaml
spec: 
  documentationUrl: https://docs.airbyte.io/integrations/sources/exchangeratesapi
  connectionSpecification:
```
Both keys are wrong and lead to an unresolved documentation_url / spec.

It should be like this:

```yaml
spec: 
  documentation_url: https://docs.airbyte.io/integrations/sources/exchangeratesapi
  connection_specification:
```

### If applicable, add links to the relevant docs that should be updated
- [3-connecting-to-the-API-source](https://github.com/airbytehq/airbyte/blob/5149108020645cb8e3ae47045eb13e270cd85e59/docs/connector-development/config-based/tutorial/3-connecting-to-the-API-source.md)
- [5-incremental-reads.md](https://github.com/airbytehq/airbyte/blob/5149108020645cb8e3ae47045eb13e270cd85e59/docs/connector-development/config-based/tutorial/5-incremental-reads.md)
- [6-testing](https://github.com/airbytehq/airbyte/blob/5149108020645cb8e3ae47045eb13e270cd85e59/docs/connector-development/config-based/tutorial/5-incremental-reads.md)
