### ISSUE TITLE
CDK: don't filter failed interpolated vars for request_options_provider.request_body_json

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#20295]
## What
In current implementation of Interpolation this does not work:
```
request_options_provider:
    request_body_json:
       key1: "{{ False }}"
       key2: "{{ 0 }}"
```

`key1`, `key2` will be removed because of this:
https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/requesters/request_options/interpolated_request_input_provider.py#L48

I propose do this "empty value" filtering only for:
`request_options_provider.get_request_params`
`request_options_provider.get_request_headers`
`request_options_provider.get_request_body_data`

but for `request_options_provider.request_body_json`  skip this filtering
