### ISSUE TITLE
Pass only needed information in `StandardTapConfig`

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#206]
## Tell us about the problem you're trying to solve
`StandardTapConfig` currently contains a lot of "wide" data types which contain a lot more data than is needed to pull data from a Singer tap. This makes writing tests more tedious than is necessary and makes it harder to understand which inputs impact behavior. 

## Describe the solution you’d like
Create new types to capture exactly the information needed for taps, and remove any extra cruft.

**Comment by cgardens** [comment]
I believe this has been done. current configuration
```
  sourceConfiguration:
    description: Integration specific blob. Must be a valid JSON string.
    type: object
    existingJavaType: com.fasterxml.jackson.databind.JsonNode
  destinationConfiguration:
    description: Integration specific blob. Must be a valid JSON string.
    type: object
    existingJavaType: com.fasterxml.jackson.databind.JsonNode
  catalog:
    description: the configured airbyte catalog
    type: object
    existingJavaType: io.airbyte.protocol.models.ConfiguredAirbyteCatalog
  state:
    description: optional state of the previous run. this object is defined per integration.
    "$ref": State.yaml
```
