### ISSUE TITLE
[Low-code CDK] Support interpolated values in request_body_json

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#20734]
## Context
When a JSON blob with deeply-nested fields is passed into the `request_body_json` field, this blob is directly decoded into an object, which means interpolated values are not resolved.

Users may want to use interpolated strings anywhere in the JSON blob, so this should be supported by the CDK.

One method of achieving this is to convert the JSON blob to a string, resolve the interpolated values, then convert back to JSON, before decoding the JSON object.

## Acceptance Criteria
- The `request_body_json` field supports interpolated values at any level of nesting in JSON blobs

**Comment by lmossman** [comment]
Grooming notes:
- If going with the suggested approach, interpolated values would need to be escaped so that something like a quote in the interpolated value does not cause the JSON syntax to be invalid
- Decide if we should allow users to inject actual JSON into the request body json, e.g. `{ mykey: {{ config[‘abc’] }} }`

**Comment by sherifnada** [comment]
seems like you can also force YAML types using `!!<type>` syntax, see here: https://www.educative.io/answers/how-to-represent-different-basic-data-types-in-yaml

**Comment by lmossman** [comment]
@maxi297 to take point on answering the open interface questions

**Comment by maxi297** [comment]
# My understanding of where the current implementation fails to support this
Currently, a RequestInput is either a str or a  Mapping[str, str]. This brings a couple of limitations:
1. Integer can't be set as values. 
```
      request_body_data:
        clause: 10
```
... would not work because the value for clause is an int and not a string
  2. We can't have nested fields
```
      request_body_data:
        clause:
          type: "timestamp"
```
... would not work because the value for "clause" is an object and not a string.

# Proposed solution
* Change the type of request_data to `RequestInput = Union[dict[str, "RequestInput"], list["RequestInput"], str, int, float, bool, None]` to support all possible JSON format
* Implement InterpolatedRequestInput that supports the different types above:
** If it's a list, InterpolatedRequestInput on every entry
** If it's a dict, interpolated keys as string and value as InterpolatedRequestInput
** Else, return the value

This would allow us to support any types  and to dig deeper into the nested objects. A quick test on my side using:
```
    request_options_provider:
      request_body_data:
        -
          clause:
            type: timestamp
            operator: 10
            parameters:
              -
                value: "{{ stream_slice['start_time'] | int * 1000 }}"
              -
                value: "{{ stream_slice['end_time'] | int * 1000 + (86400000 - 1) }}"
            orderBy: 1
            columnName: "Timestamp"
```
... generated:
```
[{'clause': {'type': 'timestamp', 'operator': 10, 'parameters': [{'value': 1595376000000}, {'value': 1604015999999}], 'orderBy': 1, 'columnName': 'Timestamp'}}]
```

Base on this:
* Is it possible to interpolate a number into the yaml? Yes
* Do interpolated string values need to be escaped, so that the JSON syntax is not made invalid? No
