### ISSUE TITLE
Connector builder server: Error if body is a json-encoded array

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#20764]
The connector builder server only responds with
```
"Could not perform read with with error: [ErrorWrapper(exc=DictError(), loc=('body',))]"
```

if the body of the response is a an array instead of ab object. The same manifest works fine if run directly via python.

Example manifest:
```
version: 0.1.0
type: DeclarativeSource
check:
  type: CheckStream
  stream_names: []
streams:
  - name: accounts
    type: DeclarativeStream
    retriever:
      type: SimpleRetriever
      name: accounts
      requester:
        name: accounts
        url_base: https://api.timelyapp.com/1.1
        path: /accounts
        authenticator:
          type: BearerAuthenticator
          api_token: '{{ config[''api_key''] }}'
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_pointer: []
      paginator:
        type: NoPagination
spec:
  type: Spec
  documentation_url: http://example.org
  connection_specification:
    $schema: http://json-schema.org/draft-07/schema
    type: object
    required:
      - api_key
    properties:
      api_key:
        type: string
        title: API Key
        airbyte_secret: true
    additionalProperties: true
```

## Solution
The server can return the body as a string and let the webapp convert it to json.
```
    HttpResponse:
      type: object
      required:
        - status
      properties:
       <...>
        body:
          type: string
          description: String representation of the body of the HTTP response, if present
       <..>
```

### Alternative
* Change the type of HttpResponse.body to anyOf(object, array, string, number, boolean)
* This approach has additional complexity because the OpenAPI generator for Python does not support anyOf

## Acceptance criteria
- The connector builder can return responses where the body is a any valid json data type (string, number, object, array, boolean, null)
- [ ] pair with frontend eng @lmossman likely to finish frontend work

## Out of scope
- Support for non-json data types
