### ISSUE TITLE
[low-code] Some string interpolation could be replaced with struct with enums

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20797]
## Current Behavior

Taking cursor pagination as an example, in addition to config and options, values can be interpolated from
- decoded_response
- headers
- last_records

This is a finite set of values which could be represented declaratively

```
  CursorPagination:
    description: Pagination strategy that evaluates an interpolated string to define the next page token
    type: object
    required:
      - type
      - cursor_source
      - cursor_value
    properties:
      type:
        type: string
        enum: [ CursorPagination ]
      cursor_source:
        type: string
        enum: [ response, headers, last_records ]
      cursor_value:
        type: string
```
