### ISSUE TITLE
Support for authentication with keys as query parameter in configuration based connectors

### ISSUE THREAD

**Issue by imrehg** [airbytehq/airbyte#20790]
## Tell us about the problem you're trying to solve
I'm working on adding a new source (#20789) and their authentication requires passing in the API key as a query parameter (called `key`). I'm planning to use the configuration based / low-code connector toolkit to build this, however such an authentication pattern is not available for that connector type (looking through [the docs](https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/authentication/)).

## Describe the solution you’d like
Option of query-parameter type authentication, similar to [the `APIKeyAuthenticator`](https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/authentication/#apikeyauthenticator) except as a query parameter with a specific key, rather than a HTTP request header.

## Describe the alternative you’ve considered or used
This could be pretty easily implementable in the [Python HTTP API based connector](https://docs.airbyte.com/connector-development/cdk-python/http-streams), but that would lose the benefits of the low-code setup, naturally.

## Additional context
N/A

## Are you willing to submit a PR?
Yes.

**Comment by girarda** [comment]
This is a good idea! As a work around until it's implemented, you can set the api key directly in the requester's

example:
```
  requester:
    url_base: "..."
    request_options_provider:
      request_parameters:
        api_key: "{{ config['api_key'] }}"
```

**Comment by imrehg** [comment]
Thanks @girarda, that's a super good point! Yeah, it would totally work, didn't think of that one. Interesting to find the right level of coding and config even in this low-code connector environment. Will give this one a try!

**Comment by girarda** [comment]
Proposed schema change:
```
  ApiKeyAuthenticator:
    title: API Key Authenticator
    description: Authenticator for requests authenticated with an API token injected as an HTTP request header.
    type: object
    required:
      - type
      - api_token
    properties:
      type:
        type: string
        enum: [ApiKeyAuthenticator]
      api_token:
        title: API Key
        description: The API key to inject in the request. Fill it in the user inputs.
        type: string
        interpolation_context:
          - config
        examples:
          - "{{ config['api_key'] }}"
          - "Token token={{ config['api_key'] }}"
      inject_into:
        title: Inject API Key Into Outgoing HTTP Request
        description: Configure how the API Key will be sent in requests to the source API.
        "ref": "#/definitions/RequestOption"
      $parameters:
        type: object
        additionalProperties: true
```
- Replace `header` field with `inject_into`

## Implementation 
- Add a query_param() and request_body() methods to `ApiKeyAuthenticator`
- BearerAuthenticator and BasicHttpAuthenticator will always set inject_to to Header
- In SimpleRetriever, inject the Authenticator's request params, request body and request headers

## Acceptance criteria
- [ ] The ApiKeyAuthenticator respects the new interface
- [ ] The authenticator's API key can be inserted as a query param
- [ ] The FE is updated
- [ ] The Congress API can be implemented in the connector builder using a standard authenticator
