### ISSUE TITLE
connector template should set the "title" property on the API key

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20793]
## Tell us about the problem you're trying to solve
connector template should set the "title" property on the API key

## Describe the solution you’d like
```
    properties:
      api_key:
        type: string
        title: API Key
        description: API Key
```
