### ISSUE TITLE
RequestOption should be split in two different structs

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20792]
## Current Behavior
RequestOptions are used to defined where to set a request parameter.

The struct has two fields:
```
    inject_into: RequestOptionType
    field_name: Optional[str] = None
```
Inject into defines how to update the request. It can either update a request param, a request header, body, or the path.

The field_name cannot be set when inject_into is path. This is done by making field_name optional and raising an exception if inject_into == path and field_name is set.

This is a problem because using a path and field_name seems like a valid manifest, but will cause a failure at runtime.

## Expected Behavior
- modifying the request path should be done using a separate struct.
- path should not be a valid RequestOptionType value

Example update schema (better name and description TBD)
```
  RequestModifier:
    anyOf:
      - "$ref": "#/definitions/RequestOption"
      - "$ref": "#/definitions/RequestPath"
  RequestOption:
    description: Describes an option to set on a request
    type: object
    required:
      - type
      - inject_into
      - field_name
    properties:
      type:
        type: string
        enum: [ RequestOption ]
      inject_into:
        enum:
          - request_parameter
          - header
          - body_data
          - body_json
      field_name:
        type: string
  RequestPath:
    description:
    type: object
    required:
      - type
      - path
    properties:
      type:
        type: string
        enum: [ RequestPath ]
      path:
        type: string
```
