### ISSUE TITLE
Connector builder server: Return details about authentication failure

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#21016]
When the configured authentication fails, the only error returned to the client is an internal exception not pointing at the root cause

Example

```
version: 0.1.0
type: DeclarativeSource
check:
  type: CheckStream
  stream_names: []
streams:
  - type: DeclarativeStream
    name: o
    primary_key: []
    retriever:
      type: SimpleRetriever
      name: o
      primary_key: []
      requester:
        type: HttpRequester
        name: o
        url_base: https://pokeapi.co/api/v2/
        path: pokemon/
        authenticator:
          type: OAuthAuthenticator
          client_id: 'A'
          client_secret: 'B'
          refresh_token: 'C'
          refresh_request_body: {}
          token_refresh_endpoint: invalid_refresh_endpoint
        config: {}
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_pointer: []
      paginator:
        type: NoPagination
      config: {}
```

returns the following `detail`:

```
"Could not perform read with with error: Every message grouping should have at least one request and response - Traceback (most recent call last):\n File \"/home/connector-builder-server/./connector_builder/impl/default_api.py\", line 115, in read_stream\n for message_group in self._get_message_groups(\n File \"/home/connector-builder-server/./connector_builder/impl/default_api.py\", line 170, in _get_message_groups\n raise ValueError(\"Every message grouping should have at least one request and response\")\nValueError: Every message grouping should have at least one request and response\n"
```

However the connector does emit a log message containing the following error, which should get forwarded to the client as part of the response to the read command:
```
raise Exception(f\"Error while refreshing access token: {e}\") from e\nException: Error while refreshing access token: Invalid URL 'invalid_refresh_endpoint': No scheme supplied. Perhaps you meant http://invalid_refresh_endpoint?
```

## Acceptance criteria

* For authentication errors like in the example above, an actionable error message is shown to the user
