### ISSUE TITLE
Read `allowed_hosts` from actor definitions yaml and store in database

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#21183]
From the [tech spec](https://docs.google.com/document/d/1NHmdzMSBtF2dZWd_XXDRpvpJtF2DUFSdXXdhY2Tz6dI/edit#):

ActorDefintions are updated so that connectors can declare which hosts/IPs they intend to connect to.  This is a new optional field in [source_definitions.yaml](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/source_definitions.yaml) and  [destination_definitions.yaml](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/destination_definitions.yaml).

```yaml
- name: HubSpot
  sourceDefinitionId: 36c891d9-4bd9-43ac-bad2-10e12756272c
  dockerRepository: airbyte/source-hubspot
  dockerImageTag: 0.3.0
  documentationUrl: https://docs.airbyte.com/integrations/sources/hubspot
  icon: hubspot.svg
  sourceType: api
  releaseStage: generally_available
  # ~~~ NEW ~~~
  allowed_hosts:
    - *.hubspot.com 
```

The new “allowed_hosts” property is an array.  It’s values can be URL matches (per the example above, e.g. "*.instagram.com"), IP address and/or CIDR ranges, or a reference to a value that will be completed by the user completing the connector’s configuration.  The reference use-case is required for those connectors who accept a dynamic hostname or IP address to connect to (e.g. a database hostname or an API sub-domain).  A reference specification could look like:

```yaml
allowed_hosts:
 - “${#/definitions/config/hostname}”
```

Finally, we can combine the approaches for when there’s a customer-specific subdomain in use with interpolation:

```yaml
allowed_hosts:
- “${#/definitions/config/subdomain}.snowflake.com”
```

**This information should be loaded by the bootloader and stored in the actor_defintions table in the database in a new column as a JSON array.**
