### ISSUE TITLE
Update OSS to latest AWS SDK

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#21229]
## Tell us about the problem you're trying to solve

Currently, OSS is tied to a very old versions of the `com.amazonaws:aws-java-sdk-s3` (version 1.12.6 from June 2021) and `software.amazon.awssdk:s3` (version 2.16.84 from June 2021) libraries.  If any other dependency is updated that pulls in a newer version of those libraries, it can cause acceptance tests to fail, due to assumptions about the format of the URL used to request objects and how we have configured our stand in [Minio](https://min.io/) instance to represent S3 for testing.  We have solved this temporarily by pinning the versions of those dependencies to ensure that a transitive dependency does not cause this to regress.  Obviously, we should fix the issue with the change in URL format so that we can stay up to date on all dependencies, including the two mentioned above.

## Describe the solution you’d like

To solve for this, we should change how we configure the [Minio](https://min.io/) instance included for acceptance testing via Kubernetes to map requests using the new format to the pod/service.  A simple approach is to explicitly set the hostname/subdomain in the deployment descriptor:

```yaml
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: airbyte-minio
spec:
  selector:
    matchLabels:
      app: airbyte-minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: airbyte-minio
    spec:
      # Refer to the PVC created earlier
      volumes:
        - name: storage
          persistentVolumeClaim:
            # Name of the PVC created earlier
            claimName: airbyte-minio-pv-claim
      containers:
        - name: airbyte-minio
          # Pulls the default Minio image from Docker Hub
          image: minio/minio:latest
          args:
            - server
            - /storage
          env:
            # Minio access key and secret key. This must match the S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY declared in /dev/.env.
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"
                      - name: MINIO_DOMAIN
                        value: "airbyte-minio-svc"
          ports:
            - containerPort: 9000
          # Mount the volume into the pod
          volumeMounts:
            - name: storage # must match the volume name, above
              mountPath: "/storage"
      hostname: airbyte-dev-logs
      subdomain: airbyte-minio-svc
```

This needs to be done to accept both requests to the log bucket AND state bucket.  The solution above only handles the log bucket requests and will work for OSS.  This will not work in cloud, which needs both.  Therefore, we will have to find a way to handle both URL requests (e.g. <bucket name>.<host name>).  If there is a way to map multiple hostnames via DNS in Kubernetes, that would be the most straightforward solution.  If not, then we may need to look into adding a proxy to do this OR launch multiple [Minio](https://min.io/) pods to handle the different concerns (logs, state).
