### ISSUE TITLE
[Low-Code CDK] Remove DefaultPaginator.url_base in favor of inheriting from HttpRequester.url_base

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#21559]
## Tell us about the problem you're trying to solve
**BREAKING CHANGE**

Within the declarative language, both the HttpRequester and the DefaultPaginator have a `url_base` field and this always ends up being duplicated across both components. This can lead to misalignment and being extra verbose.

## Describe the solution you would like

Only the HttpRequester should have a `url_base` string field and the DefaultPaginator should "inherit" this value from the HttpRequester when components are being initialized.

```
retriever:
  type: SimpleRetriever
  name: "{{ options['name'] }}"
  primary_key: "{{ options['primary_key'] }}"
  requester:
    type: HttpRequester
    name: "test"
    url_base: "https://test.something.io/v1/"
    http_method: "GET"
    authenticator:
      type: NoAuthentication
  paginator:
    type: DefaultPaginator
    pagination_strategy:
      type: OffsetIncrement
      page_size: 10
```

## Acceptance Criteria
- [x] The declarative_component_schema.yaml should be updated w/ `DefaultPaginator.url_base` removed
- [x] DefaultPaginator still supports removing the url_base from the path in the `path()` method
- [x] Either a migration is included removing all instances of `DefaultPaginator.url_base` or manually remove each
- [x] Documentation for the DefaultPaginator has been updated w/ `url_base` removed 
- [x] An associated ticket to update the connector builder UI frontend has been filed (see https://github.com/airbytehq/airbyte/issues/21926)

## Implementation Approach

- When initializing the SimpleRetriever we should initialize a child HttpRequester component using it's associated HttpRequester model. When initializing the child DefaultPaginator, the HttpRequester model's `url_base` should be passed a kwarg.
- There are 77 usages of the DefaultPaginator component, this makes sense since it's one of the most commonly used components. A migration might be worth it, but manual is also fairly quick to remove each instance.
