### ISSUE TITLE
[Low-Code CDK] DeclarativeStream should define name and primary_key and these fields should be removed from other declarative components

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#21560]
## Tell us about the problem you're trying to solve
**BREAKING CHANGE**

It is confusing to have duplicative `name` and `primary_key` fields across the `DeclarativeStream` `SimpleRetriever`, and `HttpRequester` components. 

## Describe the solution you would like

The `name` and `primary_key` fields should be consolidated onto the `DeclarativeStream` component which is the top most field where the fields are relevant. Child components like `SimpleRetriever` and `HttpRequester` can inherit this field.

```
events_stream:
  type: DeclarativeStream
  name: events
  primary_key: id
  retriever:
    type: SimpleRetriever
    requester:
      type: HttpRequester
      url_base: "https://test.something.io/v1/"
      http_method: "GET"
      authenticator:
        type: NoAuthentication
```

## Acceptance Criteria
- [ ] The declarative_component_schema.yaml should be updated w/ `name` and `primary_key` removed from other components that are not DeclarativeStream
- [ ] SimpleRetriever and HttpRequester still have `name` and `primary_key`, but inherited from the parent component 
- [ ] Either a migration is included removing all instances of `SimpleRetriever.name`, `SimpleRetriever.primary_key` and `HttpRequest.name`
- [ ] Documentation for the SimpleRetriever and HttpRequester has been updated w/ `name` and `primary_key` removed 
- [ ] An associated ticket to update the connector builder UI frontend has been filed

## Implementation Approach

- When initializing the DeclarativeStream we should initialize a child SimpleRetriever component using it's associated model. We should also pass the `name` and `primary_key` fields from the DeclarativeStream model via kwargs
- A common pattern that was used to reduce duplication of fields on existing connectors was to define `name` and `primary_key` under `$options`. This should now be unnecessary, but could be a slightly more complex migration. This would be considered out of scope, but maybe worth seeing what the lift would be. The other concern is that the JsonFileSchemaLoader path would need to continue to reuse `options.name`.
