### ISSUE TITLE
[Low-Code CDK] Remove stream_cursor_field from DeclarativeStream

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#21561]
## Tell us about the problem you're trying to solve
**BREAKING CHANGE**

We redundantly define the cursor field for incremental streams in multiple places on both the `DeclarativeStream.stream_cursor_field` and stream_slicer's `cursor_field`. Similar to other issues, these fields should be the same for a given stream so there is no need to define them twice.

## Describe the solution you would like

Because incremental syncs always require a stream slicer, the `cursor_field` should be defined on that component. The DeclarativeStream component can use the `DeclarativeStream.retriever.stream_slicer` model to get the `cursor_field`.

```
events_stream:
  type: DeclarativeStream
  name: events
  primary_key: id
  retriever:
    type: SimpleRetriever
    stream_slicer:
      type: DatetimeStreamSlicer
      start_datetime:
        datetime: "{{ config['start_date'] }}"
        datetime_format: "%Y-%m-%dT%H:%M:%S%z"
      end_datetime:
        datetime: "{{ now_utc().strftime('%Y-%m-%dT%H:%M:%S%z') }}"
        datetime_format: "%Y-%m-%dT%H:%M:%S%z"
      datetime_format: "%Y-%m-%dT%H:%M:%S.%f%z"
      cursor_granularity: "PT0.000001S"
      step: "P1D"
      cursor_field: timestamp
    requester:
      type: HttpRequester
      url_base: "https://test.something.io/v1/"
      http_method: "GET"
      authenticator:
        type: NoAuthentication
```

## Acceptance Criteria
- [ ] The declarative_component_schema.yaml should be updated w/ `stream_cursor_field` removed from DeclarativeStream
- [ ] DeclarativeStream `stream_cursor_field` is derived from the stream slicer
- [ ] Either a migration is included removing all instances of `DeclarativeStream.stream_cursor_field`
- [ ] Documentation for the DeclarativeStream has been updated
- [ ] An associated ticket to update the connector builder UI frontend has been filed

## Implementation Approach

- We had originally named the field `DeclarativeStream.stream_cursor_field` (which is redundant), because of a collision w/ the `cursor_field()` property method. We can investigate renaming, but this all under the hood so not a big deal.
- It is possible for a stream's retriever to not specify a stream slicer, such as in the case of a stream only supporting full refresh. So in the case that there is no stream slicer, we should just return `[]` like we do in the defaults.
