### ISSUE TITLE
Low Code UI: Missing field_pointer in the YAML

### ISSUE THREAD

**Issue by ryjabe** [airbytehq/airbyte#22055]
## Environment
Low Code UI
40.29

## Current Behavior
Setting a record selector/field pointer works in the UI, but it doesn't autogenerate in the browser-hosted YAML.  However, if you download the YAML though it does appear in the config.  🤷 

## Expected Behavior
Once you set the record selector in the UI it should show up in the YAML file.  

## Steps to Reproduce
1. Set the record selector
2. Check the YAML in the UI

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by lmossman** [comment]
@ryjabe I'm not able to reproduce this issue on v0.40.29. When I set a record selector in the UI and switch to the YAML, I see the following block on the stream that I set it on:
```
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_pointer:
            - results
```

and when I remove it from the UI side, that block is updated to
```
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_pointer: []
```

If you're seeing something different, do you mind recording a loom to demonstrate the issue?  Thanks!
