### ISSUE TITLE
Update helm template to load `env_vars` from global values

### ISSUE THREAD

**Issue by Santhin** [airbytehq/airbyte#22389]
## Environment
- **Airbyte version**:   chart version 0.43.22
- **Deployment**: kubernetes with helm chart

## Current Behavior
While trying to specify global env vars for deployment I need to create dummy env_vars in each application where I want to propagate these global env_vars 
Example `values.yaml` with dummy env var
```yaml
global:
  env_vars:
    HTTP_PROXY: "10.136.0.000:0000"

webapp:
  env_vars:
    DUMMY: DUMMY

server:
  env_vars:
    DUMMY: DUMMY
```
Example output:
```yaml
# Source: airbyte/charts/webapp/templates/deployment.yaml
        # Values from env
        - name: DUMMY
          value: "DUMMY"
        - name: HTTP_PROXY
          value: "10.136.0.000:0000"
# Source: airbyte/charts/server/templates/deployment.yaml
        # Values from env
        - name: DUMMY
          value: "DUMMY"
        - name: HTTP_PROXY
          value: "10.136.0.000:0000"
```

Example `values.yaml` without dummy env var
```yaml
global:
  env_vars:
    HTTP_PROXY: "10.136.0.000:0000"
```
Example output:
```yaml
# Source: airbyte/charts/webapp/templates/deployment.yaml
        # Values from env
# Source: airbyte/charts/server/templates/deployment.yaml
        # Values from env
```

## Expected Behavior
```yaml
# Source: airbyte/charts/webapp/templates/deployment.yaml
        # Values from env
        - name: HTTP_PROXY
          value: "10.136.0.000:0000"
# Source: airbyte/charts/server/templates/deployment.yaml
        # Values from env
        - name: HTTP_PROXY
          value: "10.136.0.000:0000"
```

## Proposal:

Changing this:
```yaml
{{- if .Values.env_vars }}
```
To this:
```yaml
{{- if or .Values.env_vars .Values.global.env_vars }}
```

Files that needs update:
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte-bootloader/templates/pod.yaml#L91
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte-cron/templates/deployment.yaml#L129
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte-metrics/templates/deployment.yaml#L102
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte-server/templates/deployment.yaml#L246
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte-temporal/templates/deployment.yaml#L100
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte-webapp/templates/deployment.yaml#L103
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte-worker/templates/deployment.yaml#L347
