### ISSUE TITLE
CustomFieldTransformation: list comprehension

### ISSUE THREAD

**Issue by artem1205** [airbytehq/airbyte#23134]
## Tell us about the problem you're trying to solve
Add field based on condition, to make it looks like:
```
    transformations:
      - type: AddFields
        fields:
          - path: ["custom_fields"]
            value: "{{ [{'name': k, 'value': v} for k, v in record.items() if k.startswith('cf_')] }}"
```
This structure does not work, as Jinja2 interpolation method does not support complex expressions, like comprehensions.
