### ISSUE TITLE
airbyte-metrics helm chart errors on deploy, can't find DATABASE_PASSWORD

### ISSUE THREAD

**Issue by sh4sh** [airbytehq/airbyte#23226]
## Environment
- **Airbyte version**:  helm v0.44.41 (latest)
- **OS Version / Instance**: MacOS, 
- **Deployment**: Kubernetes (Helm)
- **Step where error happened**: Deploy

## Current Behavior
airbyte-metrics chart is trying to find the `DATABASE_PASSWORD` value in the wrong location

Pods do not start, error on deploy: `secret "metrics-0.44.41" not found: CreateContainerConfigError`. The value it is looking for is actually found in the secret `<helm-release-name>-airbyte-secrets`.

[airbyte-metrics/templates/deployment.yaml](https://github.com/airbytehq/airbyte/blob/master/charts/airbyte-metrics/templates/deployment.yaml#L59-L63) tries to find the value with the following template:

```
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.database.secretName | default (include "airbyte.chart" .) }}
              key: {{ .Values.global.database.secretValue | default "postgresql-password" }}
```

`helm template` returns the following:
```
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metrics-0.44.1
              key: postgresql-password
```

## Expected Behavior

Most charts including [airbyte-server/templates/deployment.yaml](https://github.com/airbytehq/airbyte/blob/v0.44.1-helm/charts/airbyte-server/templates/deployment.yaml#L77-L81) find the value this way:

```
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.database.secretName | default (printf "%s-airbyte-secrets" .Release.Name ) }}
              key: {{ .Values.global.database.secretValue | default "DATABASE_PASSWORD" }}
```

`helm template` returns:

```
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-airbyte-secrets
              key: DATABASE_PASSWORD
```

## Steps to Reproduce
1. Deploy airbyte with airbyte-metrics using helm
2. See deploy error on airbyte-metrics pod

**Comment by sh4sh** [comment]
Workaround: set the values `global.database.secretName` and `global.database.secretValue` before deploy.

e.g. in values.yaml,

```
##  global -- Global params that are overwritten with umbrella chart
global:
  ...
  database:
    secretName: <helm-release-name>-airbyte-secrets
    secretValue: "DATABASE_PASSWORD"
```
