### ISSUE TITLE
Configure page size request option in connector builder

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#23350]
## Current Behavior
The page_size_option is an optional field on the `DefaultPaginator`, but it cannot be configured in the connector builder.

```
  DefaultPaginator:
    description: Default pagination implementation to request pages of results with a fixed size until the pagination strategy no longer returns a next_page_token
    type: object
    required:
      - type
      - pagination_strategy
    properties:
      type:
        type: string
        enum: [DefaultPaginator]
      pagination_strategy:
        anyOf:
          - "$ref": "#/definitions/CursorPagination"
          - "$ref": "#/definitions/CustomPaginationStrategy"
          - "$ref": "#/definitions/OffsetIncrement"
          - "$ref": "#/definitions/PageIncrement"
      decoder:
        "$ref": "#/definitions/JsonDecoder"
      page_size_option:
        "$ref": "#/definitions/RequestOption"
      page_token_option:
        anyOf:
          - "$ref": "#/definitions/RequestOption"
          - "$ref": "#/definitions/RequestPath"
      $parameters:
        type: object
        additionalProperties: true
```

## Expected Behavior
It should be possible to configure the paginator's page_size_option

## Acceptance criteria
- [ ] The paginator's page_size_option can be configured in the connector builder
