### ISSUE TITLE
CustomFieldTransformation: transform date-time fields to standard format

### ISSUE THREAD

**Issue by artem1205** [airbytehq/airbyte#23407]
## Tell us about the problem you're trying to solve
Resolving https://github.com/airbytehq/oncall/issues/1476.
Transformation of all date-time fields to standard date-time format was needed.

## Describe the solution you’d like

```
transformations:
  - type: DateTimeFieldsTransformation
    datetime_format: "%Y-%m-%d %H:%M:%S.%f%z"
    field_path: ['d', 'p', 'a', 't', 'h'] #Optional; passed to transform specific fields instead of all (see _get_date_time_dpath_from_schema)
```

PR: https://github.com/airbytehq/airbyte/pull/23395
