### ISSUE TITLE
Low-code CDK: Support OAuth client flow as an auth option

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#23450]
### Component Description

Some APIs support a flavor of OAuth known as OAuth Client credentials. In this flavor of OAuth, a client ID / secret are used to obtain an access token, skipping the refresh token entirely. 

Example diagram from Auth0: 
![image](https://user-images.githubusercontent.com/6246757/221279238-220634e9-b29e-4363-a4fe-ad4e8b1b499a.png)

Some example APIs which do this are: 
* [auth0](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow)
* [sellsy](https://api.sellsy.com/doc/v2/#section/Authentication)

### Proposed YAML schema

I would like to support this flow in the current OAuth authenticator or add a new OAuth authenticator which supports this flow. 

**Option 1: Add this to the current OAuth authenticator**
This should be doable if we make the `refresh_token` field optional in the current OAuth definition
```yaml
OAuthAuthenticator:
  description: Authenticator for requests using OAuth 2.0 authentication
  type: object
  required:
    - type
    - client_id
    - client_secret
    - token_refresh_endpoint
  properties:
    type:
      type: string
      enum: [OAuthAuthenticator]
    client_id:
      type: string
    client_secret:
      type: string
    refresh_token:
      type: string
    token_refresh_endpoint:
      type: string
    access_token_name:
      type: string
      default: "access_token"
    expires_in_name:
      type: string
      default: "expires_in"
    grant_type:
      type: string
      default: "refresh_token"
    refresh_request_body:
      type: object
      additionalProperties: true
    scopes:
      type: array
      items:
        type: string
    token_expiry_date:
      type: string
    token_expiry_date_format:
      description: The format of the datetime; provide it if expires_in is returned in datetime instead of seconds
      type: string
    $parameters:
      type: object
      additionalProperties: true
```
Then the user can configure the request body and grant type according to what they need. 

The downsides of this approach is that depending on the `grant_type`, `refresh_token` might actually be required. So it's not the best option. But it is workable. 

**Option 2: Optimal support in current OAuth authenticator**
Likely the optimal way to support this would be to display different required parameters depending on the `grant_type`. Something like: 

```yaml
OAuthAuthenticator:
  description: Authenticator for requests using OAuth 2.0 authentication
  type: object
  oneOf:
    - title: Refresh Token flow
      required:
      - type
      - grant_type
      - client_id
      - client_secret
      - refresh_token
      - token_refresh_endpoint
      properties:
        type:
          type: string
          enum: [OAuthAuthenticator]
        grant_type:
          type: string
          default: "refresh_token"
        client_id:
          type: string
        client_secret:
          type: string
        refresh_token:
          type: string
        token_refresh_endpoint:
          type: string
        access_token_name:
          type: string
          default: "access_token"
        expires_in_name:
          type: string
          default: "expires_in"
        refresh_request_body:
          type: object
          additionalProperties: true
        scopes:
          type: array
          items:
            type: string
        token_expiry_date:
          type: string
        token_expiry_date_format:
          description: The format of the datetime; provide it if expires_in is returned in datetime instead of seconds
          type: string
        $parameters:
          type: object
          additionalProperties: true
      - title: Client Credentials flow
        required:
        - type
        - grant_type
        - client_id
        - client_secret
        - authorization_endpoint
        properties:
          type:
            type: string
            enum: [OAuthAuthenticator]
          grant_type:
            type: string
            default: "client_credentials"
          client_id:
            type: string
          client_secret:
            type: string
          refresh_token:
            type: string
          authorization_endpoint:
            type: string
          access_token_name:
            type: string
            default: "access_token"
          expires_in_name:
            type: string
            default: "expires_in"
          refresh_request_body:
            type: object
            additionalProperties: true
          scopes:
            type: array
            items:
              type: string
          token_expiry_date:
            type: string
          token_expiry_date_format:
            description: The format of the datetime; provide it if expires_in is returned in datetime instead of seconds
            type: string
          $parameters:
            type: object
            additionalProperties: true
```

This is probably the best way to implement this change, but is also likely the most complex

**Option 3: Standalone support (additive change, not a breaking change)**

```yaml
ClientFlowOAuthAuthenticator:
    description: Authenticator for requests using OAuth 2.0 authentication
    type: object
    required:
      - type
      - client_id
      - client_secret
      - authorization_endpoint
    properties:
      type:
        type: string
        enum: [ClientFlowOAuthAuthenticator]
      client_id:
        type: string
      client_secret:
        type: string
      authorization_endpoint:
        type: string
      access_token_name:
        type: string
        default: "access_token"
      expires_in_name:
        type: string
        default: "expires_in"
      grant_type:
        type: string
        default: "client_credentials"
      authorization_request_body:
        type: object
        additionalProperties: true
      scopes:
        type: array
        items:
          type: string
      token_expiry_date:
        type: string
      token_expiry_date_format:
        description: The format of the datetime; provide it if expires_in is returned in datetime instead of seconds
        type: string
      $parameters:
        type: object
        additionalProperties: true
```
