### ISSUE TITLE
Consolidate actor definition version lookups

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#23573]
## Tell us about the problem you're trying to solve

Currently, whenever we want to access version-dependent information for an Actor Definition we directly access the values via e.g. `source.getDockerImageTag()` or `destination.getDockerImagrTag()`. This means we don't have a single place to implement overrides or feature flags for these values.

## Describe the solution you’d like

Consolidate the disparate calls to get version-specific information into a single method that would allow adding overrides later on.

### Proposal

introduce a new ActorDefinitionVersion POJO that will initially be a subset of an Actor Definition, containing only the per-version fields:

```yaml
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte-platform/blob/master/airbyte-config/models/src/main/resources/types/ActorDefinitionVersion.yaml
title: ActorDefinitionVersion
description: describes an actor definition version
type: object
required:
  - dockerRepository
  - dockerImageTag
  - documentationUrl
  - spec
additionalProperties: true
properties:
  dockerRepository:
    type: string
  dockerImageTag:
    type: string
  documentationUrl:
    type: string
  spec:
    type: object
    existingJavaType: io.airbyte.protocol.models.ConnectorSpecification
  releaseStage:
    type: string
    enum:
      - alpha
      - beta
      - generally_available
      - custom
  releaseDate:
    description: The date when this connector was first released, in yyyy-mm-dd format.
    type: string
    format: date
  protocolVersion:
    type: string
    description: the Airbyte Protocol version supported by the connector
  normalizationConfig:
    "$ref": NormalizationDestinationDefinitionConfig.yaml
  supportsDbt:
    type: boolean
    description: an optional flag indicating whether DBT is used in the normalization. If the flag value is NULL - DBT is not used.
  allowedHosts:
    "$ref": AllowedHosts.yaml
```

We can then introduce a new helper or singleton class that’ll allow getting the ActorDefinitionVersion for an actor definition + actorId. 

(pseudocode)

```java
public ActorDefinitionVersion getSourceVersion(StandardSourceDefinition sourceDefinition, UUID actorId) {
    return new ActorDefinitionVersion()
        .withDockerImageTag(sourceDefinition.dockerImageTag)
        .withXYZ();
}

public ActorDefinitionVersion getDestinationVersion(StandardDestinationDefinition sourceDefinition, UUID actorId) {
    return new ActorDefinitionVersion()
        .withDockerImageTag(destinationDefinition.dockerImageTag)
        .withXYZ();
}
```

At this stage all the information will still live in the same actor_defintions table, but we should no longer be using these fields directly.

## Acceptance criteria

- All lookups for version-specific information for actor definitions go through a method
- Version-specific actor definition fields are identified and accessed from a new POJO (ActorDefinitionVersion)

## Additional context

This is phase 0 from [[Tech Spec] Multiple Connector Versions](https://docs.google.com/document/d/1sMbAN9oumZxswnsyd2rGYwvsfOO4y8EQ_4m-WIs82hI)
