### ISSUE TITLE
Static overrides for actor definition versions

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#23574]
## Tell us about the problem you're trying to solve

We want to be able to override which version of a connector is run for a workspace or connection. After #23573 is introduced, we will have a single place to apply these kinds of overrides.

## Describe the solution you’d like

We can add an `actor_definition_version_overrides.yaml` file that can be used to set and apply version overrides.

The overrides file could look something like this:

```yaml
# GitHub
- actorDefinitionId: 1234-asdf-134-asdf-1234
  type: source
  overrides:
dockerImageTag: 1.2.3
spec: {}
actorIds:
   # Canary Workspace Source A
   - 4321-1324-asdf-wxyz
workspaceIds:
  # Acme Corp
  - 1234-1324-asdf-asdf
```

This information can then be used by the helper methods introduced in Phase 0 to override the defaults defined at the actor definition level. Note that we are including spec here, as the platform expects this information to be cached.

This would allow for applying overrides both at the actor- and workspace-level.

## Additional context

This is a temporary solution until we change the data model to support more dynamic overrides via feature flags.

This is part of phase 1 from [[Tech Spec] Multiple connector versions](https://docs.google.com/document/d/1sMbAN9oumZxswnsyd2rGYwvsfOO4y8EQ_4m-WIs82hI)

This probably works for both OSS and Cloud, but Cloud has it's own override file.

## Acceptance criteria

- Version-specific information for a connector can be overriden for a workspace and actor
