### ISSUE TITLE
Connectors using a datetime based cursor without setting request options should have a record filter on the cursor field

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#23885]
## Tell us about the problem you're trying to solve
Some of our connectors are described as being [semi-incremental](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-github/source_github/streams.py#L221-L228), in the sense that they might need to pull all records from the endpoint, but they only output new records. That can be done in low-code with a record filter.

This can be done by adding a record filter to the stream's selector:
```
selector:
  extractor:
    field_path: [ ]
  record_filter:
    type: RecordFilter
    condition: "{{ record['<stream_cursor_field>'] >= stream_slice['start_time'] and record['<stream_cursor_field>'] <= stream_slice['end_time'] }}"
```

The filter should only accept records whose cursor field is within the stream slice.

example for a stream whose cursor field is "created_at":
```
selector:
  extractor:
    field_path: [ ]
  record_filter:
    type: RecordFilter
    condition: "{{ record['updated_at'] >= stream_slice['start_time'] and record['updated_at'] <= stream_slice['end_time'] }}"
```
## Acceptance criteria
- [ ] Streams that support incremental syncs but do not have a start and end datetime request options automatically have a record filter filtering records
