### ISSUE TITLE
Connector Builder - Test read pagination retains previous slice information

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#24059]
## Environment
- **Airbyte version**:  example is 0.30.1

## Current Behavior
The first HTTP request for the next slice retains the last previous slice information

<img width="537" alt="image" src="https://user-images.githubusercontent.com/3360483/225071092-cec3fa1c-5b1a-4b94-b0ca-f3a5c0ce0117.png">

## Expected Behavior
Pagination starts from a fresh state on each slice

## Steps to Reproduce
1. In airbytehq/airbyte-platform-internal, `cd oss`
2. `VERSION=dev docker compose up`
3. `cd airbyte-webapp-e2e-tests` and `npm run createdummyapi` 
4. In a browser, go to http://localhost:8000/connector-builder
5. Create from yaml
```
version: 0.30.1
type: DeclarativeSource
check:
  type: CheckStream
  stream_names:
    - items
streams:
  - type: DeclarativeStream
    name: items
    primary_key: []
    schema_loader:
      type: InlineSchemaLoader
      schema:
        type: object
        $schema: http://json-schema.org/schema#
        properties:
          url:
            type: string
          name:
            type: string
    retriever:
      type: SimpleRetriever
      requester:
        type: HttpRequester
        url_base: http://dummy_api:6767/
        path: items/{{ stream_slice.item_id }}
        http_method: GET
        request_parameters: {}
        request_headers: {}
        request_body_json: {}
        authenticator:
          type: BearerAuthenticator
          api_token: '{{ config[''api_key''] }}'
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_path:
            - items
      paginator:
        type: DefaultPaginator
        page_token_option:
          type: RequestOption
          inject_into: header
          field_name: offset
        pagination_strategy:
          type: OffsetIncrement
          page_size: 2
      partition_router:
        - type: ListPartitionRouter
          values:
            - '1'
            - '2'
            - '3'
            - '4'
            - '5'
          cursor_field: item_id
spec:
  connection_specification:
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    required:
      - api_key
    properties:
      test_path:
        type: string
        title: test-path
      api_key:
        type: string
        title: API Key
        airbyte_secret: true
    additionalProperties: true
  documentation_url: https://example.org
  type: Spec
```
6. Set up user input authkey to `theauthkey`
7. Do a test read
