### ISSUE TITLE
Source File: Google Service Account Credentials are plain text

### ISSUE THREAD

**Issue by nina-j** [airbytehq/airbyte#24083]
## Environment
- **Airbyte version**:  0.41.0
- **OS Version / Instance**:
    - Operating System: EndeavourOS
    - Kernel: Linux 6.2.2-arch1-1
- **Deployment**: Docker running locally
- **Source Connector and version**: 0.2.33
- **Step where error happened**: Setup new source

## Current Behavior
When pasting Google Service Account JSON credentials to the file connector, it appears as plain text.

![image](https://user-images.githubusercontent.com/28903001/225269867-8a67831c-f28b-4de0-a870-eed16523f355.png)

## Expected Behavior
Credentials should be hidden in line with how they act elsewhere.

## Octavia source config
```yml
resource_name: "test_name"
definition_type: source
definition_id: 778daa7c-feaf-4db6-96f3-70fd645acc77
definition_image: airbyte/source-file
definition_version: 0.2.33

configuration:
  url: "gs://path/to/file.csv.gz"
  format: "csv"
  provider:
    storage: "GCS"
    service_account_json: ${CREDENTIALS_JSON}
  dataset_name: dataset.file
  reader_options: '{"compression": "gzip"}'

```

## Logs
n/a

## Steps to Reproduce
1. Create file connector that reads from GS and needs a `service_account_json` parameter
2. Observe that the JSON is pasted as plain text in UI

## Are you willing to submit a PR?

Yes.
