### ISSUE TITLE
Can't use Azure Database for PostgreSQL as Airbyte internal DB

### ISSUE THREAD

**Issue by detygon** [airbytehq/airbyte#24201]
## Environment
- **Airbyte version**:  0.42.0
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy

## Current Behavior
I get the following error: Unable to start server. Error: sql schema version compatibility check failed: pq: no pg_hba.conf entry for host "X.X.X.X", user "example_user", database "temporal", no encryption

## Expected Behavior

Airbyte deployed successfully.

## Logs
Unable to start server. Error: sql schema version compatibility check failed: pq: no pg_hba.conf entry for host "X.X.X.X", user "example_user", database "temporal", no encryption

## Steps to Reproduce
1. Set Azure Database for PostgreSQL as Airbyte internal DB
2.
3.

## Are you willing to submit a PR?
I can't.

**Comment by k0t3n** [comment]
I have same problem. Which postgres version are you using?

**Comment by sajarin** [comment]
Hey @detygon let us know if the above suggestion from k0r3n works for you!

**Comment by 0x006F** [comment]
@detygon / @k0t3n don't think you need to turn off secure tunnel enforcement on the server. 

You may edit `DATABASE_URL` in the `.env` file to force Airbyte to connect through secure tunnel by passing SSL params [as query strings](https://docs.sqlalchemy.org/en/20/core/engines.html#add-parameters-to-the-url-query-string) in it.

**Comment by rowanmoul** [comment]
Add this to your values.yaml:
```
temporal:
  extraEnv:
    - name: SQL_TLS
       value: "true"
     - name: SQL_TLS_ENABLED
       value: "true"
```

You may also have to override the temporal image being used. See #25815

**Comment by rensoostenbach** [comment]
The above fix worked for me, but I'd like to let people know that there is a whitespace before the first `value` which shouldn't be there, causing the YAML syntax to be incorrect. Use the following:
```
temporal:
  extraEnv:
    - name: SQL_TLS
      value: "true"
    - name: SQL_TLS_ENABLED
      value: "true"
```
