### ISSUE TITLE
QA Engine: alpha connectors with `authSpecification` should not be promoted

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#24838]
## Tell us about the problem you're trying to solve
For OAuth to work in Airbyte Cloud a java implementation of the OAuth flow is required.
The few alpha connectors not having this java implementation but declaring spec with OAuth fields should always be excluded from promotion to Cloud.

OAuth specs are characterized by the presence of these fields in their `spec.yaml/json` file:
```
authSpecification:
  auth_type: oauth2.0
  oauth2Specification:
    rootObject:
      - credentials
      - 0
    oauthFlowInitParameters:
      - ["client_id"]
      - ["client_secret"]
    oauthFlowOutputParameters:
      - ["refresh_token"]

```
