### ISSUE TITLE
Node selector not getting added to source-check as well as destination-check pods

### ISSUE THREAD

**Issue by dbanka** [airbytehq/airbyte#24894]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
In current helm charts, when we deploy airbytes. Node selector is getting added to source-read and destination-write pods but they are not getting added to connection check pods. For example, source-jira-check and destination-snowflake-check

## Expected Behavior
Node selector should get added to source-check and destination-check pods as well

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by seanglynn-thrive** [comment]
This configuration does seem to exist in the Airbyte worker kube configuration: https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-workers/src/main/resources/application.yml#L120-L126

We just need to get this added to the chart.

**Comment by seanglynn-thrive** [comment]
@dbanka 
It is possible to get these node selectors to the `check*` pods.
I can confirm the following approach works for us:
```
-- airbyte helm values.yaml
global:
...
  jobs:
  ...
    kube:
    ...
      -- 1. set node annotations/selectors/tolerations here to set JOB_KUBE_* vars.
      nodeSelector:
        workload_type: data

      tolerations:
      - key: workload_type
        operator: Equal
        value: "data"
        effect: NoSchedule

worker:
...
  extraEnv:
      -- 2. Reference JOB_KUBE_* vars in CHECK_JOB_KUBE_* vars
    - name: CHECK_JOB_KUBE_ANNOTATIONS
      value: "$(JOB_KUBE_ANNOTATIONS)"
    - name: CHECK_JOB_KUBE_SELECTORS
      value: "$(JOB_KUBE_NODE_SELECTORS)"
    - name: CHECK_JOB_KUBE_TOLERATIONS
      value: "$(JOB_KUBE_TOLERATIONS)"


```
