### ISSUE TITLE
DefaultErrorHandler should always add the default backoff strategy as a fallback option

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#24932]
## Tell us about the problem you're trying to solve
Some backoff strategies can fail to produce a backoff time. The WaitTimeFromHeaderBackOffStrategy can fail to retrieve a value if the response does not contain the expected header.

This issue can be mitigated by providing a fallback strategy:
```
        - type: DefaultErrorHandler
          backoff_strategies:
            - type: WaitTimeFromHeader
              header: "Retry-After"
            - type: ExponentialBackoffStrategy
```

We want to simplify the interface for the connector builder by limiting the error handler to a single backoff strategy. We should therefore provide a fallback strategy to protect against failure to get a backoff time.

## How
The DefaultErrorHandler already adds an ExponentialBackoffStrategy as a fallback if it does not have any backoff strategy defined.

A reasonable solution would be to always add this default strategy to its list.

This is not a breaking change, and does not require a change to the low-code interface.

## Acceptance criteria
- [ ] The DefaultErrorHandler as a default backoff strategy it can always fall back to if all its strategies fail to return a backoff time
