### ISSUE TITLE
Connector UI builder generates invalid YAML

### ISSUE THREAD

**Issue by svlada** [airbytehq/airbyte#25004]
## Environment
- **Airbyte version**: 0.41.0
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: custom connector using manifest version 0.28.0 (generated using connector builder ui)
- **Step where error happened**: python main.py spec

## Current Behavior
Connector is generated using connector builder UI tool. 
This is the segment of the generated YAML file - when incremental sync option is selected on the UI:

```
incremental_sync:
  type: DatetimeBasedCursor
  cursor_field: lastModifiedDate
  datetime_format: '%Y-%m-%d'
  cursor_granularity: P1D
  end_datetime: '2024-04-01'
  start_datetime: '2023-04-01'
  step: P1D
  start_time_option:
    inject_into: body_json
    type: RequestOption
    field_name: ddd
```

The problem is that _DatetimeBasedCursor_ is not available in cdk 0.28.0. 

Here is the exception thrown when _python main.py spec_ is executed:

```
airbyte-integrations/connectors/source-custom-connector/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/parsers/factory.py", line 198, in _create_subcomponent
    class_name = CLASS_TYPES_REGISTRY[object_type]
KeyError: 'DatetimeBasedCursor
```

## Expected Behavior

Connector UI builder should generate file compatible with the version it generates.

## Logs

```
airbyte-integrations/connectors/source-custom-connector/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/parsers/factory.py", line 198, in _create_subcomponent
    class_name = CLASS_TYPES_REGISTRY[object_type]
KeyError: 'DatetimeBasedCursor
```
