### ISSUE TITLE
Low-code CDK: The page_size field in PageIncrement and OffsetIncrement should be optional

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#25371]
### Component Description

The page_size field is used to tell the source API how many records to include in each page.
However, some APIs do not accept a parameter specifying the number of records to fetch. [The Discourse API is an example of such API](https://docs.discourse.org/#tag/Notifications/operation/markNotificationsAsRead)

We should therefore make the field optional 

## Acceptance criteria
- [ ] page_size is an optional field for the PageIncrement component
- [ ] page_size is an optional field for the OffsetIncrement component
- [ ] An error is thrown if the DefaultPaginator's page_size_option and the pagination strategy does not set a page size
- [ ] The UI is updated to only render the page_size_option fields when page_size is set (page_size_option becomes required if page_size is set) (similar to what we do for the cursor pagination)

### Proposed YAML schema

```yaml
  PageIncrement:
    description: Pagination strategy that returns the number of pages reads so far and returns it as the next page token
    type: object
    required:
      - type
    properties:
      type:
        type: string
        enum: [PageIncrement]
      page_size:
        description: The number of records to request
        type: integer
      start_from_page:
        type: integer
        default: 0
      $parameters:
        type: object
        additionalProperties: true
  OffsetIncrement:
    description: Pagination strategy that returns the number of records reads so far and returns it as the next page token
    type: object
    required:
      - type
    properties:
      type:
        type: string
        enum: [OffsetIncrement]
      page_size:
        description: The number of records to request
        anyOf:
          - type: integer
          - type: string
      $parameters:
        type: object
        additionalProperties: true
```

### Connector API Docs URL

https://docs.discourse.org/

## Alternative considered
- We could re-structure the schema to group the page_size and the page_size_option into a single optional field. 
  - This would better encapsulate the constraint, but would require a breaking change to the schema at the DefaultPaginator level

```
    description: Default pagination implementation to request pages of results with a fixed size until the pagination strategy no longer returns a next_page_token
    type: object
    required:
      - type
      - pagination_strategy
    properties:
      type:
        type: string
        enum: [DefaultPaginator]
      pagination_strategy:
        anyOf:
          - "$ref": "#/definitions/CursorPagination"
          - "$ref": "#/definitions/CustomPaginationStrategy"
          - "$ref": "#/definitions/OffsetIncrement"
          - "$ref": "#/definitions/PageIncrement"
      decoder:
        "$ref": "#/definitions/JsonDecoder"
      page_size:
        type: object
        required:
          - request_option
          - value
        properties:
          request_option:
            "$ref": "#/definitions/RequestOption"
          value:
            type: integer
      page_token_option:
        anyOf:
          - "$ref": "#/definitions/RequestOption"
          - "$ref": "#/definitions/RequestPath"
      $parameters:
        type: object
        additionalProperties: true
```
