### ISSUE TITLE
Low-code CDK: make refresh token optional

### ISSUE THREAD

**Issue by belgiandieter** [airbytehq/airbyte#25400]
### Component Description

I was configuring an Oauth authentication and I had trouble working around the refresh token. The ui requires me to insert a refresh token  while this was not necessary for the authentication I was implementing. I had to manually remove the token input field in the yml file to get it to work. Whenever I switched back to the ui to make some changes, I had to remove it in the yml file to get it to work again.

Lately, I do not have to edit the yml file anymore, but nonetheless, it is confusing that you are required to give this token, without it being used.

<img width="850" alt="image" src="https://user-images.githubusercontent.com/98825141/233643577-3a84601b-ed5c-4c1b-aa61-4e493ce1671e.png">

This is my first issue submitted ever!

### Proposed YAML schema

```
authenticator:
  type: "OAuthAuthenticator"
  token_refresh_endpoint: "https://api.searchmetrics.com/v4/token"
  client_id: "{{ config['api_key'] }}"
  client_secret: "{{ config['client_secret'] }}"
  refresh_token: "" # <-- the ui should allow you to keep this empty
```
