### ISSUE TITLE
Connector builder inserts empty strings in request headers

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#25403]
## Tell us about the problem you're trying to solve
The connector builder can the request headers to an empty string. I haven't looked into the conditions that lead to this situation.

[This slack thread has more details](https://airbytehq-team.slack.com/archives/C027KKE4BCZ/p1682067792471529)

Dieter shared the manifest that was created, and it shows that the request header's key and value are empty strings:
```
    retriever:
      type: SimpleRetriever
      requester:
        type: HttpRequester
        url_base: app.getcensus.com/api/v1
        path: >-
          https://app.getcensus.com/api/v1/syncs/{{
          stream_slice.sync_id}}/sync_runs
        http_method: GET
        request_parameters: {}
        request_headers:
          '': ''
        request_body_json: {}
```
