### ISSUE TITLE
metadata: validation of allowedHost values

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#25613]
I believe the metadata validation function should check if the values filled for `allowedHost` are valid and that no wildcard is used without a specific comment. E.G:

```yaml
data:
  allowedHosts:
    hosts:
      - "*" #  A valid reason why the connector can reach any host
```
