### ISSUE TITLE
Connector Builder: allow streams with interpolation in the path

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#25623]
## Tell us about the problem you're trying to solve
Right now, a manifest like
```
version: 0.35.1
type: DeclarativeSource
check:
  type: CheckStream
  stream_names:
    - archive
streams:
  - type: DeclarativeStream
    name: archive
    primary_key:
      - _id
    schema_loader:
      type: InlineSchemaLoader
      schema: {}
    retriever:
      type: SimpleRetriever
      requester:
        type: HttpRequester
        url_base: https://api.nytimes.com/svc
        path: >-
          /archive/v1/{{ stream_slice['start_time'].split('-')[0] | int }}/{{
          stream_slice['start_time'].split('-')[1] | int }}.json
        http_method: GET
        request_parameters:
          api-key: '{{ config[''api_key''] }}'
        request_headers: {}
        request_body_json: {}
        authenticator:
          type: NoAuth
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_path:
            - response
            - docs
      paginator:
        type: NoPagination
    incremental_sync:
      type: DatetimeBasedCursor
      name: archive
      path: >-
        /archive/v1/{{ stream_slice['start_time'].split('-')[0] | int }}/{{
        stream_slice['start_time'].split('-')[1] | int }}.json
      step: P1M
      primary_key: _id
      cursor_field: pub_date
      datetime_format: '%Y-%m-%dT%H:%M:%S%z'
      cursor_granularity: PT1S
      start_datetime:
        type: MinMaxDatetime
        datetime: '{{ config[''start_date''] }}'
        datetime_format: '%Y-%m'
      end_datetime:
        type: MinMaxDatetime
        datetime: '{{ config[''end_date''] or today_utc().strftime(''%Y-%m'') }}'
        datetime_format: '%Y-%m'
spec:
  connection_specification:
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    required:
      - start_date
    properties:
      start_date:
        type: string
        title: start_date
    additionalProperties: true
  documentation_url: https://example.org
  type: Spec
```
... will create the error 
<img width="530" alt="image" src="https://user-images.githubusercontent.com/3360483/234907393-17ca4e9e-2957-4fb9-ab08-31d4e85b3804.png">
... with stack trace:
```
Traceback (most recent call last):
  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/connector_builder_handler.py\", line 90, in list_streams
    streams = [
  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/connector_builder_handler.py\", line 91, in <listcomp>
    {\"name\": http_stream.name, \"url\": urljoin(http_stream.url_base, http_stream.path())}
  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py\", line 294, in path
    return self.requester.get_path(stream_state=self.state, stream_slice=stream_slice, next_page_token=next_page_token)
  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py\", line 81, in get_path
    path = self.path.eval(self.config, **kwargs)
  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/interpolation/interpolated_string.py\", line 40, in eval
    return self._interpolation.eval(self.string, config, self.default, parameters=self._parameters, **kwargs)
  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/interpolation/jinja.py\", line 52, in eval
    return self._literal_eval(self._eval(default, context))
  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/interpolation/jinja.py\", line 62, in _eval
    return self._environment.from_string(s).render(context)
  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/jinja2/environment.py\", line 1301, in render
    self.environment.handle_exception()
  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/jinja2/environment.py\", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File \"<template>\", line 1, in top-level template code
  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/jinja2/environment.py\", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'start_time'
```

The reason is that when listing the streams, we don't pass the different optional parameters [here](https://github.com/airbytehq/airbyte/blob/77068bcec638271d8a7a21b9446d14ef6a76a01f/airbyte-cdk/python/airbyte_cdk/connector_builder/connector_builder_handler.py#L93). Since `stream_slice` is not provided but is needed to interpolate the path, we have an error. 

Note: `stream_slice` and `stream_state` could cause the issue. To generate the `stream_slice`, we can probably use an empty state. However, what if the users uses interpolation with `stream_state`?
