### ISSUE TITLE
Connector builder: Derive date format from test data

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#25670]
It's hard but very important to configure the date format correctly for incremental syncs. If the user did a test read before and provided the cursor field, there should be logic in place to derive the format from the test data to decrease the chance of wrong configurations. It should still be possible to manually enter the format

Depends on: https://github.com/airbytehq/airbyte/issues/26903

## Java server

The Java server is sending the inferred datetime formats along with the rest of the payload to the UI. The openapi spec needs to be extended for this:

```
StreamRead:
      type: object
      required:
        - logs
        - slices
        - test_read_limit_reached
      properties:
        # ... as before
        inferred_datetime_formats:
          type: object
          additionalProperties:
            type: string
```

When calling the CDK, `inferred_datetime_formats` will be set on the response so it can be forwarded like the inferred schema.

## UI changes

The UI implements the UI described above:
* The cursor field input sets suggestions based on the field names of all recognized date fields
* The date format input renders the CTA to fill in the format if the cursor field input is set to one of the recognized date fields and its value is not equal to the inferred format for that date field
* When the CTA is clicked, the format from the server response is set in the form state

To help with custom cases, instead of the CTA below the input we should have a prominent link to documentation that’s explaining the placeholders and how to combine them (something like “Check our documentation about possible options”)

Not exact design, can be refined as part of implementation
<img width="459" alt="Screenshot 2023-06-01 at 13 04 49" src="https://github.com/airbytehq/airbyte/assets/1508364/8b5ab985-e19d-4df4-aca5-11530791c956">

To ask Nico:
* How should it look like exactly?
* Should we just fill it in if a user selects a cursor field we know the format for?
