### ISSUE TITLE
Low-code CDK: Support JWT bearer token oauth flow

### ISSUE THREAD

**Issue by belgiandieter** [airbytehq/airbyte#25728]
### Component Description

I was trying to pull meta-data from google cloud and found that the authentication method is not supported by the user interface of airbyte. For one, it does not use a refresh token. This is required in the airbyte low code ui.

~~https://developers.google.com/identity/protocols/oauth2/service-account~~
https://developers.google.com/identity/protocols/oauth2/service-account#authorizingrequests (to be more specific)

It is similar to the issue: https://github.com/airbytehq/airbyte/issues/23450

### Proposed Solution
See the [proposal doc](https://docs.google.com/document/d/1x6ZZd8UERf_qgWexk9eh_Y7pLFLZ0cZbKEPmC8PgrrQ/edit#heading=h.4d6p5yv0yytg) for the full proposal. 

Proposed schema of new JWT Authenticator component:
```
JwtAuthenticator:
    type: object
    required:
      - type
      - key
      - payload
      - algorithm
      - expiration_time
      - inject_into
    properties:
      type:
        type: string
        enum: [JwtAuthenticator]
      key:
        type: string
        description: The interpolated key used for signing (will come from the configuration in almost all cases)
      payload:
        type: object
        description: Recursively interpolated object for the payload of the JWT
      headers:
        type: object
        additionalProperties:
          type: string
        description: Single-level interpolated object for JWT header fields. If not provided, is set to {"typ": "JWT"}
      algorithm:
         type: string
         enum: [HS256, HS384, HS512, ES256, ES256K, ES384, ES512, RS256, RS384, RS512, PS256, PS384, PS512, EdDSA]
        description: The algorithm used for signing
      expiration_time:
        type: string
        description: ISO duration how long the JWT should be valid
      request_authentication:
   oneOf:
     - type:
       enum: [ApiKey]
       inject_into:
         ref: #/definitions/RequestOption
     - type:
       enum: [Bearer]
```

## Acceptance criteria

* JwtAuthenticator is implemented as specified in the proposal
* Authentication works for app store connect
