### ISSUE TITLE
pg_hba error in airbyte-temporal when trying to connect to an external database

### ISSUE THREAD

**Issue by alanszp** [airbytehq/airbyte#26089]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.44.4

### What step the error happened?

On deploy

### Revelant information

I just deployed everything on AWS EC2 but I’m having problems with the docker container airbyte-temporal .
It’s not pointing to the right `DATABASE_HOST`.

I customized the DB:

```
### DATABASE ###
# Airbyte Internal Job Database, see https://docs.airbyte.io/operator-guides/configuring-airbyte-db
DATABASE_USER=airbyte_rw
DATABASE_PASSWORD=*****
DATABASE_HOST=prd-datawarehouse.int.main.url
DATABASE_PORT=5432
DATABASE_DB=airbyte
# translate manually DATABASE_URL=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB} (do not include the username or password here)
DATABASE_URL=jdbc:postgresql://prd-datawarehouse.int.main.url:5432/airbyte
JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=0.40.26.001
```

An the `docker-compose.yml` is like this
```
airbyte-temporal:
    image: airbyte/temporal:${VERSION}
    logging: *default-logging
    container_name: airbyte-temporal
    restart: unless-stopped
    environment:
      - DB=postgresql
      - DB_PORT=${DATABASE_PORT}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - LOG_LEVEL=${LOG_LEVEL}
      - POSTGRES_PWD=${DATABASE_PASSWORD}
      - POSTGRES_SEEDS=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - airbyte_internal
```

### Relevant log output

```shell
but the temporal server keeps restarting with the logs:


2023-05-15T04:41:18.615Z	ERROR	Unable to create SQL database.	{"error": "unable to connect to DB, tried default DB names: postgres,defaultdb, errors: [pq: no pg_hba.conf entry for host \"10.0.101.173\", user \"airbyte_rw\", database \"postgres\", no encryption pq: no pg_hba.conf entry for host \"10.0.101.173\", user \"airbyte_rw\", database \"defaultdb\", no encryption]", "logging-call-at": "handler.go:97"}
``` 

*Important! host `“10.0.101.173”` ---> THIS IS THE LOCAL IP NOT `prd-datawarehouse.int.main.url`. Is the IP of the host running docker!*
```

**Comment by marcosmarxm** [comment]
@alanszp did you change anything in the default `docker-compose.yaml` file?

**Comment by alanszp** [comment]
@marcosmarxm  No. First I removed the DB container with the db storage, but then I tried again without removing anything and the same happened.

**Comment by alanszp** [comment]
All the other containers run perfectly!

**Comment by sh4sh** [comment]
Hey @alanszp, sorry if I asked this before but does the external db need encryption? If so, please take a look at [this comment](https://github.com/airbytehq/airbyte/issues/9342#issuecomment-1346262970). It looks like there is a limitation in `temporalio/auto-setup` but there is a workaround mentioned, let us know if you try it.

**Comment by alanszp** [comment]
@sh4sh  It does not need encryption, but I will try. Its a RDS isntance if you want to try.

**Comment by alanszp** [comment]
@marcosmarxm @sh4sh any news around this topic?
It's not working and it's making really unstable my installation :S

**Comment by armetiz** [comment]
Hi there.

Same problem here with an airbyte deployed on AWS EC2 using Docker.
I want to store Airbyte configuration to a RDS Postgres Instance.

I try the following :
1. `docker-compose.yaml` Add [TEMPORAL_TLS_REQUIRE_CLIENT_AUTH](https://github.com/airbytehq/airbyte/issues/9342#issuecomment-1049043037) to container `airbyte-temporal`
2. Try .env `DATABASE_URL` DSN with / without `?ssl=true&sslmode=require`

Every time : `Unable to create SQL database`.

```
{"error": "unable to connect to DB, tried default DB names: postgres,defaultdb, errors: [pq: no pg_hba.conf entry for host \"XXX.YYY\", user \"master\", database \"postgres\", no encryption pq: no pg_hba.conf entry for host \"XXX.YYY\", user \"master\", database \"defaultdb\", no encryption]", "logging-call-at": "handler.go:97"}
```


@alanszp do you have any other information ?

**Comment by smarthg** [comment]
@alanszp @armetiz Have run into the exact same issue deploying Airbyte using Terraform.

I also tried setting `TEMPORAL_TLS_REQUIRE_CLIENT_AUTH=true` and db url with / without ?ssl=true&sslmode=require.

Do share if someone figures it out!

**Comment by QuentinLuc** [comment]
Same problem for me.  And I already posted my tests here: https://github.com/airbytehq/airbyte/issues/11157#issuecomment-1632250435

**Comment by lschinasi** [comment]
Hi, I am having the same issue here, too.  I am running an EC2 instance in a private subnet behind a AWS client VPN.  I have an RDS postgres instance connected.  

I am certain that the connection from the ec2 instance to postgres works for 2 reasons: 1.  that the initialization script did provision the airbyte db tables in postgres and 2. that I have not problem reaching postgres from the ec2 instance.  The only problem is the airbyte-temporal container, which just continues to restart as instructed in the docker-compose.

I try to set this up without the private subnet and vpn - just using defaults and open network - and it worked, but of course I would not want to actually run anything in this environment.

Here are the logs from the failing airbyte-temporal container:

```
[ec2-user airbyte]$ docker logs -f --tail 10 airbyte-temporal
[Fx] ERROR		Failed to initialize custom logger: could not build arguments for function "go.uber.org/fx".(*App).constructCustomLogger.func2
	/go/pkg/mod/go.uber.org/fx@v1.18.2/app.go:414:
failed to build fxevent.Logger:
could not build arguments for function "go.temporal.io/server/temporal".glob..func8
	/home/builder/temporal/temporal/fx.go:1025:
failed to build log.Logger:
received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider
	/home/builder/temporal/temporal/fx.go:159:
sql schema version compatibility check failed: pq: no pg_hba.conf entry for host "172.32.131.33", user "devuser", database "temporal", no encryption
Unable to create server. Error: could not build arguments for function "go.uber.org/fx".(*App).constructCustomLogger.func2 (/go/pkg/mod/go.uber.org/fx@v1.18.2/app.go:414): failed to build fxevent.Logger: could not build arguments for function "go.temporal.io/server/temporal".glob..func8 (/home/builder/temporal/temporal/fx.go:1025): failed to build log.Logger: received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider (/home/builder/temporal/temporal/fx.go:159): sql schema version compatibility check failed: pq: no pg_hba.conf entry for host "172.32.131.33", user "devuser", database "temporal", no encryption.
```

**Comment by lschinasi** [comment]
@QuentinLuc @armetiz @alanszp and @smarthg I got this to work. I had to update the environment variables in the docker-compose.yaml for the airbyte-temporal service.

I added the following 4 rows to the environment variables:

```
      - SQL_TLS=true
      - SQL_TLS_DISABLE_HOST_VERIFICATION=true
      - SQL_TLS_ENABLED=true
      - SQL_HOST_VERIFICATION=false
```
      
here is what the airbyte-temporal service portion of the docker-compose.yaml now looks like:

```
  airbyte-temporal:
    image: airbyte/temporal:${VERSION}
    logging: *default-logging
    container_name: airbyte-temporal
    restart: unless-stopped
    environment:
      - DB=postgresql
      - DB_PORT=${DATABASE_PORT}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - LOG_LEVEL=${LOG_LEVEL}
      - POSTGRES_PWD=${DATABASE_PASSWORD}
      - POSTGRES_SEEDS=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - SQL_TLS=true
      - SQL_TLS_DISABLE_HOST_VERIFICATION=true
      - SQL_TLS_ENABLED=true
      - SQL_HOST_VERIFICATION=false
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - airbyte_internal
```
let me know if this works for you!
