### ISSUE TITLE
SingleUseRefreshToken in Connector Builder

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#26342]
### Component Description

Generalizing means that we want to simplify the configuration for the user and have only one interface/YAML component to support that. However, the Python CDK implementation can stay the same.

### Proposed YAML schema

```yaml
  OAuthAuthenticator:
    required:
      <...>
    properties:
      refresh_token_updater:
        properties:
          refresh_token_config_path:
            title: Config Path To refresh_token
            description: Describe where in the config the refresh token is. To be defined when the refresh token is single use. This is necessary to update the refresh token after it's been used
            type: array
            items:
              type: string
            examples:
              - ["credentials", "refresh_token"]
          access_token_config_path:
            type: array
            items:
              type: string
          token_expiry_date_config_path:
            type: array
            items:
              type: string
```
Given that `refresh_token_updater` is defined as part of OAuthAuthenticator, we will instantiate `SingleUseRefreshTokenOauth2Authenticator`.

To make it work consistently with the connector builder, two other things need to be changed:
* Expiry date format has to be supported like on regular OAuth authenticator
* Authenticator shouldn't fail if config values are missing - if no access token / expiry date is set, it's just getting a new access token via the refresh token

## Acceptance criteria
- [ ] Create single YAML interface and wire up the Python component properly
- [ ] In frontend, add switch to oauth authenticator UI and convert accordingly
- [ ] Update documentation
- [ ] Update source-quickbooks and use its example in the documentation
- [ ] Ensure that there there are no SingleUseRefreshTokenOAuthAuthenticator in the DB `select count(*) from actor_definition_config_injection where json_to_inject::text like '%SingleUseRefreshTokenOAuthAuthenticator%';`

Out-of-scope: 
- [ ] refresh token update mechanism in the frontend (see https://github.com/airbytehq/airbyte/issues/26909)
