### ISSUE TITLE
Descending-order incremental sync module

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#26343]
### Component Description

There are APIs which do not allowed to filter by time and only return data ordered by date descending (a "feed" of data).

Examples:
* Discourse: https://docs.discourse.org/#tag/Posts/operation/listPosts
* Reddit: https://www.reddit.com/dev/api/#GET_new

The current incremental sync component doesn't cover this use case.

Idea for how to represent this:
* Do not specify end date
* Introduce a "stop condition" which is evaluated for each record - if the timestamp of a record is older than the state of the start_datetime for the stream, processing stops (because we reached the newest post from the last sync)

### Proposed YAML schema

```yaml
incremental_sync:
  type: "DatetimeBasedCursor"
  start_datetime:
    datetime: "{{ config['start_date'] }}"
    datetime_format: "%Y-%m"
  datetime_format: "%Y-%m-%dT%H:%M:%S%z"
  cursor_field: "pub_date"
  is_data_feed: true
```

Given `is_data_feed` is true, we will wrap the pagination strategy with `StopConditionPaginationStrategyDecorator` which is also implementing `PaginationStrategy`.  This class will return `None` to `next_page_token` if the condition is met.
