### ISSUE TITLE
Generalized session token authenticator

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#26341]
### Component Description

The existing session token authenticator has a lot of limitations. It should be made more generic to allow different ways of passing credentials to the authentication endpoint, different ways of extracting sessions tokens from the response and different ways of injecting the session token into outgoing requests.

### Proposed YAML schema

```yaml
  GenericSessionTokenAuthenticator:
    type: object
    required:
      - type
      - login_url
      - session_token
      - inject_into
    properties:
      type:
        type: string
        enum: [GenericSessionTokenAuthenticator]
      login_requester:
        "$ref": "#/definitions/HttpRequester"
      session_token_path:
          type: array
          items: string
      expiry_time:
          type: string
     request_authentication:
       oneOf:
          - type:
             enum: [ApiKey]
             inject_into:
                ref: #/definitions/RequestOption
          - type:
             enum: [Bearer]
```

### Behavior

* Configure a regular requester for the login request as it allows to reuse the logic in place (error handling / authentication mechanisms)
* Allow session token extraction from the response via path
* Static expiry times (ISO duration)
* data_request_authentication is specifying the authentication scheme for the actual data requests
   * SessionTokenAuthenticator uses the existing apikey and bearer authenticator classes internally to implement the logic
   * It’s not using the existing component in the yaml directly because the token is controlled by the session token authenticator instead of passed in from the config

The authenticator instance holds a reference to the resolved token. If there is none, execute the login request as defined in the configuration. If it returns an OK status code, it will execute the session token interpolated string. If it fails, it raises. If it returns something, it will assume it’s authenticated and execute the defined request_authentication on data requests.

The expiry time defines how long it will use the cached token before attempting to re-authenticate.

### Implementation notes

* Implement http request invocation in the http_requester class so it’s reusable for async sources and others later on
  * For data requests, the SimpleRetriever (and its base class HttpStream) implements actually executing the request
  * As this is hard to re-use in different situations, the http requester class should implement all of this logic in one place and make it accessible via a method call (right now the retriever class only supplies arguments to the request and doesn't execute it)
  * In a later step, the SimpleRetriever can be switched to use this central logic as well
* The existing session token authenticator is marked as deprecated, but not removed yet
* The additional request triggered by the session token authenticator should also emit a log message that is consumed by the builder to make it possible to inspect the request that's made
