### ISSUE TITLE
DatetimeBasedCursor should support incremental syncs without steps

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#26570]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
Today when configuring an incremental sync, the concept of step and granularity is very confusing for a couple of reasons:
* It is implementation details and the user doesn't really understand why
* The possible values are complicated

It is possible to create a sync that is incremental without providing those. Therefore, those values should be optional.

## Describe the solution you’d like
~Bundle `step` and `granularity` together~ and make them optional. This means that this YAML component is valid:

```
    incremental_sync:
      type: "DatetimeBasedCursor"
      start_datetime:
        datetime: "{{ config['start_date'] }}"
        datetime_format: "%Y-%m"
      datetime_format: "%Y-%m-%dT%H:%M:%S%z"
      cursor_field: "pub_date"
```
which would lead to only one slice.

However, we can define it like this:
```
    incremental_sync:
      type: "DatetimeBasedCursor"
      start_datetime:
        datetime: "{{ config['start_date'] }}"
        datetime_format: "%Y-%m"
      step: "P1M"
      cursor_granularity: "PT1S"
      datetime_format: "%Y-%m-%dT%H:%M:%S%z"
      cursor_field: "pub_date"
```
... which will create multiple slices. We can set the step to`timedelta.max` within the DatetimeBasedCursor or something when the step is not provided. It should stop iterating at end_datetime so it should be fine.

### Acceptance Criteria
- [ ] Implement the proposed solution in the CDK
     - [ ] Throw and error when only one between `step` and `cursor_granularity` is defined
- [ ] Deprecated `step` and `cursor_granularity` 
- [ ] Update Connector Builder to reflect that. Right now, step is marked as “advanced” but not the cursor granularity and therefore those concepts are far away even though they are linked. It should be clear that both go together. We should as well set them both behind a checkbox under “Advanced”
- [ ] Update the documentation (`docs` folder and `declarative_component_schema.yaml`)
