### ISSUE TITLE
Low code CDK: Incremental sync with different format incoming/outgoing

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#27153]
### What area the feature impact?

None

### Revelant Information

In most APIs, dates are formatted the same way in request parameters and records in the responses. This works will with how incremental syncs are configured that just allow a single datetime format used in both directions.

However, sometimes APIs require a different format which can't be expressed using the low-code CDK right now.

For these use cases, it should be possible to define a second optional format:
```
    incremental_sync:
      cursor_field: "startDate"
      datetime_format: "%Y-%m-%d"
      cursor_granularity: "P1D"
      cursor_datetime_format: "%s"
```
