### ISSUE TITLE
Connector Builder Error: Invalid connector manifest 

### ISSUE THREAD

**Issue by saffronjane** [airbytehq/airbyte#27934]
### What step the error happened?

Testing my new connector

### Revelant information

Hello!

I am utilizing the Connector Builder GUI and am running into the below error when trying to test my connection:

```
Could not verify streams:

"Invalid connector manifest with error: Validation against json schema defined in declarative_component_schema.yaml schema failed"

In order to test a stream, ensure that the YAML is structured as described in the docs. 
```

The manifest produced by the GUI is pasted below. I also have the developer tools logs pasted below:
Manifest
```
spec:
  type: Spec
  documentation_url: https://example.org
  connection_specification:
    type: object
    $schema: http://json-schema.org/draft-07/schema#
    required:
      - api_key
    properties:
      api_key:
        type: string
        order: 0
        title: API Key
        airbyte_secret: true
    additionalProperties: true
type: DeclarativeSource
check:
  type: CheckStream
  stream_names:
    - campaigns
streams:
  - name: campaigns
    type: DeclarativeStream
    retriever:
      type: SimpleRetriever
      paginator:
        type: NoPagination
      requester:
        path: /campaigns
        type: HttpRequester
        url_base: https://api.stackadapt.com/service/v2
        http_method: GET
        authenticator:
          type: ApiKeyAuthenticator
          api_token: '{{ config[''api_key''] }}'
          inject_into:
            type: RequestOption
            field_name: X-Authorization
            inject_into: header
        request_headers: {}
        request_body_json: {}
        request_parameters: {}
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_path: []
    primary_key: []
    schema_loader:
      type: InlineSchemaLoader
      schema:
        type: object
        $schema: http://json-schema.org/draft-07/schema#
        properties: {}
        additionalProperties: true
version: 0.43.0
metadata:
  autoImportSchema:
    campaigns: true
```

### Relevant log output

```shell
POST http://localhost:8999/connector-builder-api/v1/streams/list 400 (Bad Request)
Gc @ ConnectorBuilderTestInputService-b08e6e0c.js:826
kie @ ConnectorBuilderTestInputService-b08e6e0c.js:826
ku @ useManifestToBuilderForm-7dac662a.js:32
listStreams @ useManifestToBuilderForm-7dac662a.js:32
Ft.keepPreviousData @ useManifestToBuilderForm-7dac662a.js:32
c @ ConnectorBuilderTestInputService-b08e6e0c.js:36
p @ ConnectorBuilderTestInputService-b08e6e0c.js:36
wv @ ConnectorBuilderTestInputService-b08e6e0c.js:36
fetch @ ConnectorBuilderTestInputService-b08e6e0c.js:36
executeFetch @ ConnectorBuilderTestInputService-b08e6e0c.js:36
setOptions @ ConnectorBuilderTestInputService-b08e6e0c.js:36
(anonymous) @ ConnectorBuilderTestInputService-b08e6e0c.js:44
Ay @ index-767a5ec0.js:41
e.unstable_runWithPriority @ index-767a5ec0.js:26
Hn @ index-767a5ec0.js:37
bn @ index-767a5ec0.js:41
$s @ index-767a5ec0.js:39
(anonymous) @ index-767a5ec0.js:37
e.unstable_runWithPriority @ index-767a5ec0.js:26
Hn @ index-767a5ec0.js:37
tv @ index-767a5ec0.js:37
Lt @ index-767a5ec0.js:37
hn @ index-767a5ec0.js:39
jl @ index-767a5ec0.js:37
(anonymous) @ index-6b1006d4.js:1
(anonymous) @ index-6b1006d4.js:87
g @ debounce-2d92fecf.js:1
E @ debounce-2d92fecf.js:1
s @ debounce-2d92fecf.js:1
setTimeout (async)
s @ debounce-2d92fecf.js:1
setTimeout (async)
s @ debounce-2d92fecf.js:1
setTimeout (async)
W @ debounce-2d92fecf.js:1
T @ debounce-2d92fecf.js:1
(anonymous) @ index-6b1006d4.js:87
Ay @ index-767a5ec0.js:41
e.unstable_runWithPriority @ index-767a5ec0.js:26
Hn @ index-767a5ec0.js:37
bn @ index-767a5ec0.js:41
Sl @ index-767a5ec0.js:41
El @ index-767a5ec0.js:37
n0 @ index-767a5ec0.js:37
Wp @ index-767a5ec0.js:37
bl @ index-767a5ec0.js:37
xl @ index-767a5ec0.js:37
e.unstable_runWithPriority @ index-767a5ec0.js:26
Hn @ index-767a5ec0.js:37
_p @ index-767a5ec0.js:41
w0 @ index-767a5ec0.js:37
```

### Contribute

- [ ] Yes, I want to contribute
