### ISSUE TITLE
Support nested partition fields for SubstreamPartitionRouter

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#27972]
### What area the feature impact?

Connectors

### Revelant Information

As of today, SubstreamPartitionRouter does not support nested partition fields. This means that if a user wants to use a field for partitioning and this field is nested, it will have to perform a transformation to put it on the root level. This is hacky and counterintuitive so we would like to support nested fields. 

We currently use DPath to extract the value. We know DPath can support nested fields since DpathExtractor already supports it. It's only a matter of allowing SubstreamPartitionRouter to do this as well.

YAML will look like
```
      partition_router:
        type: "SubstreamPartitionRouter"
        parent_stream_configs:
          - stream: "#/definitions/products_stream"
            parent_key: "id"
            partition_field:
              - "root"
              - "data"
```

### Acceptance Criteria
- [ ] YAML interface is updated to allow a list of InterpolatedString or string 
- [ ] CDK support the same behaviour as before + the list of InterpolatedString or string 
- [ ] Connector Builder UI is updated
- [ ] Documentation is updated
