### ISSUE TITLE
Possibility to use a custom port for the airbyte proxy set outside the docker-compose

### ISSUE THREAD

**Issue by moreaupascal56** [airbytehq/airbyte#28010]
### What area the feature impact?

Airbyte Platform

### Revelant Information

Hello :) 

I am deploying docker Airbyte using the [run-ab-platform.sh](https://github.com/airbytehq/airbyte/blob/master/run-ab-platform.sh) script. 
I had already something using the 8000 port on my server so I tried to change the exposed port of airbyte. I tried changing the WEBAPP_URL and all the related env variables but unsuccessfully. The only way to do it that I found is to change the port in the `airbyte-proxy` part of the `docker-compose.yaml`:

```
  airbyte-proxy:
    image: airbyte/proxy:${VERSION}
    container_name: airbyte-proxy
    restart: unless-stopped
    ports:
      - "8000:8000"---> Change this to YOUR_PORT:8000
      - "8001:8001"
      - "8003:8003"
    environment:
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - BASIC_AUTH_PROXY_TIMEOUT=${BASIC_AUTH_PROXY_TIMEOUT}
    networks:
      - airbyte_internal
      - airbyte_public
    depends_on:
      - webapp
      - server
```

but that is not ideal and should be done with the env variables. 

Am I missing something ? 

Thanks a lot and have a great day!
