### ISSUE TITLE
Substream cursor

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#28278]
### What area the feature impact?

Connectors

### Revelant Information

As requested in Slack: For example, the first time I get 3 ids from the API /v1/deals, I pass it to the API /v1/deals/{id}/flow, the second time I run the API /v1/deals, I get 2 new ids, then I pass it to the API /v1 /deals/{id}/flow. How to do this?

As of 2023-07-13, there are no ways to do this because it's a whole new way of managing the state (it's not incremental as "the ids are incremental" but it's incremental as "we have never fetched the information for those ids).

Proposed solution
Have a new component (name to be reworked) to allow the cursor to manage a substream like this:
```
incremental_sync:
  type: SubstreamAlreadyFetchedCursor
  parent_stream: "#/definitions/parent_stream"
  parent_key: id
```
