### ISSUE TITLE
Registry Entry Generation Fails when all registries not defined

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#28301]
## Problem

There's an issue regarding how metadata files are transformed into registry entries. Specifically, if a metadata file does not contain a registry entry for all registries, but instead only has one or none, this leads to errors.

For instance, consider a metadata file which contains entries for two registries (`cloud` and `oss`):
```
data:
  allowedHosts:
    hosts:
      - api.aptrinsic.com/v1
  registries:
    cloud:
      enabled: false
    oss:
      enabled: true
  connectorSubtype: api
  connectorType: source
  definitionId: 0da3b186-8879-4e94-8738-55b48762f1e8
  dockerImageTag: 0.1.0
  dockerRepository: airbyte/source-gainsight-px
  githubIssueLabel: source-gainsight-px
  icon: gainsight-px.svg
  license: MIT
  name: Gainsight Px
  releaseStage: alpha
  documentationUrl: https://docs.airbyte.com/integrations/sources/gainsight-px
  tags:
    - language:low-code
    - language:python
metadataSpecVersion: "1.0"
```
And compare it with this metadata file which only contains a registry entry for `oss`:
```
data:
  allowedHosts:
    hosts:
      - api.aptrinsic.com/v1
  registries:
    oss:
      enabled: true
  connectorSubtype: api
  connectorType: source
  definitionId: 0da3b186-8879-4e94-8738-55b48762f1e8
  dockerImageTag: 0.1.0
  dockerRepository: airbyte/source-gainsight-px
  githubIssueLabel: source-gainsight-px
  icon: gainsight-px.svg
  license: MIT
  name: Gainsight Px
  releaseStage: alpha
  documentationUrl: https://docs.airbyte.com/integrations/sources/gainsight-px
  tags:
    - language:low-code
    - language:python
metadataSpecVersion: "1.0"
```
This was the first instance of this error occurring, as discussed in this [Slack message](https://airbytehq-team.slack.com/archives/C056HGD1QSW/p1689276695949789).

The root of this issue likely lies in the transformation process of the metadata file into a Pydantic model, where any missing registries are marked as `None`.
