### ISSUE TITLE
Low code CDK: Conditional authenticator

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#28351]
### What area the feature impact?

None

### Revelant Information

It's a common scenario to allow the user of a connector to choose from multiple possible authentication methods. Currently this is not reflected in the low code CDK.

By introducing a new component `ConditionalAuthenticator`, this can be made a properly supported feature:
```
type: ConditionalAuthenticator
authenticators:
  - condition: "{{ config.auth.type is "username_password" }}"
    authenticator:
      # ... 
  - condition: "{{ config.auth.type is "token" }}"
    authenticator:
      type: ApiKeyAuthenticator
      header: "X-Metabase-Session"
      api_token: "{{ config.auth.session_token }}"
```

Once this is supported, the existing `LegacySessionTokenAuthenticator` can be removed as it will be possible to re-create it using the conditional authenticator.
