### ISSUE TITLE
Buliding a source and facing issue at the stop condition

### ISSUE THREAD

**Issue by saikumar1182** [airbytehq/airbyte#28659]
### Topic

At Stop condition in pagination

### Revelant information

Hello,
I was trying to implement the api stream using the cursor pagination and giving the cursor value based on the cursor value start data end end date.
My yaml pagination part is
```
paginator:
        type: DefaultPaginator
        page_token_option:
          type: RequestOption
          inject_into: request_parameter
          field_name: searchAfter
        pagination_strategy:
          type: CursorPagination
          cursor_value: '{{ last_records[-1][''siren''] }}'
          stop_condition: '{{ ''record.siren'' not in response.body.siren | length == 0 }}'
    transformations:
      - type: AddFields
        fields:
          - path:
              - siren
            value: '{{ record[''company''][''formality''][''siren''] }}'
    incremental_sync:
      type: DatetimeBasedCursor
      cursor_field: company.updatedAt
      datetime_format: '%Y-%m-%d'
      start_time_option:
        type: RequestOption
        field_name: from
        inject_into: request_parameter
      end_time_option:
        type: RequestOption
        field_name: to
        inject_into: request_parameter
      start_datetime:
        type: MinMaxDatetime
        datetime: '{{ config[''start_date''] }}'
        datetime_format: '%Y-%m-%dT%H:%M:%SZ'
      end_datetime:
        type: MinMaxDatetime
        datetime: '{{ config[''end_date''] }}'
        datetime_format: '%Y-%m-%dT%H:%M:%SZ'
```
I would like to have a stop condition when it reaches the searchAfter cursor to the end  of the siren value where no date is available.
Can someone help me defining the stop condition please.
Also i am receiving and infinite loop like 

```
2023-07-25 10:12:51 source > Backing off _send(...) for 0.0s (airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException: Request URL: https://registre-national-entreprises.inpi.fr/api/companies/diff?searchAfter=977955038&from=2023-07-01&to=2023-07-24, Response Code: 500, Response Text: {"code":"500","message":"Key not found: 4","type":"serverError"})
airbyte-worker          | 2023-07-25 10:12:51 source > Retrying. Sleeping for 10 seconds
```
