### ISSUE TITLE
helm chart 0.47.13 has hardcoded DB port (impossible to use DB not on default port)

### ISSUE THREAD

**Issue by FedorAredakov** [airbytehq/airbyte#28837]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

 0.47.13

### What step the error happened?

On deploy

### Revelant information

I use external DB config with custom db port
```        
        postgresql:
          enabled: false        
        externalDatabase:
          database: "my_airbyte"
          host: "mydbhost"
          port: 6432
          user: "my_airbyte"
          password: "my-pass"`
```
but temporal pods manifest contains hardcoded db port:
```        
spec:
  containers:
    - env:
        - name: AUTO_SETUP
          value: 'true'
        - name: DB
          value: postgresql
        - name: DB_PORT
          value: '5432'
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: DATABASE_USER
              name: airbyte-airbyte-secrets
        - name: POSTGRES_PWD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: airbyte-airbyte-secrets
```
So it can't connect to my DB.
ConfigMap airbyte-airbyte-env contains correct port value.
Could you fixed it please. It very vital for us to use external db and it's impossible to change db port as it is a managed DB cluster.
Thanks 

### Relevant log output

```shell
Waiting for PostgreSQL to startup.+ nc -z mydbhost 5432+ echo 'Waiting for PostgreSQL to startup.'+ sleep 1
```
