### ISSUE TITLE
Clean up deprecated configurations

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#28945]
## What

As we switched the resource requirements management, we have a trail of deprecated configuration variables to cleanup.

Trail of things to hunt down.
```
      source:
        cpu-limit: ${SOURCE_CONTAINER_CPU_LIMIT:}
        cpu-request: ${SOURCE_CONTAINER_CPU_REQUEST:0.5}
        memory-limit: ${SOURCE_CONTAINER_MEMORY_LIMIT:}
        memory-request: ${SOURCE_CONTAINER_MEMORY_REQUEST:}
      source-database:
        cpu-limit: ${SOURCE_DATABASE_CONTAINER_CPU_LIMIT:}
        cpu-request: ${SOURCE_DATABASE_CONTAINER_CPU_REQUEST:1}
        memory-limit: ${SOURCE_DATABASE_CONTAINER_MEMORY_LIMIT:}
        memory-request: ${SOURCE_DATABASE_CONTAINER_MEMORY_REQUEST:}
```

## How

Delete dead code / configs
