### ISSUE TITLE
New source: support for Gorgias

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#2940]
## Tell us about the new integration you’d like to have
[Gorgias](https://www.gorgias.com/)

I'd like support for the following endpoints: 

* Account
* Customers
* Events
* Statistics
* Tags
* Tickets
* Users

## Integration Vetting
**Webhook-based? (no/partially/yes)**
no

**Available authentication modes (API key/Oauth/other)**
Basic [username/password based auth](https://en.wikipedia.org/wiki/Basic_access_authentication)

**Creating an account**
_self-service free account available?_
nope cheapest price tier is $60/mo

**How to populate the account with data?**
_Can it be done entirely through the API?_ yes

**Available streams for sync**
All endpoints [here](https://developers.gorgias.com/reference) which contain a list endpoint (most of them) 

**Integration supports incremental sync?**
Not really, it would have to be client side incremental sync

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368160108635) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
## Integration Vetting
**Webhook-based? (no/partially/yes)**
no

**Available authentication modes (API key/Oauth/other)**
Basic [username/password based auth](https://en.wikipedia.org/wiki/Basic_access_authentication)

**Creating an account**
_self-service free account available?_
nope cheapest price tier is $60/mo

**How to populate the account with data?**
_Can it be done entirely through the API?_ yes

**Available streams for sync**
All endpoints [here](https://developers.gorgias.com/reference) which contain a list endpoint (most of them) 
 
**Integration supports incremental sync?**
Not really, it would have to be client side incremental sync

**Comment by sherifnada** [comment]
FYI I didn't create an account for this yet. We should create an account on the cheapest tier once we begin implementation.

**Comment by NicolasWebDev** [comment]
Maybe there is some update on when this connector is planned to be implemented?

**Comment by sherifnada** [comment]
@NicolasWebDev currently not in the short term roadmap, could you add a 👍🏼 reaction to help us gauge interest? 

Alternatively we'd be happy to help you submit this as a contribution if you like

**Comment by arjunbanker** [comment]
FYI there is a Singer/Meltano tap available - https://github.com/brooklyn-data/tap-gorgias

**Comment by enmaust** [comment]
there is a starter plan available now for $10/mth fyi

**Comment by igrankova** [comment]
Created an account: https://airbytecloud.gorgias.com/
LastPass: Gorgias Test account
API Key
We are now on the free monthly plan as the developers.

**Comment by evwltrs** [comment]
Will do this using the low code CDK 👍

**Comment by YowanR** [comment]
Hi @evwltrs, my apologies for not assigning it to you -- I just fixed that :) 
How's it going for you so far?

**Comment by evwltrs** [comment]
> Hi @evwltrs, my apologies for not assigning it to you -- I just fixed that :) 
> How's it going for you so far?

Hi @YowanR, I haven't started yet as I think I am still being processed into the Lastpass unless I missed an invite email maybe?

**Comment by YowanR** [comment]
@evwltrs Are you still awaiting the creds from LastPass?

**Comment by evwltrs** [comment]
I now have the Gorgias cress but awaiting on the help scout ones now so I can finish that connector and start this one...

**Comment by YowanR** [comment]
You're awaiting creds for help scout?

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [New Source: Gorgias](https://app.harvestr.io/components/0/list/mAZpNEwEs)

**Comment by jrolom** [comment]
Hi @evwltrs  - will you be working on this new source?

**Comment by koconder** [comment]
@jrolom i would like to take this on please, will need creds

**Comment by gnestor** [comment]
I created a custom connector for Gorgias tickets, feel free to import this or build upon it: 

```yaml
version: 0.51.41
type: DeclarativeSource
check:
  type: CheckStream
  stream_names:
    - tickets
streams:
  - type: DeclarativeStream
    name: tickets
    primary_key:
      - id
    schema_loader:
      type: InlineSchemaLoader
      schema:
        $schema: http://json-schema.org/schema#
        properties:
          assignee_team:
            properties:
              decoration:
                type: object
              id:
                type: number
              name:
                type: string
            type:
              - object
              - 'null'
          assignee_user:
            properties:
              bio:
                type: string
              email:
                type: string
              firstname:
                type: string
              id:
                type: number
              lastname:
                type: string
              meta:
                properties:
                  last_phone_call_ended_at:
                    type: string
                  profile_picture_url:
                    type:
                      - 'null'
                      - string
                type: object
              name:
                type: string
            type:
              - object
              - 'null'
          channel:
            type: string
          closed_datetime:
            type:
              - 'null'
              - string
          created_datetime:
            type: string
          customer:
            properties:
              email:
                type:
                  - 'null'
                  - string
              firstname:
                type: string
              id:
                type: number
              lastname:
                type: string
              meta:
                properties:
                  location_info:
                    properties:
                      calling_code:
                        type: string
                      city:
                        type: string
                      country_code:
                        type: string
                      country_name:
                        type: string
                      currency:
                        properties:
                          code:
                            type: string
                        type: object
                      ip:
                        type: string
                      languages:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      region:
                        type: string
                      region_code:
                        type: string
                      time_zone:
                        properties:
                          abbr:
                            type: string
                          name:
                            type: string
                          offset:
                            type: string
                        type: object
                    type: object
                  name_set_via:
                    type: string
                type:
                  - object
                  - 'null'
              name:
                type:
                  - 'null'
                  - string
            type: object
          excerpt:
            type: string
          from_agent:
            type: boolean
          id:
            type: number
          integrations:
            items:
              properties:
                address:
                  type:
                    - 'null'
                    - string
                name:
                  type: string
                type:
                  type: string
              type: object
            type: array
          is_unread:
            type: boolean
          language:
            type:
              - 'null'
              - string
          last_message_datetime:
            type: string
          last_received_message_datetime:
            type:
              - 'null'
              - string
          messages_count:
            type: number
          meta:
            properties:
              chat:
                properties:
                  application_id:
                    type: number
                  conversation_id:
                    type: string
                type: object
              rule_suggestion:
                properties:
                  id:
                    type: number
                type: object
            type:
              - object
              - 'null'
          opened_datetime:
            type:
              - 'null'
              - string
          priority:
            type: string
          spam:
            type: boolean
          status:
            type: string
          subject:
            type: string
          tags:
            items:
              properties:
                decoration:
                  properties:
                    color:
                      type: string
                  type:
                    - object
                    - 'null'
                id:
                  type: number
                name:
                  type: string
              type: object
            type: array
          updated_datetime:
            type: string
          uri:
            type: string
          via:
            type: string
        type: object
    retriever:
      type: SimpleRetriever
      requester:
        type: HttpRequester
        url_base: https://hammiesshorts.gorgias.com/api/
        path: /tickets
        http_method: GET
        request_parameters:
          order_by: created_datetime:desc
        request_headers:
          Content-Type: application/json
        authenticator:
          type: BasicHttpAuthenticator
          username: '{{ config[''username''] }}'
          password: '{{ config[''password''] }}'
        request_body_json: {}
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_path:
            - data
      paginator:
        type: DefaultPaginator
        page_token_option:
          type: RequestOption
          inject_into: request_parameter
          field_name: cursor
        page_size_option:
          inject_into: request_parameter
          type: RequestOption
          field_name: limit
        pagination_strategy:
          type: CursorPagination
          page_size: 100
          cursor_value: '{{ response.get("meta. next_cursor", {}) }}'
          stop_condition: '{{ not response.get("meta. next_cursor", {}) }}'
    incremental_sync:
      type: DatetimeBasedCursor
      cursor_field: created_datetime
      cursor_datetime_formats:
        - '%Y-%m-%dT%H:%M:%S+00:00'
        - '%Y-%m-%dT%H:%M:%S.%f+00:00'
      datetime_format: '%Y-%m-%dT%H:%M:%S+00:00'
      start_datetime:
        type: MinMaxDatetime
        datetime: '{{ config[''start_date''] }}'
        datetime_format: '%Y-%m-%dT%H:%M:%SZ'
      is_data_feed: true
  - type: DeclarativeStream
    name: messages
    primary_key:
      - id
    schema_loader:
      type: InlineSchemaLoader
      schema:
        $schema: http://json-schema.org/schema#
        properties:
          attachments:
            items:
              properties:
                content_type:
                  type: string
                name:
                  type: string
                public:
                  type: boolean
                size:
                  type: number
                url:
                  type: string
              type: object
            type:
              - array
              - 'null'
          body_html:
            type:
              - 'null'
              - string
          body_text:
            type: string
          channel:
            type: string
          created_datetime:
            type: string
          from_agent:
            type: boolean
          id:
            type: number
          integration_id:
            type:
              - 'null'
              - number
          intents:
            items:
              properties:
                is_user_feedback:
                  type: boolean
                name:
                  type: string
              type: object
            type: array
          is_retriable:
            type: boolean
          macros:
            type: array
          message_id:
            type:
              - 'null'
              - string
          public:
            type: boolean
          receiver:
            properties:
              email:
                type:
                  - 'null'
                  - string
              firstname:
                type: string
              id:
                type: number
              lastname:
                type: string
              meta:
                properties:
                  name_set_via:
                    type: string
                type: object
              name:
                type: string
            type: object
          sender:
            properties:
              email:
                type:
                  - 'null'
                  - string
              firstname:
                type: string
              id:
                type: number
              lastname:
                type: string
              meta:
                properties:
                  name_set_via:
                    type: string
                type: object
              name:
                type: string
            type: object
          sent_datetime:
            type: string
          source:
            properties:
              extra:
                properties:
                  media_id:
                    type: string
                  parent_id:
                    type: string
                  permalink:
                    type: string
                type: object
              from:
                properties:
                  address:
                    type: string
                  name:
                    type: string
                type: object
              to:
                items:
                  properties:
                    address:
                      type: string
                    name:
                      type: string
                  type: object
                type: array
              type:
                type: string
            type: object
          subject:
            type:
              - 'null'
              - string
          ticket_id:
            type: number
          uri:
            type: string
          via:
            type: string
        type: object
    retriever:
      type: SimpleRetriever
      requester:
        type: HttpRequester
        url_base: https://hammiesshorts.gorgias.com/api/
        path: /tickets/{{ stream_partition.ticket_id }}/messages
        http_method: GET
        request_parameters:
          order_by: created_datetime:desc
        request_headers:
          Content-Type: application/json
        authenticator:
          type: BasicHttpAuthenticator
          username: '{{ config[''username''] }}'
          password: '{{ config[''password''] }}'
        request_body_json: {}
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_path:
            - data
      paginator:
        type: DefaultPaginator
        page_token_option:
          type: RequestOption
          inject_into: request_parameter
          field_name: cursor
        page_size_option:
          inject_into: request_parameter
          type: RequestOption
          field_name: limit
        pagination_strategy:
          type: CursorPagination
          page_size: 100
          cursor_value: '{{ response.get("meta. next_cursor", {}) }}'
          stop_condition: '{{ not response.get("meta. next_cursor", {}) }}'
      partition_router:
        - type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: ticket_id
              stream:
                type: DeclarativeStream
                name: tickets
                primary_key:
                  - id
                schema_loader:
                  type: InlineSchemaLoader
                  schema:
                    $schema: http://json-schema.org/schema#
                    properties:
                      assignee_team:
                        properties:
                          decoration:
                            type: object
                          id:
                            type: number
                          name:
                            type: string
                        type:
                          - object
                          - 'null'
                      assignee_user:
                        properties:
                          bio:
                            type: string
                          email:
                            type: string
                          firstname:
                            type: string
                          id:
                            type: number
                          lastname:
                            type: string
                          meta:
                            properties:
                              last_phone_call_ended_at:
                                type: string
                              profile_picture_url:
                                type:
                                  - 'null'
                                  - string
                            type: object
                          name:
                            type: string
                        type:
                          - object
                          - 'null'
                      channel:
                        type: string
                      closed_datetime:
                        type:
                          - 'null'
                          - string
                      created_datetime:
                        type: string
                      customer:
                        properties:
                          email:
                            type:
                              - 'null'
                              - string
                          firstname:
                            type: string
                          id:
                            type: number
                          lastname:
                            type: string
                          meta:
                            properties:
                              location_info:
                                properties:
                                  calling_code:
                                    type: string
                                  city:
                                    type: string
                                  country_code:
                                    type: string
                                  country_name:
                                    type: string
                                  currency:
                                    properties:
                                      code:
                                        type: string
                                    type: object
                                  ip:
                                    type: string
                                  languages:
                                    items:
                                      properties:
                                        name:
                                          type: string
                                      type: object
                                    type: array
                                  region:
                                    type: string
                                  region_code:
                                    type: string
                                  time_zone:
                                    properties:
                                      abbr:
                                        type: string
                                      name:
                                        type: string
                                      offset:
                                        type: string
                                    type: object
                                type: object
                              name_set_via:
                                type: string
                            type:
                              - object
                              - 'null'
                          name:
                            type:
                              - 'null'
                              - string
                        type: object
                      excerpt:
                        type: string
                      from_agent:
                        type: boolean
                      id:
                        type: number
                      integrations:
                        items:
                          properties:
                            address:
                              type:
                                - 'null'
                                - string
                            name:
                              type: string
                            type:
                              type: string
                          type: object
                        type: array
                      is_unread:
                        type: boolean
                      language:
                        type:
                          - 'null'
                          - string
                      last_message_datetime:
                        type: string
                      last_received_message_datetime:
                        type:
                          - 'null'
                          - string
                      messages_count:
                        type: number
                      meta:
                        properties:
                          chat:
                            properties:
                              application_id:
                                type: number
                              conversation_id:
                                type: string
                            type: object
                          rule_suggestion:
                            properties:
                              id:
                                type: number
                            type: object
                        type:
                          - object
                          - 'null'
                      opened_datetime:
                        type:
                          - 'null'
                          - string
                      priority:
                        type: string
                      spam:
                        type: boolean
                      status:
                        type: string
                      subject:
                        type: string
                      tags:
                        items:
                          properties:
                            decoration:
                              properties:
                                color:
                                  type: string
                              type:
                                - object
                                - 'null'
                            id:
                              type: number
                            name:
                              type: string
                          type: object
                        type: array
                      updated_datetime:
                        type: string
                      uri:
                        type: string
                      via:
                        type: string
                    type: object
                retriever:
                  type: SimpleRetriever
                  requester:
                    type: HttpRequester
                    url_base: https://hammiesshorts.gorgias.com/api/
                    path: /tickets
                    http_method: GET
                    request_parameters:
                      order_by: created_datetime:desc
                    request_headers:
                      Content-Type: application/json
                    authenticator:
                      type: BasicHttpAuthenticator
                      username: '{{ config[''username''] }}'
                      password: '{{ config[''password''] }}'
                    request_body_json: {}
                  record_selector:
                    type: RecordSelector
                    extractor:
                      type: DpathExtractor
                      field_path:
                        - data
                  paginator:
                    type: DefaultPaginator
                    page_token_option:
                      type: RequestOption
                      inject_into: request_parameter
                      field_name: cursor
                    page_size_option:
                      inject_into: request_parameter
                      type: RequestOption
                      field_name: limit
                    pagination_strategy:
                      type: CursorPagination
                      page_size: 100
                      cursor_value: '{{ response.get("meta. next_cursor", {}) }}'
                      stop_condition: '{{ not response.get("meta. next_cursor", {}) }}'
                incremental_sync:
                  type: DatetimeBasedCursor
                  cursor_field: created_datetime
                  cursor_datetime_formats:
                    - '%Y-%m-%dT%H:%M:%S+00:00'
                    - '%Y-%m-%dT%H:%M:%S.%f+00:00'
                  datetime_format: '%Y-%m-%dT%H:%M:%S+00:00'
                  start_datetime:
                    type: MinMaxDatetime
                    datetime: '{{ config[''start_date''] }}'
                    datetime_format: '%Y-%m-%dT%H:%M:%SZ'
                  is_data_feed: true
    incremental_sync:
      type: DatetimeBasedCursor
      cursor_field: created_datetime
      cursor_datetime_formats:
        - '%Y-%m-%dT%H:%M:%S+00:00'
        - '%Y-%m-%dT%H:%M:%S.%f+00:00'
      datetime_format: '%Y-%m-%dT%H:%M:%S+00:00'
      start_datetime:
        type: MinMaxDatetime
        datetime: '{{ config[''start_date''] }}'
        datetime_format: '%Y-%m-%dT%H:%M:%SZ'
      is_data_feed: true
spec:
  connection_specification:
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    required:
      - start_date
      - username
    properties:
      start_date:
        type: string
        title: Start date
        format: date-time
        pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$
        order: 0
      username:
        type: string
        title: Username
        order: 1
      password:
        type: string
        title: Password
        always_show: true
        airbyte_secret: true
        order: 2
    additionalProperties: true
  type: Spec
metadata:
  autoImportSchema:
    tickets: true
    messages: true
```

**Comment by gnestor** [comment]
I created a custom connector for Gorgias tickets. Free free to import or build upon it: 

```yaml
version: 0.51.41
type: DeclarativeSource
check:
  type: CheckStream
  stream_names:
    - tickets
streams:
  - type: DeclarativeStream
    name: tickets
    primary_key:
      - id
    schema_loader:
      type: InlineSchemaLoader
      schema:
        $schema: http://json-schema.org/schema#
        properties:
          assignee_team:
            properties:
              decoration:
                type: object
              id:
                type: number
              name:
                type: string
            type:
              - object
              - 'null'
          assignee_user:
            properties:
              bio:
                type: string
              email:
                type: string
              firstname:
                type: string
              id:
                type: number
              lastname:
                type: string
              meta:
                properties:
                  last_phone_call_ended_at:
                    type: string
                  profile_picture_url:
                    type:
                      - 'null'
                      - string
                type: object
              name:
                type: string
            type:
              - object
              - 'null'
          channel:
            type: string
          closed_datetime:
            type:
              - 'null'
              - string
          created_datetime:
            type: string
          customer:
            properties:
              email:
                type:
                  - 'null'
                  - string
              firstname:
                type: string
              id:
                type: number
              lastname:
                type: string
              meta:
                properties:
                  location_info:
                    properties:
                      calling_code:
                        type: string
                      city:
                        type: string
                      country_code:
                        type: string
                      country_name:
                        type: string
                      currency:
                        properties:
                          code:
                            type: string
                        type: object
                      ip:
                        type: string
                      languages:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      region:
                        type: string
                      region_code:
                        type: string
                      time_zone:
                        properties:
                          abbr:
                            type: string
                          name:
                            type: string
                          offset:
                            type: string
                        type: object
                    type: object
                  name_set_via:
                    type: string
                type:
                  - object
                  - 'null'
              name:
                type:
                  - 'null'
                  - string
            type: object
          excerpt:
            type: string
          from_agent:
            type: boolean
          id:
            type: number
          integrations:
            items:
              properties:
                address:
                  type:
                    - 'null'
                    - string
                name:
                  type: string
                type:
                  type: string
              type: object
            type: array
          is_unread:
            type: boolean
          language:
            type:
              - 'null'
              - string
          last_message_datetime:
            type: string
          last_received_message_datetime:
            type:
              - 'null'
              - string
          messages_count:
            type: number
          meta:
            properties:
              chat:
                properties:
                  application_id:
                    type: number
                  conversation_id:
                    type: string
                type: object
              rule_suggestion:
                properties:
                  id:
                    type: number
                type: object
            type:
              - object
              - 'null'
          opened_datetime:
            type:
              - 'null'
              - string
          priority:
            type: string
          spam:
            type: boolean
          status:
            type: string
          subject:
            type: string
          tags:
            items:
              properties:
                decoration:
                  properties:
                    color:
                      type: string
                  type:
                    - object
                    - 'null'
                id:
                  type: number
                name:
                  type: string
              type: object
            type: array
          updated_datetime:
            type: string
          uri:
            type: string
          via:
            type: string
        type: object
    retriever:
      type: SimpleRetriever
      requester:
        type: HttpRequester
        url_base: https://hammiesshorts.gorgias.com/api/
        path: /tickets
        http_method: GET
        request_parameters:
          order_by: created_datetime:desc
        request_headers:
          Content-Type: application/json
        authenticator:
          type: BasicHttpAuthenticator
          username: '{{ config[''username''] }}'
          password: '{{ config[''password''] }}'
        request_body_json: {}
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_path:
            - data
      paginator:
        type: DefaultPaginator
        page_token_option:
          type: RequestOption
          inject_into: request_parameter
          field_name: cursor
        page_size_option:
          inject_into: request_parameter
          type: RequestOption
          field_name: limit
        pagination_strategy:
          type: CursorPagination
          page_size: 100
          cursor_value: '{{ response.get("meta. next_cursor", {}) }}'
          stop_condition: '{{ not response.get("meta. next_cursor", {}) }}'
    incremental_sync:
      type: DatetimeBasedCursor
      cursor_field: created_datetime
      cursor_datetime_formats:
        - '%Y-%m-%dT%H:%M:%S+00:00'
        - '%Y-%m-%dT%H:%M:%S.%f+00:00'
      datetime_format: '%Y-%m-%dT%H:%M:%S+00:00'
      start_datetime:
        type: MinMaxDatetime
        datetime: '{{ config[''start_date''] }}'
        datetime_format: '%Y-%m-%dT%H:%M:%SZ'
      is_data_feed: true
  - type: DeclarativeStream
    name: messages
    primary_key:
      - id
    schema_loader:
      type: InlineSchemaLoader
      schema:
        $schema: http://json-schema.org/schema#
        properties:
          attachments:
            items:
              properties:
                content_type:
                  type: string
                name:
                  type: string
                public:
                  type: boolean
                size:
                  type: number
                url:
                  type: string
              type: object
            type:
              - array
              - 'null'
          body_html:
            type:
              - 'null'
              - string
          body_text:
            type: string
          channel:
            type: string
          created_datetime:
            type: string
          from_agent:
            type: boolean
          id:
            type: number
          integration_id:
            type:
              - 'null'
              - number
          intents:
            items:
              properties:
                is_user_feedback:
                  type: boolean
                name:
                  type: string
              type: object
            type: array
          is_retriable:
            type: boolean
          macros:
            type: array
          message_id:
            type:
              - 'null'
              - string
          public:
            type: boolean
          receiver:
            properties:
              email:
                type:
                  - 'null'
                  - string
              firstname:
                type: string
              id:
                type: number
              lastname:
                type: string
              meta:
                properties:
                  name_set_via:
                    type: string
                type: object
              name:
                type: string
            type: object
          sender:
            properties:
              email:
                type:
                  - 'null'
                  - string
              firstname:
                type: string
              id:
                type: number
              lastname:
                type: string
              meta:
                properties:
                  name_set_via:
                    type: string
                type: object
              name:
                type: string
            type: object
          sent_datetime:
            type: string
          source:
            properties:
              extra:
                properties:
                  media_id:
                    type: string
                  parent_id:
                    type: string
                  permalink:
                    type: string
                type: object
              from:
                properties:
                  address:
                    type: string
                  name:
                    type: string
                type: object
              to:
                items:
                  properties:
                    address:
                      type: string
                    name:
                      type: string
                  type: object
                type: array
              type:
                type: string
            type: object
          subject:
            type:
              - 'null'
              - string
          ticket_id:
            type: number
          uri:
            type: string
          via:
            type: string
        type: object
    retriever:
      type: SimpleRetriever
      requester:
        type: HttpRequester
        url_base: https://hammiesshorts.gorgias.com/api/
        path: /tickets/{{ stream_partition.ticket_id }}/messages
        http_method: GET
        request_parameters:
          order_by: created_datetime:desc
        request_headers:
          Content-Type: application/json
        authenticator:
          type: BasicHttpAuthenticator
          username: '{{ config[''username''] }}'
          password: '{{ config[''password''] }}'
        request_body_json: {}
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_path:
            - data
      paginator:
        type: DefaultPaginator
        page_token_option:
          type: RequestOption
          inject_into: request_parameter
          field_name: cursor
        page_size_option:
          inject_into: request_parameter
          type: RequestOption
          field_name: limit
        pagination_strategy:
          type: CursorPagination
          page_size: 100
          cursor_value: '{{ response.get("meta. next_cursor", {}) }}'
          stop_condition: '{{ not response.get("meta. next_cursor", {}) }}'
      partition_router:
        - type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: ticket_id
              stream:
                type: DeclarativeStream
                name: tickets
                primary_key:
                  - id
                schema_loader:
                  type: InlineSchemaLoader
                  schema:
                    $schema: http://json-schema.org/schema#
                    properties:
                      assignee_team:
                        properties:
                          decoration:
                            type: object
                          id:
                            type: number
                          name:
                            type: string
                        type:
                          - object
                          - 'null'
                      assignee_user:
                        properties:
                          bio:
                            type: string
                          email:
                            type: string
                          firstname:
                            type: string
                          id:
                            type: number
                          lastname:
                            type: string
                          meta:
                            properties:
                              last_phone_call_ended_at:
                                type: string
                              profile_picture_url:
                                type:
                                  - 'null'
                                  - string
                            type: object
                          name:
                            type: string
                        type:
                          - object
                          - 'null'
                      channel:
                        type: string
                      closed_datetime:
                        type:
                          - 'null'
                          - string
                      created_datetime:
                        type: string
                      customer:
                        properties:
                          email:
                            type:
                              - 'null'
                              - string
                          firstname:
                            type: string
                          id:
                            type: number
                          lastname:
                            type: string
                          meta:
                            properties:
                              location_info:
                                properties:
                                  calling_code:
                                    type: string
                                  city:
                                    type: string
                                  country_code:
                                    type: string
                                  country_name:
                                    type: string
                                  currency:
                                    properties:
                                      code:
                                        type: string
                                    type: object
                                  ip:
                                    type: string
                                  languages:
                                    items:
                                      properties:
                                        name:
                                          type: string
                                      type: object
                                    type: array
                                  region:
                                    type: string
                                  region_code:
                                    type: string
                                  time_zone:
                                    properties:
                                      abbr:
                                        type: string
                                      name:
                                        type: string
                                      offset:
                                        type: string
                                    type: object
                                type: object
                              name_set_via:
                                type: string
                            type:
                              - object
                              - 'null'
                          name:
                            type:
                              - 'null'
                              - string
                        type: object
                      excerpt:
                        type: string
                      from_agent:
                        type: boolean
                      id:
                        type: number
                      integrations:
                        items:
                          properties:
                            address:
                              type:
                                - 'null'
                                - string
                            name:
                              type: string
                            type:
                              type: string
                          type: object
                        type: array
                      is_unread:
                        type: boolean
                      language:
                        type:
                          - 'null'
                          - string
                      last_message_datetime:
                        type: string
                      last_received_message_datetime:
                        type:
                          - 'null'
                          - string
                      messages_count:
                        type: number
                      meta:
                        properties:
                          chat:
                            properties:
                              application_id:
                                type: number
                              conversation_id:
                                type: string
                            type: object
                          rule_suggestion:
                            properties:
                              id:
                                type: number
                            type: object
                        type:
                          - object
                          - 'null'
                      opened_datetime:
                        type:
                          - 'null'
                          - string
                      priority:
                        type: string
                      spam:
                        type: boolean
                      status:
                        type: string
                      subject:
                        type: string
                      tags:
                        items:
                          properties:
                            decoration:
                              properties:
                                color:
                                  type: string
                              type:
                                - object
                                - 'null'
                            id:
                              type: number
                            name:
                              type: string
                          type: object
                        type: array
                      updated_datetime:
                        type: string
                      uri:
                        type: string
                      via:
                        type: string
                    type: object
                retriever:
                  type: SimpleRetriever
                  requester:
                    type: HttpRequester
                    url_base: https://hammiesshorts.gorgias.com/api/
                    path: /tickets
                    http_method: GET
                    request_parameters:
                      order_by: created_datetime:desc
                    request_headers:
                      Content-Type: application/json
                    authenticator:
                      type: BasicHttpAuthenticator
                      username: '{{ config[''username''] }}'
                      password: '{{ config[''password''] }}'
                    request_body_json: {}
                  record_selector:
                    type: RecordSelector
                    extractor:
                      type: DpathExtractor
                      field_path:
                        - data
                  paginator:
                    type: DefaultPaginator
                    page_token_option:
                      type: RequestOption
                      inject_into: request_parameter
                      field_name: cursor
                    page_size_option:
                      inject_into: request_parameter
                      type: RequestOption
                      field_name: limit
                    pagination_strategy:
                      type: CursorPagination
                      page_size: 100
                      cursor_value: '{{ response.get("meta. next_cursor", {}) }}'
                      stop_condition: '{{ not response.get("meta. next_cursor", {}) }}'
                incremental_sync:
                  type: DatetimeBasedCursor
                  cursor_field: created_datetime
                  cursor_datetime_formats:
                    - '%Y-%m-%dT%H:%M:%S+00:00'
                    - '%Y-%m-%dT%H:%M:%S.%f+00:00'
                  datetime_format: '%Y-%m-%dT%H:%M:%S+00:00'
                  start_datetime:
                    type: MinMaxDatetime
                    datetime: '{{ config[''start_date''] }}'
                    datetime_format: '%Y-%m-%dT%H:%M:%SZ'
                  is_data_feed: true
    incremental_sync:
      type: DatetimeBasedCursor
      cursor_field: created_datetime
      cursor_datetime_formats:
        - '%Y-%m-%dT%H:%M:%S+00:00'
        - '%Y-%m-%dT%H:%M:%S.%f+00:00'
      datetime_format: '%Y-%m-%dT%H:%M:%S+00:00'
      start_datetime:
        type: MinMaxDatetime
        datetime: '{{ config[''start_date''] }}'
        datetime_format: '%Y-%m-%dT%H:%M:%SZ'
      is_data_feed: true
spec:
  connection_specification:
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    required:
      - start_date
      - username
    properties:
      start_date:
        type: string
        title: Start date
        format: date-time
        pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$
        order: 0
      username:
        type: string
        title: Username
        order: 1
      password:
        type: string
        title: Password
        always_show: true
        airbyte_secret: true
        order: 2
    additionalProperties: true
  type: Spec
metadata:
  autoImportSchema:
    tickets: true
    messages: true
```
