### ISSUE TITLE
Declare a new metadata field: `connectorBaseImage`

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#30233]
Connector will declare which base image they should be built with through a new metadata field: `connectorBaseImage`. 
This field will reference an actual docker image version that should be existing in our dagger code and on DockerHub.

```yaml
data:
  allowedHosts:
    hosts:
      - api.openweathermap.org
  registries:
    oss:
      enabled: true
    cloud:
      enabled: false
  connectorBaseImage: airbyte/python-connector-base-image:0.1.0
  connectorSubtype: api
  connectorType: source
  definitionId: 561d7787-b45e-4f3b-af58-0163c3ba9d5a
  dockerImageTag: 0.2.0
  dockerRepository: airbyte/source-openweather
  githubIssueLabel: source-openweather
  icon: openweather.svg
  license: MIT
  name: Openweather
  releaseStage: alpha
  supportLevel: community
  documentationUrl: https://docs.airbyte.com/integrations/sources/openweather
  tags:
    - language:lowcode
metadataSpecVersion: "1.0"
```

This field should be optional as we'll still support builds from Dockerfile. The validation of the field value will happen later, when the first base image will actually be released.
