### ISSUE TITLE
Path Prefix for Ingress Controller in Kubernetes

### ISSUE THREAD

**Issue by sergeibelov113** [airbytehq/airbyte#30753]
### Topic

Path Prefix

### Revelant information

Hello, I am using traefik and ingressroute resource in kubernetes.

My ingressroute looks so:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: airbyte-ingress-route-https
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: PathPrefix(`/airbyte`)
    priority: 10
    services:
    - name: airbyte-airbyte-webapp-svc
      port: 80
```

I do not use separate domain at this stage, only prefix.
So airbyte should be available via IP and prefix: https://[ip address]/airbyte

But when I try to open the page I only see blank page, and debugging tool shows me that all sublinks embedded in airbyte are looks like https://[ip address]/ and not https://[ip address]/airbyte

I haven't found where I can customise prefix via helm chart.
I found environment variable WEBAPP_URL, changed it, restarted the pods but it didn't fix the issue.

Is there any way to enable prefix for ingress controller on airbyte side?

For example in argocd or dagster helm charts there is a possibility to add prefix for web requests.
