### ISSUE TITLE
Airbyte fails if it doesn't have internet access, proxy config not working as expected

### ISSUE THREAD

**Issue by kevinob11** [airbytehq/airbyte#3076]
## Expected Behavior
I run Airbyte behind a proxy. In earlier versions I allowed it around the proxy during updates, then disabled internet access after the update. In the latest update Airbyte won't load with internet access disabled. I attempted to configure our proxy so I could consider whitelisting whatever it is calling out to but the Airbyte containers (I tried with web and server) don't seem to be respecting the proxy configuration.

## Current Behavior
Airbyte ui doesn't load without internet access. Proxy configuration doesn't seem to be working as expected on docker container for server or web-ui.

## Logs
The one log I'm seeing is that this specific request throws a 500 when Airbyte can't reach the internet

airbyte-server      | 2021-04-27 00:14:06 ERROR i.a.s.RequestLogger(filter):105 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 10.55.254.4 POST 500 /api/v1/source_definitions/list_latest - {"workspaceId":"5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"}

## Steps to Reproduce
For error:

1. Disable internet access
1. Attempt to load the web ui

For proxy config

1. Configure docker proxy settings (config.json and service.d)
1. Configured env vars in docker-compose.yaml for HTTPS_PROXY and HTTP_PROXY for server and web-ui
1. Traffic is not routed through the proxy

## Severity of the bug for you
Medium

## Airbyte Version
0.20.0-alpha

## Connector Version (if applicable)
N/A

## Additional context
N/A

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368227638352) by [Unito](https://www.unito.io)

**Comment by merlixo** [comment]
Hi,
Same behaviour here: airbyte-server app is not using the proxy config of the docker container.
We also tried to set Java options for the airbyte-server java app, but it did not helped:
`-Dhttp.proxyHost=http://xxx -Dhttp.proxyPort=yyyy`
Or 
`-Djava.net.useSystemProxies=true`

**Comment by alafanechere** [comment]
To add more details to @merlixo which who I add the opportunity to have a detailed discussion on [slack](https://airbytehq.slack.com/archives/C01MFR03D5W/p1637660475360200). 

1. @merlixo wants the Airbyte's egress traffic to go through a custom proxy
2. He's set up the docker client (v20.10.11) to use an http proxy (docker config attached below)
3. He realized the `airbyte-server` egress traffic is not going through the proxy and has no internet access. During source set up `airbyte-server` calls GitHub resource to build `AirbyteGithubStor`e which leads to `java.net.http.HttpConnectTimeoutException: HTTP connect timed out` error.


Environment details:

- Airbyte version: 0.32.5-alpha
- docker version: 20.10.11
- docker-compose version:  1.29.2
- EC2 OS: Ubuntu 20.04 LTS

**Comment by jrhizor** [comment]
For the original issue:
@kevinob11 0.20.0-alpha has more problems handling errors when accessing `AirbyteGIthubStore` than later versions.
In later versions, a `ConnectException` is logged but doesn't actually cause any failures without internet access. 

For @merlixo's issue and @alafanechere:
It sounds like you have a workaround that's sufficient? From the logs it looks like it logs the errors but isn't actually failing? 
`Unable to retrieve latest Source list from Github. Using the list bundled with Airbyte. This warning is expected if this Airbyte cluster does not have internet access.`
We expect this to happen when there isn't internet access and it shouldn't impede your ability to use Airbyte. 
For proxying source / destination traffic, it looks like @merlixo has already set this up **outside of Airbyte**, which seems like the correct approach (I don't think we'll look into adding proxy support within the Airbyte system directly). 

Since it doesn't look like there's anything we should actually do for this on our side, I'm going to close the issue. Please let me know if there's something I'm missing / work that still needs to be done.

**Comment by merlixo** [comment]
@kevinob11 , another issue of running Airbyte without internet access: it is not possible to add custom ressources (request will timeout). This problem was shared in Slack discussion (https://airbytehq.slack.com/archives/C01MFR03D5W/p1637660475360200) and can be reproduced very easily.

Not being able to add custom connectors without internet access means that Airbyte cannot run without internet access. This is an important limitation for companies running resources in networks without internet access for security reasons. It would be useful to document it.

**Comment by kevinob11** [comment]
@merlixo thanks for the additional context. For now (for a few reasons) I've just fallen back to Foreign data wrappers because I have the convenience of my targeting being postgres and my sources being (mostly) MSSQL or Postgres. We still may use Airbyte for a few other external data sources that aren't as easy to handle in FDW, so I'll keep an eye on this.

**Comment by designedbyclu** [comment]
I having the same internet access issue with configured HTTP_PROXY in docker as well. Kinda difficult to get stable connection in China.

**Comment by Santhin** [comment]
Hey with these values below I managed to run airbyte deployment behind the proxy:
```
global:
  env_vars:
    HTTP_PROXY: "10.111.0.111:1111"
    HTTPS_PROXY: "10.111.0.111:1111"
    NO_PROXY: "10.0.0.0/8,localhost,127.0.0.1,1.internal,s3.amazonaws.com,.s3.us-east-1.amazonaws.com,api.ecr.us-east-1.amazonaws.com,dkr.ecr.us-east-1.amazonaws.com,ec2.us-east-1.amazonaws.com,.cluster.local,.local,.svc,airbyte-*"
    http_proxy: "10.111.0.111:1111"
    https_proxy: "10.111.0.111:1111"
    no_proxy: "10.0.0.0/8,localhost,127.0.0.1,1.internal,s3.amazonaws.com,.s3.us-east-1.amazonaws.com,api.ecr.us-east-1.amazonaws.com,dkr.ecr.us-east-1.amazonaws.com,ec2.us-east-1.amazonaws.com,.cluster.local,.local,.svc,airbyte-*"
    JAVA_TOOL_OPTIONS: "-Dhttp.proxyHost=10.111.0.111 -Dhttp.proxyPort=1111 -Dhttps.proxyHost=10.111.0.111 -Dhttps.proxyPort=1111 -Dhttp.nonProxyHosts=10.0.0.0|localhost|127.0.0.1|*.internal|s3.amazonaws.com|*.s3.us-east-1.amazonaws.com|api.ecr.us-east-1.amazonaws.com|dkr.ecr.us-east-1.amazonaws.com|ec2.us-east-1.amazonaws.com|*.cluster.local|*.local|*.svc|airbyte-*"

webapp:
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      cpu: 250m
      memory: 1Gi
  service:
    type: NodePort
  ingress:
    enabled: true
    className: alb
    annotations:
      alb.ingress.kubernetes.io/group.name: dlh-tst
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    hosts:
      - host: dummy
        paths:
        - path: "/*"
          pathType: ImplementationSpecific
  env_vars:
    DUMMY: DUMMY
    
server:
  env_vars:
    DUMMY: DUMMY
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      cpu: 1000m
      memory: 1Gi

worker:
  env_vars:
    JOB_DEFAULT_ENV_http_proxy: http://10.111.0.111:1111
    JOB_DEFAULT_ENV_https_proxy: http://10.111.0.111:1111
    JOB_DEFAULT_ENV_no_proxy: "10.0.0.0/8,localhost,127.0.0.1,1.internal,s3.amazonaws.com,.s3.us-east-1.amazonaws.com,api.ecr.us-east-1.amazonaws.com,dkr.ecr.us-east-1.amazonaws.com,ec2.us-east-1.amazonaws.com,.cluster.local,.local,.svc,airbyte-*"
    JOB_DEFAULT_ENV_HTTP_PROXY: http://10.111.0.111:1111
    JOB_DEFAULT_ENV_HTTPS_PROXY: http://10.111.0.111:1111
    JOB_DEFAULT_ENV_NO_PROXY: "10.0.0.0/8,localhost,127.0.0.1,1.internal,s3.amazonaws.com,.s3.us-east-1.amazonaws.com,api.ecr.us-east-1.amazonaws.com,dkr.ecr.us-east-1.amazonaws.com,ec2.us-east-1.amazonaws.com,.cluster.local,.local,.svc,airbyte-*"
    JOB_DEFAULT_ENV_JAVA_TOOL_OPTIONS: "-Dhttp.proxyHost=10.111.0.111 -Dhttp.proxyPort=1111 -Dhttps.proxyHost=10.111.0.111 -Dhttps.proxyPort=1111 -Dhttp.nonProxyHosts=10.0.0.0|localhost|127.0.0.1|*.internal|s3.amazonaws.com|*.s3.us-east-1.amazonaws.com|api.ecr.us-east-1.amazonaws.com|dkr.ecr.us-east-1.amazonaws.com|ec2.us-east-1.amazonaws.com|*.cluster.local|*.local|*.svc|airbyte-*"
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      cpu: 250m
      memory: 1Gi
```
