### ISSUE TITLE
Platform missmatch for Worker images for Kubernetes -> Worker fails to start jobs on the ARM64

### ISSUE THREAD

**Issue by konny07** [airbytehq/airbyte#30801]
### Topic

Worker image platform mismatch

### Revelant information

Helm Chart Version: 0.49.0
Airbyte Version: 0.50.29
Deployment: AWS EKS

Main worker containter fails to start any other worker job process with `kubectl cp failed with exit code 126` -> deploying it on ARM64 machine. It looks like the kubectl binary within the image is compiled for AMD rather than ARM.
This stops any workers being run -> can't add sources/connections/destinations because the all fail on the inital step - copying the config.json across to the init container.

On the [Aribyte dockerhub](https://hub.docker.com/layers/airbyte/worker/0.50.29/images/sha256-cf99a693e4f24c054a6922f15fc623d85a989c881bad4e55a2ba63cf2bb70ba3?context=explore) there seems to be a complied image for ARM64 for the worker in for version=0.50.29. However after further looking into it the image labeld as `linux/arm64` still uses `ARG DOCKER_BUILD_ARCH=amd64`. Could this be potentially where the error comes from?
Requires a fix as no ARM based machines will be able to run the worker pod succesfully, therefore disabling airbyte for ARM deployments

**Comment by eltorio** [comment]
I can confirm a mismatch architecture for arm64
```Dockerfile
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/${DOCKER_BUILD_ARCH}/kubectl" \
        && chmod +x kubectl && mv kubectl /usr/local/bin/
```
This command download the amd64 version
## Test on a aarch64 cluster
```
rlemeill@azure-vm1:~$ uname -a
Linux azure-vm1.azure-ns.private 6.2.0-1018-azure #18~22.04.1-Ubuntu SMP Wed Nov 22 00:23:21 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
kubectl cp airbyte-worker-65fdc8cbc7-lvwdb:/usr/local/bin/kubectl kubectl-from-pod
tar: Removing leading `/' from member names
rlemeill@azure-vm1:~$ file kubectl-from-pod 
kubectl-from-pod: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=ztlApmyqKQnUPJxUlnS8/OoMJYLOhE-Us64BkxTCr/6gyuWO1hO7tQp5lRXA-h/V8AJuph6p3kCxV2qdNLZ, stripped
```

**Comment by eltorio** [comment]
I made an image for amd64/arm64 using the correct kubectl  
https://github.com/eltorio/airbyte-worker
my values.yaml for deploying airbyte helm chart contains:
```yaml
worker:
  image:
    repository: eltorio/airbyte-worker
```

**Comment by gmontanola** [comment]
Normalization on `airbyte/normalization:0.4.3` is also failing because of architecture mismatch on it's `main` container.

I'm trying move Airbyte workload to AWS Graviton nodes but it is not as straightforward as I expected.

**Comment by eltorio** [comment]
@gmontanola I use Ampere nodes in general I don't have too many problems. 
For airbyte I adapted to amd64 and aarch64 by just replacing kubectl in airbyte images by kubectl in bitnami/kubectl:latest multiarch image

- airbyte/worker:0.50.40 -> [eltorio/airbyte-worker:0.50.40](https://hub.docker.com/layers/eltorio/airbyte-worker/0.50.40/images/sha256-2b61f96b53b653825825011f373e8ce3c540bc1df185a66c5e59792fcf39a43b?context=repo) [source](https://github.com/eltorio/airbyte-worker/blob/main/worker/Dockerfile)
- airbyte/container-orchestrator:0.50.40 -> [eltorio/airbyte-container-orchestrator:0.50.40](https://hub.docker.com/layers/eltorio/airbyte-container-orchestrator/0.50.40/images/sha256-23fec82054545e67d0e2848876240ddc606c864012b25ae525dd4bfc528cd70a?context=repo) [source](https://github.com/eltorio/airbyte-worker/blob/main/container-orchestrator/Dockerfile)

I don't use normalization in my processes but it should be possible to adapt the dockerfile.  

Where is airbyte/normalization:0.4.3 source ?

@gmontanola in general passing architecture as environment variable in Dockerfile is not a good strategy like in:  
```Dockerfile
ARG DOCKER_BUILD_ARCH=amd64
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/${DOCKER_BUILD_ARCH}/kubectl" \
        && chmod +x kubectl && mv kubectl /usr/local/bin/
```
 you should use an *in build process* detection, for example 
### for Debian/Ubuntu based images I use some blocks like:
```Dockerfile
RUN if [ "$(dpkg --print-architecture)" = "arm64" ] ; then \
     echo "do something specific to arm64 arch" ; \
     fi
```

or simply for kubectl download:
```Dockerfile
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$(dpkg --print-architecture)/kubectl" \
      && chmod +x kubectl && mv kubectl /usr/local/bin/kubectl
```
### for other Linux base images
`uname -m` works but returns **aarch64** for arm64 arch. It just need a simple *if then block* to use `arm64` string

**Comment by gmontanola** [comment]
Thanks for the awesome tips, @eltorio.

normalization source is [here](https://github.com/airbytehq/airbyte/blob/6762dcb55a6b3df49dc4022b3f140b75bb5cf7cc/airbyte-integrations/bases/base-normalization/Dockerfile)

my guess is the problem comes from:

```dockerfile
FROM fishtownanalytics/dbt:1.0.0
```

This is a old and deprecated image that is only AMD64. Airbyte team could really add your image building recommendations for the official images :)

**Comment by eltorio** [comment]
@gmontanola I tried to make a dbt:1.0.0 amd64/arm64 image [Dockerfile](https://github.com/eltorio/dbt) and docker images [eltorio/dbt:1.0.0](https://hub.docker.com/repository/docker/eltorio/dbt/general)
I did not make any test yet but I think it is possible to build a multiarch normalization image.  
if you try let me know…

**Comment by eltorio** [comment]
@gmontanola I built dbt:1.7.4 ( eltorio/dbt:1.7.4 ) successfully and normalization:0.4.3 ( eltorio/normalization:0.4.3 ) based on eltorio/dbt:1.7.4

**Comment by hollocopter** [comment]
@eltorio Can I ask, how are you setting the custom image for container-orchestrator? Your work has been extremely helpful to me for getting the worker pod to work, but it's less obvious how to replace the image of the container-orchestrator.

**Comment by eltorio** [comment]
@hollocopter you're welcome !
You can run without orchestrator… It is much simpler.  
this is my values:  
```yaml
webapp:
  ingress:
    enabled: true
    className: "haproxy"
    annotations: 
      cert-manager.io/cluster-issuer: *********-ca-issuer
      haproxy.org/auth-type: basic-auth
      haproxy.org/auth-secret: longhorn-system/longhorn-ui-haproxy-credentials
    hosts:
    - host: airbyte.****************.org
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - secretName: airbyte-************-org
      hosts:
      - airbyte.oci.sctg.eu.org

    api:
    url: /api/v1/

worker:
  image:
    repository: eltorio/airbyte-worker
  containerOrchestrator:
    image: "eltorio/airbyte-container-orchestrator"
  env_vars:
    CONTAINER_ORCHESTRATOR_IMAGE: eltorio/airbyte-container-orchestrator
    CONTAINER_ORCHESTRATOR_ENABLED: false
```
this is my bash command line:
```bash
  helm repo add airbyte https://airbytehq.github.io/helm-charts
  helm repo update airbyte
  helm upgrade --install --create-namespace --namespace airbyte  airbyte airbyte/airbyte --values $HOME/production/airbyte.yaml
```

@hollocopter I don't have enough time to finish but I'm working on the postgresql destination (eltorio/destination-postgres) for having a full working normalization
