### ISSUE TITLE
Source Amplitude: upgrade subsciption plan to test Cohorts and Annotations streams properly

### ISSUE THREAD

**Issue by roman-yermilov-gl** [airbytehq/airbyte#30958]
### Topic

Cohorts and Annotations CAT tests

### Revelant information

We need to upgrade subscription plan from **Starter** to **Growth** so that we can populate the `Cohorts` and `Annotations` streams with data. After that we can update the CAT tests for the connector so that those two streams are tested properly.

So the steps are the following:
- Upgrade plan from **Starter** to **Growth**
- Update [expected_records.jsonl](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amplitude/integration_tests/expected_records.jsonl) with expected data for the `Cohorts` and `Annotations` streams
- Rermove `empty_streams` section from [acceptance_test_config.yaml](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amplitude/acceptance-test-config.yml#L25)
```
empty_streams:
  - name: "cohorts"
    bypass_reason: "This stream is empty due to free subscription plan for the sandbox."
  - name: "annotations"
    bypass_reason: "This stream is empty due to free subscription plan for the sandbox."
```
- Remove [integration test](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amplitude/integration_tests/integration_test.py). This test runs fake data against schema for those streams and no longer needed
