### ISSUE TITLE
Pod Jobs don't support pod affinity rules

### ISSUE THREAD

**Issue by a-monteiro** [airbytehq/airbyte#31664]
### Relevant information

Hi,

We have an Airbyte k8s deployment across multiple availability zones (AZ), and for performance (and cost) reasons, we would like to schedule related job pods in the same AZ.

While this is possible by using [node selectors and tolerations](https://docs.airbyte.com/operator-guides/configuring-airbyte#jobs-1), we cannot use pod affinity rules, which limits our ability to use multiple AZs for redundancy as we have to hardcode the label value selecting a specific AZ.

Using pod affinity rules, we could use a label to match related pods (.e.g., `airbyte=job-pod`) to the same connection and topology key for AZ.

```yaml
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: airbyte
            operator: In
            values:
            - job-pod
        topologyKey: topology.kubernetes.io/zone
```

There may be another way to accomplish this that I'm missing.
