### ISSUE TITLE
[helm] worker pod is crashing after upgrading to 0.49.6+ (latest update: missing env variables. see reply for detail)

### ISSUE THREAD

**Issue by sc-yan** [airbytehq/airbyte#31988]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

helm 0.49.9

### What step the error happened?

Upgrading the Platform or Helm Chart

### Revelant information

when upgrading helm from 0.49.6 to 0.49.8/0.49.9, the worker pod keeps crashing. but if I reverted it back to 0.49.6, it's fine.

### Relevant log output

```shell
2023-10-31 00:57:57 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Error instantiating bean of type  [io.airbyte.workers.orchestrator.KubeOrchestratorHandleFactory]                                                                 │
│                                                                                                                                                                                                                                                                            │
│ Path Taken: new ApplicationInitializer() --> ApplicationInitializer.syncActivities --> List.syncActivities([ReplicationActivity replicationActivity],NormalizationActivity normalizationActivity,DbtTransformationActivity dbtTransformationActivity,NormalizationSummaryC │
│ io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.airbyte.workers.orchestrator.KubeOrchestratorHandleFactory]                                                                                                              │
│                                                                                                                                                                                                                                                                            │
│ Path Taken: new ApplicationInitializer() --> ApplicationInitializer.syncActivities --> List.syncActivities([ReplicationActivity replicationActivity],NormalizationActivity normalizationActivity,DbtTransformationActivity dbtTransformationActivity,NormalizationSummaryC │
│     at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367) ~[micronaut-inject-3.10.1.jar:3.10.1]                                                                                                                                    │
│     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305) ~[micronaut-inject-3.10.1.jar:3.10.1]                                                                                                                                            │
│     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251) ~[micronaut-inject-3.10.1.jar:3.10.1]                                                                                                                                            │
│     at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016) ~[micronaut-inject-3.10.1.jar:3.10.1]                                                                                                                                      │
│     at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80) ~[micronaut-inject-3.10.1.jar:3.10.1]                                                                                                                                                       
     at io.airbyte.workers.Application.main(Application.java:15) ~[io.airbyte-airbyte-workers-0.50.33.jar:?]                                                                                                                                                                │
│ Caused by: java.lang.IllegalArgumentException                                                                                                                                                                                                                              │
│     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131) ~[guava-31.1-jre.jar:?]                                                                                                                                                                  │
│     at io.airbyte.config.storage.DefaultS3ClientFactory.validateBase(DefaultS3ClientFactory.java:36) ~[io.airbyte.airbyte-config-config-models-0.50.33.jar:?]                                                                                                              │
│     at io.airbyte.config.storage.DefaultS3ClientFactory.validate(DefaultS3ClientFactory.java:31) ~[io.airbyte.airbyte-config-config-models-0.50.33.jar:?]                                                                                                                  │
│     at io.airbyte.config.storage.DefaultS3ClientFactory.<init>(DefaultS3ClientFactory.java:24) ~[io.airbyte.airbyte-config-config-models-0.50.33.jar:?]                                                                                                                    │
│     at io.airbyte.workers.storage.S3DocumentStoreClient.s3(S3DocumentStoreClient.java:59) ~[io.airbyte-airbyte-commons-worker-0.50.33.jar:?]                                                                                                                               │
│     at io.airbyte.workers.storage.StateClients.create(StateClients.java:27) ~[io.airbyte-airbyte-commons-worker-0.50.33.jar:?]                                                                                                                                             │
│     at io.airbyte.workers.config.ContainerOrchestratorConfigBeanFactory.kubernetesContainerOrchestratorConfig(ContainerOrchestratorConfigBeanFactory.java:91) ~[io.airbyte-airbyte-workers-0.50.33.jar:?]                                                                  │
│     at io.airbyte.workers.config.$ContainerOrchestratorConfigBeanFactory$KubernetesContainerOrchestratorConfig0$Definition.build(Unknown Source) ~[io.airbyte-airbyte-workers-0.50.33.jar:?]                                                                               │
│     at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354) ~[micronaut-inject-3.10.1.jar:3.10.1]                                                                                                                                    │
│     ... 81 more
```
```

**Comment by msaffitz** [comment]
We are seeing this error as well.  Downgrading to 0.49.6 fixed the issue for us.

**Comment by adamstrawson** [comment]
We're also experiencing this within GKE on the latest version `0.49.10`

**Comment by lydialimsetel** [comment]
Experiencing this same issue on latest V0.49.18. Downgraded to helm chart V0.49.5, works fine now.

**Comment by cappadona** [comment]
We're also running into this if we upgrade the chart past `0.49.6`

**Comment by joeybenamy** [comment]
Same issue with all charts after 0.49.6

**Comment by szemek** [comment]
After providing some environment variables in `values.yaml` I made it work. Here's how part of my configuration looks like

```
  ##  worker.extraEnv [array] Additional env vars for worker pod(s).
  ## Example:
  ##
  ## extraEnv:
  ## - name: JOB_KUBE_TOLERATIONS
  ##   value: "key=airbyte-server,operator=Equals,value=true,effect=NoSchedule"
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: AWS_ACCESS_KEY_ID
          name: airbyte-airbyte-secrets
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: AWS_SECRET_ACCESS_KEY
          name: airbyte-airbyte-secrets
    - name: STATE_STORAGE_S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: AWS_ACCESS_KEY_ID
          name: airbyte-airbyte-secrets
    - name: STATE_STORAGE_S3_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: AWS_SECRET_ACCESS_KEY
          name: airbyte-airbyte-secrets
    - name: STATE_STORAGE_S3_BUCKET_NAME
      value: ${STATE_STORAGE_S3_BUCKET_NAME}
    - name: STATE_STORAGE_S3_REGION
      value: ${STATE_STORAGE_S3_REGION}
```

Check here what environment variables you might be missing
https://github.com/airbytehq/airbyte-platform/blob/9ffa4e9f44f06e65fe3b138204367d5da8c98f2c/airbyte-config/config-models/src/main/java/io/airbyte/config/EnvConfigs.java#L133-L142

**Comment by sc-yan** [comment]
@szemek  thank you so much for the info! I followed your approach and and it worked! 
running 0.49.23 now. anyone who still has issues, please try the approach above. I'm gonna keep the issue open in case someone is looking for an answer. but please feel free to close it if you think no further action is needed.

**Comment by prafulauto1** [comment]
for maintaining state with S3. I was able to resolve it by simply adding these two environment variable :
extraEnv: 
    - name: STATE_STORAGE_S3_BUCKET_NAME
      value: ${airbyte_log_bucket}
    - name: STATE_STORAGE_S3_REGION
      value: ${airbyte_log_bucket_region}
      
    I could find this here- > https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-workers/src/main/resources/application.yml#L57-L58

**Comment by HatemLar** [comment]
Any idea on how to fix it on a EC2 deployment?

**Comment by sc-yan** [comment]
@HatemLar helm charts is supposed to be used in k8s. I assume you are deploying airbyte with docker/etc on EC2? trying to setup same env variables above following this guide.
https://docs.airbyte.com/deploying-airbyte/on-aws-ec2

**Comment by HatemLar** [comment]
@sc-yan thank you for your help!
Yes, deployed with docker on EC2, and we did follow that guide.
You think we should  declare these variables and in the instance or the docker-compose file?

**Comment by sc-yan** [comment]
@HatemLar  it really depends on how you want to manage your infra/deployment. generally, docker is acting like VM so the app is not supposed to read values from host machine(which is EC2 in your case), unless you want to mount some volume into docker. it's common to setup these env variables in docker-compose file, but if you do have special cases, feel free to adjust so.

**Comment by PurseChicken** [comment]
Using the below works (for GCS) since the values should likely already be in your configMap if you specified them in global.gcs:

```
    extraEnv:
      - name: STATE_STORAGE_GCS_BUCKET_NAME
        valueFrom:
          configMapKeyRef:
            key: GCS_LOG_BUCKET
            name: airbyte-airbyte-env
      - name: STATE_STORAGE_GCS_APPLICATION_CREDENTIALS
        valueFrom:
          configMapKeyRef:
            key: GOOGLE_APPLICATION_CREDENTIALS
            name: airbyte-airbyte-env
```

That fixes the worker pod issue, however then I ran into the following:

**Comment by lucasfcnunes** [comment]
> Using the below works (for GCS) since the values should likely already be in your configMap if you specified them in global.gcs:
> 
> ```
>     extraEnv:
>       - name: STATE_STORAGE_GCS_BUCKET_NAME
>         valueFrom:
>           configMapKeyRef:
>             key: GCS_LOG_BUCKET
>             name: airbyte-airbyte-env
>       - name: STATE_STORAGE_GCS_APPLICATION_CREDENTIALS
>         valueFrom:
>           configMapKeyRef:
>             key: GOOGLE_APPLICATION_CREDENTIALS
>             name: airbyte-airbyte-env
> ```
> 
> That fixes the worker pod issue, however then I ran into the following with `replication orchestrator`. This is not seen until you try to sync a connection.
> 
> #32203

`global.gcs.extraEnv` doesn't affect the templates.

**Comment by PurseChicken** [comment]
> > Using the below works (for GCS) since the values should likely already be in your configMap if you specified them in global.gcs:
> > ```
> >     extraEnv:
> >       - name: STATE_STORAGE_GCS_BUCKET_NAME
> >         valueFrom:
> >           configMapKeyRef:
> >             key: GCS_LOG_BUCKET
> >             name: airbyte-airbyte-env
> >       - name: STATE_STORAGE_GCS_APPLICATION_CREDENTIALS
> >         valueFrom:
> >           configMapKeyRef:
> >             key: GOOGLE_APPLICATION_CREDENTIALS
> >             name: airbyte-airbyte-env
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That fixes the worker pod issue, however then I ran into the following with `replication orchestrator`. This is not seen until you try to sync a connection.
> > #32203
> 
> `global.gcs.extraEnv` doesn't affect the templates.

What I wrote is specific to the worker key in values:

`worker.extraEnv`

**Comment by ilyasemenov84** [comment]
Is there a way to make it work with ISRA authentication (as + iam role)?

**Comment by marcosmarxm** [comment]
Hello all 👋 sorry the missing update here. I shared this with the engineering team and any update return here.

**Comment by booleanbetrayal** [comment]
Just to note that this appears to be the same solution to remediate #18016.

**Comment by raphaelauv** [comment]
I confirm that this is the current way to make it work `airbyte/worker:0.50.47`

```yaml

minio:
  enabled: false

worker:
  extraEnv:
    - name: STATE_STORAGE_S3_BUCKET_NAME
      value: "XXYYZZ"
    - name: STATE_STORAGE_S3_REGION
      value: "eu-west-3"

global:

  state:
    storage:
      type: "S3"
  logs:
    storage:
      type: "S3"
    minio:
      enabled: false
    s3:
      enabled: true
      bucket: "XXYYZZ"
      bucketRegion: "eu-west-3"
    accessKey:
      existingSecret: "airbyte-aws-creds"
      existingSecretKey: "AWS_ACCESS_KEY_ID"
    secretKey:
      existingSecret: "airbyte-aws-creds"
      existingSecretKey: "AWS_SECRET_ACCESS_KEY"

```

**Comment by StefanTUI** [comment]
I can confirm, the settings from @raphaelauv helped me to start the `worker` pods again.

I'm using helm chart '0.53.120` with 'airbyte/server:0.50.48`

The `server` pod runs, but had error messages like in the worker logs.

Adding the following in the in my yml helped to mitigate this:

```
server:
    extraEnv:
    - name: LOG4J_CONFIGURATION_FILE
      valueFrom:
        key: LOG4J_CONFIGURATION_FILE
        name: airbyte-env
```
