### ISSUE TITLE
Add `impactLimitedToScopes` to breaking change metadata (airbytehq/airbyte)

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#32932]
### Example: 
```
2.0.0:
  message: "This release introduces a default primary key for the streams UserLifetimeInsights and UserInsights. Additionally, the format of timestamp fields has been updated in the UserLifetimeInsights, UserInsights, Media, and Stories streams to include timezone information."
 impactLimitedToScopes:
   - scope_type: stream
     scope_values:
       - "user_lifetime_insights"
       - "user_insights"
       - "media"
       - "stories"
  upgradeDeadline: "2024-01-31"
```

`impactLimitedToScopes` is an optional field that allows the developer to define a list of scopes that a breaking change is specific to. If a developer provides scopes, users will only be notified about a breaking change and prompted to take action if they are affected by the scope. For example in the case of stream scope, they will only get the messaging if their actor is used in a connection that is syncing at least one of the streams. 

### Types 
`impactLimitedToScope`: `Optional[List[Scope]]`
`Scope`: class with the following properties 
  * scope_type: str
  * scope_values: List[str]
 
For now, we'll keep the scope values as a list of strings. In the future we might want to open this up to a more generalized Iterable - other scope types might want more composite information. Consider a `property` scope_type where the scope_values are a dict of [stream name, list[property_name]]. In that case we can either define a type for each of the scope value types, or do the validation hardcoded. The former is probably preferred as the platform will have to have types for this as well to resolve the impact scopes for processing. 

### Validations to consider 
1. `impactLimitedToScopes` list should not be empty (jsonschema)
2. `scope_type` is required on a scope (jsonschema)
3. `scope_values` is required and should be non-empty (jsonschema)
4. when `scope_type` is `stream`, strings in `scope_values` should all be in the list of streams defined by the connector (avoid typos, as this can cause accidental upgrades) (metadata validation)
5. (potentially) - we can warn or fail if the list of affected streams is the whole list of streams available. In this case we prefer if the user does not define `impactLimitedToScopes` as the impact cannot be limited in this way. (metadata validation)

**Comment by bnchrch** [comment]
grooming:
1. How do we make this discoverable?
2. How do we make this optional?
3. How do we name this so that its clear?
4. How do we allow for the additional of new filter dimensions?
5. Ella to come up with examples and pose them to the team
6. Most natural default is always apply
7. Do we need to consider dynamic streams (e.g. column type???)?
8. How does a dynamic stream declare itself?

Random possible defaults
```
breakingChange:
   1.0.0:
```

```
breakingChange:
   1.0.0:
       filters:
          streams:
               - "*"
```

```
breakingChange:
   1.0.0:
       affectedStreams:
           - a
           - b
           - c
```

```
breakingChange:
   1.0.0:
       affectsAllStreams: true
```

**Comment by erohmensing** [comment]
Compiled a list of different examples based on breaking changes that have already happened. Would love some async feedback on it @pedroslopez @alafanechere @bnchrch https://docs.google.com/document/d/1JJK3AvMPip1tHDThi00V8IB2wx_yQx1tTaP2jRuEoaY/edit#heading=h.yf06gvppvz6c

**Comment by erohmensing** [comment]
# Previous notes

## Plan

Add a new property to the `VersionBreakingChange` class in the [ConnectorReleases](https://github.com/airbytehq/airbyte/blob/38a189e829491995f027fc497a30b48d510fca03/airbyte-ci/connectors/metadata_service/lib/metadata_service/models/src/ConnectorReleases.yaml) class. 
```
      affectedStreams:
        type: array
        description: "An array of streams affected by this breaking change."
        items:
          type: string
        default: []
```

The property is not required (in the case that affected streams is not given, the assumption is made that all streams are affected). 

## Thoughts 

If we don't require the property, we risk someone not realizing the property exists and therefore making it affect all streams when we could have reduced the scope. 

A few other ideas: 
1. Make multiple properties, such as `affectsAllStreams: bool` and `affectedStreams`, where the first is required, and the second only required if the first is True. In this case it would be a requirement for the list to be non-empty. 
  a. This, to me, is clearer. However if we move toward more specifics such as looking at the config, or sync mode, etc., then it starts to get a bit verbose. 
2. Combine the above multiple properties in a similar manner: `affectsSpecificStreams` (req) which is either `False` or a non-empty list of specifically affected streams
3. Make the property required, and come up with a way to indicate that all streams are affected. In this case, the list must be non-empty, but could be just `["*"]` for example. 

If we do require the property we will have to go back and add this property to previous changes to ensure the registry can be built. Would we also need to backfill this in the platform DB?
