### ISSUE TITLE
[helm] `DATABASE_URL` ignored by Temporal pods

### ISSUE THREAD

**Issue by monik-a** [airbytehq/airbyte#32980]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

0.50.34

### What step the error happened?

Other

### Revelant information

We have the `externalDatabase.jdbcUrl` parameter used to enable SSL when Airbyte connects to its database. 
(cf. https://github.com/airbytehq/airbyte/issues/17995)

The main database is therefore covered. This however doesn't work for temporal components and their dbs (`temporal` and `temporal-visibility`).
I tried to inject the `DATABASE_URL` into the temporal container and it is present there as an env variable, but it is very much ignored when connection happens. There's also no variables I found in the doc that I could pass connection params to and have them respected.
I'm logging it as an issue, but if there's another way to enforce it, please let me know 🙏 

Cf. [this comment](https://github.com/airbytehq/airbyte/issues/30484#issuecomment-1724973011) too

**Comment by mrfzy00** [comment]
any update to related this issue?

**Comment by minyukim** [comment]
@monik-a @mrfzy00 Hello guys.
Have you ever tried below?
```yaml
temporal:
  extraEnv:
    - name: SQL_TLS
      value: "true"
    - name: SQL_TLS_DISABLE_HOST_VERIFICATION
      value: "true"
    - name: SQL_TLS_ENABLED
      value: "true"
    - name: SQL_HOST_VERIFICATION
      value: "false"
```
I had the same temporal SSL encryption problem, which is resolved by that configuration. (Refer: https://github.com/airbytehq/airbyte/issues/11157#issuecomment-1927515718)
