### ISSUE TITLE
Transient (Job sync) pods don't get populate labels from JOB_KUBE_LABELS env.

### ISSUE THREAD

**Issue by ilyasemenov84** [airbytehq/airbyte#33068]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

0.50.3

### What step the error happened?

During the Sync

### Revelant information

JOB_KUBE_LABELS exist in the configMap:
`JOB_KUBE_LABELS: component_id=data_app_airbyte1`
JOB_KUBE_LABELS env being populated as the env var in worker's deployment:
`JOB_KUBE_LABELS=component_id=data_app_airbyte1`
But the sync job pods (check source/destination, read, normalize, write, etc.) don't pick it up and it's missing in the POD's labels.

### Relevant log output

```shell
n/a
```

**Comment by kevin-astrafy** [comment]
I can confirm that the issue is still present in the latest airbyte version (0.57.3 as of today)

**Comment by ableev** [comment]
Same issue here, JOB_KUBE_LABELS doesn't work on jobs' pods

**Comment by yohannj** [comment]
Hi, using 0.50.56, i can confirm the issue. Here are my observations.

I have multiple labels and annotations set in the env vars of my workers (actual values renamed):
```sh
$ printenv | grep  -E -i -w 'JOB_KUBE_LABELS|JOB_KUBE_ANNOTATIONS'
JOB_KUBE_LABELS=labelA=valueA,labelB=valueB
JOB_KUBE_ANNOTATIONS=annotationA=valueA,annotationB=valueB
```

Running `kubectl describe pod airbyte-write-<id>-0-ybzmq` I can see the annotations are correctly set, while none of the labels in `JOB_KUBE_LABELS` are present.

Looking at the codebase, both annotations and labels are retrieved in a similar way [in the code](https://github.com/airbytehq/airbyte-platform/blob/7de218d4b443352da65ee04f4a449ab1335e2c68/airbyte-config/config-models/src/main/java/io/airbyte/config/EnvConfigs.java#L443), and the config looks correctly used later on.

One diff I can see is in the orchestrator which [doesn't seem to pick up on the labels](https://github.com/airbytehq/airbyte-platform/blob/v0.50.56/airbyte-container-orchestrator/src/main/resources/application.yml).
But still, even when disabling `containerOrchestrator`, the labels are not picked up.

**Comment by stevenmurphy12** [comment]
Seeing the same behaviour as @yohannj on v1.2.0 (annotations get set OK, labels are missing)

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by kevin-astrafy** [comment]
I encountered this problem and had to rely on a workaround to auto-inject missing labels at runtime with a hook. Does anybody know if this is fixed in version 1.6+ ?

**Comment by Anton-Shutik** [comment]
Not working on helm-chart: 2.0.18, app: 2.0.0

Here is my values:

```yaml
global:
  jobs:
    kube:
      labels:
        compute/run-on: fargate
```

Configmap contains this env var (which is ok and expected)

```
JOB_KUBE_LABELS: compute/run-on=fargate
```

And here is labels I really get on the pod, `compute/run-on: fargate` is not there for some reason

```
  labels:
    actor_type: source
    airbyte: job-pod
    attempt_id: "0"
    auto_id: 01184b08-380e-41e9-8f6e-8a57db8988e5
    connection_id: e99855c3-24c5-4815-a156-3b72ca9eaca7
    destination_image_name: destination-snowflake
    destination_image_version: 3.15.10
    job_id: "17176"
    job_type: sync
    mutex_key: e99855c3-24c5-4815-a156-3b72ca9eaca7
    orchestrator_image_name: container-orchestrator
    orchestrator_image_version: 2.0.0
    source_image_name: source-declarative-manifest
    source_image_version: 7.4.1
    sync_step: replication
    workload_id: e99855c3-24c5-4815-a156-3b72ca9eaca7_17176_0_sync
    workspace_id: f97a03fa-7fc7-459c-963e-e82aeeaf42ab
```
