### ISSUE TITLE
[Helm] Airbyte deploy with external database with existing secret failed to start bootloader

### ISSUE THREAD

**Issue by litaxc** [airbytehq/airbyte#33212]
### Helm Chart Version

0.50.7

### What step the error happened?

On deploy

### Revelant information

While deploy Airbyte with external database, and using external secrets to provide the connection credentials with the following `values.yaml`
```yaml
externalDatabase:
  host: "...rds.amazonaws.com"
  user: airbyteadmin
  existingSecret: "airbyte"
  existingSecretPasswordKey: "rds_password"
postgresql:
  enabled: false
```
After deployed with helm, `airbyte-airbyte-bootloader` container failed to start with kubelet error:
```
Error: couldn't find key DATABASE_PASSWORD in Secret namespace/airbyte-airbyte-secrets
```
this is probably related to #22094
