### ISSUE TITLE
Add CAT scenario that tests that all streams of a connector define a primary key

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#33329]
## Description

As the first new test that we are adding to the CAT framework, we want to use this issue to solve for two things:

- Standing up the necessary test fixtures, any new config reader code, and the overall structure in the repository for where the new tests will be defined and invoked from.
- The first test to serve as an example of how to implement new tests and future certification criteria tests can be modeled after the primary key check

## Implementation Details

Code Structure:

This can be defined in one of two ways:
- We incorporate new tests into their relevant existing base test class (`TestSpec`, `TestRead`, etc) - This can be nice because we don't explicitly associate functionality with certification criteria vs what is just a unit of functionality

```
discovery:
  tests:
    - config_path: secrets/config.json
      backward_compatibility_tests_config:
        disable_for_version: "1.1.0"
      streams_without_primary_key:
        - a_report_stream
```

- We create a new base test class `TestCertification` which will house the necessary tests - This makes it very explicit what is a certification test so it might be more obvious why something failed. But it does clutter the testing infra a little bit. It also requires that adding silver certification test need to update `acceptance-test-config.yml` and we need another test to verify that the config specifies this.

```
certification:
  tests:
    - streams_without_primary_key:
        - a_report_stream
```

When should tests be run?

- As an initial first pass, we are going to rely on reading the connector's `metadata.yaml` to figure out the quality level and compare that against whether a test is for silver certification. If they match then we run the test
- The reason why we're opting for this approach is because it doesn't require that we change either the `acceptance-test-config.yml` or the `metadata.yaml` to detect if silver tests need to be invoked (pending the above).

How to verify the stream has valid primary keys?

By calling a connector's `discover` method, we get back a catalog. For each stream in the catalog, there should be a field `source_defined_primary_key` which needs to contain a value. We should be able to validate this criteria w/o the need to 

## Acceptance Criteria:

- [ ] New fixtures are created which allow a test to derive whether it should be run based on its quality level.
- [ ] There is a new test that verifies that every stream for a connector contains a valid primary key
- [ ] Some streams don't make sense to have a primary key so the `acceptance-test-config.yml` must allow developers to specify certain streams to skip
- [ ] Tests should allow for `acceptance-test-config.yml` to support an override field to skip this test in the immediate to derisk this upfront
