### ISSUE TITLE
Set Refresh Request headers and params

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#33641]
## Context

A user has reported that they need to set a custom header on the refresh request that is performed in the OAuth authenticator.

Currently, the OAuth authenticator only allows a custom _body_ to be set for the Refresh Request, so the user is unable to use the OAuth authenticator for their use case.

To resolve this, we should allow request headers, and request parameters while we are at it, to be set for the refresh request.

Proposed additions to the `OAuthAuthenticator` component:
```
refresh_request_headers:
  anyOf:
    - type: string
    - type: object
       additionalProperties:
         type: string
refresh_request_parameters
  anyOf:
    - type: string
    - type: object
       additionalProperties:
         type: string
```
(copied from request_headers and request_parameters properties on HttpRequester)

## Acceptance Criteria
- Users can set custom headers and parameters on refresh requests
- An issue to update the Builder UI is created
