### ISSUE TITLE
Dynamically created Jobs pods do not have Kub Labels from Helm Chart values

### ISSUE THREAD

**Issue by sookeke** [airbytehq/airbyte#33867]
### Topic

Jobs pods Labels

### Relevant information

I am currently deploying Aribyte `0.50.38` on Kubernetes using the Helm Chart with Chart version 0.50.17. Within our Kubernetes environment, it is a requirement that every pod possesses a custom label. Upon inspection, I've observed that the pods created for jobs in both the test connection (source and destination connection), as well as the sync read-write pods, lack the labels specified in the Helm values configuration for the example below:
```
  jobs:

    .....

    kube:
      ## JOB_KUBE_ANNOTATIONS
      ## pod annotations of the sync job and the default pod annotations fallback for others jobs
      ##  jobs.kube.annotations [object] key/value annotations applied to kube jobs
      annotations: {}

      ## JOB_KUBE_LABELS
      ## pod labels of the sync job and the default pod labels fallback for others jobs
      ##  jobs.kube.labels [object] key/value labels applied to kube jobs
      labels:
         label1: test
         label2: airbyte-worker-pods

```
Do you know how I can inject custom labels to all async job pods that are dynamically created to job process? Thank you!
