### ISSUE TITLE
[metrics-reporter] `FRAME_SIZE_ERROR` on metrics export

### ISSUE THREAD

**Issue by moreiramarti** [airbytehq/airbyte#34374]
### Topic

metrics

### Relevant information

Hi,

I activated metrics recently and I have an error message during metrics export :
`SEVERE: Failed to export metrics. The request could not be executed. Full error message: FRAME_SIZE_ERROR: 4740180`

Is there a way to fix this ?

Thanks

**Comment by moreiramarti** [comment]
Hi,
Sorry for the delay, I'm using platform v0.50.48.
I only enable metrics deployment from helm chart.

```
airbyte:
  global:
    metrics:
      metricClient: "otel"
      otelCollectorEndpoint: http://prometheus-operator-prometheus.kube-system:9090/api/v1/otlp/v1/metrics
  metrics:
    enabled: true
```
