### ISSUE TITLE
Forward Temporal metrics to Datadog

### ISSUE THREAD

**Issue by MassyB** [airbytehq/airbyte#35211]
### Helm Chart Version

0.49.1

### What step the error happened?

Other

### Revelant information

👋 I’m trying to see Temporal metrics in Datadog.  According to this [PR](https://github.com/airbytehq/airbyte/pull/14842/files) it is now possible. 

In my org, we deployed Airbyte v0.50.30 on K8s and we already setup Datadog monitoring by modifying :

The values.yaml for the [workers](https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/values.yaml#L754)

```yaml
    - name: PUBLISH_METRICS
      value: "true"
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: DD_DOGSTATSD_PORT
      value: "8125"
    # Enable JVM metrics collection, profiling and code vulnerability detection
    - name: JAVA_OPTS
      value: "-javaagent:/app/dd-java-agent.jar -Ddd.iast.enabled=true"
    - name: DD_PROFILING_ENABLED
      value: "true"
```
In addition to the metrics client env variable [here](https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/values.yaml#L91)
```yaml
metrics:
    ## These parameters are used in the airbyte-env ConfigMap, which is then mounted in deployments in the airbyte-worker and airbyte-metrics Charts.
    ##  global.metrics.metricClient The metric client to configure globally. Supports "otel"
    metricClient: "datadog"
```

I can see the env variables in the `airbyte-metric` and `airbyte-worker` containers.

We are currently receiving in Datadog most of the metrics defined [here](https://github.com/airbytehq/airbyte-platform/blob/8fff5c7bc48451a0c371f5c16f816c2fe470ea23/airbyte-metrics/metrics-lib/src/main/java/io/airbyte/metrics/lib/OssMetricsRegistry.java#L34)

Questions: 

1. Is there some configuration I’m missing to get ALL the Temporal metrics defined in this [PR](https://github.com/airbytehq/airbyte/pull/14842/files)](https://github.com/airbytehq/airbyte/pull/14842/files)
2. Is there another way of getting those metrics in Datadog ?

**Comment by MassyB** [comment]
it's possible with  datadog's Temporal integration. 
### Useful documentation
1. dd temporal [integration](https://docs.datadoghq.com/integrations/temporal/) 
2. temporal prometheus [configuration](https://docs.temporal.io/references/configuration#prometheus) 


### Configuration
In our case we are deploying airbyte using helm and this configuration forwards the metrics to datadog

```yaml
### in airbyte-temporal/values.yaml
...
##  temporal.podAnnotations [object] Add extra annotations to the temporal pod
##
podAnnotations:
  ad.datadoghq.com/airbyte-temporal.checks: |
    {
      "temporal": {
        "instances": [{
            "openmetrics_endpoint": "http://%%host%%:9090/metrics"
        }]
      }
    }
```
```yaml
#### in airbyte-temporal/templates/deployment.yaml
imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- if eq .Values.global.deploymentMode "oss"}}
          - name: PROMETHEUS_ENDPOINT
            value: "0.0.0.0:9090"
....
```
