### ISSUE TITLE
[connector-builder ]Editing custom connector results in error immediately after saving

### ISSUE THREAD

**Issue by adc-cjewett** [airbytehq/airbyte#35770]
### Topic

Custom connector fails to load in UI builder immediately after saving

### Relevant information

The yaml spec below was generated using the Builder GUI. Immediately after saving I attempt to edit it and it runs into this error: 
```
Could not validate your connector as specified:

Unknown error (http.405.bCN27gfga8ZUFTDb2QCBFB)

If the error persists, please contact Airbyte support. 
```

You can view the yaml when editing but you can't switch tabs to the UI section or release a new version because of the error.

```
spec:
  type: Spec
  connection_specification:
    type: object
    $schema: http://json-schema.org/draft-07/schema#
    required: []
    properties: {}
    additionalProperties: true
type: DeclarativeSource
check:
  type: CheckStream
  stream_names:
    - Get
streams:
  - name: Get
    type: DeclarativeStream
    retriever:
      type: SimpleRetriever
      paginator:
        type: NoPagination
      requester:
        path: /public/crocodiles
        type: HttpRequester
        url_base: https://test-api.k6.io
        http_method: GET
        authenticator:
          type: NoAuth
        request_headers: {}
        request_body_json: {}
        request_parameters: {}
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_path: []
      partition_router: []
    primary_key: []
    schema_loader:
      type: InlineSchemaLoader
      schema:
        type: object
        $schema: http://json-schema.org/schema#
        properties:
          id:
            type: number
          age:
            type: number
          sex:
            type: string
          name:
            type: string
          date_of_birth:
            type: string
version: 0.65.0
metadata:
  autoImportSchema:
    Get: true

```
