### ISSUE TITLE
allow configurable kubernetes namespaces

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3636]
Allow a user to run Airbyte in a specific kubernetes namespace with minimal changes. Currently the launchers only use the default namespace.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200387300005647) by [Unito](https://www.unito.io)

**Comment by ecray** [comment]
I was able to deploy Airbyte to another namespace quite easily using Kustomize overlays:

# kube/overlays/stable/kustomization.yaml  
```
configMapGenerator:
  - name: airbyte-env
    envs:
      - .env

namespace: airbyte
```
