### ISSUE TITLE
Disk space is not released when syncs are finished (50Gb json.log file)

### ISSUE THREAD

**Issue by akoshterek** [airbytehq/airbyte#3665]
## Expected Behavior
json.log in airbyte-scheduler should not eat all the space

## Current Behavior
After some syncs I've noticed that disk space is not released. I've inspected docker volumes and found 50Gb $containerId-json.log file

```
root@airbyte:/var/lib/docker/containers/39193f243f242b08493ec98b17795582c96efac67d032b174d0126c1ff2b455e# du -s --block-size=1G *
50  39193f243f242b08493ec98b17795582c96efac67d032b174d0126c1ff2b455e-json.log
1   checkpoints
1   config.v2.json
1   hostconfig.json
1   hostname
1   hosts
1   mounts
1   resolv.conf
1   resolv.conf.hash
```

## Steps to Reproduce
Just run some significant size syncs

## Severity of the bug for you
Critical

## Airbyte Version
0.24.2-alpha

## Additional context
Slack thread https://airbytehq.slack.com/archives/C01MFR03D5W/p1622125807321400

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200392637650389) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
I'm pretty sure we need something like
```
my-app:
    image: my-app:latest
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
```

for all of our containers so the docker-compose logs don't grow indefinitely.
