### ISSUE TITLE
[secret-manager] Cannot enable AWS Secrets Manager for secret storage with existing connections

### ISSUE THREAD

**Issue by adam-bloom** [airbytehq/airbyte#36754]
### Helm Chart Version

0.62.0

### What step the error happened?

Other

### Revelant information

I added configuration to use AWS Secrets Manager for source/destination credentials to a deployment with existing connections. My assumption was that newly created connections would use secrets manager (which did indeed work!), while existing ones continued to use local storage until they were updated. The latter is where things went south.
1. I tried to update the credentials to get them to insert into secrets manager, but any updates to the source or destination failed with a 400 error from secrets manager
2. I tried to delete the source/destination to recreate it, but that also failed with a 400 error from secrets manager, since it couldn't delete a secret it hadn't created

I'm on airbyte 0.55.2.

The workaround was to try the delete, get the secret ID it wanted to delete, manually create it (remove the _v1 from the name), and then you can delete the source/destination.

This is very user unfriendly, and I believe an expected backward compatibility miss.

**Comment by marcosmarxm** [comment]
@adam-bloom I added this to the deployment team backlog for further investigation.
Can you share your values file (at least the part you're configuring the secret manager?)

**Comment by adam-bloom** [comment]
Here's the applicable section (this is from our template, so doesn't have the rendered values):
```
global:
  storage:
    type: s3
    bucket:
      log: ${s3_logs_bucket}
      state: ${state_bucket}
    s3:
      authenticationType: instanceProfile
      region: ${aws_region}
  secretsManager:
    type: awsSecretManager
    awsSecretManager:
      authenticationType: instanceProfile
      region: ${aws_region}
      kms: ${kms_key_arn}
```
