### ISSUE TITLE
Cannot find how to use an external Minio

### ISSUE THREAD

**Issue by francois-travais** [airbytehq/airbyte#36826]
### Helm Chart Version

0.64.0

### What step the error happened?

Upgrading the Platform or Helm Chart

### Revelant information

I'm using an external minio with Airbyte. I'm using Helm CHart 0.53.313 with success today. But I cannot upgrade to 0.64.0 and keeping the internal minio chart disabled, the property `global.logs.minio.enabled` is still in the configuration but is useless anymore.

**Comment by marcosmarxm** [comment]
Thanks for reporting @francois-travais I added the issue to the deployment team backlog for future invesgation. There are some work being done in this area hope we can get an update soon.

**Comment by aqeelat** [comment]
I'm highly interested in this as well.

I tried avoiding setting `global.storage.type: "minio"` because this will install the statefulset.

So far, this is what I have:
```
global:
  storage:
    type: "" 
    storageSecretName: "airbyte-config-secrets"

    bucket:
      log: "dev-airbyte-bucket"
      state: "dev-airbyte-bucket"
      workloadOutput: "dev-airbyte-bucket"
    s3:
      authenticationType: "credentials"
      accessKeyIdSecretKey: "minio-access-key"
      secretAccessKeySecretKey: "minio-secret-key"
    minio:
      endpoint: "http://minio.minio.svc.cluster.local"
```

However, I still cannot set S3_PATH_STYLE_ACCESS to true because it specifically checks the if type is equal to minio ([link](https://github.com/airbytehq/airbyte-platform/blob/4351d1404b7a60a5a716bb1af6d39eada4c1471a/charts/airbyte/templates/_helpers.tpl#L116-L118)).

I'm considering subcharting this and overriding the helper functions but I don't know if that will even work.
