### ISSUE TITLE
Cannot be able to see external logs on GCS

### ISSUE THREAD

**Issue by mkaramuk** [airbytehq/airbyte#37335]
### Helm Chart Version

0.64.139

### What step the error happened?

Other

### Revelant information

Use that values:
```yaml
global:
...
  logs:
    gcs:
       bucket: <bucket_name>
      credentialsJson: <base64 encoded json>
    storage:
      type: GCS
  state:
    gcs:
      bucket: <bucket_name>
      credentialsJson: <base64 encoded json>
    storage:
      type: GCS
  storage:
    gcs:
      bucket: <bucket_name>
      credentialsJson: <base64 encoded json>
    type: GCS
    bucket:
      log: <bucket_name>
      state: <bucket_name>
      workloadOutput: <bucket_name>
      activityPayload: <bucket_name>
...
worker:
...
  extraEnv:
    - name: STATE_STORAGE_GCS_BUCKET_NAME
      value: <bucket_name>
    - name: STATE_STORAGE_GCS_APPLICATION_CREDENTIALS
      value: /secrets/gcs-log-creds/gcp.json
    - name: CONTAINER_ORCHESTRATOR_SECRET_NAME
      value: 'airbyte-gcs-log-creds'
    - name: CONTAINER_ORCHESTRATOR_SECRET_MOUNT_PATH
      value: /secrets/gcs-log-creds/
...
```

The state saved to the bucket, but the logs are not.
