### ISSUE TITLE
Help Needed with Connecting S3 Storage to Airbyte Deployment

### ISSUE THREAD

**Issue by SharonDiskin** [airbytehq/airbyte#37548]
### Topic

S3 storage

### Relevant information

Hi,

I'm having trouble connecting an external S3 storage to my Airbyte deployment. I'm deploying Airbyte version 0.57.0 using the airbyte-0.63.18 chart, but it's not working. I keep encountering the following error:

`message='io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Running the launcher replication-orchestrator failed', type='java.lang.RuntimeException', nonRetryable=false.
`
Here are the Helm values I've set:
```
    global:
      storage:
        type: s3
        bucket:
          log: "${var.env_name}-sharon-airbyte-logs"
          state:  "${var.env_name}-sharon-airbyte-state"
          workloadOutput:  "${var.env_name}-sharon-airbyte-workflow-output"
          payloadActivity:  "${var.env_name}-sharon-airbyte-payload-activity"
        s3:
          region: us-east-2
          authenticationType: instanceProfile
        minio:
          enabled: false
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: ${var.service_account_iam_role}
```

I'm using a service account (the same one I use to pull Docker images successfully) without passing a key and secret. Can you help me figure out what I'm missing? Any help would be greatly appreciated!

Thank you!
