### ISSUE TITLE
Cannot pass environment variables to read and write pods

### ISSUE THREAD

**Issue by onurmus** [airbytehq/airbyte#38158]
### Helm Chart Version

0.53.3 and 0.64.388 

### What step the error happened?

During the Sync

### Relevant information

Hi! I need to pass HTTP_PROXY environment variables to my connector during sync. I add the environment variables to _extraEnv_ or _env_vars_ for the worker, global, and all the other sections in _values.yaml_ file. As a result, these variables are passed to check and discover pods but not passed to the orchestrator, read and write pods.  I checked the environment variables using `kubectl describe pod` and also tried squid proxy. I expect to see these variables in all pods. Here is an example configuration for worker in _values.yaml_:

``` 
env_vars:
    JOB_DEFAULT_ENV_HTTP_PROXY: loremIpsum
    JOB_DEFAULT_ENV_HTTPS_PROXY: loremIpsum
    JOB_DEFAULT_ENV_NO_PROXY: loremIpsum
    JOB_DEFAULT_ENV_JAVA_TOOL_OPTIONS: loremIpsum
extraEnv:
    - name: JOB_DEFAULT_ENV_HTTP_PROXY
      value: loremIpsum
......
```
