### ISSUE TITLE
SAT: Test for nested streams

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#3833]
## Tell us about the problem you're trying to solve
This test is a part of the incremental suite because it uses STATE.

The test should verify that child entity updated after date DT1 will be synced even if it belongs to a parent entity that was already synced. This test will probably need data populated in a specific way.

- Parent1 updated <= DT1
- Child1 updated <= DT1
- Child2 updated > DT1

The test needs to know which stream is a child and which is a parent. Something like this:
```yml
test_child_sync:
   - parent: user
      childs:
          - events
          - orders
   - parent: product
      childs:
          - colors
```
