### ISSUE TITLE
Temporal v1.23.0 fails to start with error: Unable to create SQL database, but v1.20.1 works fine.

### ISSUE THREAD

**Issue by ichait-bgl** [airbytehq/airbyte#38593]
### Helm Chart Version

0.60.1

### What step the error happened?

On deploy

### Relevant information

The issue is with the new temporal image temporalio/auto-setup:1.23.0: when deploying to EKS (with AWS RDS as host), temporal fails to connect with that error seen above.
Changing the image on the fly of the pod to the old image 1.20.1, temporal connects to the DB properly and does its job fine.
=> it seems that either the new image has an issue, or the helm chart is missing something to account for changes in the new image ?

### Relevant log output

```shell
ERROR	Unable to create SQL database.	{"error": "unable to connect to DB, tried default DB names: postgres,defaultdb, errors: [pq: no pg_hba.conf entry for host \"10.111.68.17\", user \"airbyte\", database \"postgres\", no encryption pq: no pg_hba.conf entry for host \"10.111.68.17\", user \"airbyte\", database \"defaultdb\", no encryption]", "logging-call-at": "handler.go:94"}
```

**Comment by marcosmarxm** [comment]
Can you provide steps of what are you trying to run?
Are you trying to connect your deployment to an external database or are you running the default helm install airbyte?

**Comment by ichait-bgl** [comment]
Thanks @marcosmarxm!

We receive the error as part of installing/upgrading the airbyte helm chart.
We are connecting to an external AWS RDS Postgres instance.
It should be noted that only Temporal has the issue connecting to the db. The other airbyte modules connect fine.

As an aside, another user also confirmed that downgrading Temporal to previous version fixed the issue ... [Airbyte-slack](https://airbytehq.slack.com/archives/C01AHCD885S/p1716473184500899?thread_ts=1716321472.479589&cid=C01AHCD885S)

Please let me know if you need any further info.

**Comment by marcosmarxm** [comment]
Thanks for the info @ichait-bgl I added the issue to the platform team backlog. Let's see if this impact more users to get a signal is something wrong.

**Comment by jkleinkauff** [comment]
@marcosmarxm we are facing the same issue after trying the upgrade from 0.54.15 to 0.293.4 (chart version).
Temporal section in values.yaml was left untouched:
```
temporal:
  replicaCount: 1
  extraEnv:
    - name: "SQL_TLS" 
      value: "true"
    - name: "SQL_TLS_DISABLE_HOST_VERIFICATION"
      value: "true"
    - name: "SQL_TLS_ENABLED"
      value: "true"
    - name: "SQL_HOST_VERIFICATION" 
      value: "false"
    - name: SKIP_DB_CREATE
      value: "true"
    - name: DBNAME
      value: temporal_db
    - name: VISIBILITY_DBNAME
      value: temporal_visibility_db
```
