### ISSUE TITLE
Deployment docs are lacking

### ISSUE THREAD

**Issue by aDingil** [airbytehq/airbyte#38796]
### Page URL
- https://github.com/airbytehq/airbyte/blob/5ceb14a91ef4c75b72cc46cf91267db6d54fdb68/airbyte-proxy/README.md

### Description

Is there any usable documation how to deploy airbyte with docker compose and ssl?
Most docs are just go to ip:port finished.
Even the proxy doc is pretty frustrating

Best case how to do it with traefik 

Still awesome project thx for your hard work

**Comment by aDingil** [comment]
with my current traefik setup i always get:
Gateway Timeout

```yml
  airbyte-api-server:
    image: airbyte/airbyte-api-server:${VERSION}
    logging: *default-logging
    container_name: airbyte-api-server
    restart: unless-stopped
    ports:
      - 8006:32890
    # ports:
    #   - "8006"
    environment:
      - AIRBYTE_API_HOST=${AIRBYTE_API_HOST}
      - AIRBYTE_VERSION=${VERSION}
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE}
      - INTERNAL_API_HOST=${INTERNAL_API_URL} # Non-ideal, but the existing URL can't have https:// added because it's used for nginx conf
      - LOG_LEVEL=${LOG_LEVEL}
      - MICROMETER_METRICS_ENABLED=${MICROMETER_METRICS_ENABLED}
      - MICROMETER_METRICS_STATSD_FLAVOR=${MICROMETER_METRICS_STATSD_FLAVOR}
      - SEGMENT_WRITE_KEY=${SEGMENT_WRITE_KEY}
      - STATSD_HOST=${STATSD_HOST}
      - STATSD_PORT=${STATSD_PORT}
      - TRACKING_STRATEGY=${TRACKING_STRATEGY}
    networks:
      - airbyte_internal
    depends_on:
      bootloader:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.airbyte-api-server.loadbalancer.server.port=8006"
      - "traefik.http.routers.airbyte-api-server.rule=Host(`REDACTED`)"
      - "traefik.http.routers.airbyte-api-server.entrypoints=websecure"
      - "traefik.http.routers.airbyte-api-server.tls.certresolver=myresolver" 
```

**Comment by aDingil** [comment]
i just used the api docs as a simple playground for my traefic setup

**Comment by aDingil** [comment]
fixed it:

main docker compose:
```yml
include:
- ../airbyte-pgvector/docker-compose.yaml
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      # - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
     # needs to access all networks 
    networks:
      - airbyte_internal
      - airbyte_public
      - default
```

within the airbyte docker compose adopt the proxy:
```yaml
  airbyte-proxy:
    image: airbyte/proxy:${VERSION}
    container_name: airbyte-proxy
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8003:8003"
      - "8006:8006"
    environment:
      # auth is handled by traefik and not by nginx/airbyte 
      # - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
      # - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - BASIC_AUTH_PROXY_TIMEOUT=${BASIC_AUTH_PROXY_TIMEOUT}
    networks:
      - airbyte_internal
      - airbyte_public
    depends_on:
      - webapp
      - server
      - airbyte-api-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.airbyte-proxy.loadbalancer.server.port=8000"
      - "traefik.http.routers.airbyte-proxy.rule=Host(``)"
      - "traefik.http.routers.airbyte-proxy.entrypoints=websecure"
      - "traefik.http.routers.airbyte-proxy.tls.certresolver=myresolver"
```
