### ISSUE TITLE
Custom Connector incremental sync creating duplicate rows

### ISSUE THREAD

**Issue by ShawnSack** [airbytehq/airbyte#39566]
### Topic

Connector built in Builder is creating duplicate rows

### Relevant information

I've created a custom connector in builder on oss that utilizes incremental sync to pull data using %Y%U as far back as 2017. My state is getting created correctly and shows 202423 for each object. However, every time I start a sync, it pulls beginning at 202401 and I end up with weeks of duplicate rows. (Actually, I'm just assuming it is pulling from 202401 as that is when the duplicates begin, I'm not sure how to see the individual calls.) See YAML below. 
Version: 0.50.54

```
spec:
  type: Spec
  connection_specification:
    type: object
    $schema: http://json-schema.org/draft-07/schema#
    required:
      - api_key
      - password
      - songlist
      - username
    properties:
      api_key:
        type: string
        order: 0
        title: API Key
        airbyte_secret: true
      country:
        type: string
        order: 1
        title: country
        default: US
      password:
        type: string
        order: 2
        title: password
        airbyte_secret: true
      songlist:
        type: string
        order: 3
        title: songList
      username:
        type: string
        order: 4
        title: username
    additionalProperties: true
type: DeclarativeSource
check:
  type: CheckStream
  stream_names:
    - song
streams:
  - name: song
    type: DeclarativeStream
    retriever:
      type: SimpleRetriever
      paginator:
        type: NoPagination
      requester:
        path: /api/isrc/data/{{ stream_partition.song.ISRC }}/song
        type: HttpRequester
        url_base: REDACTED
        http_method: POST
        authenticator:
          type: SessionTokenAuthenticator
          login_requester:
            path: auth
            type: HttpRequester
            url_base: REDACTED
            http_method: POST
            authenticator:
              type: NoAuth
            request_headers:
              X-API-Key: '{{ config[''api_key''] }}'
            request_body_data:
              password: '{{ config[''password''] }}'
              username: '{{ config[''username''] }}'
            request_parameters: {}
          session_token_path:
            - access_token
          expiration_duration: P1D
          request_authentication:
            type: ApiKey
            inject_into:
              type: RequestOption
              field_name: Authorization
              inject_into: header
        error_handler:
          type: CompositeErrorHandler
          error_handlers:
            - type: DefaultErrorHandler
              backoff_strategies:
                - type: ExponentialBackoffStrategy
                  factor: 1
            - type: DefaultErrorHandler
              response_filters:
                - type: HttpResponseFilter
                  action: IGNORE
                  http_codes:
                    - 400
                  error_message_contains: Additional permissions are required
        request_headers:
          X-API-Key: '{{ config[''api_key''] }}'
        request_body_json:
          country: '{{ config[''country''] }}'
        request_parameters: {}
      record_selector:
        type: RecordSelector
        extractor:
          type: DpathExtractor
          field_path: []
      partition_router:
        - type: ListPartitionRouter
          values: '{{ config[''songlist''] }}'
          cursor_field: song
    primary_key:
      - isrc
      - week_id
    schema_loader:
      type: InlineSchemaLoader
      schema:
        type: object
        $schema: http://json-schema.org/schema#
        properties:
          isrc:
            type: string
          genre:
            type: string
          Catalog:
            type: string
          country:
            type: string
          metrics:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                value:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: number
          week_id:
            type: number
          core_genre:
            type: string
          title_name:
            type: string
          addl_fields:
            type: object
            properties:
              ISRC:
                type: string
              Title:
                type: string
              Artist:
                type: string
              Collection:
                type: string
          artist_name:
            type: string
          release_date:
            type: string
          Audio Streams:
            type: number
          Video Streams:
            type: number
          Digital Tracks:
            type: number
          label_abbreviation:
            type: string
          Song w/SES On-Demand:
            type: number
          last_processing_date:
            type: string
          Streaming On-Demand Total:
            type: number
          Song w/SES On-Demand Audio:
            type: number
    transformations:
      - type: AddFields
        fields:
          - path:
              - isrc
            value: '{{ stream_partition.song.ISRC }}'
      - type: AddFields
        fields:
          - path:
              - addl_fields
            value: '{{ stream_partition.song }}'
      - type: AddFields
        fields:
          - path:
              - Audio Streams
            value: >-
              {% for metric in record.metrics %}{% if metric.name == "Streaming
              On-Demand Audio" %}{% for value in metric.value %}{% if value.name
              == "tp" %}{{ value.value }}{% endif %}{% endfor %}{% endif %}{%
              endfor %}
      - type: AddFields
        fields:
          - path:
              - Video Streams
            value: >-
              {% for metric in record.metrics %}{% if metric.name == "Streaming
              On-Demand Video" %}{% for value in metric.value %}{% if value.name
              == "tp" %}{{ value.value }}{% endif %}{% endfor %}{% endif %}{%
              endfor %}
      - type: AddFields
        fields:
          - path:
              - Song w/SES On-Demand
            value: >-
              {% for metric in record.metrics %}{% if metric.name == "Song w/SES
              On-Demand" %}{% for value in metric.value %}{% if value.name ==
              "tp" %}{{ value.value }}{% endif %}{% endfor %}{% endif %}{%
              endfor %}
      - type: AddFields
        fields:
          - path:
              - Song w/SES On-Demand Audio
            value: >-
              {% for metric in record.metrics %}{% if metric.name == "Song w/SES
              On-Demand Audio" %}{% for value in metric.value %}{% if value.name
              == "tp" %}{{ value.value }}{% endif %}{% endfor %}{% endif %}{%
              endfor %}
      - type: AddFields
        fields:
          - path:
              - Digital Tracks
            value: >-
              {% for metric in record.metrics %}{% if metric.name == "Digital
              Tracks" %}{% for value in metric.value %}{% if value.name == "tp"
              %}{{ value.value }}{% endif %}{% endfor %}{% endif %}{% endfor %}
      - type: AddFields
        fields:
          - path:
              - Streaming On-Demand Total
            value: >-
              {% for metric in record.metrics %}{% if metric.name == "Streaming
              On-Demand Total" %}{% for value in metric.value %}{% if value.name
              == "tp" %}{{ value.value }}{% endif %}{% endfor %}{% endif %}{%
              endfor %}
      - type: AddFields
        fields:
          - path:
              - Catalog
            value: '{{ stream_partition.song.Catalog }}'
    incremental_sync:
      step: P1W
      type: DatetimeBasedCursor
      cursor_field: week_id
      end_datetime:
        type: MinMaxDatetime
        datetime: '{{ now_utc().strftime(''%Y-%m-%dT%H:%M:%SZ'') }}'
        datetime_format: '%Y-%m-%dT%H:%M:%SZ'
      start_datetime:
        type: MinMaxDatetime
        datetime: '201702'
        datetime_format: '%Y%U'
      datetime_format: '%Y%U'
      start_time_option:
        type: RequestOption
        field_name: week_id
        inject_into: body_json
      cursor_granularity: P1W
      cursor_datetime_formats:
        - '%Y%U'
version: 0.65.0
metadata:
  autoImportSchema:
    song: true

```
