### ISSUE TITLE
[helm] Heating 429 Too Many Requests on orchestrator-repl-job pods

### ISSUE THREAD

**Issue by AronsonDan** [airbytehq/airbyte#42091]
### Helm Chart Version

0.293.4

### What step the error happened?

Upgrading the Platform or Helm Chart

### Relevant information

During the upgrade to the new `0.293.4` helm chart im getting:
```
Failed to pull image "airbyte/container-orchestrator:0.63.8": failed to pull and unpack image "docker.io/airbyte/container-orchestrator:0.63.8": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry1.docker.io/v2/airbyte/containerorchestrator/manifests/sha256:f2277e78343406ff9adddcb13b79078893e747ec3ef2353b7510c60c0a637e22: 429 Too Many Requests -Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

In my values, i set the following:
```
    jobs:
        main_container_image_pull_secret: "dockerhub-secret"
  worker:
    image:
      repository: 143653229561.dkr.ecr.us-east-1.amazonaws.com/docker-hub/airbyte/worker
    containerOrchestrator:
      image: 143653229561.dkr.ecr.us-east-1.amazonaws.com/docker-hub/airbyte/container-orchestrator:0.63.8
  workload-launcher:
    image:
      repository: 143653229561.dkr.ecr.us-east-1.amazonaws.com/docker-hub/airbyte/workload-launcher
    containerOrchestrator:
      image: 143653229561.dkr.ecr.us-east-1.amazonaws.com/docker-hub/airbyte/container-orchestrator:0.63.8
```

Im using ecr pull through cache so i wont have the docker server throttling issue.

When im looking at the `airbyte-env` config map, I see the following value:
`CONTAINER_ORCHESTRATOR_IMAGE: 143653229561.dkr.ecr.us-east-1.amazonaws.com/docker-hub/airbyte/container-orchestrator:0.63.8`

But when `orchestrator-repl-job` are starting they appear with the following image: `image: airbyte/container-orchestrator:0.63.8`

On top of that, when I set `main_container_image_pull_secret: "dockerhub-secret"` i would have expected the pull to be made using my docker hub credentials which is not happenning:
```
- name: JOB_KUBE_MAIN_CONTAINER_IMAGE_PULL_SECRET                                                                                                                  
   value: dockerhub-secret
```

Would love to get your help on that :-)
