### ISSUE TITLE
Platform Chart changes to Temporal Deployment causing TLS issues.

### ISSUE THREAD

**Issue by PurseChicken** [airbytehq/airbyte#43328]
### Helm Chart Version

0.399.0

### What step the error happened?

On deploy

### Relevant information

The Temporal Deployment manifest was [changed](https://github.com/airbytehq/airbyte-platform/commit/4731a0b246eb9767ec61faf211097c8f0f68fb5b) to assume that TLS\SSL is needed if using an external Database:

```
        {{- if eq .Values.global.database.type "external" }}
        # Assume an external database requires SSL.
          - name: POSTGRES_TLS_ENABLED
            value: "true"
          - name: POSTGRES_TLS_DISABLE_HOST_VERIFICATION
            value: "true"
          - name: SQL_TLS_ENABLED
            value: "true"
          - name: SQL_TLS_DISABLE_HOST_VERIFICATION
            value: "true"
        {{- end }}
```

This causes significant issues when using, for example, a sidecar Proxy which does not require TLS.

We should not be making an assumption here. In my opinion, there should be a key value pair in values which enables \ disables TLS\SSL if required in the deployment.

E.G.

```
temporal:
  enabled: true
  externalSSL: false
```

### Relevant log output

```shell
[Fx] Error returned: received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider
	/home/builder/temporal/temporal/fx.go:180:
sql schema version compatibility check failed: pq: SSL is not enabled on the server
```

**Comment by chulkilee** [comment]
Hitting this issue as well. Please do not make assumptions without making it configurable.

**Comment by film42** [comment]
@davinchia Can we get a fix for this? This broke the helm chart.

**Comment by davinchia** [comment]
Hi everyone, thanks for the feedback, and sorry for the inconvenience.

Curious, why are folks setting this field? This doesn't do anything except enable Temporal SSL on the backend, and is more of an experimental flag we are testing internally. Unsetting this should fix this for everyone.

**Comment by film42** [comment]
I didn’t set any flag, I think. It failed when I upgraded the helm chart version.

**Comment by PurseChicken** [comment]
> Hi everyone, thanks for the feedback, and sorry for the inconvenience.
> 
> Curious, why are folks setting this field? This doesn't do anything except enable Temporal SSL on the backend, and is more of an experimental flag we are testing internally. Unsetting this should fix this for everyone.

What field are you referring to? .Values.global.database.type?

The issue here is that if .Values.global.database.type is set to external, then automatically the Temporal deployment gets specific TLS environment variables applied which is causing issues. I believe most of us who are running into issues are using external databases and setting .Values.global.database.type to external.

**Comment by film42** [comment]
For the moment I deploy the helm chart and manually edit the airbyte-temporal so the following envs are `"false"`:

```
        - name: POSTGRES_TLS_ENABLED
          value: "false"
        - name: SQL_TLS_ENABLED
          value: "false"
```

If you're using something like kustomize you might be able to apply a patch to do this but the stack I have using Airbyte isn't set up that way. Hoping to see this issue fixed soon.

**Comment by marcosmarxm** [comment]
Hello all 👋 sorry the lack of updates. I asked the platform team to take a look into https://github.com/airbytehq/airbyte-platform/pull/361 any return from them I'm going to update here.

**Comment by PurseChicken** [comment]
Just checking in on this issue. This is still a problem in v1.1.1 of the helm chart. This is preventing us from updating.

Thank you

**Comment by PurseChicken** [comment]
As a workaround to this issue, you can set ".Values.global.database.type" to internal, and then the TLS environment variables will not be added to the temporal deployment.

I looked pretty heavily through the charts manifests, and currently it seems only the temporal deployment references the ".Values.global.database.type" key in values. If that key is ever used elsewhere in the future this could be problematic though.. but for now as a workaround you can set it to the default of internal. I do feel strongly that this should still be tied to something more specific and not by an assumption.

**Comment by kev-datams** [comment]
@PurseChicken the problem is that we want to use an external database without SSL, as the `CloudSQL Auth Proxy` (GCP) is already managing the TLS/SSL natively

**Comment by PurseChicken** [comment]
> [@PurseChicken](https://github.com/PurseChicken) the problem is that we want to use an external database without SSL, as the `CloudSQL Auth Proxy` (GCP) is already managing the TLS/SSL natively

You can still do so even with setting ".Values.global.database.type" to internal. Fortunately, as of now the chart does not use that value for anything other than setting the TLS environment variables on the temporal deployment.

By no means am I saying this is a fix. This should definitely not be the way. That said, since that key is only used for the temporal deployment, setting it to internal has no other affect. External databases can still be used (Or CloudSQL proxy etc). Its merely a workaround.

**Comment by kev-datams** [comment]
@PurseChicken you mean we can set `values.yaml` like this:
```
postgresql:
  enabled: false

global:
  database:
    type: internal
    secretName: "airbyte-config-secrets"
    host: "x.x.x.x"
    port: 5432
    database: "airbyte"
    userSecretKey: "database-user"
    passwordSecretKey: "database-password"
```

and it will use the `external` database ? 🤔 

Also, do you already managed to set up an external db using the Cloud SQL Proxy on a GCP VM ?

Thanks

**Comment by PurseChicken** [comment]
@kev-datams, Sorry for the delay.


You are correct. even if you set .Values.global.database.type to internal, it will still use an external database. The only thing that is currently set by that key is the TLS configuration on the temporal deployment.


This is how I have configured it for CloudSQL Proxy using IAM credentials (Workload Identity)
_P.S. Not sure if externalDatabase section is required anymore either_

```
global:
  database:
    type: "internal" 
    host: "cloud-sql-proxy"
    port: "5432"
    database: "airbyte"
    user: "my-service@my-project.iam"
    password: "notreal"
postgresql:
  enabled: false
externalDatabase:
  host: "cloud-sql-proxy"
  user: "my-service@my-project.iam"
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: ""
  database: "airbyte"
  port: "5432"
  jdbcUrl: ""
```

Yes I have used Airbyte using cloudSQL proxy both as a sidecar to each pod as well as just a separate pod that was deployed along side the airbyte deployment. In the most recent versions of the Airbyte helm chart its been harder to use the sidecar approach, so moving to a separate pod deployment has been better \ easier.

**Comment by kev-datams** [comment]
@PurseChicken thanks ! please could you share your YAML of the CloudSQLProxy ? 🙏 

few complementary questions:
- was it mandatory to bind the IAM SA with the K8 SA ?
- did you use the `--auto-iam-authn` flag in the Proxy pod ?

Thanks :)

**Comment by PurseChicken** [comment]
@kev-datams If you want to use Workload Identity for authentication into cloudSQLProxy, then yes the K8's SA needs to be bound to the IAM SA:

role: roles/iam.workloadIdentityUser
Members: serviceAccount:my-project.svc.id.goog[my-namespace/my-k8s-service-account]

Also the IAM SA needs to have CloudSQL Client and CloudSQL Instance User GCP roles.

Finally, yes, I use --auto-iam-authn on the proxy pod.

If you have more questions about this setup, please message me directly. Lets not litter the original issue with this conversation.

Thanks!

**Comment by PurseChicken** [comment]
@kev-datams I use Argo for deployment. So I either sync the pod  and service first or add an annotation which sync's those resources before anything else. That's how I make sure the pod is running first. Then everything else works. In your case it shows your hostname not existing, So the name is either wrong, or the service is not deployed yet.

I never had to mess with abctl so I can't comment on that.

**Comment by PurseChicken** [comment]
@stemarks I think that .Values.externalDatabase might now be left over from a previous way to configure things. I also am not finding reference to that key in any of the templates.

That said, deploying airbyte does require temporal databases if you have temporal enabled (which I believe it is by default). You can control what the database names are in .Values.temporal:

```
temporal:
  enabled: true

  ## Example:
  ##
  ## extraEnv:
  ## - name: SAMPLE_ENV_VAR
  ##   value: "key=sample-value"
  # -- Additional env vars for temporal pod(s).
  extraEnv:
    - name: DBNAME
      value: "airbyte-temporal"
    - name: VISIBILITY_DBNAME
      value: "airbyte-temporal-visibility"
    - name: SKIP_DB_CREATE
      value: "true"
```

I use "SKIP_DB_CREATE" with the value of true so that the chart does not try to create these databases, They are created using IaC as part of the overall airbyte deployment (external to the airbyte chart).
