### ISSUE TITLE
Log Level - Docker

### ISSUE THREAD

**Issue by panhavad** [airbytehq/airbyte#4386]
## Tell us about the problem you're trying to solve
The verbose in the terminal display during docker-compose is overwhelm.

It would be great to have more control over those verbose, like enable the change of log level on each component (airbyte-server, airbyte-temporal)

## Describe the solution you’d like
- Log level setting could be managed/change from the Environment Variable. (INFO, DEBUG, WARNING, CRITICAL, FATAL)
- The option is available for all component of Airbyte, especially Airbyte server and Airbyte Temporal

**Comment by panhavad** [comment]
My suggestion is that if this LOG_LEVEL is stick in docker-compose.yaml it will be so flexible for integration with other application. The variable can be change to anything we want.

**Comment by marcosmarxm** [comment]
@panhavad the idea is to have an enviroment variable and you can choose which level do you want:
https://github.com/airbytehq/airbyte/blob/0f171a11f74350e498fa3293026f97a8f9468242/.env#L39

@davinchia do you think that #4365 closes this issue?

**Comment by panhavad** [comment]
> the idea is to have an environment variable and you can choose which level do you want:
@marcosmarxm Understood, it would be more dynamic if we import the value through docker-compose.yaml like other variables.
It would look like this .env -> docker-compose.yaml -> untilize_in_code

**Comment by davinchia** [comment]
@panhavad that was my bad, I forgot to include this for docker as well, do so here: https://github.com/airbytehq/airbyte/pull/4498.

I do think Temporal is noisy and can be reduced. Unfortunately this is running the official Temporal image, so we don't control it directly. Configuring Temporal is pretty low down our priority list, so we won't get to this in the next couple of weeks. Would you be willing to figure this out? Definitely would appreciate contributions.

I think this can be done as a separate ticket to this one, which can be closed by the PR I am about to merge.

**Comment by panhavad** [comment]
@davinchia Thank you for the update. I still did not get the LOG_LEVEL to work smoothly. Sometime even I change the LOG_LEVEL to ERROR but still it shown INFO log of airbyte-scheduler on terminal.

And for temporal, I have check it source code and feel like by default the temporal postgres that airbyte using we can pass LOG_LEVEL in environment too:
```
...
airbyte-temporal:
    image: temporalio/auto-setup:1.7.0
    logging: *default-logging
    container_name: airbyte-temporal
    restart: unless-stopped
    ports:
      - 7233:7233
    environment:
      - DB=postgresql
      - DB_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PWD=${DATABASE_PASSWORD}
      - POSTGRES_SEEDS=${DATABASE_HOST}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - LOG_LEVEL=ERROR
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
     ...
   ``` 

I have try LOG_LEVEL info, debug and error seem like it was working. We might not have to do custom configure for temporal because by default seem like they accept LOG_LEVEL too.
If you think this could help, I can make a quick Merge Request for your team to check and verify.
