### ISSUE TITLE
[platform] unknown object type "nil" in ConfigMap.data.CONNECTOR_SIDECAR_IMAGE

### ISSUE THREAD

**Issue by BenGalewsky** [airbytehq/airbyte#44171]
### Helm Chart Version

0.429.0

### What step the error happened?

On deploy

### Relevant information

I'm deploying to plan kubernetes cluster (docker desktop) - I'm starting with a minimal `values.yaml`. 

```yaml
global:
  # -- The URL where Airbyte will be reached; This should match your Ingress host
  airbyteUrl: "https://localhost"

  secretsManager:
    awsSecretManager:
      authenticationType: ""
  storage:
    s3:
      authenticationType: ""

  # -- Auth configuration
  auth:
    # -- Whether auth is enabled
    enabled: false

workload-launcher:
  connectorSidecar:
    image: "sidecar"
  containerOrchestrator:
    image: "orch"
  workloadInit:
    image: "sss"
```

My first attempt resulted in an error:
```
Error: template: airbyte/charts/workload-launcher/templates/deployment.yaml:341:15: executing "airbyte/charts/workload-launcher/templates/deployment.yaml" at <eq ((((.Values.global).secretsManager).awsSecretManager).authenticationType) "credentials">: error calling eq: incompatible types for comparison
```
I added the settings for `global.secretsManager` to get past that error.

No matter what, I can't get past the errors in `env-configmap.yaml` - I would think explicitly setting the values in `workload-launcher` would prevent the unknown object type, but it seems to be expecting it from somewhere else...

This issue is related to a [thread in slack](https://airbytehq.slack.com/archives/C021JANJ6TY/p1722973078617399)

### Relevant log output

```shell
Error: failed pre-install: unable to build kubernetes object for pre-install hook airbyte/templates/env-configmap.yaml: error validating "": error validating data: [unknown object type "nil" in ConfigMap.data.CONNECTOR_SIDECAR_IMAGE, unknown object type "nil" in ConfigMap.data.CONTAINER_ORCHESTRATOR_IMAGE, unknown object type "nil" in ConfigMap.data.WORKLOAD_INIT_IMAGE]
helm.go:81: [debug] failed pre-install: unable to build kubernetes object for pre-install hook airbyte/templates/env-configmap.yaml: error validating "": error validating data: [unknown object type "nil" in ConfigMap.data.CONNECTOR_SIDECAR_IMAGE, unknown object type "nil" in ConfigMap.data.CONTAINER_ORCHESTRATOR_IMAGE, unknown object type "nil" in ConfigMap.data.WORKLOAD_INIT_IMAGE]
```
