### ISSUE TITLE
[abctl] documentation for external database is not updated

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#45408]
### What happened?

https://docs.airbyte.com/deploying-airbyte/integrations/database says you can create a secret for host, user and database, something like:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: airbyte-config-secrets
type: Opaque
stringData:
  # Database Secrets
  ## database-host: ## e.g. database.internal
  ## database-port: ## e.g. 5432
  ## database-name: ## e.g. airbyte
  ## database-user: ## e.g. airbyte
  database-password: ## e.g. password
```

and then the create a values.yaml
```yaml
postgresql:
  enabled: false

global:
  database:
    # -- Secret name where database credentials are stored
    secretName: "" # e.g. "airbyte-config-secrets"

    # -- The database host
    host: ""
    # -- The key within `secretName` where host is stored 
    #hostSecretKey: "" # e.g. "database-host"

    # -- The database port
    port: ""
    # -- The key within `secretName` where port is stored 
    #portSecretKey: "" # e.g. "database-port" 

    # -- The database name
    database: ""
    # -- The key within `secretName` where the database name is stored 
    #databaseSecretKey: "" # e.g. "database-name" 

    # -- The database user
    user: ""
    # -- The key within `secretName` where the user is stored 
    #userSecretKey: "" # e.g. "database-user"

    # -- The key within `secretName` where password is stored
    passwordSecretKey: "" # e.g."database-password"
```

Replacing the `database` variable for `databaseSecretKey`.
The problem is the chart doesn't handle port/database or user.
See example for port:
https://github.com/airbytehq/airbyte-platform/blob/10eb8ca320d36d46fc598abfaa7145ebe1e250ef/charts/airbyte/templates/_database.tpl#L32-L40

### What did you expect to happen?

Docs show correct method to deploy Airbyte using external database.

### Abctl Version

.

### Docker Version

.

### OS Version

.
