### ISSUE TITLE
Unclear documentation regarding local file source connector

### ISSUE THREAD

**Issue by Joly0** [airbytehq/airbyte#45645]
### What happened?

Hey, i have just installed airbyte using the abctl command on a windows vm. I want to add a local folder so i can add that as a source for local files.
The problem here is, that the documentation is talking about configs in the .env file, but that is when using the docker-compose approach which, according to the documentation, is the old way to do it and the new and recommended way is abctl instead. But i have not found any way using the abctl approach to add a local folder as a source.

### What did you expect to happen?

A clear and concise documentation how to add a local source folder to airbyte using abctl

### Abctl Version

<details>

```console
$ abctl version
version: v0.15.1
```

</details>

### Docker Version

<details>

```console
$ docker version
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:17:17 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.34.1 (166053)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

### OS Version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here

# On Mac:
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
Invalid GET Expression.

The correct command is:
wmic os get Caption,Version,BuildNumber,OSArchitecture
Output is:
BuildNumber  Caption                                 OSArchitecture  Version
20348        Microsoft Windows Server 2022 Standard  64-bit          10.0.20348
```

</details>

**Comment by techieshark** [comment]
I had this issue as well (unclear how to access the CSV files or if even possible); I reported in Slack with some discussion there - https://airbytehq.slack.com/archives/C021JANJ6TY/p1726562874434619 

Another user reported that the "files are written on destination connector pod file system, but data are gone when synchronization is done"

**Comment by Joly0** [comment]
Thanks @techieshark i am trying to get into the slack, but it keeps complaining that i need an invitation.

**Comment by techieshark** [comment]
@Joly0 I suspect you got in but just in case, here's where to get info about airbyte slack https://airbyte.com/community/community

**Comment by bgroff** [comment]
Following up here, support for writing to a local filesystem is currently not functioning. We have a plan to fix that issue, but it is currently not at the top of the priority list.

Thumbs up this post if this is a critical feature for you and that will help us rank this issue higher.

**Comment by yogesch** [comment]
How incredibly inconvenient. It is so nicely documented but doesn't actually work. Wasted a half day to discover this... Guys, please...

**Comment by yogesch** [comment]
> [@bgroff](https://github.com/bgroff) I think it's a rather big issue. We wanted to evaluate airbyte for our use case, and obviously the very first thing we tried was streaming to local, and were immediately hit by this.
> 
> Could you add a word of warning to the documentation to at least warn that it's currently broken, please?

Exactly the same problem. Many people want to self-deploy.

**Comment by szemek** [comment]
I found a way to make it work :slightly_smiling_face:

Create values.yaml with a configuration like this:

```yaml
global:
  jobs:
    local:
      volume:
        enabled: true
```

Run `abctl local install --values values.yaml`

Set context for kubectl

Install kubectx + kubens (https://github.com/ahmetb/kubectx)
Execute commands:
```
mkdir -p ~/.kube
KUBECONFIG=~/.airbyte/abctl/abctl.kubeconfig kubectl config view --flatten > ~/.kube/config
kubectx kind-airbyte-abctl
kubens airbyte-abctl
```

Restart deployment `kubectl rollout restart deployment airbyte-abctl-workload-launcher`

Create `pv.yaml` with a definition:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airbyte-local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /var/local-path-provisioner/airbyte-local
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem 
```

And create `pvc.yaml` with a definition

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbyte-local-pvc
  namespace: airbyte-abctl
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: airbyte-local
```

Apply changes `kubectl apply -f pv.yaml -f pvc.yaml`

In Local JSON destination connector I set Destination Path to `/data` (for source connector I used Faker)

After running synchronization I found data in `~/.airbyte/abctl/data/airbyte-local/`

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.

**Comment by pramodbiligiri** [comment]
A slight variation of the @szemek approach above worked for me, probably because the [V2 version](https://github.com/airbytehq/airbyte-platform/blob/v2.0.0/charts/v2/airbyte/values.yaml) of airbyte's values.yaml is different from the [V1 version](https://github.com/airbytehq/airbyte-platform/blob/v1.8.0/charts/airbyte/values.yaml). Tested with the Motherduck destination connector (couldn't get DuckDB destination connector to work).

values.yaml (injected via `abctl local install --low-resource-mode --volume=~/.airbyte/abctl/data/airbyte-duckdb:/local --values=values.yaml`):
```
global:
  jobs:
    kube:
      localVolume:
        enabled: true
```

pv.yaml:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airbyte-local
spec:
  accessModes:
    - ReadWriteMany # Changed from ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /local # Changed to /local
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
```

pvc.yaml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbyte-local-pvc
  namespace: airbyte-abctl
spec:
  accessModes:
    - ReadWriteMany # Changed from ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: airbyte-local
```

The above are applied through `kubectl apply -f`
