### ISSUE TITLE
[helm] Job tolerations are ignored

### ISSUE THREAD

**Issue by joeybenamy** [airbytehq/airbyte#45903]
### Helm Chart Version

1.0.0

### What step the error happened?

On deploy

### Relevant information

On prior versions of the Helm Chart, tolerations set in Helm values are properly propagated to the job pods.  In the new version, the tolerations in Helm values are not added to the job pods.  As a result, our jobs cannot be scheduled.

In Helm values:
```
global:
  jobs:
    kube:
      tolerations:
      - key: "usage"
        operator: "Equal"
        value: "airbyte"
        effect: "NoExecute"
      nodeSelector:
        usage: airbyte
```

From the job pods:
```
  nodeSelector:
    usage: airbyte
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```

### Relevant log output

> Pod airbyte/source-postgres-check-16279-1-tefxt can't be scheduled on eks-airbyte-uat-20240307203630429500000001-d4c70d50-dd55-3f1f-3a66-11baf39a636f, predicate checking error: node(s) had untolerated taint {usage: airbyte}; predicateName=TaintToleration; reasons: node(s) had untolerated taint {usage: airbyte}; debugInfo=taints on node: []v1.Taint{v1.Taint{Key:"usage", Value:"airbyte", Effect:"NoExecute", TimeAdded:<nil>}}
