### ISSUE TITLE
[helm] Template not using secret keys to recover Host, Port and Database

### ISSUE THREAD

**Issue by matheusnd** [airbytehq/airbyte#45949]
### Helm Chart Version

1.0.0

### What step the error happened?

On deploy

### Relevant information

Values file:
```yaml
postgresql:
  enabled: false

global:  
  database:
    type: external
    secretName: airbyte-config-secrets
    portSecretKey: database-port
    databaseSecretKey: database-host
    userSecretKey: database-user
    passwordSecretKey: database-password
```

This deploy is failing due to the missing keys: `host`, `port` and `database`
If the secret keys are define, it was supposed to get from the secret instead of the values file.

### Relevant log output

```shell
Error: INSTALLATION FAILED: execution error at (airbyte/templates/env-configmap.yaml:34:6): You must set `global.database.port` when using an external database
```
```
