### ISSUE TITLE
helm values from global.metrics are not mapped to pods

### ISSUE THREAD

**Issue by AurimasNav** [airbytehq/airbyte#46701]
### Helm Chart Version

1.1.0

### What step the error happened?

Other

### Relevant information

values.yaml
```yaml
global:
  metrics:
    metricClient: otel
    otelCollectorEndpoint: http://opentelemetry-collector.opentelemetry:4317
```

it seems that this value is used in [configMap](https://github.com/airbytehq/airbyte-platform/blob/36c4046ea6f0669ba9a0c3272bc9299b7869b7ff/charts/airbyte/templates/env-configmap.yaml#L137-L138)

but I don't see it anywhere on [airbyte-server,](https://github.com/airbytehq/airbyte-platform/blob/36c4046ea6f0669ba9a0c3272bc9299b7869b7ff/charts/airbyte-server/templates/deployment.yaml#L61) or [airbyte-cron](https://github.com/airbytehq/airbyte-platform/blob/36c4046ea6f0669ba9a0c3272bc9299b7869b7ff/charts/airbyte-cron/templates/deployment.yaml#L58)

### Relevant log output

```shell
from airbyte-server or other relevant pods:

> 2024-10-10 07:22:39 WARN i.a.m.l.MetricClientFactory(initialize):72 - MetricClient was not recognized or not provided. Accepted values are `datadog` or `otel`.
```
