### ISSUE TITLE
[source-intercom] Update conversation stream schema

### ISSUE THREAD

**Issue by scalauser4** [airbytehq/airbyte#47745]
### Connector Name

intercom

### Connector Version

0.8.1

### What step the error happened?

During the sync

### Relevant information

I'm reaching out to request an enhancement to the Intercom Source Connector. Currently, the conversation stream does not include ticket information available in Intercom's API response from the listconversations endpoint. This ticket object provides additional context to conversations, which is crucial for our workflows.

Here’s a link to the relevant Intercom documentation: [listconversations API endpoint](https://developers.intercom.com/docs/references/2.9/rest-api/api.intercom.io/conversations/listconversations)

`Suggested Update`

Would it be possible to add the ticket schema to the conversation stream in the manifest.yaml file? Below is an example schema that defines the properties of ticket, as they appear in the Intercom API.

```

ticket:
  description: Details related to the ticket.
  type:
    - "null"
    - object
  properties:
    type:
      description: The type of the ticket
      type:
        - "null"
        - string
    id:
      description: Unique identifier for the ticket
      type:
        - "null"
        - integer
    url:
      description: URL link to the ticket in Intercom
      type:
        - "null"
        - string
    custom_attributes:
      description: Custom attributes associated with the ticket
      type:
        - "null"
        - object
    state:
      description: The current state of the ticket
      type:
        - "null"
        - string
    ticket_type:
      description: The type of the ticket
      type:
        - "null"
        - string
    ticket_type_description:
      description: Description of the ticket type
      type:
        - "null"
        - string
    ticket_type_emoji:
      description: Emoji representing the ticket type
      type:
        - "null"
        - string
    ticket_custom_state_admin_label:
      description: Custom state label for the ticket (admin view)
      type:
        - "null"
        - string
    ticket_custom_state_user_label:
      description: Custom state label for the ticket (user view)
      type:
        - "null"
        - string
```

Benefit

Including the ticket information in the conversation stream would provide valuable insight into the status and type of conversations, helping us to analyze and manage tickets effectively within our Intercom integration.

Thank you for considering this request. Please let me know if I can assist with any further details.

### Contribute

- [x] Yes, I want to contribute
