### ISSUE TITLE
Universal File Transfer: Raw File Copying in Airbyte

### ISSUE THREAD

**Issue by Hesperide** [airbytehq/airbyte#48463]
### Relevant information

# Introducing Universal File Transfer: Raw File Copying in Airbyte

Airbyte's current data movement methods involve parsing individual records, which is not suitable for transferring unstructured text data, non-text data, or compressed files. There is a need for a capability that allows copying raw files without parsing their contents.

Starting in version 1.2+ of Airbyte, we now support copying raw files in Airbyte without parsing their contents. This capability is in early access, and currently only available for moving data from the "SFTP Bulk" or "S3" sources to the "S3" destination. Bits are copied into the destination exactly as they appeared in the source. This is recommended for use with unstructured text data, non-text and compressed files. We currently support copying files up to 1GB in size. This is an entirely new way of moving data through Airbyte, as all pre-existing data movement methods involved parsing individual records.

In the future, we expect to support the following sources and destinations for universal file transfer. Please request additional connectors if this capability is required for your use case:
* Sources: SFTP Bulk, S3, GCS, Azure Blob Storage, Google Drive and SharePoint
* Destinations: S3, GCS and Azure Blob Storage

![Image](https://github.com/user-attachments/assets/960ae00f-0e12-4b08-a967-54dd7fd5ca71)

## Implementation

![Image](https://github.com/user-attachments/assets/df476eeb-0ff0-4076-9313-911012cbe140)

Airbyte's file transfer capability is implemented in the File Connector Development Kit (CDK). We leverage the file CDK's ability to write the source data locally, and emit a new record message with metadata related to the file. Attached is an example record passed through the Airbyte platform, which points to the location of the source data:

```yaml
{
  "type": "RECORD",
  "record": {
    "stream": "simpsons_locations",
    "file": {
      "file_url": "/tmp/airbyte-file-transfer/sftp-testing-for-file-transfer/sftp-folder/simpsons_locations.csv",
      "bytes": 182776,
      "file_relative_path": "sftp-testing-for-file-transfer/sftp-folder/simpsons_locations.csv",
      "modified": 1728330963000,
      "source_file_url": "//sftp-testing-for-file-transfer/sftp-folder/simpsons_locations.csv"
    },
    "emitted_at": 1730226374632,
    "data": {}
  }
}
```

## Feedback Requested

This feature is available as of Airbyte version 1.2+ in early access. If you attempt to copy raw files in an older version of the Airbyte platform, your sync will fail. Feedback and testing are encouraged to improve this functionality and support in future releases. 

Areas of planned improvement are:
* Supporting new sources and destinations.
* Supporting larger files (e.g. 5 GB, 10 GB+ per file).
* Emitting multiple state messages per file (checkpointing on partial file progress).

**Please leave feedback in the comments. Thank you for your continued support, and we look forward to hearing your feedback on file transfers in Airbyte!**
