### ISSUE TITLE
Minimal Postgres Version Supported as External Database

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#48542]
### Helm Chart Version

-

### What step the error happened?

Other

### Relevant information

The [documentation External Database](https://docs.airbyte.com/deploying-airbyte/integrations/database) do not inform users what is the minimal and maximum version supported. This can cause confusion to users.

### Relevant log output

```shell

```

**Comment by joeybenamy** [comment]
This would be helpful for us.  We are looking for info on Postgres 17 support.

**Comment by PrestonBlackburn** [comment]
I did some minimal testing with various Postgres versions on AWS RDS for the external database. Here are the results:

|  Postgres Version |  Test Status  |
| -------------- | ------------ |
| 12.19  |  Passed |
| 13.15  |  Passed |
| 14.12  |  Passed |
| 15.7    | Passed  |
| 16.3    | Passed  |
| 17.1    | Passed  |


For the tests, I just checked to see if the helm chart would deploy and then if I could create an connect a Snowflake destination.


### Setup:
**Helm Chart Version: 1.3.0**

`values.yaml`
(just the changes)
```yaml
postgresql:
  enabled: false

global:
  database:
    type: "external"
    secretName: "airbyte-config-secrets"
    host: "<rds db name>.<rds id>.<rds region>.rds.amazonaws.com"
    port: "5432"
    database: "airbyte"
    userSecretKey: "database-user"
    passwordSecretKey: "database-password"
```
`secrets.yaml`
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: airbyte-config-secrets

type: Opaque
stringData:
  database-user: postgres
  database-password: my_password
```

*Note*
Sometimes the helm install command would fail - and it seems like it was due to timeout issues, since if I ran the command again it would succeeed. I'd recommend increasing the timeout if you run into this issue, ex:
```bash
helm install release-1 airbyte/airbyte -f values.yaml --timeout 10m0s
```

I also needed to create the Airbyte databases before deploying the helm charts
```sql
CREATE DATABASE airbyte WITH OWNER = postgres;
CREATE DATABASE temporal WITH OWNER = postgres;
CREATE DATABASE temporal_visibility WITH OWNER = postgres;
```
