### ISSUE TITLE
Cannot use Airbyte on Kubernetes due to OOM when setting up connector

### ISSUE THREAD

**Issue by jomach** [airbytehq/airbyte#48816]
### Helm Chart Version

1.2.0

### What step the error happened?

During the Sync

### Relevant information

Hi, I deployed Airbyte on K8 with default values.yaml. Deployment works and I can login. When I try to add a postgres or a databricks destination the step of checking if everything works fails.  The problem is that the resources are not respected from the values.yml: 

```
  jobs:
    resources:
      ## Example:
      ## requests:
      ##    memory: 256Mi
      ##    cpu: 250m
      # -- Job resource requests
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 1Gi
```

From what I understood the values of jobs.resources are passed into the vars JOB_MAIN_CONTAINER_MEMORY_REQUEST etc. But these are being ignored by airbyte when it spawns the pods. 

### Relevant log output

```shell
kubectl describe pod gives me: 


   State:          Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Thu, 05 Dec 2024 08:19:47 +0100
      Finished:     Thu, 05 Dec 2024 08:19:50 +0100
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1100m
      memory:  256Mi
    Requests:
      cpu:     10m
      memory:  1Mi
    Environment:
      AIRBYTE_VERSION:                 1.2.0
      AIRBYTE_ROLE:
      DEPLOYMENT_MODE:                 OSS
      USE_RUNTIME_SECRET_PERSISTENCE:  false
      OPERATION_TYPE:                  check
      WORKLOAD_ID:                     072d5540-f236-4294-ba7c-ade8fd918496_e1032a7c-f92d-4460-86a3-164bff86258f_0_check
    Mounts:
      /config from airbyte-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tj4gr (ro)
```

**Comment by jomach** [comment]
In the meantime, this is really a deal breaker. I think there is a bug in the Java issue

**Comment by jomach** [comment]
@marcosmarxm  you were the only one that reacted. Do you have the same issue ?

**Comment by DatameshJulia** [comment]
We were able to solve this problem by taking a deep dive into the source code. Apparently Airbyte uses a different environment variable for each of the different processes like connector check, discovery and so forth. Setting the Variables mentioned in the documentation  [Configuring Airbyte](https://docs.airbyte.com/operator-guides/configuring-airbyte) only sets the resource limits and requests for the actual connection. 
Therefore, when creating an new source connector and executing the check these values are not used and Kubernetes falls back to the cluster specific limits defined with a Kubernetes limitrange. Hence, having low a low cluster limitrange leads to the OOM error.

Setting all of the following variables solved the issue for us:

```yml
# values.yaml
global:
  env_vars:
    JOB_MAIN_CONTAINER_CPU_REQUEST: ...
    JOB_MAIN_CONTAINER_CPU_LIMIT: ...
    JOB_MAIN_CONTAINER_MEMORY_REQUEST: ...
    JOB_MAIN_CONTAINER_MEMORY_LIMIT: ...
    CHECK_JOB_MAIN_CONTAINER_CPU_REQUEST: ...
    CHECK_JOB_MAIN_CONTAINER_CPU_LIMIT: ...
    CHECK_JOB_MAIN_CONTAINER_MEMORY_REQUEST: ...
    CHECK_JOB_MAIN_CONTAINER_MEMORY_LIMIT: ...
    DISCOVER_JOB_MAIN_CONTAINER_CPU_REQUEST: ...
    DISCOVER_JOB_MAIN_CONTAINER_CPU_LIMIT: ...
    DISCOVER_JOB_MAIN_CONTAINER_MEMORY_REQUEST: ...
    DISCOVER_JOB_MAIN_CONTAINER_MEMORY_LIMIT: ...
    SPEC_JOB_MAIN_CONTAINER_CPU_REQUEST: ...
    SPEC_JOB_MAIN_CONTAINER_CPU_LIMIT: ...
    SPEC_JOB_MAIN_CONTAINER_MEMORY_REQUEST: ...
    SPEC_JOB_MAIN_CONTAINER_MEMORY_LIMIT: ...
    SIDECAR_MAIN_CONTAINER_CPU_REQUEST: ...
    SIDECAR_MAIN_CONTAINER_CPU_LIMIT: ...
    SIDECAR_MAIN_CONTAINER_MEMORY_REQUEST: ...
    SIDECAR_MAIN_CONTAINER_MEMORY_LIMIT: ...
```

It would be very helpful to add one default variable for cpu und memory requests and limit to which all of the above can default, if not set individually. 

Also please add a hint in the documentation that there are more than just the `JOB_MAIN_*` variables
