### ISSUE TITLE
Airbyte does not correctly manage secrets in AWS Secrets Manager nor correctly setup login credentials when aws credentials are set in secret.yml

### ISSUE THREAD

**Issue by giacomochiarella** [airbytehq/airbyte#50975]
### Topic

aws secrets login

### Relevant information

I've deployed Airbyte 1.3.0 version using this command
```
RELEASE_TAG=v1.3.0 bash abctl_install.sh
abctl local install --low-resource-mode --no-browser --secret secret.yml --values value.yml
```
the secret.yml is the following
```
apiVersion: v1
kind: Secret
metadata:
  name: airbyte-config-secrets
type: Opaque
stringData:
  instance-admin-email: "email@domain.com"
  instance-admin-password: "mypassword"
  aws-secret-manager-access-key-id: "<aws key id>"
  aws-secret-manager-secret-access-key: "<aws secret key>"
```
the value.yml is the following
```
global:
  secretsManager:
    type: awsSecretManager
    secretName: "airbyte-config-secrets"
    awsSecretManager:
      region: eu-west-1
      authenticationType: credentials
      tags:
        - key: airbyte_managed
          value: true
  auth:
    enabled: true
    instanceAdmin:
      emailSecretKey: "instance-admin-email"
      secretName: "airbyte-config-secrets"
      passwordSecretKey: "instance-admin-password"
```
When I add a source/destination, Airbyte creates 2 secrets in AWS Secrets Manager.
If I change a secret of a source/destination it recreates a new secret.
If I retest without changing the secret if does not recreate it.
If I schedule for deletion all the secrets but the newest one and I retest the source/destination connection the I get this error:
```
Internal message: Init container error encountered while processing workload for id: 25c5221d-dce2-4163-ade9-739ef790f503_036a655a-44de-4fed-bbed-5c44e5cd8b38_0_check. Encountered exception of type: class com.amazonaws.services.secretsmanager.model.InvalidRequestException. Exception message: You can't perform this operation on the secret because it was marked for deletion. (Service: AWSSecretsManager; Status Code: 400; Error Code: InvalidRequestException; Request ID: a60aae16-ff9c-4e59-b5ec-196041423703; Proxy: null).
Failure origin: airbyte_platform
```
If I delete a source/destination, secrets in aws secrets manager are not deleted nor scheduled for deletion.
Moreover, when aws credentials are added in the secret.yml, Airbyte does not take login email and password from the secret.yml, it always creates a random password without any email. If I open Airbyte in the browser it shows the user creation page where I can insert my email but not the password (the password I need is the random one created by Airbyte). In order to setup my login credentials I need to run `abctl local credentials --email=email@domain.com --password=mypassword` after the installation
