### ISSUE TITLE
[source-custom] OffetIncrement is not sent on first request even when inject_on_first_request is set to true

### ISSUE THREAD

**Issue by comtef** [airbytehq/airbyte#51505]
### Connector Name

source-custom

### Connector Version

6.17.0

### What step the error happened?

During the sync

### Relevant information

When using a custom connector based on no code configuration (YAML), the Offset pagination does not work anymore.
The Offset is not sent on first request even when inject_on_first_request is set to true.

```
pagination_strategy:
            type: OffsetIncrement
            page_size: 10000
            inject_on_first_request: true
```

It seems related to an upgrade of airbyte/source-declarative-manifest (to version 6.17.0) that includes CDK changes related to pagination (https://github.com/airbytehq/airbyte-python-cdk/commit/0e7802a4c485355d8d5abaa5f23b48b682dc4eb7)

I couldn't find any workaround, none of the following options seems possible:

- Manually forcing a version of airbyte/source-declarative-manifest
- Set a default value of the offset parameter in request options (triggers a duplicate parameter error in the builder)

### Relevant log output

```shell

```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Can you share the complete YAML file for the connector @comtef ?

The latest version of pagination is:
```yaml
          pagination_strategy:
            type: OffsetIncrement
            page_size: 10
```
For the page limit you don't need to inject to first request as it always insert the page size.
