### ISSUE TITLE
Airbyte deployed with abctl does not have any logs in any container in /tmp/

### ISSUE THREAD

**Issue by giacomochiarella** [airbytehq/airbyte#52029]
### What happened?

I’ve added this configuration to the value.yml
```
server:
  extraVolumeMounts:
    - name: logs
      mountPath: /tmp/workspace
  extraVolumes:
    - name: logs
      hostPath:
        path: /tmp/airbyte/logs/server
        type: DirectoryOrCreate
worker:
  extraVolumeMounts:
    - name: logs
      mountPath: /tmp/workspace
  extraVolumes:
    - name: logs
      hostPath:
        path: /tmp/airbyte/logs/worker
        type: DirectoryOrCreate
```
and I’ve installed Airbyte using
`abctl local install --low-resource-mode --no-browser --secret secret.yml --values value.yml`
but I cannot see any log coming in the host folder.
I’ve logged in into the container also using
`kubectl --kubeconfig ~/.airbyte/abctl/abctl.kubeconfig --namespace airbyte-abctl exec -i -t airbyte-abctl-server-64fdbc9897-bkgq7 -- /bin/bash`
but I don’t see any log neither if I execute ls -la /tmp in the container.
I've tried the same thing by adding /tmp/airbyte_internal instead of /tmp/workspace but the outcome is the same.
Am I missing something? Where are the logs saved? Should I enable anyhow?

### What did you expect to happen?

I expect logs are written into files in /tmp/workspace or /tmp/airbyte_internal

### Abctl Version

<details>

```console
$ abctl version
# paste output here
```

</details>

### Docker Version

<details>

```console
$ docker version
# paste output here
version: v0.24.0
```

</details>

### OS Version

<details>

```
# On Mac:
$ uname -a
# paste output here
Darwin Kernel Version 24.2.0: Fri Dec  6 18:41:43 PST 2024; root:xnu-11215.61.5~2/RELEASE_X86_64 x86_64
```

</details>
