### ISSUE TITLE
[api-sources] Inconsistencies with source > custom report names

### ISSUE THREAD

**Issue by Rykarix** [airbytehq/airbyte#52082]
### Connector Name

LinkedIn Ads v5.1.1, Facebook Marketing v3.3.26

### Connector Version

LinkedIn Ads v5.1.1, Facebook Marketing v3.3.26

### What step the error happened?

None

### Relevant information

I've set up custom reports for the following Source Connectors.
- Bing Ads v2.8.10
- LinkedIn Ads v5.1.1
- Facebook Marketing v3.3.26
- Google Ads v3.7.10

Each of these sources has a custom defined report/query/insight. This has been named: `paid_budget`

For each connection, I've also set up a custom prefix in the settings: `linkedinads_, facebookads_, bingads_, googleads_`

These are the following outputs in the schema:
- `bingads_paid_budget` for Bing Ads 
- `googleads_paid_budget` for Google Ads
- `linkedin_custom_paid_budget` for LinkedIn Ads
- `facebookads_custompaid_budget` for Facebook Marketing

Notice the naming convention for linkedin and facebook. 

I did not ask you to put `custom_` for linkedin, or `custom` for facebook.

Please fix this

### Relevant log output

```shell

```

### Contribute

- [ ] Yes, I want to contribute

**Comment by Rykarix** [comment]
Linkedin Issue location: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-linkedin-ads/source_linkedin_ads/manifest.yaml
Line: 1448
```yaml
      components_mapping:
        - type: ComponentMappingDefinition
          field_path: ["**", "name"]
          value: "custom_{{components_values['name']}}"
```
