### ISSUE TITLE
[Feature Request] - Extend functionality of custom table prefix name by adding it as a text input to advanced settings

### ISSUE THREAD

**Issue by Rykarix** [airbytehq/airbyte#53615]
### Topic

Extend all connectors with 'custom' functionality to be named as users want

### Relevant information

Feature request to 1. solve [this issue](https://github.com/airbytehq/airbyte/issues/52082#issuecomment-2648057487), 2. extend functionallity to users

Allow users to modify the prefix name of all connectors in the UI like so:

yaml integration:
```yaml
      components_mapping:
        - type: ComponentMappingDefinition
          field_path: ["**", "name"]
          value: "custom_{{components_values['name']}}"
```
to
```yaml
      components_mapping:
        - type: ComponentMappingDefinition
          field_path: ["**", "name"]
          value: "custom_{{components_values['name']}}"
          custom_table_prefix_default: "custom_"
```

py integration:
```py
            stream = AdsInsights(
                api=api,
                account_ids=config.account_ids,
                name=f"Custom{insight.name}",
```
to
```py
            stream = AdsInsights(
                api=api,
                account_ids=config.account_ids,
                name=f"{insight.name}",
                custom_table_prefix_default="Custom"
```

Then allow users to change it in UI:

![Image](https://github.com/user-attachments/assets/fc865ef5-2a41-4fe2-b382-d088f301965d)
