### ISSUE TITLE
Review schema changes 504 timeout error

### ISSUE THREAD

**Issue by GamesmenJordan** [airbytehq/airbyte#55690]
### Helm Chart Version

1.3.1

### What step the error happened?

None

### Relevant information

Requests to `/api/v1/web_backend/connections/get` timeout with 504 error

In the logs it is showing that the client disconnected, but I am unable to effectuate any config that increases the timeout beyond 60 seconds.

`"POST /api/v1/web_backend/connections/get HTTP/1.1" 499`

Ingress configuration:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airbyte-ingress
  namespace: airbyte
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/issuer: lets-encrypt
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
...
```

Application is running on DigitalOcean, this loadbalance has also been configured with an extended timeout:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-http-idle-timeout-seconds: "600"
...
```
Airbyte config also has extended timeouts, though it's unclear if these are required:
```yaml
server:
  extraEnvs:
    - name: HTTP_IDLE_TIMEOUT
      value: 600s
    - name: READ_TIMEOUT
      value: 600s
```

It's not clear to me what else would be configured with a hard 60 seconds timeout that hasn't already been reconfigured for 600 seconds.

### Relevant log output

```shell

```

**Comment by polo4096** [comment]
Hello there, did you resolve your issue ?

I have extanded timeouts too but it doesn't seem to resolve it.

for Helm v2
```
server:
  httpIdleTimeout: 20m
  extraEnv:
    - name: READ_TIMEOUT
      value: 30m
```
