### ISSUE TITLE
[kubernetes/helm] Allow authentication to AWS using roles

### ISSUE THREAD

**Issue by i-yordanova** [airbytehq/airbyte#5942]
## Tell us about the problem you're trying to solve

Current version of Airbyte I tested (v0.29.15-alpha) requests providing access key Id and secret access key in all cases where authentication for AWS is required. 

## Describe the solution you’d like

It would be good to allow using roles instead i.e provide the option to use either/whichever works for the user.

## Describe the alternative you’ve considered or used
N/A

## Additional context
N/A

**Comment by marcosmarxm** [comment]
thanks for the suggestion @i-yordanova. Is it something critical or blocks your use of the Airbyte?

**Comment by miguel-firebolt** [comment]
Thanks for submitting this @i-yordanova! @marcosmarxm we are looking at deploying Airbyte at Firebolt and this is a potential blocker for us deploying Airbyte while following our security best practices.

**Comment by i-yordanova** [comment]
@marcosmarxm Yes, in a way it is  for similar security concerns mentioned by @miguel-firebolt

**Comment by cgardens** [comment]
## What we want
Affects S3 (source and destination) & Redshift in both Docker and K8s. Need to allow falling back on Airbyte instance-level roles.

## Current workaround
Use a service account. 

@i-yordanova would using a service account work for your use case?

**Comment by ChristopheDuong** [comment]
THis seems similar to the work provided to BigQuery case here: On google, a user submitted this PR a while back: https://github.com/airbytehq/airbyte/pull/3947

**Comment by i-yordanova** [comment]
@cgardens I was thinking it's probably as simple as making the `secret_access_key` and `access_key_id` optional and if missing using `ProfileCredentialsProvider` instead of the `BasicAWSCredentials` one but then I am having trouble testing that out locally

**Comment by cgardens** [comment]
yeah. so i have to open question here that i have not had time to look into
1. how does instance-level role propagate (if at all) into docker / k8s.
2. how do we present this to the user intuitively. they will have to know that account the airbyte instance has access somehow. for anyone who didn't set up airbyte themselves this will be opaque. we will also want to change the configuration model to be clear about using a service account or the instance-level role.

**Comment by i-yordanova** [comment]
@cgardens the 2nd point seem more like a strategic/design decision more than anything. We are getting to a point where this is a blocker and I was hoping to get some approximation how much work and time this would require and it seems more complicated than expected.

Just noticed you mentions `S3 (source and destination) & Redshift` as "components" affected by the change but wanted to note that it's also `Snowflake` destination when using S3 staging

**Comment by pgovind** [comment]
> For both the Java and Python SDKs, it should be enough to just build the service client without any creds when they are not specified by the user, and it will search for creds to use as per:
> Java https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html

I just tried doing this locally on an EC2 instance. I changed `S3StreamCopier.java` to use 
```java
    if (endpoint.isEmpty()) {
      return AmazonS3ClientBuilder.standard()
          .withCredentials(new InstanceProfileCredentialsProvider(true))
          .withRegion(s3Config.getRegion())
          .build();

    } else {
...
```
S3DestinationConfig.java to 
```java
    if (endpoint == null || endpoint.isEmpty()) {
      return AmazonS3ClientBuilder.standard()
          .withCredentials(new InstanceProfileCredentialsProvider(true))
          .withRegion(bucketRegion)
          .build();
    }
...
```
and S3Destination.java to:
```java
  @Override
  public AirbyteConnectionStatus check(final JsonNode config) {
    try {
      S3StreamCopier.attemptS3WriteAndDelete(S3Config.getS3Config(config), config.get("s3_bucket_path").asText());
      return new AirbyteConnectionStatus().withStatus(Status.SUCCEEDED);
    } catch (final Exception e) {
      LOGGER.error("A CHANGE: Exception attempting to access the S3 bucket: ", e);
      return new AirbyteConnectionStatus()
          .withStatus(AirbyteConnectionStatus.Status.FAILED)
          .withMessage("Could not connect to the S3 bucket with the provided configuration. \n" + e
              .getMessage());
    }
  }
```

I had to comment out a few failing tests (could be unrelated, couldn't quite tell from the errors) but I eventually got a build. However I don't think the built bits are being used at all. I'm following these instruction from https://docs.airbyte.io/contributing-to-airbyte/developing-locally:
```
SUB_BUILD=PLATFORM ./gradlew build
VERSION=dev docker-compose up
```

When I attempt to add a new S3 destination, I get an error saying `Could not connect to the S3 bucket with the provided configuration....`. What's more interesting is that I see this in the console:
```
airbyte-worker      | 2021-11-01 19:46:24 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):62 - {ActivityId=555b669c-24ce-36b1-8f78-79e3060cb9c7, ActivityType=Run, Namespace=default, RunId=7156f9f4-301f-40c5-9b9f-2824ed34cfe9, TaskQueue=CHECK_CONNECTION, WorkflowId=0f2d8fcd-d433-44d7-bd27-b9e0fccc77cf, job_log_path=/tmp/workspace/283aca4a-be6e-4c0d-ad72-7f86e9dc0b24/0/logs.log} - 2021-11-01 19:46:24 ERROR i.a.i.d.s.S3Destination(check):58 - {} - Exception attempting to access the S3 bucket:
```

It should be saying `A CHANGE: Exception attempting to access the S3 bucket:`, but instead the `A CHANGE` is missing which leads me to think that the locally built bits are not being used. Anybody see what I'm doing wrong?

**Comment by sdairs** [comment]
You should be able to build just the connector with something like `./gradlew :airbyte-integrations:connectors:destination-<name>:build` then in in the UI > Settings, find the S3 Destination and set the version to `dev`  and hit Change - should pick it up the newly built image

You can also manually do things without the UI https://docs.airbyte.io/connector-development/tutorials/building-a-java-destination#directly-running-the-destination-using-docker

**Comment by cgardens** [comment]
Nice! @sdairs is right, you should be able to point to the dev version of the connector locally. I do not know how / if AWS creds propagate into docker. It is possible that you'll need to do something additional there as well.

**Comment by alafanechere** [comment]
Just to add my knowledge around role propagation on EKS clusters: A mapping between a K8S Service account and an AWS role is possible by using OpenID Connect (OIDC) identity providers. AWS calls this IRSA (IAM role for Service Account). How to set this up is well documented [here](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) 

Users could add the `eks.amazonaws.com/role-arn` annotation to the `airbyte-admin` K8S Service account which will enable the pod with this service account to benefit from IAM policies defined for this role.

**Comment by alvaroqueiroz** [comment]
this issue can be closed, [9399](https://github.com/airbytehq/airbyte/pull/9399) was merged

**Comment by casperbiering** [comment]
Unfortunately #9399 doesn't implement support for [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) which is the official way to assume an role in EKS.

What I've seen in other software projects, is that they implement [DefaultAWSCredentialsProviderChain](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) instead of [InstanceProfileCredentialsProvider](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/InstanceProfileCredentialsProvider.html) (used in #9399) which supports all the usual ways of providing access to the AWS SDK.

**Comment by alvaroqueiroz** [comment]
@casperbiering i was able to use the s3 destination connector on eks using instanceprofile of the nodes

**Comment by casperbiering** [comment]
@alvaroqueiroz true, but by using the instanceprofile you give all containers/pods/software running on that node access, which does not follow the Principle of Least Privilege. By using IRSA you only give access to a specific pod making it the more secure solution.

**Comment by prein** [comment]
@tuliren Is my thinking correct that the S3 parquet output doesn't support using IAM roles?

**Comment by tuliren** [comment]
> @tuliren Is my thinking correct that the S3 parquet output doesn't support using IAM roles?

It looks like the case. If I remember correctly, IAM role for S3 is only introduced recently. The Parquet and Avro writers are constructed different from the CSV and JsonL writers. It's fairly possible that the IAM role change only works for the latter two writers.

> If so, should I create a separate issue on that?

I have created an issue here: https://github.com/airbytehq/airbyte/issues/10581

**Comment by xorl** [comment]
I rewrote the module to allow for ServiceAccount using the DefaultAWSCredentialsProviderChain() and it works pretty effortlessly other than the fact that you have to patch the worker to force it to use the service account and build that manually. Otherwise, i'll submit a patch for just the destination s3 portion of this.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-23 at 17:13:*

<blockquote><div class="zd-comment" dir="auto">Today Airbyte doesn't allow you to create a source/destination in AWS using roles.&nbsp;<br>There is a Github Issue to implement this feature: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/5942">https://github.com/airbytehq/airbyte/issues/5942</a><br>&nbsp;<br></div></blockquote>

**Comment by xorl** [comment]
https://github.com/airbytehq/airbyte/pull/14231 PR open for this fix.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-30 at 17:41:*

<blockquote><div class="zd-comment" dir="auto">Alexandre, there is an implementation for this open <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/pull/14231"><span style="background-color: rgb(255,247,237);">https://github.com/airbytehq/airbyte/pull/14231</span></a><span style="background-color: rgb(255,247,237); color: rgb(20,74,117);"> you can copy the branch and deploy a dev version locally to test it?</span><br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-05 at 07:55:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Oh wow ! Thanks Marcos for your answers and sorry for not answering sooner, I see that the PR has been merged, that was fast <img src="https://emoji.discourse-cdn.com/twitter/slight_smile.png?v=12" title=":slight_smile:" alt=":slight_smile:" width="20" height="20"> I will test it and get back to you here <img src="https://emoji.discourse-cdn.com/twitter/+1.png?v=12" title=":+1:" alt=":+1:" width="20" height="20"></p> 

 [<a href="https://discuss.airbyte.io/t/cannot-use-ec2-iam-role-to-create-s3-source/1558/4" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by davinchia** [comment]
@xorl did your PR solve this for you?

**Comment by xorl** [comment]
Sorry for the late response it did with modification to the service role portion of Airbyte directly. Since the pods launch w/out the service account attached so the annotation does nothing without that.

**Comment by tooptoop4** [comment]
@xorl did u get IRSA working with EKS?

**Comment by KPhans** [comment]
> @xorl did u get IRSA working with EKS?

to echo this, did we end up getting airbyte to connect to s3 using IRSA? Still being prompted to enter hard access key IDs and secret key

**Comment by KPhans** [comment]
> @tuliren I checked the S3 Avro writer and I can confirm that it works with IAM role. The only problematic writer is Parquet.

Hi! which version were you on when you verified that this works (I am on 0.40.0-alpha)? Setting S3 destination now using IRSA. Proving to be a bit challenging

**Comment by dnrce** [comment]
I don't see it noted yet so I'll call out that this can also be applicable to RDS databases if IAM authentication is in use.

**Comment by sherifnada** [comment]
@bleonard adding this to DB team backlog though this maybe involves a platform team or connector ops since it's likely to be cross-cutting across any AWS-related connector

**Comment by murat-cetinkaya** [comment]
I need IAM EC2 profile support for DynamoDB source connector. Do you think I should create a new issue?

**Comment by redterror** [comment]
I think the AWS secretsmanager integration has a similar problem.  I tried granting my EC2 instance permissions via a role / instance profile, but the server failed to start since the access / secret key wasn't explicitly set.

**Comment by pmossman** [comment]
Hey all, we merged a contribution that enables IRSA support for source/destination pods: https://github.com/airbytehq/airbyte-platform/commit/37ba07b5001f825abaa2191422be7b04f72fff4d

This is available in the following release: https://github.com/airbytehq/airbyte-platform/releases/tag/v0.50.2

I believe there is still some amount of work that would need to be done to support IRSA for secret management and log storage.

**Comment by drewipsonhq** [comment]
@pmossman tracking this contribution that was merged. Are there any docs on how to deploy this to EKS in 0.50.2 or higher? I'm not sure where the IAM role needs to come from in order for the S3 destination to get access. 

Appreciate any clarification on how to leverage this new contribution.

**Comment by Sahith-8055** [comment]
> Hey all, we merged a contribution that enables IRSA support for source/destination pods: [airbytehq/airbyte-platform@37ba07b](https://github.com/airbytehq/airbyte-platform/commit/37ba07b5001f825abaa2191422be7b04f72fff4d)
> 
> This is available in the following release: https://github.com/airbytehq/airbyte-platform/releases/tag/v0.50.2
> 
> I believe there is still some amount of work that would need to be done to support IRSA for secret management and log storage.

Hi @pmossman tracking this contribution that was merged. Is there any timeline to create a Helm Chart for this release?

**Comment by raphaelauv** [comment]
airbyte not working with AWS OIDC ( tried eks_referal_identity and eks_pod_identity )

**Comment by abrazouski** [comment]
Got it finally working with IRSA. 
Chart version: `0.54.15`.

Helm chart config:
```yaml
global:
  log4jConfig: "log4j2-no-minio.xml"
  state:
    storage:
      type: "S3"
  logs:
    storage:
      type: "S3"
    minio:
      enabled: false
    s3:
      enabled: true
      bucket: S3_BUCKET_NAME
      bucketRegion: S3_BUCKET_REGION

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: IAM_ROLE_ARN

server:
  enabled: true
  extraEnv:
    - name: LOG4J_CONFIGURATION_FILE
       valueFrom:
         configMapKeyRef:
           name: {{ .Release.Name }}-airbyte-env
           key: LOG4J_CONFIGURATION_FILE
    - name: STATE_STORAGE_S3_BUCKET_NAME
       valueFrom:
         configMapKeyRef:
           name: {{ .Release.Name }}-airbyte-env
           key: S3_LOG_BUCKET
    - name: STATE_STORAGE_S3_REGION
       valueFrom:
         configMapKeyRef:
           name: {{ .Release.Name }}-airbyte-env
           key: S3_LOG_BUCKET_REGION

worker:
  enabled: true
  extraEnv:
    - name: LOG4J_CONFIGURATION_FILE
       valueFrom:
         configMapKeyRef:
           name: {{ .Release.Name }}-airbyte-env
           key: LOG4J_CONFIGURATION_FILE
    - name: STATE_STORAGE_S3_BUCKET_NAME
       valueFrom:
         configMapKeyRef:
           name: {{ .Release.Name }}-airbyte-env
           key: S3_LOG_BUCKET
    - name: STATE_STORAGE_S3_REGION
       valueFrom:
         configMapKeyRef:
           name: {{ .Release.Name }}-airbyte-env
           key: S3_LOG_BUCKET_REGION

minio:
  enabled: false
```

**Comment by DeepakRai94** [comment]
IRSA Role is functional with chart version 0.58.26.

Below is the updated Helm Config:

```
global:
  storage:
    type: s3
    bucket:
      log: S3_BUCKET_NAME
      state: S3_BUCKET_NAME
      workloadOutput: airbyte-storage
    s3:
      region: eu-west-1
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: IAM_ROLE_ARN
```

However, it appears that the [values](https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/values.yaml) in the Helm repository have not been updated to reflect these changes.
