### ISSUE TITLE
Airbyte Temporal context deadline exceeded on eks

### ISSUE THREAD

**Issue by PauloJMF** [airbytehq/airbyte#59730]
### Helm Chart Version

1.5.1

### What step the error happened?

None

### Relevant information

I'm running Airbyte using the Helm chart version 1.5.1 on my development cluster. After fine-tuning the CPU and RAM resources in the values.yaml file, I decided to deploy the same version on my production cluster.

After the initial setup, while trying to create a source or destination, the UI consistently returns the following error:  
`Airbyte is temporarily unavailable. Please try again. (HTTP 502)`

The only difference between these two `environments is that the production cluster uses an external database located in a different region, but I don't believe that is the issue. 
I have tried performing a fresh setup on multiple versions, but the airbyte-temporal pod does not seem to work on any of the versions I tested. 

Has anyone encountered this issue before? Below are the logs from the airbyte-temporal pod.

### Relevant log output

```shell
{"level":"info","ts":"2025-05-08T19:46:41.122Z","msg":"Stopped physicalTaskQueueManager","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-processor-parent-close-policy/3","wf-task-queue-type":"Workflow","wf-namespace":"temporal-system","worker-build-id":"_unversioned_","lifecycle":"Stopped","cause":"Idle","logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/service/matching/physical_task_queue_manager.go:312"}
{"level":"info","ts":"2025-05-08T19:46:43.234Z","msg":"Started physicalTaskQueueManager","component":"matching-engine","wf-task-queue-name":"/_sys/temporal-sys-processor-parent-close-policy/3","wf-task-queue-type":"Workflow","wf-namespace":"temporal-system","worker-build-id":"_unversioned_","lifecycle":"Started","cause":"Poll","logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/service/matching/physical_task_queue_manager.go:294"}
{"level":"info","ts":"2025-05-08T19:46:45.248Z","msg":"Started physicalTaskQueueManager","component":"matching-engine","wf-task-queue-name":"/_sys/default-worker-tq/1","wf-task-queue-type":"Workflow","wf-namespace":"temporal-system","worker-build-id":"_unversioned_","lifecycle":"Started","cause":"Poll","logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/service/matching/physical_task_queue_manager.go:294"}
{"level":"warn","ts":"2025-05-08T19:46:45.674Z","msg":"Critical attempts processing workflow task","service":"history","shard-id":2,"address":"REDACTED","wf-namespace":"default","wf-id":"check_46c8d40d-fc7d-465d-ab33-af9dab78ad04","wf-run-id":"d7009e5c-d45a-43a7-a207-de9383847d93","attempt":16,"logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/service/history/workflow/workflow_task_state_machine.go:1196"}
{"level":"info","ts":"2025-05-08T19:46:47.249Z","msg":"history client encountered error","service":"matching","error":"Workflow task already started.","service-error-type":"serviceerror.TaskAlreadyStarted","logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/client/history/metric_client.go:103"}
{"level":"info","ts":"2025-05-08T19:47:13.402Z","msg":"history client encountered error","service":"matching","error":"Workflow task already started.","service-error-type":"serviceerror.TaskAlreadyStarted","logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/client/history/metric_client.go:103"}
{"level":"info","ts":"2025-05-08T19:47:33.035Z","msg":"Stopped physicalTaskQueueManager","component":"matching-engine","wf-task-queue-name":"/_sys/DISCOVER_SCHEMA/1","wf-task-queue-type":"Workflow","wf-namespace":"default","worker-build-id":"_unversioned_","lifecycle":"Stopped","cause":"Idle","logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/service/matching/physical_task_queue_manager.go:312"}
{"level":"warn","ts":"2025-05-08T19:48:16.731Z","msg":"Critical attempts processing workflow task","service":"history","shard-id":2,"address":"REDACTED","wf-namespace":"default","wf-id":"check_7b8c77f4-d04e-40a4-9986-fe99776b030a","wf-run-id":"08255d05-a19b-4c52-9794-aef3d7641d92","attempt":10,"logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/service/history/workflow/workflow_task_state_machine.go:1196"}
{"level":"info","ts":"2025-05-08T19:48:18.305Z","msg":"history client encountered error","service":"matching","error":"Workflow task already started.","service-error-type":"serviceerror.TaskAlreadyStarted","logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/client/history/metric_client.go:103"}
{"level":"warn","ts":"2025-05-08T19:48:42.046Z","msg":"Critical attempts processing workflow task","service":"history","shard-id":2,"address":"REDACTED","wf-namespace":"default","wf-id":"check_96881a14-d721-4fba-b239-503602eb4a8e","wf-run-id":"c89e78e7-bb14-4aea-9bee-bb679db15bae","attempt":15,"logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/service/history/workflow/workflow_task_state_machine.go:1196"}
{"level":"warn","ts":"2025-05-08T19:48:43.047Z","msg":"Fail to process task","shard-id":2,"address":"REDACTED","component":"transfer-queue-processor","wf-namespace-id":"4b4ff0ab-a793-43a7-9312-d875995eaae3","wf-id":"check_96881a14-d721-4fba-b239-503602eb4a8e","wf-run-id":"c89e78e7-bb14-4aea-9bee-bb679db15bae","queue-task-key":{"FireTime":"1970-01-01T00:00:00Z","TaskID":10485821},"queue-task-type":"TransferWorkflowTask","queue-task":"4b4ff0ab-a793-43a7-9312-d875995eaae3/check_96881a14-d721-4fba-b239-503602eb4a8e/c89e78e7-bb14-4aea-9bee-bb679db15bae","wf-history-event-id":5,"error":"context deadline exceeded","error-type":"serviceerror.DeadlineExceeded","unexpected-error-attempts":1,"lifecycle":"ProcessingFailed","logging-call-at":"/home/runner/work/docker-builds/docker-builds/temporal/common/log/lazy_logger.go:63"}
```

**Comment by PauloJMF** [comment]
Also posting my values.yaml file using
````
global:
  image:
    registry: "REDACTED"

  airbyteUrl: "REDACTED"
  serviceAccountName: &serviceAccountName "airbyte"
  auth:
    enabled: true
    secretName: "airbyte-auth-secrets"
    instanceAdmin:
      firstName: "hive"
      lastName: "data"
      secretName: "airbyte-admin"
      emailSecretKey: "airbyte-admin-email"
      passwordSecretKey: "airbyte-admin-password"

  database: ##
    type: "external"
    host: "REDACTED"
    port: "5432"
    database: "airbyte_kube_app"
    secretName: "airbyte-database"
    userSecretKey: "airbyte-db-user"
    passwordSecretKey: "airbyte-db-pass"

  storage:
    type: s3
    bucket:
      log: &bucketName "configured-per-environment"
      state: *bucketName
      workloadOutput: *bucketName
    s3:
      region: "us-east-1"
      authenticationType: instanceProfile

  jobs:
    resources:
      requests:
        memory: 2Gi
        cpu: 300m
      limits:
        memory: 6Gi
        cpu: 750m
    kube:
      serviceAccountName: airbyte

      nodeSelector:
        abc/node-group: airbyte-workers

      tolerations:
        - key: abc/node-group
          value: airbyte-workers
          effect: NoSchedule
          operator: Equal

airbyte:
  enable: false
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "REDACTED"
  webapp:
    resources:
      requests:
        memory: 100Mi
        cpu: 5m
      limits:
        memory: 512Mi
        cpu: 10m
    ingress:
      enabled: true
      className: "private-nginx"
      annotations:
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-body-size: "200M"
      hosts:
      - host: "REDACTED"
  pod-sweeper:
    resources:
      requests:
        memory: 10Mi
        cpu: 10m
      limits:
        memory: 100Mi
        cpu: 100m
  server:
    resources:
      requests:
        memory: 4Gi
        cpu: 1
      limits:
        memory: 6Gi
        cpu: 2
  worker:
    livenessProbe:
      initialDelaySeconds: 90
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 200m
    env_vars:
      MAX_SYNC_WORKERS: 20
      MAX_CHECK_WORKERS: 20
    nodeSelector:
      abc/node-group: airbyte-workers
    tolerations:
      - key: abc/node-group
        value: airbyte-workers
        effect: NoSchedule
        operator: Equal
  workload-launcher:
    resources:
      requests:
        memory: 600Mi
        cpu: 250m
      limits:
        memory: "1.2Gi"
        cpu: 500m
    extraEnvs:
      - name: JOB_KUBE_NODE_SELECTORS
        value: abc/node-group=airbyte-workers
      - name: SPEC_JOB_KUBE_NODE_SELECTORS
        value: abc/node-group=airbyte-workers
      - name: CHECK_JOB_KUBE_NODE_SELECTORS
        value: abc/node-group=airbyte-workers
      - name: DISCOVER_JOB_KUBE_NODE_SELECTORS
        value: abc/node-group=airbyte-workers
  airbyte-bootloader:
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 2Gi
        cpu: 2
  temporal:
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 512Mi
        cpu: 200m
    extraEnv:
      - name: SKIP_DB_CREATE
        value: "true"
      - name: DBNAME
        value: airbyte_kube_temporal
      - name: VISIBILITY_DBNAME
        value: airbyte_kube_temporal_visibility
  cron:
    resources:
      requests:
        memory: 300Mi
        cpu: 10m
      limits:
        memory: 800Mi
        cpu: 500m
  connector-builder-server:
    livenessProbe:
      initialDelaySeconds: 90
    resources:
      requests:
        memory: 350Mi
        cpu: 10m
      limits:
        memory: 500Mi
        cpu: 200m
    service:
      type: ClusterIP
  workload-api-server:
    resources:
      requests:
        memory: 300Mi
        cpu: 10m
      limits:
        memory: 800Mi
        cpu: 500m
    nodeSelector:
      abc/node-group: airbyte-workers
    tolerations:
      - key: abc/node-group
        value: airbyte-workers
        effect: NoSchedule
        operator: Equal
  postgresql:
    enabled: false

  keycloak:
    enabled: false

  keycloak-setup:
    enabled: false

externalSecret:
  enabled: true

  secretStore:
    kind: ClusterSecretStore
    name: secretstore-eso

  database:
    userSsm: configured-per-environment
    passSsm: configured-per-environment

  admin:
    emailSsm: configured-per-environment
    passSsm: configured-per-environment
````
