### ISSUE TITLE
High Number of idle database connections

### ISSUE THREAD

**Issue by apostoltego** [airbytehq/airbyte#5986]
## Enviroment
- **Airbyte version**:  example is 0.29.12-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: n.a
- **Destination Connector and version**: n.a
- **Severity**: Medium
- **Step where error happened**: General upkeep

## Current Behavior
*Tell us what happens.*
We've noticed a very high number of concurrent database connections when jobs are running from Airbyte. These are connections to the custom airbyte application database. Most importantly we're seeing connections in the `temporal` db stick around in idle state even when there's no jobs taking place.

In the second image that contains database connections over time you can see database connections before and after we configured it to be the application database for airbyte. On the 24th of August we set it up. This same RDS instance was and is still used as a destination for some of our airbyte jobs. The spikes correlate with some of the heavier syncs that push >1m rows to the destination. 

## Expected Behavior
*Tell us what should happen.*
The number of connections to the database shouldn't exceed what's necessary and these should be closed after the necessary jobs are complete. 

## Logs
Relevant [slack thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1631278772131900)
<details>
<summary>LOG</summary> 

![Screenshot 2021-09-10 at 13 55 54](https://user-images.githubusercontent.com/16501677/132893248-20ac22d0-6239-4f5f-94b5-716e2edb4f4c.png)
![image (2)](https://user-images.githubusercontent.com/16501677/132893325-1dc12979-60bc-4c7d-8ca8-652b30677687.png)

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by apostoltego** [comment]
You may find the idle queries on temporal db useful:

![Screenshot 2021-09-10 at 19 56 27](https://user-images.githubusercontent.com/16501677/132903594-be0dc435-2bd0-4506-ab5f-2dc02a5a202a.png)

The **select** queries: 
`SELECT id, name, is_global, data, data_encoding, notification_version FROM namespaces WHERE partition_id=$1 ORDER BY id LIMIT $2
`

`SELECT task_id, data, data_encoding 
 FROM transfer_tasks WHERE shard_id = $1 AND task_id > $2 AND task_id <= $3 ORDER BY shard_id, task_id`

`INSERT INTO
cluster_membership (membership_partition, host_id, rpc_address, rpc_port, role, session_start, last_heartbeat, record_expiry)
VALUES($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(membership_partition, host_id)
DO UPDATE SET 
membership_partition = $1, host_id = $2, rpc_address = $3, rpc_port = $4, role = $5, session_start = $6, last_heartbeat = $7, record_expiry = $8`

**Comment by jrhizor** [comment]
After digging just a little, it looks like we can set `SQL_MAX_IDLE_CONNS` in the `.env` file and use it in `docker-compose.yaml` file like:
```
  airbyte-temporal:
    image: temporalio/auto-setup:1.7.0
    logging: *default-logging
    container_name: airbyte-temporal
    restart: unless-stopped
    ports:
      - 7233:7233
    environment:
      - DB=postgresql
      - DB_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PWD=${DATABASE_PASSWORD}
      - POSTGRES_SEEDS=${DATABASE_HOST}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - LOG_LEVEL=${LOG_LEVEL}
      - SQL_MAX_IDLE_CONNS=${SQL_MAX_IDLE_CONNS}
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
```

We'd need to reproduce the increased connection counts and check that this actually solves the problem of course, but I _think_ it's configurable.
