### ISSUE TITLE
Jobs Resources Support Setting Only Request

### ISSUE THREAD

**Issue by jacoblElementor** [airbytehq/airbyte#60809]
### Helm Chart Version

1.3.1

### What step the error happened?

During the Sync

### Relevant information

**The Request:**
When configuring Job's CPU/Memory resources requests and limits, I want to be able to configure only CPU request, and set unlimited CPU (no limit for the CPU)
**Bug:**
When setting only request, the configured request is ignored, and the request & limit resources are configured as the default configurations (as if I didn't set any)
For example:
I set:
```yaml
global:
  jobs:
    resources:
      limits:
        memory: 4Gi
      requests:
        memory: 2Gi
        cpu: 2000m
```
When running the sync job, the pod's containers get the following resources:
```yaml
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    memory: 2Gi
    cpu: 1
```
As you can see, the memory - since I've configured both `requests` & `limits` are as I configure, but the CPU request is ignored.
**Important Note**
When configuring both `requests` and `limits` for cpu/memory - the resources are as configured - this works.

### Relevant log output

```shell

```
