### ISSUE TITLE
Kube: worker pod tolerations

### ISSUE THREAD

**Issue by m-ronchi** [airbytehq/airbyte#6086]
## Current Behavior
https://github.com/airbytehq/airbyte/pull/5585 introduced `WORKER_POD_TOLERATIONS` env var that can specify tolerations for scheduling worker pods, but it missed to add the value from the `.env` file to the appropriate deployments yaml

## Expected Behavior
config is linked end to end from the `.env` file to javaland

## Are you willing to submit a PR?
yes, if you tell me which deployments needs the env injected. I guess only the scheduler?

**Comment by prasrvenkat** [comment]
Are you talking about `airbyte-scheduler`, `airbyte-temporal`, `airbyte-webapp` etc.,?
Those can be done with a [`kustomization`](https://docs.airbyte.io/deploying-airbyte/on-kubernetes#customizing-airbyte-manifests) yaml file. 
This env is added only because the scheduled/dynamic workloads use programmatic way of creating pods and not yamls.

For example, something like

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-scheduler
spec:
  template:
    spec:
      containers:
        - name: airbyte-scheduler-container
          resources:
            limits:
              cpu: 1
              memory: 512Mi
      nodeSelector:
        airbyte: 'server'
      tolerations:
        - key: "airbyte"
          operator: "Equal"
          value: "false"
          effect: "NoSchedule"
```

**Comment by m-ronchi** [comment]
no, the worker pods created dynamically by airbyte (source-*** / destination-***). 

#5585 added the ability to inject tolerations via env, but forgot to expose that env to https://github.com/airbytehq/airbyte/blob/master/kube/overlays/stable/.env (via an `envFrom:...` field in the respective yamls)

**Comment by prasrvenkat** [comment]
> no, the worker pods created dynamically by airbyte (source-*** / destination-***).
> 
> #5585 added the ability to inject tolerations via env, but forgot to expose that env to https://github.com/airbytehq/airbyte/blob/master/kube/overlays/stable/.env (via an `envFrom:...` field in the respective yamls)
> 
> right now adding `WORKER_POD_TOLERATIONS="whatever"` to our `.env` has no effect

Ah, ok got it. I will send a PR for that and see if airbyte team would want to merge with empty default.
But you can still use kustomization to inject it.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-scheduler
spec:
  template:
    spec:
      containers:
        - name: airbyte-scheduler-container
          env:
            - name: WORKER_POD_TOLERATIONS
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: WORKER_POD_TOLERATIONS
          resources:
            limits:
              cpu: 1
              memory: 512Mi
      nodeSelector:
        airbyte: 'server'
      tolerations:
        - key: "airbyte"
          operator: "Equal"
          value: "false"
          effect: "NoSchedule"
```

If interested, my kustomization.yaml uses
```
configMapGenerator:
  - name: airbyte-env
    env: .env
    behavior: replace
```
