### ISSUE TITLE
Worker: No bean of type [org.jooq.DSLContext] exists for the given qualifier: @Named('local-secrets')

### ISSUE THREAD

**Issue by SergioMunozGamarra** [airbytehq/airbyte#60915]
### Helm Chart Version

1.6.1

### What step the error happened?

On deploy

### Relevant information

What I’m doing
	•	Using a kustomization.yaml with an airbyte Helm chart v1.6.1
	•	Pulling DB credentials and local‐secrets creds via ExternalSecrets
	•	Everything spins up fine except the airbyte-worker pods
	•	Using an external postgresql database (RDS)

My kustomization.yaml is the following:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-secrets.yaml
helmCharts:
  - name: airbyte
    version: 1.6.1
    repo: https://airbytehq.github.io/helm-charts
    releaseName: airbyte
    namespace: airbyte
    valuesInline:
      global:
        serviceAccountName: airbyte-admin
        edition: "community"
        # -- Auth configuration
        auth:
          # -- Whether auth is enabled
          enabled: true
          # -- Admin user configuration
          secretName: "airbyte-auth-secrets"
          instanceAdmin:
            # -- Secret name where the instanceAdmin configuration is stored
            secretName: "airbyte-auth-secrets"
            firstName: "airbyte"
            lastName: "admin"

        database:
          type: "external"
          secretName: "airbyte-db-credentials"
          host: "xxxxx"
          port: xxxx
          database: airbyte
          userSecretKey: username
          passwordSecretKey: password

        storage:
          type: s3
          bucket:
            log: factorial-airbyte
            state: factorial-airbyte
            workloadOutput: factorial-airbyte
          s3:
            region: "eu-central-1"
            authenticationType: instanceProfile

        jobs:
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 1

      # secrets:
      #   persistence:
      #     localSecretsDatabase:
      #       existingSecret: airbyte-db-credentials
      #       host: "xxxx"
      #       port: xxxx
      #       database: airbyte
      #       userSecretKey: username
      #       passwordSecretKey: password

      serviceAccount:
        create: true
        annotations:
          "eks.amazonaws.com/role-arn": "arn:aws:iam::xxxxxxxxxx:role/airbyte-sa-role"
        name: airbyte-admin

      ## @section Webapp Parameters
      webapp:
        enabled: true
        replicaCount: 2
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            memory: 256Mi
            cpu: 250m

      ## @section Server parameters
      server:
        enabled: true
        replicaCount: 2
        service:
          port: 8000
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            memory: 512Mi
            cpu: 500m
        log:
          level: "INFO"
        extraEnv:
          - name: AIRBYTE_DATA_PLANE_ENABLED
            value: "true"

      ## @section Worker Parameters
      worker:
        enabled: true
        replicaCount: 2
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            memory: 256Mi
            cpu: 200m
        debug:
          enabled: true
        extraEnv:
          - name: AIRBYTE_DATA_PLANE_ENABLED
            value: "true"
          - name: SECRET_PERSISTENCE
            value: "TESTING_CONFIG_DB_TABLE"
          - name: AIRBYTE_LOCAL_SECRETS_DB_HOST
            value: "xxxxx"
          - name: AIRBYTE_LOCAL_SECRETS_DB_PORT
            value: "xxxx"
          - name: AIRBYTE_LOCAL_SECRETS_DB_DATABASE
            value: "airbyte"
          - name: AIRBYTE_LOCAL_SECRETS_DB_USER
            valueFrom:
              secretKeyRef:
                name: airbyte-db-credentials
                key: username
          - name: AIRBYTE_LOCAL_SECRETS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: airbyte-db-credentials
                key: password

      ## @section Workload Launcher Parameters
      workload-launcher:
        enabled: true
        replicaCount: 2
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            memory: 256Mi
            cpu: 250m
        log:
          level: "INFO"
        debug:
          enabled: true

      ## @section Rollout Worker Parameters
      connector-rollout-worker:
        enabled: true
        replicaCount: 2
        log:
          level: "INFO"
        debug:
          enabled: false

      ## @section Metrics parameters
      metrics:
        enabled: false
        replicaCount: 1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            memory: 256Mi
            cpu: 200m

      ## @section Bootloader Parameters
      airbyte-bootloader:
        enabled: true
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            memory: 256Mi
            cpu: 200m

      temporal:
        enabled: true

      temporal-ui:
        enabled: false
        replicaCount: 2
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 1

      ## @section Airbyte Database parameters
      postgresql:
        enabled: false

      ## @section cron parameters
      cron:
        enabled: true
        replicaCount: 1

        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 1
        log:
          level: "INFO"

      connector-builder-server:
        enabled: true
        replicaCount: 2
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            memory: 256Mi
            cpu: 200m

        log:
          level: "INFO"

      keycloak:
        enabled: false

      keycloak-setup:
        enabled: false

      workload-api-server:
        enabled: true
        replicaCount: 2

        log:
          level: "INFO"


      featureflag-server:
        enabled: true

        replicaCount: 1

        image:
          repository: airbyte/featureflag-server
          pullPolicy: IfNotPresent

        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 1

        log:
          level: "INFO"
```

When I deploy every service enabled everything is ok except worker pods that return this error:
    at io.airbyte.workers.$ApplicationInitializer$Definition.inject(Unknown Source)                                                                                                                              │
│     at io.airbyte.workers.$ApplicationInitializer$Definition.instantiate(Unknown Source)                                                                                                                         │
│     at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2334)                                                                                                                │
│     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2304)                                                                                                                        │
│     at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2316)                                                                                                                        │
│     at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3127)                                                                                                                  │
│     at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)                                                                                                                                   │
│     at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3029)                                                                                               │
│     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2990)                                                                                                             │
│     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2963)                                                                                                             │
│     at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3581)                                                                                                                  │
│     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3536)                                                                                                            │
│     at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3510)                                                                                                                │
│     at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1446)                                                                                                                      │
│     at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:883)                                                                                                                       │
│     at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:873)                                                                                                                       │
│     at io.micronaut.context.event.ApplicationEventPublisherFactory$2.lambda$$1(ApplicationEventPublisherFactory.java:215)                                                                                        │
│     at io.micronaut.core.util.SupplierUtil$1.get(SupplierUtil.java:47)                                                                                                                                           │
│     at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)                                                                                     │
│     at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery.onStart(NettyServiceDiscovery.java:54)                                                                                                     │
│     at io.micronaut.http.server.netty.discovery.$NettyServiceDiscovery$Definition$Exec.dispatch(Unknown Source)                                                                                                  │
│     at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)                                                                  │
│     at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3944)                                                                                                          │
│     at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:87)                                                                                                                         │
│     at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:143)                                                                                                                    │
│     at io.micronaut.http.server.netty.discovery.NettyServiceDiscovery$ApplicationEventListener$onStart1$Intercepted.onApplicationEvent(Unknown Source)                                                           │
│     at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266)                                                                               │
│     at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)                                                                                     │
│     at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:692)                                                                                                                │
│     at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:314)                                                                                                                            │
│     at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:112)                                                                                                                            │
│     at io.micronaut.runtime.Micronaut.start(Micronaut.java:81)                                                                                                                                                   │
│     at io.airbyte.workers.Application.main(Application.java:19)                                                                                                                                                  │
│ Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [org.jooq.DSLContext] exists for the given qualifier: @Named('local-secrets').                                                   │
│ * [DSLContext] requires the presence of a bean of type [org.jooq.Configuration] with qualifier [@Named('local-secrets')].                                                                                        │
│  * [Configuration] requires the presence of a bean of type [io.r2dbc.spi.ConnectionFactory] with qualifier [@Named('local-secrets')].                                                                            │
│  * [Configuration] requires the presence of a bean of type [javax.sql.DataSource] with qualifier [@Named('local-secrets')].                                                                                      │
│   * [DataSource] requires the presence of a bean of type [io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration] with qualifier [@Named('local-secrets')].                                              │
│    * [DatasourceConfiguration] is disabled because:                                                                                                                                                              │
│     - Configuration requires entries under the prefix: [datasources.local-secrets]                                                                                                                               │
│     at io.micronaut.context.DefaultBeanContext.newNoSuchBeanException(DefaultBeanContext.java:2798)                                                                                                              │
│     at io.micronaut.context.DefaultApplicationContext.newNoSuchBeanException(DefaultApplicationContext.java:329)                                                                                                 │
│     at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2761)                                                                                                             │
│     at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1745)                                                                                                                             │
│     at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)                                                                                                         │
│     at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2188)                                                                                       │
│     ... 112 common frames omitted                                                          

Looks like Micronaut never picks up a `datasources.local-secrets` config so the DSLContext/DataSource never get created. I’ve defined the env vars and ExternalSecret, but maybe I need to enable a top-level datasource block in the Helm values? Has anyone seen this before or know how to hook up a second (local-secrets) datasource in the chart? Any pointers would be hugely appreciated 

### Relevant log output

```shell

```
