### ISSUE TITLE
:building_construction: SAT: add ability to override config.json fields from acceptance-test-config.yml file.

### ISSUE THREAD

**Issue by avida** [airbytehq/airbyte#6207]
## Tell us about the problem you're trying to solve
Sometime it is useful to override config variables for some SAT test cases.

## Describe the solution you’d like
Add "config_update" section to config file
```yaml
connector_image: airbyte/source-<image>:dev
tests:
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog_rest.json"
      - config_update:
          _page_size: 200
    - config_path: "secrets/config_bulk.json"
      configured_catalog_path: "integration_tests/configured_catalog_bulk.json
...
```
It should add  "_page_size" parameter to  original secrets/config.json file. 

## Describe the alternative you’ve considered or used
Since secrets/ dir content is populated by CI scripts no alternative beside manually updating config file content via CI env.

## Are you willing to submit a PR?
Yes
