### ISSUE TITLE
SAT: add option to ignore specific fields when checking expected records

### ISSUE THREAD

**Issue by avida** [airbytehq/airbyte#6433]
## Tell us about the problem you're trying to solve

When doing SAT for some API there could be some data fields  that constantly changed, e.g. for facebook we have fields that constantly changing if company is running like hit count or total budget. Also that could be values representing that item had been updated. 

Fails like this don't mean that connector is bad, its just data changed and we should specify this condition in acceptance-test-config.yml file. 

## Describe the solution you’d like
Solution 1
Is to use existing [expect_records.extra_fields](https://docs.airbyte.io/connector-development/testing-connectors/source-acceptance-tests-reference#test-basic-read) functionality by manually removing  expected records from expect_records.path file and set extra_fields parameter to yes:

```yaml
      expect_records:
        path: "integration_tests/expected_products_stream.txt"
        extra_fields: yes
```
Solution 2

Add ignore_fields parameter with list of object path pattern SAT should ignore when comparing records:
```yaml
      expect_records:
        path: "integration_tests/expected_products_stream.txt"
        ignore_fields: 
         - "object_key/object_key2"
         - "object_key/object_key2/value"
         - "object_key/*/object_key2"
```

## Describe the alternative you’ve considered or used

Using solution 1 with extra_fields but in this case we need to add support of lists and unit tests.

## Are you willing to submit a PR?

Yes
