### ISSUE TITLE
[Helm Chart] ExternalDB settings are not passed to temporal deployment

### ISSUE THREAD

**Issue by jonstacks** [airbytehq/airbyte#7067]
Logging this on behalf of a user in slack: https://airbytehq.slack.com/archives/C01MFR03D5W/p1634216387012800

## Enviroment
- **Airbyte version**:  multiple
- **OS Version / Instance**: Kubernetes
- **Deployment**: Kubernetes (Helm)
- **Source Connector and version**: N/A
- **Destination Connector and version**: N/A
- **Severity**: Medium
- **Step where error happened**: Deploy

## Current Behavior

When using the Airbyte helm chart with an external database(`postgresql.enabled=false`), the external DB connection parameters are not passed to the temporal deployment.

## Expected Behavior

When specifying manually specifying a database(`postgresql.enabled=false`) that should be used for airbyte, by using the `externalDatabase` settings, the helm chart should pass those to the temporal deployment.

## Logs

</details>

## Steps to Reproduce
1. Change directory to the Airbyte helm chart directory: `cd charts/airbyte`
2. Create an `external-db.yaml` file with the following as an example:
```
postgresql:
  enabled: false

externalDatabase:
  host: cloudsql-proxy.airbyte.svc.cluster.local
  user: airbyte-test
  password: ""
  existingSecret: "external-db-secret"
  existingSecretPasswordKey: "external-db-password"
  database: airbyte
  port: 5432

```
3. Run: `helm template --release-name airbyte -f external-db.yaml -s templates/temporal/deployment.yaml .` and verify the config

## Are you willing to submit a PR?

Yes

**Comment by nik-nazarov** [comment]
I confirm the problem, I ran into it today

**Comment by surajrubik** [comment]
I had this from starting,
and to resolve this I created a file to create a secret named "airbyte-externaldb", with the content:

```
apiVersion: v1
kind: Secret
metadata:
  name: airbyte-externaldb
data:
  postgresql-password: {{ .Values.externalDatabase.password | b64enc }}
```
Values of values.yaml will remain the same, the password will fetch from the values.yaml file.
