### ISSUE TITLE
create web backend endpoint for per-connection billing

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#7130]
Not all of the information is available in the billing endpoint for the https://github.com/airbytehq/airbyte/issues/6956 display. We need to create a web backend endpoint that adds metadata about connections onto the responses from the billing handler so the frontend can easily consume it.

The implementor should sync with Artem to ensure the necessary metadata is exposed by the proposed endpoints. 

Design here https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=26991%3A93697

**Comment by airbyte-jenny** [comment]
I discussed this with Jared to understand the requirements a bit better.  Here's a summary of outcome and plans.

We will add a new endpoint that provides data to feed the front end.  We have existing endpoints that provide some billing data, but not in the format we need for this page.  We already have the per-connection billing data saved, so we're not acquiring any new data for this feature.  We're just sending a new structure.  Right now it can receive only a connection id, which isn't really enough; we need to expand that domain object and look at the source, the destination, and other relevant metadata, plus names.

We did notice that we need to somehow identify each connector listed on the per-connection billing, in a way that's unique even if the customer has that source->destination used more than once.  We'll look at doing this with metadata already available for connections, but not looking into the json schemas at all.  (Looking into schemas for db hostnames etc might happen someday but not now).  There might be UI followups for Artem, for instance linking from the per-connection billing page to the actual connections, so people can navigate and verify configs as needed.  We also might prefer to update the UI to show more connection name information, instead of just source/dest generic names.

The first step in this is to get a data structure spec'd out in config.yml and pass that over to Artem for review, before we implement it.

Then implementation should be a very straightforward web endpoint that collates data and sends it in the expected data structure.  This is read-only, not interactive.

**Comment by airbyte-jenny** [comment]
Prototype of a modification to the openapi spec, to accommodate the wireframe, follows.  The mockup is out of date; we're not calculating based on egress credits used, due to a change as cloud was going live.  So there aren't two bars to show per connector, but just one.  Because of that, the credits used field is just a single field in this prototype.

```
    ConnectorConsumptionRead:
      type: object
      required:
        - connectionId
        - creditsConsumed
        - sourceId
        - sourceDefinitionId
        - sourceDefinitionName
        - sourceConnectionName
        - destinationId
        - destinationDefinitionId
        - destinationDefinitionName
        - destinationConnectionName
      properties:
        connectionId:
          type: string
          format: uuid
        creditsConsumed:
          description: Number of credits consumed rounded to two decimal places.
          type: number
          format: double
        sourceId:
          type: string
          format: uuid
        sourceDefinitionId:
          type: string
          format: uuid
        sourceDefinitionName:
          description: Name of the type of source
          type: string
        sourceConnectionName:
          description: Name of this particular source as used in a single sync connection
          type: string
        destinationId:
          type: string
          format: uuid
        destinationDefinitionId:
          type: string
          format: uuid
        destinationDefinitionName:
          description: Name of the type of destination
          type: string
        destinationConnectionName:
          description: Name of this particular destination as used in a single sync connection
          type: string
```

This data object previously only held connectorId and creditUsage.  The rest of the fields are being added to better identify each connector (by type and by actual name), so that UI presented to the user for per-connection usage is more sensible and easy to follow.

I will move ahead on implementing to this spec, and can integrate any small changes after the fact as we need them.
