### ISSUE TITLE
Helm deployment: The Access Key Id you provided does not exist

### ISSUE THREAD

**Issue by gajus** [airbytehq/airbyte#8805]
Getting this error when trying to add source:

<img width="896" alt="Screen Shot 2021-12-14 at 10 33 59 PM" src="https://user-images.githubusercontent.com/973543/146123830-f9e2d87d-7ae0-494d-bda4-9b818bb40074.png">

Using Helm chart with the following values:

```yaml
postgresql:
  enabled: true
logs:
  s3:
    enabled: false
```

**Comment by gajus** [comment]
Reverting to the commit before [this change](https://github.com/airbytehq/airbyte/commit/9e36c38583ff620f9793d430d44ac60739278184#diff-1d5333bd9b8863a7adad535b9c42940e577d7e89f0fa9d24dc8d352d039d6c64) makes it work.

There is a regression.

**Comment by alafanechere** [comment]
Hi @gajus your problem happens for a specific source selection or is it common to all sources during set up and you think its related to S3 logs setup. Could you please share your server log?

**Comment by alafanechere** [comment]
@vnourdin and @davinchia do you have an insight of the root cause of this regression that appeared after merging https://github.com/airbytehq/airbyte/pull/8736?

**Comment by vnourdin** [comment]
I can't find what could trigger such error :thinking:
I just renamed the helm value used to set AWS credentials env variables but kept the same default value.
There is also [this change](https://github.com/airbytehq/airbyte/pull/8736/files#diff-8a27c194cc3e847e121a87f03b7636af1265a0df60d53307e17e76bcc42ac103), but I don't see why it would create any problem neither.

@gajus, could you compare AWS credentials in the ConfigMap `airbyte-env` and in the worker env variables both before and after my changes ? If you don't overwrite them, it should always be `minio`:`minio123`

**Comment by mohamagdy** [comment]
@gajus did you upgrade from previous versions of Airbyte and had MinIO running as a dependency or is it a fresh installation of Airbyte?

**Comment by gajus** [comment]
I did fresh install in both cases. The latest version does not work. The one from a commit from before the one I referenced works fine. I can replicate this consistently since I built and rebuilt our test environment many times.

**Comment by mohamagdy** [comment]
I see. I had some other issues with the referenced merge listed [here](https://github.com/airbytehq/airbyte/issues/8783#issuecomment-994510734).

For me this works:

```yaml
logs:
  accessKey:
    password: <access-key>
  secretKey:
    password: <secret-key>
  minio:
    enabled: true

# Yes again!
minio:
  accessKey:
    password: <access-key>
  secretKey:
    password: <secret-key>
```

**Comment by thodquach** [comment]
I met this problem with default values.yaml.
chart version: "0.39.10-alpha"
How can we fix this for now?

**Comment by yoavtzelnick** [comment]
Having the same problem as @thodquach . 
I think this is caused by 0.39.8-alpha with updating the Chart.yaml minio version from 7 to 11.

**Comment by stasrelevanceai** [comment]
We also faced with this error yesterday. This helped:

```
minio:
  accessKey:
    password: minio
  secretKey:
    password: minio123
  auth:
   rootUser: minio
   rootPassword: minio123
```

`auth` block was added as the latest version minio requires different configuration: https://github.com/bitnami/charts/tree/master/bitnami/minio#to-900

airbyte helm chart should be updated with a newer configuration for minio helm chart.
