### ISSUE TITLE
Helm chart: externalDatabase.password has no effect as it still retrieves from the secret

### ISSUE THREAD

**Issue by jsrcodes** [airbytehq/airbyte#9979]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: AWS EKS
- **Deployment**: Kubernetes deploy env
- **Severity**:  Low
- **Step where error happened**: Deploy

## Current Behavior
`externalDatabase.password` has no effect as it still retrieves from the secret

## Expected Behavior
When externalDatabase.password is set, the template should use it instead of retrieving from a secret.

## Root cause:
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/bootloader/pod.yaml#L33
This if-else condition needs to be fixed, as it uses password from the secrets for the external DB.
```yaml
        {{- if .Values.postgresql.enabled }}
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: airbyte-env
              key: DATABASE_PASSWORD
        {{- else }}
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "airbyte.postgresql.secretName" . }}
              key: {{ include "airbyte.database.existingsecret.key" . }}
        {{- end }}
```

## Steps to Reproduce
1. Use the helm chart as follows for externalDatabase section
```yaml
        externalDatabase:
          host: HOST
          user: USER
          password: {{ requiredEnv "STAGING_DB_PWD" | quote }}
          existingSecret: false
          database: db-airbyte
          port: 5432
```
2. deploy on K8s

**Comment by evantahler** [comment]
This should have been fixed by https://github.com/airbytehq/airbyte/pull/14794

**Comment by shaoye** [comment]
hi can we reopen this?

I don't think #14794 fixed this, we are still hardcoding it everywhere

```
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.database.secretName | default (printf "%s-postgresql" .Release.Name ) }}
              key: {{ .Values.global.database.secretValue | default "DATABASE_PASSWORD" }}
```
